### ISSUE TITLE
Having a column with request/response size

### ISSUE THREAD

**Issue by arx-it** [ProxymanApp/Proxyman#100]
Hi, first I want to say that your app is very promising, I'll follow it very closely.

As may users I guess, I use Fiddler on Windows, and one feature I'm using is having a column with request/response size in the main list of requests.

**Comment by NghiaTranUIT** [comment]
You're right. I totally miss it.

I will support it in next build 1.3.5 👍 

If you don't mind, please `watch` this repo to get updated release. Thank you in advance.

**Comment by arx-it** [comment]
Repo watched :thumbsup:

Good job

**Comment by NghiaTranUIT** [comment]
All done in Proxyman 1.4.3.1 🥇 

## 🤯 Changelogs 
- [x] Introduce request/Response size column and FlowPresentable

**Comment by NghiaTranUIT** [comment]
Hey @arx-it,

Please check out the official [Proxyman 1.3.4.1](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.1) or update directly from the app (Preference -> Check for Update) 🥇 

Proxyman has Request/Response columns now 😃

**Comment by arx-it** [comment]
Thanks a lot 👍
