### ISSUE TITLE
Response Body Horizontal Scrolling is Reversed

### ISSUE THREAD

**Issue by ptrkstr** [ProxymanApp/Proxyman#1008]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.33.0 (23300)

### macOS Version? (Ex. mac 10.14)
11.6 (20G165)

### Steps to reproduce 
1. Select a request that has a large horizontal response body
2. Scroll to the left or right

### Expected behavior
- Horizontal scrolling behaviour matches that of scrolling in request TableView or any other mac app

### Actual behavior
- Horizontal scrolling behaviour is reversed

### Additional notes
I believe this was caused by a recent update as I previously didn't have this issue.

**Comment by NghiaTranUIT** [comment]
I tested with a very long response body but I could not reproduce it 🤔 

Here is how I test:
1. Turn off "Word Warp in Body Previewer" in Preference -> Advanced => It's important to show a horizontal scroller.
2. Open System Preference -> Touchpad -> Scroll & Zoom -> Check the "Natural" scroll direction
3. Try to scroll on the main table view of Proxyman and the body response.

From what I observe, it's the same direction when using the touchpad. Even though I turn off the "Natural", they are still in the same scroll direction.

Just wondering: Do you encounter the bug by using a touch pad or mouse?

------------------------
To workaround by disabling the Horizontal, you can disable it in Preference -> Advanced -> Turn ON "Word Warp in Body Previewer"

**Comment by NghiaTranUIT** [comment]
Just figure it out that I can scroll horizontally by holding SHIFT + scroll the wheel 🤯 and it works fine too

**Comment by ptrkstr** [comment]
This is strange! I restarted my mac and the issue is resolved. 🤷‍♂️
