### ISSUE TITLE
Add a search bar to Map Local window

### ISSUE THREAD

**Issue by weazyexe** [ProxymanApp/Proxyman#1016]
### Proxyman version? (Ex. Proxyman 1.4.3)

2.32.0

### macOS Version? (Ex. mac 10.14)

11.5.2

Hey! I have a handy improvement idea for map local window. Can you add a search bar to it please? Because it's really hard to find exact rule if you have a lot of rules 🥲

Add an icon, shortcut like cmd+f or smth

Thank you! Proxyman is amazing ✨

**Comment by NghiaTranUIT** [comment]
We're working on Folder for Rules #713, which you can easily organize/filter your rules 👍 

And it will ship with the filter too 👍

**Comment by weazyexe** [comment]
Sounds cool! Thank you 🤪

Looking forward the feature!

**Comment by JasonBoy** [comment]
@NghiaTranUIT  I wish you can add this search bar to map remote too, I'm a heavy user of map remote tool:
![CleanShot 2024-10-11 at 19 34 46](https://github.com/user-attachments/assets/be48d9fd-0ff1-4355-98cd-7ac5bb0b8a30)

**Comment by NghiaTranUIT** [comment]
@JasonBoy it's done at https://github.com/ProxymanApp/Proxyman/issues/2157#issuecomment-2409909387

**Comment by JasonBoy** [comment]
> @JasonBoy it's done at [#2157 (comment)](https://github.com/ProxymanApp/Proxyman/issues/2157#issuecomment-2409909387)

@NghiaTranUIT  Awesome, thank you
