### ISSUE TITLE
Breakpoints managing in System Status Bar

### ISSUE THREAD

**Issue by compl** [ProxymanApp/Proxyman#1032]
Would be great to have the ability to turn on/off breakpoints in System Status Bar:

![image](https://user-images.githubusercontent.com/9084162/137370234-1d24901e-c135-4a9f-b363-8dae2cbd01cc.png)

Like in Toolbar:

![image](https://user-images.githubusercontent.com/9084162/137370409-d6678ff8-e7f4-4c92-abb3-ab6497a6a422.png)

In order not to open the app every time just for enabling/disabling breakpoints

**Comment by compl** [comment]
@NghiaTranUIT, hey
Just to understand, features that were included in milestones [<3.0.0] specifically this one are going to be released?

**Comment by NghiaTranUIT** [comment]
Sorry @compl, we consider not implementing this feature yet since I haven't collected enough same requests. I'd keep this ticket as a open status and collect more request 👍

**Comment by keenwon** [comment]
also turn on/off script in System Status Bar

**Comment by NghiaTranUIT** [comment]
@keenwon @compl please try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.0.0_Toogle_debugging_tool_in_system_menu.dmg

You can quickly toggle these debugging tools in the Status Bar menu 👍 

<img width="521" alt="Proxyman toggles debugging tools" src="https://user-images.githubusercontent.com/5878421/153330281-8977ae2b-55e6-4647-a4a9-aadcf05a5f00.png">
