### ISSUE TITLE
Export Raw Request & Response  - HTTP/1.1 wrong end-of-line marker

### ISSUE THREAD

**Issue by csftech** [ProxymanApp/Proxyman#1033]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 2.33.0

### macOS Version? (Ex. mac 10.14)
macOS 11.6

### Steps to reproduce 
1. Select one request and click Export Raw Request & Response option
2. Check the end-of-line marker in request/response file

### Expected behavior
According to [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-2.2), HTTP/1.1 uses CR LF as the end-of-line marker.

### Screenshots (optional)
Current version uses LF.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/14951751/137495942-82ccaf80-4c10-4c8f-ab3f-00464f998514.png">

**Comment by NghiaTranUIT** [comment]
Thanks. We weren't aware of that. It's a 🐞 . Will fix and send you beta build soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @csftech Please check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.34.1_Fix_CRLF_when_exporting_raw_Reqest_&_Response.dmg

From now, Proxyman will export CRLF properly (See the screenshot, View by Sublime + RawLineEdit package)

<img width="967" alt="Screen Shot 2021-10-17 at 10 16 32" src="https://user-images.githubusercontent.com/5878421/137610438-4cd57c6d-99ff-4064-bd44-1eb0a6ba1e37.png">

**Comment by csftech** [comment]
@NghiaTranUIT The marker issue has been fixed in the beta build. Thank you.
