### ISSUE TITLE
Internal Error in M1 Pro

### ISSUE THREAD

**Issue by tianpeili** [ProxymanApp/Proxyman#1068]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.35.0 (23500)
### macOS Version? (Ex. mac 10.14)
12.0.1 (21A559) M1 pro
### Steps to reproduce 
`handshakeFailed(NIOSSL.BoringSSLError.sslError([])) `
can not load google.com in Safari

reinstall the certificate in Mac and iOS.
I have two iPhone. Both have a same problem
### Screenshots (optional)
![image](https://user-images.githubusercontent.com/94671838/142606946-dbf935f9-60eb-442b-9112-363edbc8f3aa.png)

**Comment by NghiaTranUIT** [comment]
It looks like the Proxyman certificate is not trusted properly.

Can you open the Keychain Access app -> Search Proxyamn CA -> Double click to open -> and verify that you have a Blue tick (Marked as trust) like the following screenshot 🤔 

<img width="731" alt="Screen_Shot_2021-11-19_at_17_24_44" src="https://user-images.githubusercontent.com/5878421/142607391-e4d18483-5cfd-42a0-afde-195cc3563076.png">

**Comment by NghiaTranUIT** [comment]
I'm running on M1 without any issues. I don't think M1 Pro is different.

**Comment by tianpeili** [comment]
Just wondering: When you mention "Reinstall the certificate", is it Automatic or Manual (In Certificate Menu -> Install on this Mac)?
Yes, I followed the guide in https://docs.proxyman.io/troubleshooting/get-ssl-error-from-https-request-and-response.
I delete the certificate and automatic install the certificate.

![image](https://user-images.githubusercontent.com/94671838/142619987-23512987-96ed-4056-9840-297ddaa22b38.png)

The screenshot means "Always Trust" in every selection.

**Comment by VaslD** [comment]
It looks like the failed request is coming from a device (other than your MacBook) on the local network. You'll have to trust the certificate on that specific device (not necessarily on your MacBook, which Proxyman's automatic setup does) for its traffic to be captured.

**Comment by tianpeili** [comment]
It work after I delete the certificate, reinstall and trust. Thanks~
