### ISSUE TITLE
Properly detect response data

### ISSUE THREAD

**Issue by duraki** [ProxymanApp/Proxyman#107]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))

Latest version.

### What OS Version are you using? (Ex. mac 10.13)

Latest version.

### Steps to reproduce this issue

* Sniff endpoint for which response answers with:
  * Header `accept: application/vnd.app.normalized+json+2.1`
  * Body outputs dummy JSON
* Check response (and attached screenshot)
* **JSON output not properly formatted**

### Screenshots (optional)

![Screenshot 2019-04-07 at 23 12 51](https://user-images.githubusercontent.com/5892610/55689912-d840e000-598a-11e9-8743-a6cfac71c9eb.png)

Might relate to #106.

**Comment by NghiaTranUIT** [comment]
It doens't recognize the JSON since the Content-Type is not a default (application/json). Thus, I couldn't aware of it.

Will fix it today 👍

**Comment by NghiaTranUIT** [comment]
Hey @duraki, 

Here is the fix of this ticket #107 and "Missing cookies in cURL" #108 : https://www.dropbox.com/s/geo0fm288ds10cj/Proxyman_1.3.4.2.dmg?dl=0

I will official rollout this fixes in Proxyman 1.3.4.3 soon.

**Comment by NghiaTranUIT** [comment]
Let me know if it works in your side 🥇 😁

**Comment by duraki** [comment]
Testing in progress for both issues. Will let you know.

**Comment by NghiaTranUIT** [comment]
@duraki Just let you know that the official Proxyman 1.3.4.3 is released successfully.

It includes all your bugs and several improvements here (https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.3) ⚡️

Thank you so much 👍

**Comment by duraki** [comment]
Everything works as expected. Highly appreciate quick fixes! Keep it up @NghiaTranUIT, hopefully someone more natural to Apple SDK will join you development.
