### ISSUE TITLE
Atlantis minimum version

### ISSUE THREAD

**Issue by CyberMew** [ProxymanApp/Proxyman#1073]
module 'Atlantis' has a minimum deployment target of iOS 13.0

but website says 12+: https://docs.proxyman.io/atlantis/atlantis-for-ios#:~:text=iOS%2012.0%2B%20/%20macOS%2010.12%2B

Also, any chance to get it to run for lower iOS versions as well?

**Comment by NghiaTranUIT** [comment]
Since [Atlantis 1.13.0](https://github.com/ProxymanApp/atlantis/releases/tag/1.13.0), we bump the minimum OS to iOS 13.0. I will update the Doc soon.

If you'd like to use iOS 11, iOS 12, you can use Atlantis at 1.12.0 or lower 👍

**Comment by CyberMew** [comment]
Thanks for the info! I will try 1.12.0, is it compatible with the current macOS versions? I think this is good information if included in the docs as well 👍

**Comment by NghiaTranUIT** [comment]
It's compatible with the latest Proxyman 2.35.0 @CyberMew 👍
