### ISSUE TITLE
cURL is missing request cookies

### ISSUE THREAD

**Issue by duraki** [ProxymanApp/Proxyman#108]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))

Latest version.

### What OS Version are you using? (Ex. mac 10.13)

Latest version.

### Steps to reproduce this issue

* Copy request as cURL. (Request needs a dummy cookie)
* **Copied cURL command is missing cookie(s)**
* *Add* `--cookie "name=value" ...` *in cURL args*

**Comment by NghiaTranUIT** [comment]
Thank for the report 🤝 I will investigate it today 🌆

**Comment by NghiaTranUIT** [comment]
All done in [Proxyman 1.3.4.3](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.3)

**Comment by duraki** [comment]
Bless you 🙏
