### ISSUE TITLE
Setapp and Premium Proxyman for iOS

### ISSUE THREAD

**Issue by inickt** [ProxymanApp/Proxyman#1082]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 2.35.1

### macOS Version? (Ex. mac 10.14)
macOS 11.6

### Steps to reproduce 
1. Open `Proxyman` -> `Liscense...` menu
2. Still see the option for instructions of how to activate the premium version of Proxyman for iOS

### Expected behavior
Unsure if this is a bug/working as intended but could be expressed clearer. I thought I have read before that Setapp subscriptions don't include premium for iOS, but can't find where I thought I saw that now. I'd expect to either have a code to unlock OR have some text explaining that premium isn't included with the Setapp version.

As always, thanks for making such a great app! 

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/4574041/144893976-f86f04db-2904-49af-a747-12b2923fa9e0.png)

**Comment by NghiaTranUIT** [comment]
Sorry @inickt, it's my mistake 😿

Basically, it only displays on the non-Setapp-build where you have a license key to activate a Premium iOS. I'm going to fix it and release in the next hotfix 👍

**Comment by NghiaTranUIT** [comment]
Just let you know that it's fixed and we're going to submit to Setapp today 👍
