### ISSUE TITLE
Request and Response preview tabs selection don't persist

### ISSUE THREAD

**Issue by christos** [ProxymanApp/Proxyman#1083]
### Proxyman version? 

Version 2.35.1 (23510)

### macOS Version? (Ex. mac 10.14)

12.0.1 (21A559)

### Steps to reproduce 

This happens no matter the request but I mostly use it with SSL proxied request from mobile devices.

* Click on a domain to see request and response details (any request will do)
* Click on any previewer (both the default ones, or custom ones like JSON) to see a preview 
* Quit the App
* Launch the App
* Click on the same domain as before to see another request
* The previewer selection has gone back to *Header* and *Header*

### Expected behavior

The previewer selection should persist (Header, Raw, JSON, JSON Tree, etc.)

### Screenshots (optional)

![ScreenShot 2021-12-06 at 20 20 36@2x](https://user-images.githubusercontent.com/736/144908681-a352fdec-0cca-4466-a32f-fcc96ae82d18.png)

**Comment by NghiaTranUIT** [comment]
Thanks for your sugestion. It makes sense to persist the previous state of the Request/Response panel 👍

**Comment by NghiaTranUIT** [comment]
Here is your beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.35.1_Persist_selected_Request_Response_tab.dmg

In this build, Proxyman will persist your last Request/Response tab as you mention 😄 You can opt-out in Preference -> Advanced

**Comment by christos** [comment]
Awesome! Works like a treat.
