### ISSUE TITLE
The proxy port for Flutter apps using Dio is incorrect in documentation

### ISSUE THREAD

**Issue by f-person** [ProxymanApp/Proxyman#1105]
In the [Dio part](https://docs.proxyman.io/debug-devices/flutter#dio) of Flutter documentation the proxy port is `8888` instead of `9090`. It's correct for the `http` package and `HTTPClient`.

**Comment by NghiaTranUIT** [comment]
Thanks. let me update it 👍

**Comment by NghiaTranUIT** [comment]
It's done. Thanks for your report 🎉
