### ISSUE TITLE
OAuth/Bearer Authorization Tab Weirdness 

### ISSUE THREAD

**Issue by VaslD** [ProxymanApp/Proxyman#1116]
### Proxyman version? (Ex. Proxyman 1.4.3)

2.35.4 (23540)

### macOS Version? (Ex. mac 10.14)

12.1 (21C52)

### Steps to reproduce

Send a request with OAuth Bearer Authorization header to any site. Observe:

- Token in Auth tab is cut, padding omitted.
- Token in Auth tab wraps unexpectedly.
- Token in Auth tab shows under Key column, and leaves Value empty.

### Expected behavior

- For one, the token string should not be cut in any way, even if it's Base64 and some characters represent null bytes or padding. A token is only valid in full. Proxyman should not determine what's not important and omit that information.
- Then it feels off to have the actual token show under *Key* column and matches an empty *Value* on the same row. This split also causes token to wrap to multiple lines when there's clearly space to the right. Not pretty! Bearer tokens don't use a traditional key-value format like some other auth. If you really want to keep that UI, I suggest filling the *Key* field as "Bearer" and leave the token as value. It is somewhat a value after all.
- On that note, if the token **has** to wrap, it should wrap unconditionally at fixed length, not follow English grammar and wrap at grammatical word/sentence boundary characters. That makes it really awkward if the token has character `/` or `+` at the second index, e.g. `Y/c+bG8gV29ybTWFueSBoYW5kcyBtYWtlIGxpZ2h0IHdvcmsuGQ=` (made that up, not conforming to any standard) might show up as:
  ```
  Y/
  c+
  bG8gV29ybTWFueSBoYW5kcyBtYWtlIGxpZ2h0IHdvcmsuGQ=
  ```

### Screenshots (optional)

Headers Tab:

![Headers Tab](https://user-images.githubusercontent.com/3415065/150474762-2e2b2a0e-2b1d-4bd3-8697-62bb757aca89.png)

Authorization Tab:

![Authorization Tab](https://user-images.githubusercontent.com/3415065/150474788-de66e3e6-e310-4a14-b397-61147c635c75.png)

**Comment by NghiaTranUIT** [comment]
@VaslD I've fixed it on this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.0.0_Support_OAuth1.0_Hawk_Auth.dmg
