### ISSUE TITLE
After hitting clear, the first network call made shows up twice

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1124]
### Proxyman version?
Version 3.0.0 (30000)

### macOS Version?
m1 mac 12.1 (21C52)

### Issue
I noticed the issue because I have a refresh button in my android app. every time I hit the refresh button I would watch proxyman for the network log. After a while I clear the list, then hit the button in my app again and... TWO requests show up. Clear again + button in my app = 2 requests! If you see the video... if I wait 5+ seconds after hitting "clear" then I get only get ONE request. I hope this helps you fix this. thank you

https://user-images.githubusercontent.com/31751141/151103248-8345abf1-3ceb-437a-b167-0d73d624240b.mp4

**Comment by NghiaTranUIT** [comment]
Thanks. Your video is super useful for me to reproduce the bug 😄 

It's a bug. I assume that when the connection is stopped (Click on the Clear button), it's accidentally added to the main table view. It's incorrect behavior.

**Comment by ColtonIdle** [comment]
Thanks @NghiaTranUIT !

**Comment by NghiaTranUIT** [comment]
@ColtonIdle I tried to reproduce your issue on the latest build 3.3.0, but I'm not able to reproduce it.

It seems that this issues are fixed 👍

**Comment by ColtonIdle** [comment]
Awesome. Thank you @NghiaTranUIT !!!
