### ISSUE TITLE
[iOS App] Not detecting certificate installed

### ISSUE THREAD

**Issue by nouun** [ProxymanApp/Proxyman#1128]
### Proxyman version
1.5.6

### iOS Version
iOS 15.0 RC (19A344)

### Steps to reproduce
Install certificate following provided instructions.

### Expected behavior
Certificate to install and be detected inside of Proxyman. 

### Screenshots (optional)
![A6FDE497-532D-48F8-98F7-65A84BF9F7DC](https://user-images.githubusercontent.com/92670069/151300828-1afe46f4-e284-4408-b7d5-80def122ddca.png)
![0728191C-04D3-4F2D-B4ED-D2E3CFC033B1](https://user-images.githubusercontent.com/92670069/151300836-bf2ecf8f-277c-4025-9fdb-70a2c3303cea.png)
![24E8D8DA-FD6D-4FBD-B7B8-D6017B9432D2](https://user-images.githubusercontent.com/92670069/151300834-f27f02a2-3bc9-4405-b14c-6d6f2f1fbcb9.png)

**Comment by nouun** [comment]
I’ve tried reinstalling the app as well as deleting and regenerating the certificate several times.

**Comment by NghiaTranUIT** [comment]
Thanks for the report @nouun.

Technically, a sandboxed iOS app could not detect whether or not the self-signed certificate is installed and trusted in the System Keychain.

What the Proxyman app does is check if Proxyman can intercept an API call to Proxyman Server. Unfortunately, Proxyman server was down hours ago and it is now fully restored 👍  

@nouun please try again, I believe that it works 👍

**Comment by nouun** [comment]
Everything is working now, thanks for the update.
