### ISSUE TITLE
Curl requests made in terminal don't show in Proxyman

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1130]
### Steps to reproduce 
Make a curl request in terminal. Expect to see it in proxyman.

**Comment by NghiaTranUIT** [comment]
You have to use `--proxy localhost:9090` that tells curl to proxy the request to Proxyman @ColtonIdle. By default, curl doesn't use HTTP Proxy.

For example:
```
curl https://httpbin.org/get --proxy localhost:9090
```

It also applies to other HTTP Client too: https://docs.proxyman.io/debug-devices/http-clients

**Comment by ColtonIdle** [comment]
weird. i thought my mac had ALL traffic running through proxyman... hm. What else doesn't get funneled through proxyman by default?

**Comment by NghiaTranUIT** [comment]
Some apps don't respect the system HTTP proxy (such as curl, postman, insomnia, ...), so it goes straight into the Internet instead of Proxyman/CharlesProxy. We have to explicitly config.

**Comment by ColtonIdle** [comment]
Thank you! I'm still learning!
That is really interesting that some apps can just not respect the system proxy. I wonder if there's a way to "force" all traffic to always go through the proxy (im really interested in ALL of the data thats leaving my mac). I suppose somehow setting up a VPN would force all traffic to funnel through the vpn. I wonder if proxyman + vpn could work together to force all traffic?

**Comment by NghiaTranUIT** [comment]
You can force all traffic that goes through your server by using the VPN or Kernal Extension (it's what Little Snitch does). It monitors TCP/UDP in a transport layer.

To intercept HTTP/HTTPS traffic (which is the Application Layer), it's where Proxyman, Charles Proxy, and Fiddler be a player.

To make VPN apps work with Proxyman, it depends on what VPN app you're using. Here is a [Document](https://docs.proxyman.io/troubleshooting/proxyman-does-not-work-with-vpn-apps), which I've collected from Proxyman users.

**Comment by ColtonIdle** [comment]
thank you for teaching. I learned something new. cheers!
