### ISSUE TITLE
Suggestion to avoid requests.exceptions.SSLError

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1131]
When proxyMan is running and a request is sent from python requests, you get the following error:
```
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.HOST.com', port=443): Max retries exceeded with url: URL (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```
Clicking on pause button in Proxyman stops the data to be added to the lists in the app, but doesn't stop the listening. It could be nice if this button could stops listening too so we don't have to quit completely Proxyman each time we send a request. Thanks !

**Comment by NghiaTranUIT** [comment]
> Clicking on pause button in Proxyman stops the data to be added to the lists in the app, but doesn't stop the listening.

If you would like Proxyman to stop listening, you can toggle it at Tool -> Proxy Setting -> Override macOS Proxy. Or using OPTION+CMD+O as a shortcut.

---------------------------

Regarding the SSL Error from your python code, you have to tell your Python to use Proxyman Certificate. You can follow the Doc at https://docs.proxyman.io/debug-devices/python

**Comment by novitae** [comment]
amazing, thanks a lot !
