### ISSUE TITLE
MacOS 12.2: no content proxied

### ISSUE THREAD

**Issue by andig** [ProxymanApp/Proxyman#1133]
### Proxyman version? (Ex. Proxyman 1.4.3)

    Version 3.0.0 (30000)

### macOS Version? (Ex. mac 10.14)

    12.2

### Steps to reproduce 

1. Start PM
2. Ensure certificates are installed and MacOS Proxy overridden
3. Ensure capture started
3. Open google in Safari
<img width="269" alt="Screenshot 2022-02-02 at 08 33 23" src="https://user-images.githubusercontent.com/184815/152112145-dc2cc7ae-0df6-41cc-b1a6-57dc1e6e5666.png">

### Expected behavior

Expect requests intercepted. Actual behaviour is that proxyman does not see any requests. Apps/ Domains stays empty. This used to work before upgrading MacOS.

**Comment by NghiaTranUIT** [comment]
If you don’t mind, please open Proxyman. Then opening the System Preferences -> network -> Wifi -> advanced-> Proxies and see if HTTP HTTPS checkboxes are enabled?

**Comment by NghiaTranUIT** [comment]
Just wondering: do you use any VPN app?

**Comment by andig** [comment]
"Automatic Proxy Conf" is checked, the individual proxies are not. Unchecking "Automatic Proxy Conf" plus checking the proxy boxes (127.0.0.1:9090) plus retry does not fix it .

This is the ProxyMan Config:

<img width="554" alt="Screenshot 2022-02-02 at 08 53 22" src="https://user-images.githubusercontent.com/184815/152114511-09910975-99ac-4475-af5b-7b3285b3501d.png">

I'm using VPN, but service is disabled at this time and config did not change compared to yesterday.

**Comment by NghiaTranUIT** [comment]
Please install the Helper tool and try again 👍

**Comment by andig** [comment]
> Please install the Helper tool and try again 👍

It didn't seem mandatory. Done and no change. I'm really stumped:

<img width="564" alt="Screenshot 2022-02-02 at 09 03 42" src="https://user-images.githubusercontent.com/184815/152115737-82a0f4e7-404b-4b13-9bbb-7725f0a3890e.png">

**Comment by NghiaTranUIT** [comment]
Sorry for your trouble. Please quit and reopen Proxyman. The Helper tool will automatically enable the proxy

**Comment by andig** [comment]
Thanks @NghiaTranUIT. I'm sure I did restart. At some point after installing the helper, it started working again (I cannot trace it to a specific action). I still didn't get it working for python scripts despite using:

    SSL_CERT_FILE=~/proxyman.pem REQUESTS_CA_BUNDLE=~/proxyman.pem python3 script.py

Today, also that is working again. I'm stumped why.

Nevertheless, I'm grateful for your help and the good dev experience you're providing by linking from the certificate menu to the docs. 10/10!

**Comment by NghiaTranUIT** [comment]
maybe after executing these lines, you have to reload a bash.

I will keep an eye on your proxy issue and see if we can find a root of problem 👍
