### ISSUE TITLE
[Map-Local][Breakpoint][BUG] Map Local or Breakpoint don't work

### ISSUE THREAD

**Issue by YarikArsenkinDrest** [ProxymanApp/Proxyman#1142]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.1.0 (30100)

### macOS Version? (Ex. mac 10.14)
mac 12.2

### Steps to reproduce 
Map local doesn't work - I make the body have empty arrays, however, when I click on the request, I see that it wasn't "faked", it is an actual response from the server.
Breakpoints are not triggered either.

I am trying to fake the body for a query that ends with the `.gz`, if that has any relevance.

### Expected behavior
To be able to "fake" the response through the tool.

**Comment by NghiaTranUIT** [comment]
It seems that your matching URL is not correct, so both Map Local and Breakpoint don't work.

Can you share with me the matching URL that you're using to match all `.gz` requests? 🤔 

---------------------------

I suppose that it should be: 
- Use Wildcard
```
https://myserver.com/*.gz
```

**Comment by YarikArsenkinDrest** [comment]
I am using it like this for both tools: 
```
https://assets.company_url.com/static/models/v2/2022.02.10.09.18/17364522.gz
```

**Comment by NghiaTranUIT** [comment]
ah, the problem is Atlantis. When you're using Atlantis. It's not possible to use any debugging tool, unfortunately.

To use Map Local or Breakpoint, please [install & trust the certificate](https://docs.proxyman.io/debug-devices/ios-device) on your devices 👍

**Comment by YarikArsenkinDrest** [comment]
Oh man, what's the point of Atlantis then? 😅

**Comment by NghiaTranUIT** [comment]
Atlantis facilitates how you can quickly inspect the traffic without messing with the certificate.

However, there is a drawback, that debugging tools don't work.

**Comment by YarikArsenkinDrest** [comment]
Thanks for letting me know!

**Comment by YarikArsenkinDrest** [comment]
That resolves it, thank you!
