### ISSUE TITLE
Support Android Emulator and Android device Debugger

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#115]
## 🐶 Brief
It's time to support Android Emulator and Android device debugging 😄 

## 👑 Criteria
- [ ] Support Android Emulator and Android Device guideline 
- [ ] Logic for capturing all requests from Android Emulator (Install Certificate)
- [ ] Logic for capturing all request from Android Remote Device

**Comment by NghiaTranUIT** [comment]
On progress now 🚧

**Comment by NghiaTranUIT** [comment]
All done 

## 🤯 Changelogs 
- [x] Support Android debugging
- [x] Refactor layout for iOS and Android setup guide
- [x] Script to override proxy setting for Android N

<img width="860" alt="Screen Shot 2019-06-18 at 11 54 34" src="https://user-images.githubusercontent.com/5878421/59654320-ddf34700-91bf-11e9-847f-679d6cc91214.png">

**Comment by yauheniprakapenka** [comment]
Is it possible to use android **emulator** to intercept traffic from applications?

**Comment by NghiaTranUIT** [comment]
@yauheniprakapenka Sorry for the late reply. Yes, it's possible to use Proxyman to intercept Android apps from Emulator. I tested and work well with Android Studio Emulator and Blue Stack.

You can a Doc at https://docs.proxyman.io/debug-devices/android-device

**Comment by NghiaTranUIT** [comment]
It's tricky to install and trust the certificate on Blue Stack Emulator

**Comment by vjpr** [comment]
I actually couldn't get it working in the end. Seems like they have locked things down more.

**Comment by NghiaTranUIT** [comment]
@vjpr I highly recommend using Android Emulators from Android Studio, then you can run an automatic script to do it.

Doc: https://docs.proxyman.io/debug-devices/android-device/automatic-script-for-android-emulator

P/S: It uses `adb` CLI 😄

**Comment by vjpr** [comment]
Would this work for thirty-party apps?

**Comment by NghiaTranUIT** [comment]
This automatic script would help you to override the HTTP Proxy, download, install and trust the certificate with 1 click. 

You have to config two following files in order to see the HTTPS Content from your app:

1. res/xml/network_security_config.xml
2. AndroidManifest.xml

If you are not able to access the source code of the third-party app, you couldn't do it, unfortunately.
