### ISSUE TITLE
Breakpoint not working on a scripted request

### ISSUE THREAD

**Issue by W1MMER** [ProxymanApp/Proxyman#1153]
### Proxyman version?

3.1.0

### macOS Version?

11.5.2 (20G95)

### Steps to reproduce 

Have scripting running on a request that you're trying to intercept.

### Expected behavior

A breakpoint window should show up

I have a script running on all requests of a certain domain. I need to intercept one route so I've got a breakpoint setup there. However the breakpoint seems to be ignored and the request just carries on as normal. Charles doesn't do this with it's rewrite so I'm not sure why Proxyman isn't letting me modify the request. Is this a bug or a "feature"?

**Comment by NghiaTranUIT** [comment]
Unfortunately, we don't allow using Breakpoint after it's modified by the Scripting.

It's a small drawback, we will keep open your ticket and implement it soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @W1MMER let try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.3.0_Set_Breakpoint_after_scripting.dmg

From now, the request can be modified by the Script, then the Breakpoint 👍

**Comment by W1MMER** [comment]
Thanks! This works great. Good job.
