### ISSUE TITLE
Map remote work bad  with webpack devserver

### ISSUE THREAD

**Issue by WeiShengv99** [ProxymanApp/Proxyman#1155]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.1.0 (30100)

### macOS Version? (Ex. mac 10.14)
bigsur 11.6 (20G165)

### Steps to reproduce 
i am Front-end development engineer, 
i use map remote tool to help me dev in local. when i use webpack dev server with proxyman, i get some problem 

 something is break when my base url have query. 
if url looks like  `http://mydevhost.com/sdfsdf?foo=13`, it work fine,
if url looks like  `http://localhost:8080/?foo=13`, it work fine,
if url looks like  `http://127.0.0.1:8080/?foo=13`, it work fine,
but if url is `http://mydevhost.com/?foo=13` , it break with http code 400, i dont know what happen 

### Expected behavior
i dont know why http response is 400,how to fixed it.

### Screenshots (optional)
<img width="813" alt="image" src="https://user-images.githubusercontent.com/35689628/155494998-f26cd278-d008-4077-8e3e-bae5675c6fb4.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/35689628/155495339-48033644-5c2d-405e-a3d9-4f94c5a83a0d.png">

![image](https://user-images.githubusercontent.com/35689628/155495702-d70cf2d6-f6ea-41be-b9ae-f7691116495a.png)

![image](https://user-images.githubusercontent.com/35689628/155495765-7e14c782-29a1-4de7-9565-e9a53db88b15.png)

**Comment by NghiaTranUIT** [comment]
It seems a bug from Map REmote.

Can you try again with the Scripting?

## Scripting
```js
function onRequest(context, url, request) {
  // console.log(request);
  console.log(url);

  request.scheme = "http"
  request.host = "127.0.0.1"
  request.port = 8080;

  // Done
  return request;
}
```

<img width="1456" alt="Screen Shot 2022-02-24 at 20 43 41" src="https://user-images.githubusercontent.com/5878421/155535514-02678250-b623-4714-a9d1-6fcd0947f3e6.png">

**Comment by WeiShengv99** [comment]
> ```js
> function onRequest(context, url, request) {
>   // console.log(request);
>   console.log(url);
> 
>   request.scheme = "http"
>   request.host = "127.0.0.1"
>   request.port = 8080;
> 
>   // Done
>   return request;
> }
> ```
Yes , this script reslove my problem,its  awsome.

**Comment by raxityo** [comment]
@NghiaTranUIT I just ran into this issue and was wondering if you have any plans on fixing the Map Remote to support query parameters on the root domain.
