### ISSUE TITLE
Shortcut to toggle External Proxy

### ISSUE THREAD

**Issue by ilendemli** [ProxymanApp/Proxyman#1156]
Hey!

Is there a shortcut to toggle External Proxy on and off?
Like cmnd+option+O to toggle the Proxy Override on and off.

If not, may I suggest to add this functionality?

Best regards!

**Comment by NghiaTranUIT** [comment]
Sorry but we don't have the shortcut to enable/disable the External Proxy.

However, your suggestion is reasonable. Let me implement it and send you a beta build soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @ilendemli please try this build beta build if you don't mind: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.3.0_Toggle_External_Proxy_Tool.dmg

From now, you can toggle the external proxy by using the shortcut: CMD+OPTION+E 👍

**Comment by ilendemli** [comment]
@NghiaTranUIT Works great! Thank you! Only thing I noticed is, if you have the External Proxy Settings screen open and toggle it using the shortcut, the checkmark is not being toggled, but that is just a minor ui thing.
