### ISSUE TITLE
Typo on Protobuf message type window: Mesasge instead of Message

### ISSUE THREAD

**Issue by rpassis** [ProxymanApp/Proxyman#1169]
### Proxyman version? (Ex. Proxyman 1.4.3)

Version 3.2.0 (30200)

### macOS Version? (Ex. mac 10.14)

12.3 Beta (21E5227a)

### Steps to reproduce 

See screenshot attached below

### Screenshots (optional)

<img width="786" alt="image" src="https://user-images.githubusercontent.com/387079/157792362-a1271cd6-7ef9-4bf9-9322-0423d11cdb13.png">

**Comment by NghiaTranUIT** [comment]
Thanks. Consider it's fixed 👍

**Comment by rpassis** [comment]
Fixed!
