### ISSUE TITLE
Pause does not remove proxy

### ISSUE THREAD

**Issue by CyberMew** [ProxymanApp/Proxyman#1176]
Not sure if this is intended, but pausing still show the proxy being used in network settings. This is causing issues with other apps where I really need the proxy to be removed. Is the only way out of this is to quit the app?

**Comment by NghiaTranUIT** [comment]
Pause is just stopped adding new requests/responses to the app.

If you'd like to stop the Proxy, you can go to Tools -> Proxy Setting -> Override HTTP Proxy. Or using the shortcut: ⌥⌘O

**Comment by CyberMew** [comment]
Thanks! I found the next best thing - configuring toolbar to show the stop button (or rather, the Wifi icon). The toolbar icons are so convenient, can't believe I have been pressing option+cmd+b to turn on/off since there is no shortcut like the override http proxy.

<img width="400" alt="CleanShot 2022-03-18 at 15 36 00@2x" src="https://user-images.githubusercontent.com/4715911/158957134-88aab224-490e-455e-a4d2-08f8510e3849.png">
