### ISSUE TITLE
same title .proxymanlog files not being loaded

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1195]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.3.0
### macOS Version? (Ex. mac 10.14)
12.0.1 
### Steps to reproduce 
export two Proxyman logs with the exact same name in two different directories, then close Proxyman and load these two logs.
### Expected behavior
Only one should show up (probably because they have the same name)

**Comment by NghiaTranUIT** [comment]
@novitae I've fixed your issue. If you don't mind, let try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.3.0_Allow_Open_Same_File.dmg

**Comment by novitae** [comment]
It works 👌
<img width="186" alt="Capture d’écran 2022-04-14 à 10 50 56" src="https://user-images.githubusercontent.com/85891169/163349711-4b71da3a-463e-44b8-b5e4-f8858e031ee3.png">
