### ISSUE TITLE
Anonfiles.com traffic not recorded on safari

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1201]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.3.0
### macOS Version? (Ex. mac 10.14)
12.3
### Steps to reproduce 
record traffic on Proxyman, open safari, and go to https://anonfiles.com
### Expected behavior
the site traffic shouldn't be recorded in Proxyman

I have no idea if it comes from me or not, but I use Proxyman for a long time ago and never had problems like this. The traffic is just not appearing at all for this website, while it does for all others.

**Comment by NghiaTranUIT** [comment]
It seems it works for me. I can see this traffic.

<img width="1624" alt="Screen Shot 2022-04-10 at 17 39 44" src="https://user-images.githubusercontent.com/5878421/162614275-00321b98-fc0a-4607-a295-9a3a7b6cd9a6.png">

----------------
If you could not see it, it might be in the bypass list. Can you check:
1. Make sure this domain is not in Block List Tool (Hide, but not Block)
2. Network Preference -> Wifi -> Advanced -> Proxies Tab -> Bypass Proxy List

**Comment by novitae** [comment]
very weird, thanks for your help I thought it was a bug for everyone !
