### ISSUE TITLE
[Enhancement] Alphabetical order for pinned domains

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1215]
It could be nice if the paths or the pinned domains could be sorted alphabetically. When it starts to be a lot, it becomes more and more complicated to find a specific path in it. Thanks !
<img width="177" alt="Capture d’écran 2022-04-25 à 18 01 16" src="https://user-images.githubusercontent.com/85891169/165128116-7f3133e6-383a-4330-8f98-7099ccfc6baa.png">

**Comment by NghiaTranUIT** [comment]
Hey @novitae let's try this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.4.0_Sort_domains_and_paths_by_alphabet_order.dmg

You can enable the "Auto Sort by alphabet order" in the Preference -> Advance tab.

It will also sort all sub-paths of the current domain too 👍

**Comment by novitae** [comment]
It works, thanks !

But there's something ... When we activate the option but there's already some requests that have been made, the older domains won't be sorted. See below with `/status` that have been made before the sorting activation, and staying in the middle. I don't think it is very important but I am telling you anyway.

<img width="186" alt="Capture d’écran 2022-04-26 à 10 46 33" src="https://user-images.githubusercontent.com/85891169/165260922-fd4e423c-2283-4275-bfd4-a135f41d6d41.png">

**Comment by NghiaTranUIT** [comment]
Ah thanks. I will look on it 👍
