### ISSUE TITLE
Unable to install SSL certificate to KeyChain

### ISSUE THREAD

**Issue by csanivar** [ProxymanApp/Proxyman#1221]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.4.0
### macOS Version? (Ex. mac 10.14)
12.3 (Intel Chip Mac)
### Steps to reproduce 
When I try to install the certificate it shows the loading icon and doesn't finish.
If I download and certificate and try to install it manually, KeyChain hangs with the loading icon.
### Expected behavior
I should be able to install the SSL certificate for SSL proxying.

**Comment by NghiaTranUIT** [comment]
Hey, it seems your Keychain app has a problem when adding a new certificate.

Just wondering: Are you an admin of your devices? or a Guest user?

I tested it on macOS 12.3.1 and it works fine (both auto and manual)

**Comment by NghiaTranUIT** [comment]
If you don't mind, please follow this guideline to manually generate a certificate, and add it to your Keychain system. (Don't forget to trust it too): https://docs.proxyman.io/advanced-features/custom-certificates#6.-how-to-generate-self-signed-certificates-for-custom-root-certificate-that-comply-with-new-apples

**Comment by csanivar** [comment]
I am not a Guest user. I have all the root privileges but this is a work machine though. Not sure if there any restrictions from _work_ side. 
I will try to generate a manual certificate and try.
Thanks

**Comment by csanivar** [comment]
So it worked after I restarted my Mac. 
When you try to install a certificate Key Chain was support to ask for password, but previously it wasn't asking me and was hanging at that part.
But after restarting, the prompt was shown and I was able to add the certificate without any problems.
