### ISSUE TITLE
No Internet Connection after configuring proxy settings on iPhone 

### ISSUE THREAD

**Issue by khaptonstall** [ProxymanApp/Proxyman#1232]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.4.0

### macOS Version? (Ex. mac 10.14)
12.3.1

### Steps to reproduce 
1. Install Proxyman on macOS
2. Open iOS Setup Guide
3. Install and trust Root Certificate
4. Follow steps to configure Wifi settings on iPhone (iOS 15.3.1) 
5. Open Safari
6. Navigate to proxy.man/ssl
7. Unable to connect

Additionally:
- I cannot connect to _any_ website after performing these steps
- iOS Wifi settings for my connected network now show "No Internet Connection"
- I'm on a home network (not a corporate network)

This was working just fine for me yesterday (in fact I've been using Proxyman without issue for months on these two devices). I also tried the same steps using my iPhone on a separate MacBook, and then tried the same steps on both MacBooks with a new iPhone, but kept hitting the same issue.

Also went through all steps in the [Troubleshooting](https://docs.proxyman.io/troubleshooting/my-ios-devices-couldnt-connect-to-proxyman-via-proxy) guide to verify my setup is correct.

### Expected behavior
I'm able to download and install a certificate, then view iPhone traffic on my Mac.

Please let me know what additional info (if any) that I could provide in order to help debug this.

**Comment by khaptonstall** [comment]
**Update:** I tested this out by switching my devices to a new network (using a personal hotspot) and everything between the iPhone and Mac work as expected. 🤔 

My home network is using Xfinity and their [xFi Advanced Gateway (XB7)](https://www.xfinity.com/support/articles/broadband-gateways-userguides).

**Comment by khaptonstall** [comment]
I ended up restarting my router and the issue has resolved 🎉

**Comment by NghiaTranUIT** [comment]
Glad to know that you've resolved it 🎉 

Sometime, restart the router does the trick 😄
