### ISSUE TITLE
iPhone Full Trust For Root Certificates 999 issue

### ISSUE THREAD

**Issue by pedro380085** [ProxymanApp/Proxyman#1233]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 3.4.0 (30400)

### macOS Version? (Ex. mac 10.14)
Mac 12.3.1

###Description
Hi there, when I am trying to enable. As soon as I complete all the steps, including the Trust Root Certificate as per the installation guidelines for iOS, I don't get any other request to be successful when using the apps. The Chrome and Safari browsers both continue to work. Just the native apps that don't work anymore.

### Steps to reproduce 
Launch proxyman
Monitor the logs
See 999 error

### Expected behavior
Show proper return code instead of 999

### Screenshots (optional)
<img width="1300" alt="Screen Shot 2022-05-13 at 15 00 27" src="https://user-images.githubusercontent.com/1212753/168374015-2af96a8e-1e1a-44f2-8629-441976e9ea69.png">

**Comment by NghiaTranUIT** [comment]
hey @pedro380085 if you can intercept HTTPS traffic from GoogleChrome/Safari on your iOS device, it means you set up everything correctly 👍 

The reason why you get a lot of 999 SSL Errors on the Facebook, and Instagram apps is that these apps are protected by SSL Pinning. SSL Pinning is a security mechanism that prevents the app to be intercepted by any MitM apps.

There is no way to bypass the SSL Pinning unless you have their private key.

You can read more at https://proxyman.io/posts/2019-11-15-Can-we-bypass-ssl-pinning

**Comment by NghiaTranUIT** [comment]
Just clarify that all well-known apps, such as FB, IG, Whatapps, iTunes, AppStore, etc have SSL Pinning.

**Comment by pedro380085** [comment]
Thank you for your comment and explanation. I appreciate your time.
