### ISSUE TITLE
Can I import *.saz file to proxyman?

### ISSUE THREAD

**Issue by qq2519157** [ProxymanApp/Proxyman#1252]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 3.5.2 (30520)
### macOS Version? (Ex. mac 10.14)
Mac OS 12.4
### Steps to reproduce 
there is a situation that someone who used Windows and fiddler sent me a saz file to be debug . how can i open it in my proxyman?

**Comment by NghiaTranUIT** [comment]
Proxyman doesn't support the SAZ file.  You can ask your teammate to export the HAR file from Fiddler. Then, you can open it with Proxyman app 👍

**Comment by qq2519157** [comment]
cool，it really works！thank you so much!
