### ISSUE TITLE
Websockets not intercepted by breakpoints

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1253]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.5.2
### macOS Version? (Ex. mac 10.14)
12.3
### Steps to reproduce 
- Find a process that uses websockets that are visible in Proxyman
- Add the  `wss://...` url in breakpoints
- Restart the websocket connection
### Expected behavior
The websocket connection request is not intercepted by the breakpoint

**Comment by NghiaTranUIT** [comment]
Sorry to say that Proxyman doesn't support Breakpoint with Websocket connection.

We might support it later if we have more requests.
