### ISSUE TITLE
No SSL traffic with iOS Simulator 15.5

### ISSUE THREAD

**Issue by MediaComputing** [ProxymanApp/Proxyman#1254]
### Steps to reproduce 

XCode 13.4.1, iOS Simulator with OS 15.5
Certificate is installed on simulator as usual and is also marked as trusted within the simulator. 
When running my application I only see the following message as response:

"It could be SSL Certificate Pinning, or try installing CA Certificate on iOS Simulators again (code=999)"

### Expected behavior

See any SSL traffic as before. 
With any iOS 15.4 simulator it is still working as expected.

**Comment by NghiaTranUIT** [comment]
Not sure what causes your problem.

I tested with iOS 15.5 on Xcode 13.4.1, on the [Alamofire Example](https://github.com/Alamofire/Alamofire) app. It works fine.

<img width="1512" alt="Screen Shot 2022-06-16 at 08 48 27" src="https://user-images.githubusercontent.com/5878421/173973977-73ca5ae3-378e-47f3-9f5a-92df3c849cf9.png">

If you don't mind, please download this source, open `Example/iOS Example.xcodeproj`, and try to install the certificate on your iOS Simulator. 

Make sure you: Device -> Erase all Content & Data 👍

**Comment by NghiaTranUIT** [comment]
Glad to know it fixes. I suppose that the certificate on your iOS device might be expired. `Erase the device` will do the trick 👍
