### ISSUE TITLE
When will the Chinese version be available?

### ISSUE THREAD

**Issue by jiayouzl** [ProxymanApp/Proxyman#1257]
When will the Chinese version be available?

**Comment by NghiaTranUIT** [comment]
Sorry, we don't have any plan to support Chinese Localization at the moment. We might support it soon if we have more requests.

**Comment by jiayouzl** [comment]
.

**Comment by NghiaTranUIT** [comment]
Hey @jiayouzl , sorry for the late updates:

Here is the good news: Chinese Simplified localization is added, but we need your help to test it. Please check out this comment: https://github.com/ProxymanApp/Proxyman/issues/1326#issuecomment-1285148612

**Comment by jiayouzl** [comment]
> Hey @jiayouzl , sorry for the late updates:
> 
> 
> 
> Here is the good news: Chinese Simplified localization is added, but we need your help to test it. Please check out this comment: https://github.com/ProxymanApp/Proxyman/issues/1326#issuecomment-1285148612

I'm out right now. I'll test it when I get home.
