### ISSUE TITLE
Integer values become float ones by using scripting

### ISSUE THREAD

**Issue by torokdnl** [ProxymanApp/Proxyman#1261]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman Version 3.6.0 (30600)

### macOS Version? (Ex. mac 10.14)
macOS Monterey 12.3.1 (21E258) 
macOS Monterey 12.4 (21F79)

### Steps to reproduce 
1. Turn on scripting (in my case it's a simple if-else what colors the request/responses)
2. Get your request with the original integer value (in my case it's a "randomTimestamp")

Original value: 1655989280365

I can see this value in the following requests like this:
- Without the scripting: 1655989280365
- With the scripting: 1655991846719.0002

### Expected behavior
The original value should be kept until the script modifies it (or the tester manually overwrites it).

**Comment by NghiaTranUIT** [comment]
Look like it's a different issue, when passing this big int to JavascriptCore, it might be converted improperly.

I will check it out 👍

**Comment by torokdnl** [comment]
@NghiaTranUIT - 

The build is working correctly, integers remain integers. Thanks a lot for fixing it quickly and for the explanation as well!
