### ISSUE TITLE
changed  code signature in macOS version 3.6.0?

### ISSUE THREAD

**Issue by suschizu** [ProxymanApp/Proxyman#1262]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.6.0

### macOS Version? (Ex. mac 10.14)
11.6.7

### Steps to reproduce 
codesign -dv --verbose=4 /Path/To/Application.app

Hello - I've received a warning that the code signature has changed between v 3.5.1 and 3.6.0

EXPECTED 
TablePlus Inc (3X57WP8E8V) 
but FOUND 
Pham Huy (3X57WP8E8V)

can you confirm this?

Thanks!

**Comment by NghiaTranUIT** [comment]
Oh no, it's my mistake. The latest build is archived by my new Macbook, so it uses the old Developer ID certificate. They are both the same Team ID (3X57WP8E8V), so there is no major change.

I'm going to archive again and update the build.

**Comment by NghiaTranUIT** [comment]
Hey @suschizu I've updated the new build with the correct code signing 👍 

You can download the latest build again at https://proxyman.io/release/osx/Proxyman_latest.dmg

**Comment by suschizu** [comment]
Great thanks a lot :)
