### ISSUE TITLE
proxy.man/ssl is not loading when trying to install certificate on iOS Device

### ISSUE THREAD

**Issue by mrk-han** [ProxymanApp/Proxyman#1266]
**Proxyman version? (Ex. Proxyman 1.4.3)**

Version 3.6.0 (30600) Free Version

**iPhone Version:**
iOS 15.5

**macOS Version? (Ex. mac 10.14)**

12.3.1 Monterey 

**Steps to reproduce**

- Install Proxyman fresh

- Install and trust root certificate via Certificates menu
 
- Load iOS help screen by selecting "Install certificate on iOS devices"
 
- Follow the instructions, have devices on same internet connection, and when accessing proxy.man/ssl on the device, the request hangs. 
 

**Expected behavior**

The application delivers the certificate to the iOS device for installation.

**Comment by NghiaTranUIT** [comment]
Hey, there are many things can cause this issue, such as the Firewall option, incorrect IP, the VPN app, etc.

Please checkout this troubleshooting which I collect all common issue: https://docs.proxyman.io/troubleshooting/my-ios-devices-couldnt-connect-to-proxyman-via-proxy

**Comment by mrk-han** [comment]
Double checking all of these now, will respond soon

**Comment by NghiaTranUIT** [comment]
> Stealth mode turned on above might be the reason?

Yes, probably, please try turning it off, and make sure no VPN app on both iOS and macOS apps.

Not sure what iOS version you're using? If you're using iOS 16 beta 1, you might encounter this issue because the Beta build is buggy.

**Comment by mrk-han** [comment]
I'm on 15.5 -- I'm going to double check our company has port 9090 unblocked, or maybe try changing to Charles' default port cause I know that's open -- and I'll try to turn off stealth mode, but it looks like it's controlled by security software.

**Comment by mrk-han** [comment]
Thanks for the incredibly fast response by the way, I am loving Proxyman (just been only using it with simulators until this point). It is a game changer.

**Comment by NghiaTranUIT** [comment]
If Charles works fine, you can check what port the Chares is running. Then you can set Proxyman to this port (in Preference -> Port Number). I guess the security team might block Charles's port (8080).

> Thanks for the incredibly fast response by the way, I am loving Proxyman (just been only using it with simulators until this point). It is a game changer.

Appreciate it  🙌 😄

**Comment by mrk-han** [comment]
Got everything working! It was likely some wifi configuration thing on my work's  network. Everything worked perfectly on my home wifi.

Thanks for your help!

**Comment by NghiaTranUIT** [comment]
Glad to hear that 👍

**Comment by esquillidd** [comment]
I'm having the same issue. After some debugging, the issue is because of iOS 16. Is there anything that I can do or just wait?
