### ISSUE TITLE
How to edit POST body in Map Local tool?

### ISSUE THREAD

**Issue by amorphius** [ProxymanApp/Proxyman#1269]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 3.6.0

### macOS Version? (Ex. mac 10.14)
mac 12.3.1

### Steps to reproduce 
1. Create Map Local for any of POST request/response that has non-empty body
2. In Map Tool observe that response is saved and can be edited but not POST request itself

### Expected behavior
Is it possible to edit request and particularly body of POST request in Map Local tool?

**Comment by NghiaTranUIT** [comment]
No, it's not possible to edit the **request** because Map Local is for the Response.

If you'd like to modify the Request, please try using Scripting or Breakpoint.

You can check out the Snippet code: https://docs.proxyman.io/scripting/snippet-code
