### ISSUE TITLE
Every request from my (atlantis) iOS 16 app is remaining active once it's completed

### ISSUE THREAD

**Issue by chrismash2** [ProxymanApp/Proxyman#1271]
### Proxyman version?
Proxyman App: 3.6.0
Proxyman Atlantis: 1.17.0

### macOS Version?
macOS 12.4

### Steps to reproduce 
Launch iOS project in Xcode 14 (beta 1, maybe 2 as well) and launch on an iOS 16 simulator. All network requests will function correctly within the app but be left marked as active, with no response data, in Proxyman. Using an iOS 15.5 simulator (in Xocde 13 or 14) the network requests transition to their correct final state

Note: The project _might_ need to use Atlantis exclusively for capturing the network traffic, with Proxyman's 'auto override system proxy configs at launch time' disabled

### Expected behavior
The network requests should update to their correct final state and show response data

### Screenshots (optional)
iOS 15.5
![Screenshot 2022-06-27 at 15 46 12](https://user-images.githubusercontent.com/64631051/175969407-a19590dc-f6de-48f4-b260-b3ab93a6f37c.png)

iOS 16
![Screenshot 2022-06-27 at 15 46 26](https://user-images.githubusercontent.com/64631051/175969424-b95845e9-fa91-46f7-baa3-5d253aaeacf5.png)

**Comment by NghiaTranUIT** [comment]
I'm able to reproduce the issue on iOS 16 + Xcode 14 beta too. Gonna fix it now 🙌

**Comment by chrismash2** [comment]
such speed :D

**Comment by NghiaTranUIT** [comment]
@chrismash2 I've fixed the issue on iOS 16. Please update the Atlantis to [1.18.0](https://github.com/ProxymanApp/atlantis/releases/tag/1.18.0)

![Proxyman iOS 16](https://user-images.githubusercontent.com/5878421/176119369-b861750c-6346-43f4-b37e-6871b984ddf0.jpg)

**Comment by chrismash2** [comment]
Just had a chance to confirm this, kudos on the super fast turnaround, impressive and appreciated!
