### ISSUE TITLE
[Feature Request] Set different protobuf message type for request and response of same url

### ISSUE THREAD

**Issue by jjmean2** [ProxymanApp/Proxyman#1281]
Hello. 
I love new feature that supports protobuf File Descriptor!
My server has lots of proto files and it was hard to add proto files in proper order, so I can't use protobuf viewer before 3.6.0, and finally I succeed import proto spec into Proxyman in version 3.6.0! I appreciate it!

But my server api use different message type for request and response, and I cannot find how to set different message type for request and response in same url. Is it not possible in current version? if so, it would be very helpful if this feature updated. Thanks!

### Proxyman version?
Proxyman 3.6.0

### macOS Version?
mac 12.4

**Comment by NghiaTranUIT** [comment]
It's not possible to set multiple message types to a single URL.

Just wondering: 
1. Does your request/response use either message type at once or use both of them?
2. What is your current solution? From what I know, Charles Proxy only supports a single message type (like Proxyman)

**Comment by jjmean2** [comment]
Thanks for reply!

1. it uses both of them.
For example, I have an API to book a hotel booking, and its message type for request is about input values for booking and its message type for response is about booking result.
I can view proto field name in only either of request or response because I can set only one message type of them.

2. I also use Charles Proxy, and I can set message type for request and response separately.

![176576060-7cf69208-cb5b-4c0f-97d0-024fb78d5472 복사본](https://user-images.githubusercontent.com/11574475/176576332-0923d678-453e-4c69-8fb5-62082cdb79e3.png)

**Comment by NghiaTranUIT** [comment]
Ah, I understand. I'm going to implement this feature and send you a Beta build soon 👍

**Comment by jjmean2** [comment]
Oh! Thanks, I appreciate it 🙏

**Comment by NghiaTranUIT** [comment]
@jjmean2 let's try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.6.0_Protobuf_Support_Message_type_for_request_and_response.dmg

From now, you can define each MEssage Type for the Request and Response 👍 

### Screenshot
![Screen_Shot_2022-07-01_at_10_31_01](https://user-images.githubusercontent.com/5878421/176819326-745d173d-2899-4add-ad99-e3b97c2b4a7c.jpg)
![Screen_Shot_2022-07-01_at_10_29_59](https://user-images.githubusercontent.com/5878421/176819340-ff1672f4-024a-443c-8441-7222f106aab2.jpg)

**Comment by jjmean2** [comment]
It works like a charm! 👍 
Thanks for your work~
