### ISSUE TITLE
[Bug] Multiple "View As" entries present in Filter text field context menu

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#1284]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.6.0 (30600)
### macOS Version? (Ex. mac 10.14)
macOS 12.4
### Steps to reproduce 
No STR

I saw multiple (I think it was 4) "View as" menu items in the context menu for the Filter text field. I'm not sure how to reproduce it, and unfortunately, I didn't think to grab a screenshot when I first saw this. I restarted Proxyman to see if it would clear, and it did. Proxyman had been running for a day or two without a restart before this happened.

### Screenshots (optional)
Screenshot doesn't show the issue, just including to illustrate the affected menu.

![CleanShot 2022-06-30 at 15 47 14](https://user-images.githubusercontent.com/1638278/176791101-48920d4b-a909-4f52-93fa-01b7070a55a2.png)

**Comment by NghiaTranUIT** [comment]
Yes, I've noticed this issue too. Sometimes, there are 2 View As menus when right-clicking on the Body. I will check it out and fix it 🙌

**Comment by NghiaTranUIT** [comment]
It's fixed 🙌 https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.6.0_Support_Header_Size.dmg
