### ISSUE TITLE
Breakpoint window is drawn incorrectly if Proxyman theme is set differently than system

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#1295]
If Proxyman is set to Dark mode and system is set to Light mode, the Breakpoint window is themed incorrectly (see screenshot). This also happens if the themes are reversed.

I didn't observe the issue on any other Proxyman windows.

The workaround is to set Proxyman and macOS to use the same theme.

### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.6.2 (30620)
### macOS Version? (Ex. mac 10.14)
macOS 12.4
### Steps to reproduce 
1. Set Proxyman to Dark theme 
2. Set macOS to Light theme
3. Set a breakpoint for *example.com
4. Visit example.com from a proxying device
5. When breakpoints triggers, observe Breakpoint window theme
### Screenshots (optional)
![proxyman-breakpoint-theme](https://user-images.githubusercontent.com/1638278/179261385-34d5f03f-980a-48fb-a197-d7c7eddeb95e.png)

**Comment by NghiaTranUIT** [comment]
Yes, it's fixed at https://github.com/ProxymanApp/Proxyman/issues/1291#issuecomment-1179461942

I'm going to release a build this weekend 🙌
