### ISSUE TITLE
writeToFil Unable to append file in new line（想要在文件追加信息）

### ISSUE THREAD

**Issue by jihtsan** [ProxymanApp/Proxyman#1298]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 3.6.2
### macOS Version? (Ex. mac 10.14)
Mac（12.4）
### Steps to reproduce 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/20720673/179355220-34e6ac76-979a-4c2a-9cdd-cc5aeeb68087.png">

but after the response file is：
<img width="593" alt="image" src="https://user-images.githubusercontent.com/20720673/179355294-199297d3-6022-4823-9002-1c91ffe5aa8a.png">

### Expected behavior
1. response body append in target file and have new line;

**Comment by NghiaTranUIT** [comment]
@jihtsan please provide the `var opt = {appendFile: true}` to the `writeToFile`

```js
async function onResponse(context, url, request, response) {

  // Append to the existed file
  // Or create a new file if it doesn't exist
  var opt = {appendFile: true}
  writeToFile(response.body, "~/Desktop/body.json", opt);

  // Done
  return response;
}
```

If you don't provide the `opt`, it will override the file 👍 

Ref: https://docs.proxyman.io/scripting/snippet-code#write-export-to-a-local-file

**Comment by jihtsan** [comment]
I think , but this code didn't in new line ,so i want to append '\n' .

**Comment by jihtsan** [comment]
![Uploading image.png…]()

this can fix it.
response.body is jsonobject , i didnt know how to convert to jsonString

**Comment by jihtsan** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/20720673/179455375-9562d2ec-0b60-4119-b004-65783a8abecb.png">
