### ISSUE TITLE
[Feature] Add the ability to sort JSON keys in diff view

### ISSUE THREAD

**Issue by travisstraub** [ProxymanApp/Proxyman#1304]
When comparing JSON bodies from two different requests/responses, sometimes the keys/values are present, but not always returned in the same order. This causes the diff to show differences where they may not necessarily exist. Is there a way to sort keys in Proxyman currently, or can this feature be added? Thanks in advance! 

Proxyman Version 3.7.0 (30700)

**Comment by NghiaTranUIT** [comment]
Thanks for the suggestion @travisstraub, since it's a trivial changes, I gonna add it and send you a Beta soon 🙌

**Comment by travisstraub** [comment]
Excellent, thank you so much!

**Comment by NghiaTranUIT** [comment]
@travisstraub Good news, let's try this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.7.0_Diff_Sorting_JSON_Key.dmg

You can enable the Sorting JSON Key in the Diff Option Dropdown button (Default is off) 👍 

### Screenshots
![Screen_Shot_2022-07-24_at_14_22_47](https://user-images.githubusercontent.com/5878421/180637223-f98b5b4c-212d-44a2-bb7f-86db2b80318c.jpg)
![Screen_Shot_2022-07-24_at_14_22_57](https://user-images.githubusercontent.com/5878421/180637227-9b3cb73c-4704-4995-ab46-0923b095b9f0.jpg)

**Comment by travisstraub** [comment]
Works great, thanks @NghiaTranUIT !
