### ISSUE TITLE
Proxyman support network interface switch

### ISSUE THREAD

**Issue by JamesWDGu** [ProxymanApp/Proxyman#1310]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.7.0 (30700)

### macOS Version? (Ex. mac 10.14)
macOS 12.5

### Expected behavior
I have multiple network, they are independent. At this time, I can't decide which network to capture in Proxyman, unless I disable others network. It's very inconvenient for me.

**Comment by NghiaTranUIT** [comment]
Can you list how many and name of network interfaces? Currently, Proxyman would override all of them

**Comment by JamesWDGu** [comment]
Hi @NghiaTranUIT,
I checked, you are right, all interfaces has been overrided. I thought only the network interface shown at the top of the panel had been override.

Thanks your support !!!
