### ISSUE TITLE
Proxyman not quitting/force-quitting in a reasonable time, hanging in dock

### ISSUE THREAD

**Issue by carstenhag** [ProxymanApp/Proxyman#1317]
### Proxyman version? (Ex. Proxyman 1.4.3)
 3.7.0

### macOS Version? (Ex. mac 10.14)
12.4, m1 pro macbook

### Steps to reproduce 
1. Open Proxyman
2. Quit/Close Proxyman entirely (command+q)
3. Proxyman window closes, but the program itself is still running in the dock. Rightclicking, it tells me proxyman is hanging. Force quititing does not help either. After ~20 seconds, proxyman is finally closed

### Expected behavior
Proxyman quits in <2 seconds

#### Further details

The helper tools is installed. I can consistently reproduce this issue.  
With previous version & afaik also with my previous macbook (intel-based) I had the same issue.

**Comment by NghiaTranUIT** [comment]
Hmm, it's odd. The app opens/closes fine on my machine and other users (No report so far on this issue).

1. Preference -> Advanced -> Uninstall helper tool.
2. Help Menu -> Advanced -> Factory Reset
3. Does it fix 🤔 ?

When closing the app, the Helper Tool will try to revert the proxy, it might make the app unresponsive. If we uninstall it, it just reverts the proxy by using a `networksetup` command line.

I have some questions to investigate:
1. Are you using any VPN apps? I suppose that it might conflict at some point.
2. Is it a Setapp build or the app, which is downloaded from the Proxyman website?

**Comment by carstenhag** [comment]
Just tried uninstalling & installing the helper tool, that seems to have helped. Weird. I will try it out the next days after using the VPN and so on.

I'm using Cisco AnyConnect, but currently don't have a VPN session active.  
I downloaded Proxyman from your website.

**Comment by carstenhag** [comment]
I'll close this issue and re-open if I have issues again :) Thank you!

**Comment by NghiaTranUIT** [comment]
Thanks. Let me know again if it still happens 🙌
