### ISSUE TITLE
Scripting console output visible through bottom tool area

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#1325]
The tools at the bottom of the scripting console can be obscured by console logs.

### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.7.0 (30700)
### macOS Version? (Ex. mac 10.14)
macOS 12.5
### Steps to reproduce
1. Enable a script and trigger it using any method
2. Repeat until console is full (can help to shorten window, or add a console.log statement that output lots of text) 
3. Observe console output is behind the console bottom tools (see screenshot)
### Expected behavior
Console bottom toolbar should be above console logs
### Screenshots (optional)
![scripting-console-tools](https://user-images.githubusercontent.com/1638278/183223687-5fad5753-8dab-417c-953d-94118b7f0b80.png)

**Comment by NghiaTranUIT** [comment]
Thanks 🙌 Going to fix on the next release ✅

**Comment by NghiaTranUIT** [comment]
Fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.7.0_Fix_Scripting_layout.dmg

![Screen_Shot_2022-08-06_at_19_14_32](https://user-images.githubusercontent.com/5878421/183249168-f788d2c2-0476-4cdd-b977-ef0282c07103.jpg)
