### ISSUE TITLE
Couldn't capture any traffic

### ISSUE THREAD

**Issue by mehmetugur-gural** [ProxymanApp/Proxyman#133]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
Latest : 1.3.6
### What OS Version are you using? (Ex. mac 10.13)
Mojave 10.14.4
### Steps to reproduce this issue
- Make a fresh install from website
- Start application
- Application started, listening on port 9090
- App can not capture any traffic for both app and traffic sections, list is empty.
### Screenshots (optional)
<img width="1440" alt="Screen Shot 2019-04-29 at 21 04 10" src="https://user-images.githubusercontent.com/22577614/56916821-8b9c8080-6ac2-11e9-89b7-99c296eaede5.png">

**Comment by joanbono** [comment]
Try the following in your terminal with Proxyman listening on port 9090: 

```bash
$ curl -x "http://localhost:9090" -L -X GET https://github.com
```

**Comment by NghiaTranUIT** [comment]
Hey @mehmetugur-gural , thank for reaching out to me.

Ideally, Proxyman automatically override the Proxy Configuration in Network Preference. However if there is no request, it means that something wrongs, and my script couldn't override it appropriately 🤔  .

1. You can by-pass the bug by overriding manually the Proxy of your network to port `9090` (See the screenshot)
2. Can you help me: What kind of network device are you using? Wifi or Ethernet or iPhone-sharing?
I will investigate it 

## Screenshot
<img width="780" alt="Screen Shot 2019-04-30 at 17 07 33" src="https://user-images.githubusercontent.com/5878421/56955107-a88c8e80-6b6a-11e9-9d22-7ca303956fa3.png">

**Comment by mehmetugur-gural** [comment]
Hi @NghiaTranUIT, thanks for the quick response. I tried to answer your questions below :

1 - When i first ran the application, it successfully updated the proxy configs, you can see in the screenshot, so i guess there is nothing to add manually again.

2 - Currently i'm using internet connection via iphone, not wifi.

I have checked the firewall also just in case, and i can see the permission in there so this is not the case i believe, also there is no anti virus app installed.

@joanbono thanks for the message, i tried your suggestion and i could see the request details in the proxyman, screenshot below.

### Screenshots
---
Question 1 : <img width="665" alt="Screen Shot 2019-04-30 at 21 30 38" src="https://user-images.githubusercontent.com/22577614/56984745-688bd280-6b8f-11e9-858f-279f6fdc88a9.png">
Question 2:
<img width="666" alt="Screen Shot 2019-04-30 at 21 33 19" src="https://user-images.githubusercontent.com/22577614/56984888-cddfc380-6b8f-11e9-8adf-6cab52b06369.png">
Firewall:
<img width="666" alt="Screen Shot 2019-04-30 at 21 37 00" src="https://user-images.githubusercontent.com/22577614/56985044-1e572100-6b90-11e9-92ee-4f716a4e535d.png">
Proxyman after executing curl command :
<img width="1440" alt="Screen Shot 2019-04-30 at 21 41 07" src="https://user-images.githubusercontent.com/22577614/56985282-afc69300-6b90-11e9-91e6-44847583e411.png">

**Comment by NghiaTranUIT** [comment]
Thank your detail screenshots 👍 

From what I see, Proxyman is unable to override the Proxy when you're sharing the Internet through iPhone. It's a bug, I will fix it today 👍 

For now, you can use Proxyman by **switching to WiFi**, it will works since Proxyman is completely supported WiFi connections.

**Comment by NghiaTranUIT** [comment]
Hey @mehmetugur-gural, you can check the [Proxyman 1.3.8](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.8) or update directly from your Proxyman. It includes the fix on your bug (Can't override the Proxy when sharing Internet via iPhone USB)

Sorry for late a bit, since I have to dive into the [SystemConfiguration](https://developer.apple.com/documentation/systemconfiguration) framework to fix the bug 😅

**Comment by mehmetugur-gural** [comment]
Hi @NghiaTranUIT , thanks for the update. I got the latest version now and i can confirm it is working right properly right now.

**Comment by NghiaTranUIT** [comment]
This awesome to hear that 👏
