### ISSUE TITLE
Can't see curl requests

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ProxymanApp/Proxyman#1356]
## Description
I'm sending curl request to a given server

## Expected Behavior

Should appears in Proxyman logs

## Current Behavior

Doesn't appears in Proxyman logs

## Steps to Reproduce

1. `curl -v  https://api.telegram.org/botsdfsd/getMe`

## Environment

- App version: e.g Proxyman 3.9.0 30900
- macOS version: e.g macOS Monterey 12.5.1

**Comment by NghiaTranUIT** [comment]
Hey @yaroslavyaroslav it's not a bug. You have to use the `--proxy localhost:9090` flag to tell the `cURL` to make a request to Proxyman Server.

By default, the `cURL` doesn't use Proxy, so Proxyman could not capture it 👍
