### ISSUE TITLE
can Filter  support multiple select？

### ISSUE THREAD

**Issue by woden234** [ProxymanApp/Proxyman#1357]
## Description
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/16451600/189529009-b3d53636-19bc-484e-8994-ba82acaa8aff.png">
when l select Filter option , everytime l just can select one ,but sometimes the request is not standard，for example ,the request  is post  but return json data ,finally the result is in Form  tab,not in json tab . so if Filter support multiple sleect ,l can select multiple  Filter option to solve the problem。 Thank you , this  optimization can help me work more  efficient

**Comment by NghiaTranUIT** [comment]
You can use the Command key + Click to select multiple filters at the same time 👍 

Video:

https://user-images.githubusercontent.com/5878421/189529681-d310b21b-7d4f-4cb1-a373-90daa871f155.mp4

**Comment by woden234** [comment]
> You can use the Command key + Click to select multiple filters at the same time 👍
> 
> Video:
> 
>  CleanShot.2022-09-11.at.20.15.56.mp4

thank you ,this is what l want.
