### ISSUE TITLE
Pin to Favorites didn't work

### ISSUE THREAD

**Issue by woden234** [ProxymanApp/Proxyman#1365]
## Description

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/16451600/190875505-2ac5af03-3de4-412c-ab95-f40161c23243.png">
when I click the “pin to favorites", it seem not work, the request api not show in the Favorites Folder

## Environment

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey 12.6

**Comment by NghiaTranUIT** [comment]
Hey @woden234 It's not a bug I guess.

Currently, "Pin to Favorites" when right-clicking on the request, it doesn't pin this particular request (WE haven't implemented it yet).

It means it will pin the domain of this request. Then, it displays all requests from this pinned domain.

- Click to expand the Pin section -> You might see the pinned domain (Not a pinned request)
![190875505-2ac5af03-3de4-412c-ab95-f40161c23243](https://user-images.githubusercontent.com/5878421/190882458-ae97e453-3f51-4224-a06b-e64b1bd49a81.jpg)

**Comment by NghiaTranUIT** [comment]
I suppose I should rename the "Pin to Favorites" menu to "Pin this domain" to make it clear.

Speaking of "Pin a request" -> We notice the UX confusion -> We will support it soon :+1

**Comment by woden234** [comment]
ok,the function "Pin a request" is great, some websites have many request that l want to  collect some important to use 。so l try another way to active it ，but it didn‘t work 。
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16451600/190882848-d9335f24-b1ff-4a3a-ab7e-914b22746243.png">
so  "Pin a request" is a great function.

**Comment by NghiaTranUIT** [comment]
You're right. The requests in the Favorites Section are not persisted. It will reset when closing the app.

To persist it, you can export it as a ProxymanLog and reopen it again (Drag & Drop is fine)

**Comment by woden234** [comment]
ok ，thank you
