### ISSUE TITLE
Drag & drop multiple domains

### ISSUE THREAD

**Issue by maximebories** [ProxymanApp/Proxyman#1373]
## Description

As you can see in the video below, when you select multiple domains in the pinned domains section, not only you can drop them only on the folder itself or just below, not between any other domain in the folder, but also, it will only drag and drop 1 of the domains, so you have to move them 1 by 1. Nothing terrible but a little bit annoying.

## Steps to Reproduce

https://user-images.githubusercontent.com/30550722/192687432-a3a159dd-ef36-43b7-84cf-e97c628eca85.mp4

## Current Behavior

- Can only drag and drop 1 domain at a time
- Can only drag and drop domain over the folder or just below, not between other domains contained in this folder.

## Environment

- App version: Proxyman 3.10.0 (31000)
- macOS version: Ventura 13.0 (22A5342f)

**Comment by NghiaTranUIT** [comment]
Thanks for the video. It's definitely a shortcoming of the left panel. 

Let me improve it 👍 
- Support multiple drag & drop
- Drop at anywhere (In the video, only drop at the top)

**Comment by NghiaTranUIT** [comment]
@maximebories Let's try this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.10.0_Multiple_drop_and_drag.dmg

From now, you can drag&drop multiple items as you mention 👍 

https://user-images.githubusercontent.com/5878421/192746982-2741f948-e704-4d4d-aab9-37639e65f43f.mp4

**Comment by maximebories** [comment]
Perfect !
