### ISSUE TITLE
Domains pinned by Atlantis don't share the filter from the domains pinned by the browser

### ISSUE THREAD

**Issue by raxityo** [ProxymanApp/Proxyman#1376]
## Description
The pinned area doesn't seem to share the domains pinned by the apps that use [Atlantis](https://github.com/ProxymanApp/atlantis).

## Steps to Reproduce
1. Open an app that's configured to use Atlantis
2. Pin a domain from that app. Let's say it's httpbin.org
3. Select httpbin.org in pinned domains
4. Open httpbin.org in your local browser

## Current Behavior
The request from the browser doesn't show up in the pinned domain. The request can be seen under "Apps" and "Domains" sections.

## Expected Behavior
Domains pinned by Atlantis powered apps should show requests from other sources.

## Additional notes:
The same bug happens if you do the opposite - pin a domain from browser.
1. Open httpbin.org in your local browser
1. Pin httpbin.org
1. Open an app that's configured to use Atlantis and make a network call to httpbin.org
1. Select httpbin.org in pinned domains
1. The request from the app doesn't show up.

## Environment
- App version: Proxyman 3.10.0 (31000)
- macOS version: macOS Monterey 12.6

**Comment by NghiaTranUIT** [comment]
The first issue is definitely a bug. Not sure why the request from a local browser doesn't come through. I will check out tomorrow 👍 

------------------
The second issue is not. The traffic from Atlantis is isolated on the Atlantis Section (our decision), so it doesn't mix with other requests, which go through the Proxy.

FYI, Atlantis traffic is not normal proxy traffic. It's captured by the Atlantis framework (Swizzle Method) and sent to Proxyman via Bonjour Service.

**Comment by raxityo** [comment]
Actually, I take this issue back. 

> The traffic from Atlantis is isolated on the Atlantis Section 

This led to the confusion I had. I had configured pinned applications and domains without Atlantis before but after enabling Atlantis, the pins were not showing the results from the Atlantis, not the other way around as I mentioned earlier.

Apologies for reporting a non-issue.
