### ISSUE TITLE
Proxy Overridden function make the app store not work

### ISSUE THREAD

**Issue by woden234** [ProxymanApp/Proxyman#1377]
## Steps to Reproduce
 when l select the proxy overridden open ,the app store display white, like blow:
<img width="5162" alt="image" src="https://user-images.githubusercontent.com/16451600/193451004-e1e6ce79-e9b7-4663-951c-a038539ada36.png">

when l close the proxy overridden, the app store is work fine.

**Comment by NghiaTranUIT** [comment]
`App Store` app is protected by SSL Pinning. As soon as you override the proxy, it will enable the SSL Proxying -> Causes the SSL Error -> The app display an empty screen.

Unfortunately, there is no solution to bypass the SSL Pinning.

**Comment by woden234** [comment]
ok
