### ISSUE TITLE
Prefs panel cut off on 1280x832 display

### ISSUE THREAD

**Issue by edrozenberg** [ProxymanApp/Proxyman#1391]
## Description
MacBook Air M2 1280x832 (native resolution) - several tabs in prefs panel do not fit in this height.

Would be even worse on older M1 MacBooks (800 height).

## Steps to Reproduce

1. Set MacBook resolution to 1280x800+ (native resolution, non-scaled)
2. Open Proxyman prefs panel
3. Click to select General or Tools tab
4. Tabs don't fit vertically, bottom is cut off

## Current Behavior

Several tabs of the pref panel do not fit in 800 / 832 pixel height

## Expected Behavior

All tabs of the pref panel do should fit in 800 / 832 pixel height

## Environment
- App version: Version 3.11.0 (31100)
- macOS version: 12.6 (21G115) Monterey, MacBook Air (M2, 2022)

![Pref Panel Cut Off](https://user-images.githubusercontent.com/2648417/195474991-60e52a8e-e825-41b9-b4fe-2c0d83819445.jpg)

**Comment by NghiaTranUIT** [comment]
Thanks for the screenshot. I might reduce the padding to make it fit smaller screens 👍

**Comment by NghiaTranUIT** [comment]
Hey @edrozenberg, It's fixed with this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.11.0_Fix_Preference_Windows_on_small_Macbook.dmg

Basically, it automatically detects if the Preference Windows is bigger than the visible frame (Screen height - Dock Height - system bar), the padding will become smaller to fit the screen 👍 

<img width="700" alt="Screen Shot 2022-10-15 at 09 32 54" src="https://user-images.githubusercontent.com/5878421/195966955-670fd2ea-177c-4171-ba14-5d2d876a5bac.png">

**Comment by edrozenberg** [comment]
@NghiaTranUIT thank you, this is fitting great with Dock hidden (I normally run this way).

With Dock visible, it cuts off a little, but all controls are accessible. No problem.

Thank you for the fast fix!

![Prefs - General](https://user-images.githubusercontent.com/2648417/196067112-9b7cd2be-57b6-4a67-a942-1a547f8982ef.jpg)

![Prefs - Appearance](https://user-images.githubusercontent.com/2648417/196067123-65bb9876-7502-4fcd-b5e2-ecb4c1a7e5c5.jpg)

![Prefs - Tools](https://user-images.githubusercontent.com/2648417/196067133-22f16d3a-f24e-4268-8d80-777492f1b6ff.jpg)

**Comment by floam** [comment]
> With Dock visible, it cuts off a little, but all controls are accessible. No problem.

I'll point out, on my computer it goes RIGHT down to the Dock and is so flush that, being new to ProxyMan, I was sure part of the window **was** cut off, and I wasted some time trying to drag the window around higher off the top of the screen to see what was occluded below (doh, you can't do this on macOS), then switching into Expose mode a few times and back to get a look at it during the animation to try to see what options I was missing, before I realized I could drag the window to the left or right to the gap on the side of the Dock...

![nogap@2x](https://user-images.githubusercontent.com/291142/210273166-dc113ac8-e00d-43f2-9d69-e1490570256d.jpg)

I think making sure there is a small but obvious margin would improve the UX here e.g. 

![gap@2x](https://user-images.githubusercontent.com/291142/210273171-908cbd0e-94cc-4f4b-8fba-2adf207a999b.jpg)

**Comment by NghiaTranUIT** [comment]
It seems you're using an old build (before the fix on 3.12.0) 🤔 

In your screenshot, the margin between each UI is large. On 3.12.0, if the `visibleHeight` (Height of the screen - height of the dock) < 820, It will become the compact mode (Small margin/padding). 

If you're using the latest build, and the bug still occurs, I guess it's time to redesign the Preference UI 👍

**Comment by floam** [comment]
That's not the case. 

<img width="1225" alt="Screenshot 2023-01-02 at 6 14 11 PM" src="https://user-images.githubusercontent.com/291142/210292303-811690bf-9ecd-4f35-891c-5dcb9e14fdf3.png">

**Comment by floam** [comment]
I'd say my visibleHeight is well over 900, if you were being precise about those numbers.

**Comment by NghiaTranUIT** [comment]
Thanks for the number @floam. Setting it to 1000px could fix it and other small screens.

**Comment by floam** [comment]
(This is a 14" MacBook Pro from 2022, - the notch adds some screen height and brings things to about 16:10, even after the 74 px of taller menu bar.)
