### ISSUE TITLE
handshakeFailed(NIOSSL.BoringSSLError.sslError([Error:  EOF during handshake])) in new Macbook

### ISSUE THREAD

**Issue by comicola** [ProxymanApp/Proxyman#1393]
## Description
I used Proxyman normally on my macOS Catalina computer for almost 2 years. I can see all the SSL requests from my iPhone 11 (iOS 14.8.1)
After I switch to Macbook M1 Max macOS Monterey, I get the error **handshakeFailed(NIOSSL.BoringSSLError.sslError([Error:  EOF during handshake]))**

## Steps to Reproduce

1. I have 2 MacBooks running the latest proxyman version. Both Installed and Trusted CA Certificate. 
2. I have an iPhone 11 iOS 14.8.1. All my devices run on the same wifi network.
3. When I set the iPhone proxy to the macOS Catalina device, I can see all the SSL requests.
4. When I set the iPhone proxy to the macOS Monterey device, I get handshakeFailed error ( from the same app, the same request that opens normally when connect to macOS Catalina )

## Environment

- App version: Proxyman 3.11.0
- macOS version: macOS Monterey

**Comment by NghiaTranUIT** [comment]
Have you tried to install & trust the Certificate from your new MacBook on your iPhone 11?

Especially, the step 4 and 5:

<img width="744" alt="Screen Shot 2022-10-14 at 15 58 21" src="https://user-images.githubusercontent.com/5878421/195806758-576f86f9-b1f3-4d42-8e33-8c8b9fdc1af9.png">

Please note that: You have to install & trust the certificate from 2 new Macbooks. I assume you've done that on the old Macbook, not not the new one,

Doc: https://docs.proxyman.io/debug-devices/ios-device

**Comment by comicola** [comment]
Thanks @NghiaTranUIT. My fault, I forgot to switch ON when Enable full trust, haha.
