### ISSUE TITLE
Add compressed request/response sizes

### ISSUE THREAD

**Issue by trispo** [ProxymanApp/Proxyman#141]
It would be great if you could add the compressed request/response sizes alongside the uncompressed ones. This makes it easy to compare which impact the chosen compression type (gzip,...) has. 

### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
Proxyman 1.3.8 (1380)

### What OS Version are you using? (Ex. mac 10.13)
macOS 10.14.5 Beta (18F127a)

### Steps to reproduce this issue
Make a request for which you know the compressed and uncompressed response sizes. You will see the uncompressed response size only.

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/1045441/57603594-5c761c80-7562-11e9-97c4-6ce1a0c2ea82.png)

**Comment by NghiaTranUIT** [comment]
All done 😄 

## 🤯 Changelogs 
- [x] Fix caching on Repeat flow when the response if 304
- [x] Support Menu for Show/hide your columns
- [x] Save the state of columns (position, show/hide columns)
- [x] Add compressed size for request / response

**Comment by NghiaTranUIT** [comment]
Hey @trispo,

I've official released the Proxyman 1.3.9, which include the the "Compressed Request/Response" columns 📮

You can also customize your columns as well.

<img width="373" alt="Screen Shot 2019-05-19 at 22 40 16" src="https://user-images.githubusercontent.com/5878421/57984558-26b3c500-7a87-11e9-8de7-e864d821b486.png">

You can update directly from Proxyman, or download [Proxyman 1.3.9](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.9)

Thank you in advance 👏

**Comment by trispo** [comment]
Wunderful, works like a charm! Thanks

**Comment by NghiaTranUIT** [comment]
Glad to hear that 😻
