### ISSUE TITLE
自由设置语言

### ISSUE THREAD

**Issue by jokerwking** [ProxymanApp/Proxyman#1412]
今天我更新了proxyman 它变成了中文版的，对于一直使用 英文版的我来说，这让我非常的不适应，能否出一个可以自由切换语言的功能。

**Comment by NghiaTranUIT** [comment]
@jokerwking You can manually override it: System Preference -> Language & Region -> Select Apps Tab -> Add Proxyman app -> Click the + button -> Select Proxyman app and English.

**Comment by jokerwking** [comment]
@NghiaTranUIT Thank you very much. According to your prompt, I solved my problem successfully。 You can make this method of setting the language public in obvious places, to avoid other people have similar questions
