### ISSUE TITLE
Add support to delete single requests from the table

### ISSUE THREAD

**Issue by trispo** [ProxymanApp/Proxyman#142]
If you have multiple requests in the table you can only clear the whole table by using the Clear button. It would be awesome to delete just the selected line.

### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
Proxyman 1.3.8 (1380)

### What OS Version are you using? (Ex. mac 10.13)
macOS 10.14.5 Beta (18F127a)

### Steps to reproduce this issue
none

### Screenshots (optional)

**Comment by NghiaTranUIT** [comment]
Thank for this request. 

I will implement this feature in next release as well as an ability to select/de-select the columns you prefer. So, overall, it doesn't impact the neatness of the app 😄 

Stay tuned! 🥇

**Comment by NghiaTranUIT** [comment]
Hey @trispo 

I've just implemented this "Delete single flow", and you can try in this build: https://www.dropbox.com/s/dadqt19pqyjz2tw/Proxyman_1.3.8.dmg?dl=0

You can delete the selected Flow by Cmd+Backspace or access from Right Menu
<img width="249" alt="Screen Shot 2019-05-13 at 23 06 52" src="https://user-images.githubusercontent.com/5878421/57636703-d4305f80-75d3-11e9-8fe8-e2f012b9442f.png">

I will officially publish in next release. Thank you so much 🥇

**Comment by trispo** [comment]
Hey @NghiaTranUIT,

wow, this was fast. Thanks, it works! 

Why did you decide to use Cmd + Backspace instead of only Backspace? It would be even better if I could use multi-selection in the table.

**Comment by NghiaTranUIT** [comment]
The problem is that there is the conflict between hotkey when using "Backspace" and writing JSON in Compose screen. I will refactor properly entire the hot-key mechanism by following the First-responder from Cocoa app in next release. Therefore, it's good to go right now.

**Comment by trispo** [comment]
Perfect. I really like the app and you seem to be very enthusiastic in programming those features. Keep on with your work. It is a huge step forward coming from Charles Proxy.
