### ISSUE TITLE
May I buy a license at lizhi.io?

### ISSUE THREAD

**Issue by 4332weizi** [ProxymanApp/Proxyman#1424]
The license on [lizhi.io](https://store.lizhi.io/site/products/id/96) is much cheaper than the official website.  Is there any difference?

By the way, will Proxyman discount for Black Friday?

**Comment by NghiaTranUIT** [comment]
Yes, we always have discount for the next Black Friday, but only for our store.

You can purchase via lizhi store, which is only available for Chinese users

**Comment by 4332weizi** [comment]
Can I renew my license on the [official website](https://proxyman.io/order/renew-license) if I purchase via lizhi store?

**Comment by NghiaTranUIT** [comment]
Yes, you can do it too @4332weizi 👍

**Comment by 4332weizi** [comment]
Thanks
