### ISSUE TITLE
[Feature Request] Export and import protobuf Rules

### ISSUE THREAD

**Issue by jjmean2** [ProxymanApp/Proxyman#1430]
## Description

Proxyman can export and import settings for other kinds of rules such as scripting, breakpoint, ... but cannot export and import protobuf rules.
It would be great if it can export and import protobuf rules from one proxyman instance to other.

## Why this feature/change is important?

I make lots of protobuf rules, because I need one rule per every single API call. And it's not trivial work to make all set of rules for entire API call. So I want to share them with my colleagues, not to let them go through same process.

I'm not sure about the flow of this feature, because I think protobuf rules require the same protobuf schema to work. Maybe it could be export and import bundle of protobuf schema and selected rules together? But it would be good if it can export and import only rules without protobuf schema, too.

Thanks for reading!

**Comment by mattijsf** [comment]
I would love this too!

For the time being you could consider sharing the content of:

```bash
cat "$HOME/Library/Application Support/com.proxyman.NSProxy/user-data/ProtobufMessageTypeStorage"
```

Which is just json. This works as long as the schema definiations are added on both ends.

**Comment by NghiaTranUIT** [comment]
Thanks for letting me know. I'm going to implement it on the next release (3.15.0) 👍

**Comment by jjmean2** [comment]
@mattijsf 
Oh, I didn't know that. Thanks for the information!

@NghiaTranUIT 
Thanks! I appreciate it.

**Comment by NghiaTranUIT** [comment]
@jjmean2 @mattijsf let's try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.14.0_Import_Export_Protobuf_Setting.dmg

We can import/export Protobuf Rules 👍  However, it doesn't automatically export Desc files. You have to import it manually.

<img width="1135" alt="Screenshot 2022-12-24 at 14 44 49" src="https://user-images.githubusercontent.com/5878421/209425322-9a2ebae3-4e51-4dbb-b298-c080350ffd88.png">

**Comment by mattijsf** [comment]
Thanks for this quick addition! 👍 

Some feedback:
1. It was not immediately clear that it was only exporting the selected item(s). By default the first row is selected so when pressing `More > Export Settings...` I assumed it was exporting the entire list.
2. When importing a set of rules they will always be appended regardless when a rule with the exact attributes already exist. It differs per use case whether or not this is expected / convenient. In my case, when sharing a set (that could grow over time) with colleagues they need to make sure they delete existing (related) rules first to prevent duplicates.
3. Nice to have: To prevent confusion when people try to import a set of rules it would be useful to warn them immediately when a any `Message Type` is missing from the list itself. Currently you'll have to navigate to the detail page to find out.
<img width="640" alt="Screenshot 2022-12-25 at 21 23 59" src="https://user-images.githubusercontent.com/706368/209481138-ed3b26bd-7d32-4b8f-8967-edb135c378ed.png">
<img width="640" alt="Screenshot 2022-12-25 at 21 24 06" src="https://user-images.githubusercontent.com/706368/209481139-4f8ad121-47e9-473d-91be-d3905c208d86.png">

Other than that, it just works. Awesome.

**Comment by jjmean2** [comment]
It works! Thanks for your work.

**Comment by NghiaTranUIT** [comment]
Thanks for the feedback @mattijsf 

> It was not immediately clear that it was only exporting the selected item(s). By default the first row is selected so when pressing More > Export Settings... I assumed it was exporting the entire list.

It's the default behavior with other tools too. Able to export the selected rules. Thus, I would like to make it consistent.

> When importing a set of rules they will always be appended regardless when a rule with the exact attributes already exist. It differs per use case whether or not this is expected / convenient. In my case, when sharing a set (that could grow over time) with colleagues they need to make sure they delete existing (related) rules first to prevent duplicates.

Noted.

> Nice to have: To prevent confusion when people try to import a set of rules it would be useful to warn them immediately when any Message Type is missing from the list itself. Maybe with a little warning icon in the Message Type column. Currently you'll have to navigate to the detail page to find out. This is not really related to importing but does make it more likely to cause confusion when rules are not working.

It makes sense. I'm working on it now 👍

**Comment by NghiaTranUIT** [comment]
@mattijsf I've added the warning icon if the schema is missing. Here is the Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.14.0_Show_missing_protobuf_files.dmg

<img width="1149" alt="Screenshot 2022-12-27 at 10 22 23" src="https://user-images.githubusercontent.com/5878421/209606140-2995451c-3f2b-4eb7-8cde-6f1330ca230d.png">

**Comment by mattijsf** [comment]
> It's the default behavior with other tools too. Able to export the selected rules. Thus, I would like to make it consistent.

Got it. 

> @mattijsf I've added the warning icon if the schema is missing. Here is the Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.14.0_Show_missing_protobuf_files.dmg

Just tried it. Works great!
