### ISSUE TITLE
Pinned Favorites have incorrect icons

### ISSUE THREAD

**Issue by shawnkc** [ProxymanApp/Proxyman#1432]
## Description
When iOS simulator apps are pinned, all of them end up with the same icon even though they're completely different apps with different icons in the "Apps" section.

## Steps to Reproduce
Pin 2 or more iOS simulator apps.
Run one app after the other.
Close Proxyman and reopen it. The icons show an older "cached" icon.

## Environment

- App version: Proxyman 3.11.0
- macOS version: macOS Ventura

**Comment by NghiaTranUIT** [comment]
Thanks. I'm able to reproduce this issue. Let me fix it 👍

**Comment by NghiaTranUIT** [comment]
@shawnkc here is the Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.13.0_Fix_iOS_Simulator_Icon.dmg

Basically, the app could not retrieve the correct app icon -> Show the "cached" version -> Fixed and it works fine 👍

**Comment by shawnkc** [comment]
Confirmed fixed in the beta! Thanks!!
