### ISSUE TITLE
[Bug] Not support the Websocket Proxy with static IP

### ISSUE THREAD

**Issue by noblel** [ProxymanApp/Proxyman#1440]
## Description

The WS messages are missed by Proxyman for unknown reasons when the Server is local and in the form of IP. This will not happen when i use Charles. 

## Steps to Reproduce

1. Open Proxyman
2. Start the [Server](https://github.com/noblel/websocket-server)
3. Start the emulator and set the proxy
4. Start the Android [Client](https://github.com/noblel/websocket)
5. Click the 'send to server' button in the websocket android app to make a WS/WSS request
6. Observe the request(xxxx:8887) in Proxyman

## Current Behavior

![image](https://user-images.githubusercontent.com/12093801/202843887-d7f9c643-ace6-4be4-86d6-09699cd71643.png)

## Expected Behavior

Show the content in the Websocket Tab as Charles. 

![image](https://user-images.githubusercontent.com/12093801/202843893-8dd89866-34ab-4be8-ac3c-51b4d786b034.png)

## Environment

- App version: Proxyman 3.13.0
- macOS version: macOS Monterey 12.3.1
- Android version: 13

**Comment by NghiaTranUIT** [comment]
Can you try this Beta build: https://github.com/ProxymanApp/Proxyman/issues/1438 ? We have similar bugs and it's fixed

**Comment by NghiaTranUIT** [comment]
From the user message: it can reproduce if we connect the WS Server with IP.

- WS Server: https://github.com/noblel/websocket-server
- WS Client: https://github.com/noblel/websocket

**Comment by NghiaTranUIT** [comment]
@noblel it's fixed with this Beta: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.13.0_Fix_Websocket_failed.dmg
