### ISSUE TITLE
Improve ProxymanCore with gzip encoding/decoding

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#145]
## 🐶 Brief
We shouldn't remove `accept-encoding` from Proxyman -> Server. We should keep it then decoding gzip when receiving data from server.

Therefore, we can get the uncompress body size, and compress body size. As well as increase the performance of Proxyman

Ref: https://github.com/nicklockwood/GZIP

## 👑 Criteria
- [ ] Keep the accept-encoding in header from Proxyman -> Server
- [ ] Detect encoding type and decompress if possible
- [ ] Able to see gzip content properly

**Comment by NghiaTranUIT** [comment]
All done 💯 

## 🤯 Changelogs 
- [x] Support gzip, deflate, br decoding
- [x] Send Accept-Encoding from Proxyman -> Server
- [x] Decode encoded data appropriately
- [x] Able to see all old response before

**Comment by david-ortegon-meli** [comment]
After this change. Where can I see the compressed size vs the decompressed size in Proxyman?

**Comment by NghiaTranUIT** [comment]
@david-ortegon-meli You have two ways to show this data:

1. From the Summary Tab
![CleanShot 2023-07-11 at 07 31 52@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/94c26981-4330-4af7-8ff6-cc817c86fa44)


2. From the main table view column
![1](https://github.com/ProxymanApp/Proxyman/assets/5878421/af5c9742-d611-42e6-b400-cc32b73a4821)
