### ISSUE TITLE
Is there a way to always start proxyman with "Proxy overriden" set to false?

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1483]
## Description

Everytime I start proxyman (esp after a proxyman update) proxy is overriden. I don't want it to be overridden after I turned it off already.

**Comment by NghiaTranUIT** [comment]
@ColtonIdle You can simply open the Preference -> General -> Disable the "Auto Override Proxy at launch time" 👍 

![Screenshot_2023-01-01_at_09_22_14](https://user-images.githubusercontent.com/5878421/210159357-c0314a67-8f1d-4d94-8729-8cc18662c746.jpg)

**Comment by ColtonIdle** [comment]
that did the trick. thank yoU!
