### ISSUE TITLE
Repeated IDs

### ISSUE THREAD

**Issue by CyberMew** [ProxymanApp/Proxyman#1495]
## Description

IDs are being repeated. Not sure if this is intended or a bug

## Steps to Reproduce

1. Start a fresh session and do some network calls. Notice the ID numbers in Domains tab are increasing. 
2. Save the session to file. 
3. Load the session. 
4. Do some network calls. Notice the ID numbers in the Domains tab start from 1, clashing with the old IDs, instead of the next biggest ID we would expect. 

## Current Behavior

ID counter are reset to 1 in a saved Proxyman session file, instead of resuming from the next biggest ID currently in the session. 

## Expected Behavior

IDs should not clash with existing IDs but should continue where it left off. 

## Environment

- App version: e.g Proxyman 3.1.3
- macOS version: e.g macOS 12.6.1

**Comment by NghiaTranUIT** [comment]
Yes, it's our intention. The ID is not unique and it could be duplicated with other requests, which are imported from the file.

**Comment by CyberMew** [comment]
Ah ok got it then I will sort by time instead. Thanks for confirming.
