### ISSUE TITLE
Doesn't proxy Best Buy app on iOS

### ISSUE THREAD

**Issue by JohnCoates** [ProxymanApp/Proxyman#1506]
## Description
Using Proxyman for iOS, I can't see search requests done on the Best Buy app. https://apps.apple.com/us/app/best-buy/id314855255

## Steps to Reproduce

1. Run Best Buy app, do a search
2. Search doesn't show up, and neither do resource loads

## Current Behavior
Searches and resource loads don't show up

## Expected Behavior

Searches and resource loads show up

## Environment

- App version: Proxyman iOS 1.17.0
- iOS version: 16.2

**Comment by raxityo** [comment]
Best Buy app seems to be using Flutter.

Flutter ignores system proxy settings, so the traffic from the apps built with Flutter doesn't go through Proxyman.

Same thing happens with any other apps built with Flutter such as OpenSea.

**Comment by NghiaTranUIT** [comment]
Yes, it's correct. Some React Native doesn't use the HTTP Proxy too. To intercept Flutter apps, it's required some config: https://docs.proxyman.io/debug-devices/flutter

**Comment by JohnCoates** [comment]
Great, thanks for the heads up.
