### ISSUE TITLE
Remap Request/Response feature

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#151]
## 🐶 Brief
It's time to implement the key feature, which is the "Remap request/response". 

It means that you can pre-defined your response and map it to the on-going requests on the fly. It's super useful for debugging from iOS device.

## 👑 Criteria
- [x] Layout for Remap UI
- [x] Able to select specific domain or via regex
- [x] Able to select response
- [x] Logic for mapping response to the destination requests/response.

**Comment by nghiaphunguyen** [comment]
hope this visible soon. nice job bro

**Comment by NghiaTranUIT** [comment]
Hey @nghiaphunguyen and @JUSTINMKAUFMAN

I've rollout the Map Local BETA from file at https://github.com/ProxymanApp/Proxyman/issues/224#issuecomment-517331332

Basically, we can map the local file as a response of matching requests. I could fulfill your request before big remap feature 😄. Let give it a try.

Thank you guys in advance!

**Comment by NghiaTranUIT** [comment]
The first part of Remap is Map Local, and it's been out https://proxyman.io/blog/2019/08/map-local-feature.html

Next version 1.5.0 will be the remaining part. Stay tuned guys 😍

**Comment by NghiaTranUIT** [comment]
Hey, @nghiaphunguyen @JUSTINMKAUFMAN

Just friendly reminder that Proxyman 1.5.0 with **Breakpoint** has been out 😍 

You can download or update from the app directly https://github.com/ProxymanApp/Proxyman/releases/tag/1.5.0

Thank you in advance 👍

**Comment by nghiaphunguyen** [comment]
@NghiaTranUIT thanks a lot, grace for all your work.

**Comment by nghiaphunguyen** [comment]
@NghiaTranUIT just have 1 minor feedback. should we have feature to intercept response from file or url ?

**Comment by NghiaTranUIT** [comment]
Hey @nghiaphunguyen, I'm not sure what you mean Intercept the HTTP Response from File or URL 🤔 

- If you would change the response body with local file -> **Map Local** is a tool you're looking for. You can access by Tool -> Map Local or **⌥ + ⌘ + L**
- If you would change response body from body in different URL. Ex: the body of http://domain.io/user should be replace with http://domain.io/data -> It could be "Map Remote", which we haven't supported it yet.
- or ?

I'd be great if you can give us some example how it works, then I answer the question properly 👍 Thank you in advance 😄
