### ISSUE TITLE
Certificate -  Install certificate on iOS/Android - Real device. Add QR-code with link http://proxy.man/ssl

### ISSUE THREAD

**Issue by almaz010891** [ProxymanApp/Proxyman#1514]
## Description

Certificate -  Install certificate on iOS/Android - Real device. Add QR-code with link http://proxy.man/ssl

## Why this feature/change is important?

Because it will make the process of going through the link faster (using standart camera feature - qr-code recognition) without manual input or copy/paste link through messenger between macOS and iOS/Android

**Comment by NghiaTranUIT** [comment]
Sure, I will add this feature 👍

**Comment by NghiaTranUIT** [comment]
@almaz010891 let's try this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_4.1.0_Support_QR_Code.dmg

There is a QR button next to the `http://proxy.man/ssl` label.

![CleanShot 2023-01-29 at 09 41 19@2x](https://user-images.githubusercontent.com/5878421/215302049-e1d17d98-8e7a-4d91-90ed-372b6a1e7453.jpg)

**Comment by almaz010891** [comment]
Perfect!
