### ISSUE TITLE
Proxyman doesn't intercept all HTTP requests

### ISSUE THREAD

**Issue by biryusal** [ProxymanApp/Proxyman#1515]
## Description
Proxyman works fine in most cases, but it skips some requests for some reason

## Steps to Reproduce

1. Open proxyman
2. Enable VPN
3. Try to catch ALL requests/responses

P.S. I've disabled "cache", reinstalled my app, but it didn't work
For once somehow I catched a HTTP-request, that I've never catch before, and there was response-body that I need
But it was only for once
How to catch all http requests/responses?

## Current Behavior

Some dynamic data I see in Proxyman, but some data there's not at all

## Expected Behavior

I see all HTTPs requests/responses

## Environment

- App version: Proxyman 1.17.0
- iOS version: 16.0

**Comment by NghiaTranUIT** [comment]
Maybe your app is using the cached Response version.

1. The Response is cached on your app -> The request is never called -> Proxyman could not capture it.

To fix it:
1. Delete your app that you're like to intercept
2. Open Proxyman for iOS -> More Tab -> No Caching -> Turn ON
3. Try again

**Comment by biryusal** [comment]
Thanks a lot for your quick response!

Yep, I've installed and trusted certificate, I see all HTTPs responses

I uninstalled the application and all data associated with it, reinstalled it, and turned off request and response caching before launching
But still I didn't see any data I needed
This is an online store (mobile app), and the prices there are updated very often.
But in requests, I see only pictures, that is, even service information, by the type of product name and its price is not displayed in my Proxyman
I see some JSON's responses, but there is nothing that I need (kinda deviceId, local secret, and etc.)

Although once I was able to catch such a request that returns information about a specific product
But I also need others, such as getting products by category


Do you have any other guesses?

**Comment by biryusal** [comment]
This issue was wrong, I found requests that I needed

**Comment by NghiaTranUIT** [comment]
Maybe the app doesn't use URLSession (Apple Framework) to make a networking request. If it's an online app, it can be a React Native, Flutter app, which (by default) doesn't go through the VPN.

Thus, Proxyman could not capture it.

If it's true, there is no way to force it to use the VPN unless you're a developer of this app. You need to add some configuration in the source code.

**Comment by biryusal** [comment]
So there's no other way to parse data from this mobile app?
Or maybe do you know another solution?

I will close this thread, ofc, but I want to hear the answer if you know it

Thanks!

**Comment by NghiaTranUIT** [comment]
As I mention @biryusal, if you're not a developer of the app, maybe there is no solution to force all traffic to go to the Proxyman app.

**Comment by biryusal** [comment]
I meant any other solution, maybe except the proxyman?
