### ISSUE TITLE
Breakpoint Window: Selecting entire body (in my case to delete it) takes multiple seconds

### ISSUE THREAD

**Issue by carstenhag** [ProxymanApp/Proxyman#1529]
## Description
1. Make an API call, set a breakpoint on it, wait for the response breakpoint to trigger, have the API return ~500 KB of response as json.
2. Have a different response ready, so you just want to paste in the new one. The old one doesn't matter at all.
3. In order to delete the old response, you must select it. This takes multiple seconds right now, probably due to the syntax-enabled edit field.
4. Pasting the new text takes 0.5 seconds which is not too jarring/annoying, which is fine.

## Improvement idea
To solve point 3, either there should be an option to delete the entire text or selecting the entire text should take less time

## Why this feature/change is important?
So that the UX is better and users spend less time waiting :D

**Comment by NghiaTranUIT** [comment]
Thanks. The "Select All" issue when selecting a huge stage on Code Mirror is a known issue. I tried to use the latest CodeMirror, but it doesn't completely fix.

I guess I will add a small button, so you can select the text-based file, and it replaces it automatically. Save time to CMD+A, CMD+C, then CMD+V 😄

**Comment by carstenhag** [comment]
That would be great :) Thank you!

**Comment by NghiaTranUIT** [comment]
@carstenhag let's check this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_4.2.0_Select_File_on_Body_Breakpoint.dmg

Basically, on the Body Tab (Request/Response) from the Breakpoint Windows, you can select a local file. It will replace the body and prompt to change the Content-Type header if need 👍 

![Screenshot_2023-02-09_at_20_51_44](https://user-images.githubusercontent.com/5878421/217831993-3d491668-49f4-4d2d-9d92-d4b7b56b630d.jpg)

**Comment by carstenhag** [comment]
Thanks, that seems to work. In my case I usually don't save the files locally, I only keep it in an editor/in my clipboard. Is there a way to have a "paste from clipboard" button?

**Comment by NghiaTranUIT** [comment]
Thanks. I can add "Paste from clipboard" too 👍
