### ISSUE TITLE
Proxyman has stopped responding to most mouse clicks

### ISSUE THREAD

**Issue by ianiv** [ProxymanApp/Proxyman#1545]
## Description

Clicking on many UI elements no longer works. e.g. toolbar buttons, right clicking request list, filter controls.
I don't know what could've caused it, it just suddenly stopped working a couple of days ago.
I've tried the "Factory Reset" option but it made no difference.

## Steps to Reproduce

Open proxyman and try to use it normally.

## Current Behavior

See this video, you can see I am clicking on various elements and nothing happens

https://user-images.githubusercontent.com/46598/219175058-c15f5389-1ef4-49a7-bde7-322f0195b3d8.mov

## Environment

- App version: Proxyman 4.2.1
- macOS version: macOS 13.2.1

**Comment by NghiaTranUIT** [comment]
Hm, it's really odd. I've never seen this bug before @ianiv 

Can you try with some older Proxyman builds to see if you can reproduce it? You can download it at https://proxyman.io/changelog

From your video, Proxyman isn't unresponsive, or hanging (You can click on the third row on the main table), I guess the app is conflicted with some apps on your Macbook.

**Comment by ianiv** [comment]
Turns out it responds find if I "tap to click" on the trackpad but doesn't if I "press to click" instead. So I have a workaround, I think.

Even older versions that used to work fine no longer work, so this is likely something specific to my machine. No worries.

**Comment by NghiaTranUIT** [comment]
It seems it's a bug from Apple 🤔 

Anyway, thanks for informing me that it's fixed 😄

**Comment by ianiv** [comment]
I wouldn't say it is fixed, but very likely not Proxyman's fault?

**Comment by NghiaTranUIT** [comment]
Unfortunately, I don't know how to fix it. Proxyman uses a lot of native UI Components from AppKit (We don't customize or override keyboard/mouse events). 

I will keep an eye on this issue and see if there are more reports.
