### ISSUE TITLE
Scripts aren't combining themselves for same endpoints requests

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1548]
## Description
When creating two scripts with the same wildcard, when requesting (idk if it does the same for the response), only one script will be executed.

## Steps to Reproduce
1. Create first script for a domain, add a key `"script1"` and a value `"value"` in the headers.
2. Create a second script for the same domain, add a key `"script2"` and a value `"value"` in the headers.
3. Send a request to this domain.

## Current Behavior
You should see only one of the two keys `"script1"` or `"script2"`

## Expected Behavior
You should see both of the keys, the scripts should be executed one after the other on the request, and also one after the other on the response.

## Environment

- App version: e.g Proxyman 4.2.1
- macOS version: e.g macOS Ventura 13.2

**Comment by NghiaTranUIT** [comment]
It's related to https://github.com/ProxymanApp/Proxyman/issues/1190

Basically, we decide that one Request can be executed by one Scripting Rule. We don't allow multiple scripts to run on a single Request/Response.
