### ISSUE TITLE
Request information area disappeared

### ISSUE THREAD

**Issue by qwertywelch** [ProxymanApp/Proxyman#1562]
## Description
After using Proxyman for several months, last week the area at the bottom of the window which shows the information about the selected request has disappeared. Not sure what this area is officially called.

<img width="1286" alt="Screen Shot 2023-03-02 at 9 25 59 AM" src="https://user-images.githubusercontent.com/1254417/222456690-cfbce807-2020-45f4-84e3-9f3ac8b8e081.png">

- At one point I know I had selected the "View > Detach Content Windows" option, but there are _no other open Proxyman windows_ and trying to toggle this option again doesn't do anything.
- Selecting any of the "View > Toggle Dock.." options doesn't do anything.
- Double clicking on requests doesn't do anything.
- Quitting and reopening does not fix.
- Rebooting computer does not fix.

## Current Behavior

Selected request information area has disappeared and cannot be re-enabled.

## Expected Behavior

Should be able to see it always.

## Environment

- App version: Proxyman 4.3.1
- macOS version: macOS Monterey 12.6

**Comment by NghiaTranUIT** [comment]
@qwertywelch You can hit the Space button, it will toggle the Request/Response info.

**Comment by NghiaTranUIT** [comment]
To show the Toggle Bar, pleae right click on the Toolbar -> Customize Toolbar -> Drag the Toggle App Panel.

Then you can toggle the left/bottom/right panel.

![CleanShot 2023-03-02 at 21 37 13@2x](https://user-images.githubusercontent.com/5878421/222459151-2132cdcb-8351-41ad-9315-e34177e1ab15.jpg)

**Comment by qwertywelch** [comment]
Ahh! I see. Would love to have this in the View menu as well.

Thanks for the help and for the great app!
