### ISSUE TITLE
If you hit backspace to delete an entry in the list, the entry deletes, but the request+response windows still show the deleted item

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1563]
## Description
If you hit backspace to delete an entry in the list, the entry deletes, but the request+response windows still show the deleted item

## Current Behavior

Deletes the entry, but keeps the entry's response/request info

## Expected Behavior

Item should delete and request and response bodies should show the currently highlighted item

**Comment by ColtonIdle** [comment]
On mobile at the moment so I can't record a video, but maybe something interesting to note is that i had a url filter set. Maybe that was part of the issue?

**Comment by NghiaTranUIT** [comment]
I've tested again with the filter, and it just works fine.

**Comment by ColtonIdle** [comment]
Hm. Closing this for now. on holiday until next week. cheers
