### ISSUE TITLE
Android Studio SSL Proxy Not Working

### ISSUE THREAD

**Issue by AlanCPSC** [ProxymanApp/Proxyman#1575]
## Description
I am unable to successfully set up SSL proxying for the Mac and Android Studio Emulator.

After exhausting all suggestions available on the website, I am now out of any further ideas.

## Steps to Reproduce
1. Install certificate on this Mac...
2. Install certificate on this Emulator...
3. Update res/xml/network_security_config.xml
4. Update AndroidManifest.xml

## Current Behavior
* When proxyman is running Mac Chrome HTTP works
* When proxyman is running Mac Chrome HTTPS works
* When proxyman is running Emulator Chrome HTTP works
* When proxyman is running Emulator Chrome HTTPS **DOES NOT** works

## Expected Behavior
* When proxyman is running Mac Chrome HTTP works
* When proxyman is running Mac Chrome HTTPS works
* When proxyman is running Emulator Chrome HTTP works
* When proxyman is running Emulator Chrome HTTPS works

## Environment
- App version: Proxyman 4.4.0
- macOS version: macOS Ventura 13.1

<img width="1359" alt="problem_screenshot" src="https://user-images.githubusercontent.com/22120384/224614157-ec41a58f-48c2-4d71-8085-e28f9614f9cb.png">

**Comment by AlanCPSC** [comment]
Despite restarting multiple times and attempting to reinstall the certificates, no progress has been made.

Does anyone have any suggestions on how to effectively address this problem? 🤔

**Comment by AlanCPSC** [comment]
Here is screenshot proof that I have configured certificate on both Mac & Emulator:
<img width="1071" alt="screenshot_proof" src="https://user-images.githubusercontent.com/22120384/224617130-12519a08-d001-4a65-9e55-7b0f28d2b148.png">


Here is screenshot error that I get each time I try to make a https request on Emulator:
<img width="488" alt="screenshot_error" src="https://user-images.githubusercontent.com/22120384/224617095-925fa091-39e5-4c90-8680-89085a6aeac1.png">

**Comment by NghiaTranUIT** [comment]
@AlanCPSC Can you try using the [Automatic Script for Android Emulator](https://docs.proxyman.io/debug-devices/android-device/automatic-script-for-android-emulator) 🤔 

To make sure that it's installed & trusted properly.

The Emulator must not be an Google Play version.

**Comment by AlanCPSC** [comment]
@NghiaTranUIT. I already installed it using the [Automatic Script for Android Emulator](https://docs.proxyman.io/debug-devices/android-device/automatic-script-for-android-emulator).

I am able to connect inside the Android Emulator when I turn OFF SSL proxying:
<img width="1558" alt="screenshot_success" src="https://user-images.githubusercontent.com/22120384/224619221-cb49db5c-cdcd-4c3b-b1a9-764375cbe16f.png">

I am NOT able to connect inside the Android Emulator when I turn ON SSL proxying:
<img width="1556" alt="screenshot_failure" src="https://user-images.githubusercontent.com/22120384/224619261-e22cc857-fbf3-4b39-8d99-ae25d209cf79.png">

**Comment by NghiaTranUIT** [comment]
Do you have access to the Source code of your app? (Facebook Login) 

It seems you're trying to intercept these famous apps (Facebook, Google, IG), and they're protected by SSL Pinning.

**Comment by AlanCPSC** [comment]
But I have the same problem with EVERY https request. Including benign apps like [https://httpbin.org/get](https://httpbin.org/get)

**Comment by AlanCPSC** [comment]
But I have the same problem with EVERY https request. Including benign apps like [https://httpbin.org/get](https://httpbin.org/get).

**Comment by AlanCPSC** [comment]
But I have the same problem with EVERY https request. Including benign apps like [https://httpbin.org/get](https://httpbin.org/get).

Additionally, I am able to intercept these famous apps on MacOS Chrome. Just not through the Android Emulator.

**Comment by NghiaTranUIT** [comment]
Can you try on this sample code: https://github.com/ProxymanApp/OKHTTP-Android-Sample

It's already added the res/xml/network_security_config.xml and AndroidManifest.xml

If you can intercept the HTTPS traffic from this app, it means you setup properly. The problem maybe from your app.

**Comment by NghiaTranUIT** [comment]
Please note that Android Security is higher and trickier than the iOS app. You have to be the owner of your apps, which allows you to modify the `res/xml/network_security_config.xml` and `AndroidManifest.xml` files.

These files need to define the domain that you're owing too. It's not possible to intercept HTTPS traffic from Social website.

**Comment by AlanCPSC** [comment]
@NghiaTranUIT

I discovered what was going on. Proxyman does not work with [Mozilla's GeckoView](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/geckoview-quick-start.html) for some reason.

I am not sure why, but when I switch back to using a standard Android WebView, I can intercept all SSL traffic again.

**Comment by AlanCPSC** [comment]
Also regarding the claim "It's not possible to intercept HTTPS traffic from Social website."

I actually can - I just have to do it on a standard WebView. See the following screenshot:

<img width="1392" alt="screenshot_webview" src="https://user-images.githubusercontent.com/22120384/224811918-9b828fb8-1187-4e27-bc98-e8ff7a0c305a.png">

**Comment by AlanCPSC** [comment]
Also regarding the claim "It's not possible to intercept HTTPS traffic from Social website."

I actually can - I just have to do it on a standard WebView. See the following screenshot:

<img width="1392" alt="screenshot_webview" src="https://user-images.githubusercontent.com/22120384/224811918-9b828fb8-1187-4e27-bc98-e8ff7a0c305a.png">

If you fine folks can look into supporting Mozilla's GeckoView in the future, that would be wonderful.

**Comment by NghiaTranUIT** [comment]
@AlanCPSC Firefox or Mozilla GeckoView required you to add Proxyman Certificate to their trust store.

- Firefox on macOS: https://docs.proxyman.io/debug-devices/firefox
- Mozilla on Android: https://blog.jeroenhd.nl/article/firefox-for-android-using-a-custom-certificate-authority

Mozilla doesn't provide the UI to add the certificate, the above link is a workaround.

**Comment by AlanCPSC** [comment]
@NghiaTranUIT Found the following additional threads regarding this issue:

* [Bug 1553265 - No way to bypass certificate error pages, such as self-signed certs](https://bugzilla.mozilla.org/show_bug.cgi?id=1553265)

* [Bug 868370 - Provide a way to import user certificates from PKCS#12/PFX files](https://bugzilla.mozilla.org/show_bug.cgi?id=868370)

Closing this issue since the problem does not appear to be related to Proxyman. Thank you for your help.
