### ISSUE TITLE
Map Remote / Map Local on Windows

### ISSUE THREAD

**Issue by cholwell** [ProxymanApp/Proxyman#1580]
## Description

Hello, is support for map local and map remote tools on the horizon for the new Windows version?

## Why this feature/change is important?

Because they are great tools!

Thanks a lot

**Comment by NghiaTranUIT** [comment]
Hey @cholwell we're working on the Map Local for Windows. You can check out our Windows roadmap at https://github.com/ProxymanApp/proxyman-windows-linux/projects/1

**Comment by cholwell** [comment]
Amazing @NghiaTranUIT thanks for the quick response!
