### ISSUE TITLE
Automation Permission unable to be given.

### ISSUE THREAD

**Issue by Camus1859** [ProxymanApp/Proxyman#1584]
## Description

I am following this page here.https://docs.proxyman.io/debug-devices/android-device/automatic-script-for-android-emulator

 When I get to this step here, I do not see `Proxyman app` available to select.
 
 I have tried to restart my computer multiple times.

> Proxyman requires Automation Permission in order to execute the automation script by [AppleScript](https://developer.apple.com/documentation/foundation/nsapplescript). Please consider granting Proxyman app in System Preference -> Security & Privacy -> Privacy -> Automation -> Allow Proxyman app.

## Current Behavior
1. Download Proxyman
2. Go to  System Settings --> Privacy & Security --> Automation ---> `Proxyman app should be here but its not`
3. What I do see iTerm and Terminal  ---> System Events and Google Chrome
        

## Expected Behavior

Like the docs state I should see `Proxyman app` after I select `Automation`

## Environment

- App version: e.g Proxyman 4.5.0
- macOS version: Ventura 13.2.1 Apple M1 Pro

**Comment by NghiaTranUIT** [comment]
It seems that you've figured it out 👍 

----------

@Camus1859 if you run the Emulator Script for the first time, the OS will ask your permission. Then, you can grant it and it will appear in the Automation script.

Some users don't allow it, so it instructs the user to enable it in the Privacy -> Automation tab.
