### ISSUE TITLE
Export/import individual Map Local rule/payload combo

### ISSUE THREAD

**Issue by jacobvanorder** [ProxymanApp/Proxyman#1589]
## Description

The ability to export and import an individual map local rule and payload combination.

## Why this feature/change is important?

On our team, we utilize Map Local to do work that might not be ready on the API side. For our PRs, we have to link to the json as well as paste in the URL. It'd be nice to be able to export the combination for sharing.

**Comment by NghiaTranUIT** [comment]
Hey @jacobvanorder, this feature is already shipped in the latest build 👍 

You can simple export your Map Local Rule, then import it again on your colleague's Macs. All local files of the Map Local are included.

![Proxyman with Map Local Export](https://user-images.githubusercontent.com/5878421/229004129-6852f60f-e6bd-45c0-9cb9-58e3ac823d7a.jpg)

**Comment by jacobvanorder** [comment]
Excellent! Thank you for the great explanation! I assumed that `Export Settings…` would export _all_ map local but this works great! Thank you so much.
