### ISSUE TITLE
Aborting requests

### ISSUE THREAD

**Issue by KirillKornev** [ProxymanApp/Proxyman#1606]
## Description

Hi! Could you help me?
In old versions I often used aborting requests in breakpoint screen.
It worked perfect, I got result on the screen(my device) immediately and device got an error. We used aborting for testing scenarios when user got en error from backend for current request.
After update to version 4.6.1 something changed and aborting request abort it, but my device just make new requests, time after time try to call new request. It now looks like you don't have an internet connection.

Is it possible to change some settings to abort requests like in old versions?

Thank you!

**Comment by KirillKornev** [comment]
Just for clear understanding attached an screenshot.
I tap abort button, but my request call again and again.

In old version it was aborted and I got an error on device.

<img width="1341" alt="Снимок экрана 2023-04-19 в 13 18 15" src="https://user-images.githubusercontent.com/56608476/233030364-d8de8d12-e787-4d87-a0a0-3c46edd70647.png">

**Comment by NghiaTranUIT** [comment]
Thanks. On the latest version, we change the behavior of aborting, instead of close the connection immediately, it returns 503 error.

I will revert it and add options to choose which behavior it should be.

**Comment by KirillKornev** [comment]
Thank you!
I hope this will be fixed in the next versions.

**Comment by NghiaTranUIT** [comment]
I will fix and send you a Beta build tomorrow 👍

**Comment by KirillKornev** [comment]
Really fast answer. Thanks!
