### ISSUE TITLE
[Bug]Map remote not in effect

### ISSUE THREAD

**Issue by bikedawuwang** [ProxymanApp/Proxyman#1613]
## Steps to Reproduce

1. open proxy man
2. set map remote

## Current Behavior

The map remote did not take effect as expected, and I did not see any feedback during debugging

<img width="768" alt="image" src="https://user-images.githubusercontent.com/16474060/234286625-8555f080-b9b2-4473-a850-2c276c8e287b.png">

## Expected Behavior

Map remote can take effect as expected, and I can read local files through map remote

## Environment

- App version: e.g Proxyman 4.6.1 
- macOS version: e.g macOS Ventura 13.2.1

**Comment by NghiaTranUIT** [comment]
Can you with me your real URL and the Map Remote Rule? It seems the Rule URL doesn't match your real URL.

**Comment by bikedawuwang** [comment]
> Can you with me your real URL and the Map Remote Rule? It seems the Rule URL doesn't match your real URL.

I have identified the problem. Have I mapped the HTML file locally? This problem has been resolved
