### ISSUE TITLE
[MacOS][Bug] Map Rmote Not Keep Original Host

### ISSUE THREAD

**Issue by liudongyang1** [ProxymanApp/Proxyman#1628]
## Description

Version 4.7.1 (47010) On MacOS Map Rmote Not Keep Original Host.

## Steps to Reproduce

1. Add a new map from a.com to localhost:xyz
2. The Host Header use "localhost:xyz", Not the "a.com"

For NGINX that has started multiple servers locally, routing resolution cannot be completed through the "localhost" host.
Please add an option to preserve the original Host header

## Environment

- App version: 4.7.1 (47010)
- macOS version: MacOS 13.2

**Comment by NghiaTranUIT** [comment]
@liudongyang1 please try this beta build: https://github.com/ProxymanApp/Proxyman/issues/1448#issuecomment-1531007482

and enable the `Preseve the Host Header` option in your rule 👍

**Comment by liudongyang1** [comment]
Thanks @NghiaTranUIT
