### ISSUE TITLE
Can't intercept request in some apps

### ISSUE THREAD

**Issue by vimaxwell** [ProxymanApp/Proxyman#1640]
## Steps to Reproduce

1. Download the Sounter app https://apps.apple.com/us/app/sounter-learn-languages/id1505600864
2. Enable VPN or Proxy on iOS

## Current Behavior
Can't find any requests on ios VPN app or proxy on Macos from Sounter app. Howerver, Its still working on other apps

## Expected Behavior
Can inspect all requests

## Environment

- App version: Version 4.7.1 (47010)
- ios version: 1.29.0
- macOS version: macOS Ventura 13.2

**Comment by NghiaTranUIT** [comment]
It's not the fault of Proxyman, it's how this app works.

They might not use a URLSession (Maybe they're a React Native, or Flutter app), so this app doesn't use system HTTP Proxy -> Proxyman could not capture it.

**Comment by vimaxwell** [comment]
Thanks
