### ISSUE TITLE
Add option disable Content-Length in copy curl 

### ISSUE THREAD

**Issue by fleytman** [ProxymanApp/Proxyman#1646]
Hello,

I have encountered an issue related to copying requests in Proxyman. When copying a request in cURL format, it's easy to overlook or not pay attention to the Content-Length header. This can lead to difficulties later on when making modifications to the copied request, as it may start behaving incorrectly.

My feature request is to add an option that explicitly enable/disable of the Content-Length header when copying a request. This will help users easily notice and consider this header when making changes to requests.

Additionally, I believe that it would be better to disable the automatic addition of the Content-Length header by default when copying a request. This will prevent situations where users, who only modify the request body, don't notice the presence of this header and encounter non-functional requests.

One typical use case for me is that I usually copy a cURL request and paste it into Postman, then only modify the request body. In such cases, disabling the automatic addition of the Content-Length header will help me avoid issues with requests that arise from the header being overlooked.

I believe that adding this option will make using Proxyman more reliable and convenient, especially for users who frequently modify only the request body.

**Comment by NghiaTranUIT** [comment]
Hey @fleytman,

It's a good idea to add an option to opt-out of the `Content-Length` in the cURL. I will put it in the Setting -> Tool -> cURL section.

However, I'd set it OFF by default.

**Comment by NghiaTranUIT** [comment]
@fleytman you can try this Beta build: https://download.proxyman.io/beta/Proxyman_4.7.1_Support_ContentLength_option_in_cURL.dmg

You can opt-out it Setting -> Tool 

![CleanShot 2023-05-23 at 09 02 45@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/3618b1b8-0893-48f6-a0e2-ce3e3a81583a)

**Comment by fleytman** [comment]
I would like to express my gratitude for adding the feature to Proxyman that I suggested. It's work!

> However, I'd set it ON by default. It means, it always includes the Content-Length unless you opt-out.

However, I would like to share my opinion regarding the default setting for this feature.

In my suggestion, I mentioned the need to disable the Content-Length header by default when copying a request. I would like to justify this request and explain why I believe that OFF should be the preferred default value.

1. Simplicity of use: Most users, when copying a request in cURL format, are likely to overlook the presence of the Content-Length header. This can lead to undesired results, especially if they are only modifying the request body. Disabling the header by default will prevent such situations and help avoid potential issues.

2. Increased flexibility: Some APIs and services require the Content-Length header not to be included in requests. Enabling the header by default can create unnecessary headaches for users who need to explicitly exclude this header in their requests.

**Comment by NghiaTranUIT** [comment]
Thanks. It makes sense 👍 I will make it OFF by default 👍
