### ISSUE TITLE
[Breakpoint] Breakpoint for Response

### ISSUE THREAD

**Issue by 8bitzz** [ProxymanApp/Proxyman#1649]
### Request Tab
<img width="573" alt="Screen Shot 2023-05-23 at 15 31 25" src="https://github.com/ProxymanApp/Proxyman/assets/23531403/661245b7-113c-4fa1-a933-424bacbe822a">

- Users are able to select `Request` tab, swipe for navigation
- Display URL, Method, Headers, Queries, Body in `ReadOnly` mode
- Users are unable to edit these fields

### Response Tab
<img width="565" alt="Screen Shot 2023-05-23 at 15 31 41" src="https://github.com/ProxymanApp/Proxyman/assets/23531403/270b185b-93dc-4676-8722-be09c31e76d7">

- Looks similar to Breakpoint for Request
- Allow users to modify: Status Code, Headers, Body

##### Status Code 
- Tap on Header cell should show StatusCodeEditorView
- Reuse the HeaderEditorViewController, logic similar to MapLocalTool

##### Header 
- Tap on Header cell should show HeaderEditorView
- Reuse the HeaderEditorViewController, logic similar to MapLocalTool
- Display custom keyboard for auto completion/ suggestion
- Change query params should update URL automatically and vice versa

##### Body
- Tap on Body cell should show BodyEditorView
- Reuse the BodyEditorViewController, logic similar to MapLocalTool
- Display custom keyboard for auto completion/ suggestion

### Breakpoint Action Menu
- Set menu action on right bar button on navigation bar
- Display 3 options: `Execute`, `Abort`, `Continue` for users to select

**Comment by NghiaTranUIT** [comment]
### Requirement Update 1
#### Header / Query Editor
- After editing the Header Editor -> Save -> Back to the Request/Response Breakpoint Editor -> The number of headers must be updated.
- The same with Query Editor too.

#### Body
- Body doesn't have (0 items) -> Use the size:
```swift
HumanFormatter.shared.format(data: .byte(body.count)
```
