### ISSUE TITLE
Grouping of different Chrome channels

### ISSUE THREAD

**Issue by rifaidev** [ProxymanApp/Proxyman#1650]
## Description

Why are separate versions of Safari and Firefox listed individually, while different versions/channels of Chrome (Beta, Dev, Canary) are all grouped together as a single application? Is there a specific technical reason for this distinction?

<img width="217" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/4334778/f14b2e5c-d6ee-4409-b36e-9fe346b187c0">

**Comment by rifaidev** [comment]
But they actually differ

<img width="849" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/4334778/5adbb2c5-5053-4b5c-ae22-35f48faeee59">

**Comment by NghiaTranUIT** [comment]
Ah, I see what you mean. It's my little legacy code because they have the same process name: `Google Chrome Helper`, so I incorrectly treat it as the same app.

I will download the Google Chrome Canary and fix it 👍

**Comment by NghiaTranUIT** [comment]
@rifaidev here is the fix 👍 https://download.proxyman.io/beta/Proxyman_4.8.0_Fix_Google_Chrome_App_Icon.dmg

![CleanShot 2023-05-23 at 19 28 39@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/89aec3c4-6542-4b7d-99e2-b2bb5bf45d67)
