### ISSUE TITLE
在关闭ProxyMan时恢复至以前的代理无效

### ISSUE THREAD

**Issue by zhengjianyang** [ProxymanApp/Proxyman#1653]
## Steps to Reproduce

1. 开启Surge代理工具并设置为系统代理
2. 打开ProxyMan并设置为系统代理
3. 关闭ProxyMan系统代理
4. 并没有恢复至Surge的系统代理设置

## 我现在ProxyMan的版本是Version 4.8.0 (48000)，在之前的版本中是没有这个问题的，就在最近的几次更新中出现了这个问题，我记不清具体是哪一次更新了。

- App version: e.g Proxyman Version 4.8.0 (48000)
- macOS version: e.g macOS Ventura 13.3.1

**Comment by NghiaTranUIT** [comment]
Related to https://github.com/ProxymanApp/Proxyman/issues/1656#issuecomment-1566701243
