### ISSUE TITLE
Values under the "Form" tab become url encoded after sorting

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/Proxyman#1659]
## Description
After sorting, values under the "Form" tab become url encoded. See attached files with before and after screenshots.

<img width="735" alt="before" src="https://github.com/ProxymanApp/Proxyman/assets/4147381/fe97ea1f-9bba-4b32-9ae2-4b8bb9e82239">

<img width="712" alt="after" src="https://github.com/ProxymanApp/Proxyman/assets/4147381/7157a9b7-0223-40d8-b2f9-e5600f9f1ff4">

## Steps to Reproduce

1. Record a form submission
2. Go to the "Form" tab
3. Note the value of some field in the form
4. Sort the tab by either columns.

## Current Behavior

All values become url encoded.

## Expected Behavior

Values shouldn't change.

## Environment

- App version: Proxyman 4.8.0
- macOS version: macOs Ventura 13.4 (22F66)

**Comment by NghiaTranUIT** [comment]
Thanks. I'm able to reproduce the bug. I'm working on the fix now 👍

**Comment by NghiaTranUIT** [comment]
Fixed: https://download.proxyman.io/beta/Proxyman_4.8.0_Fix_form_sorting.dmg


https://github.com/ProxymanApp/Proxyman/assets/5878421/bd5d8b21-f825-4d9c-80b7-3981cedb8aac

**Comment by seidnerj** [comment]
Awesome! Thanks a lot!
