### ISSUE TITLE
Feature Request:  Export Full folder to web archive

### ISSUE THREAD

**Issue by jason-edstrom** [ProxymanApp/Proxyman#166]
When you have a list of service calls, it would be nice to be able to export the list in a fashion that would work with a program like [Paw](https://paw.cloud).

**Comment by NghiaTranUIT** [comment]
Hey, thank for the feature request 👋 

We're aiming this high priority feature by introducing the HAP as a standard of web archive. 

Therefore, Paw could import them by [HAR extension](https://paw.cloud/extensions/HARImporter).

**Comment by jason-edstrom** [comment]
Great to hear!  I love what you have done so far!

**Comment by NghiaTranUIT** [comment]
Hey @jason-edstrom, I'm glad to inform you that I've finished the HAR Support ticket at https://github.com/ProxymanApp/Proxyman/issues/196 🌮

From now, you can export / import requests from Paw and Proxyman easily 🎉 

We will officially release this tonight. Stay tuned!

**Comment by jason-edstrom** [comment]
@NghiaTranUIT, Awesome news!  Huge props to you, sir.  I'm really excited about this feautre.
