### ISSUE TITLE
Connection is reset when clicking the "clear entire session" button

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/Proxyman#1660]
## Description
Connection is reset when clicking the "clear entire session" button

## Steps to Reproduce

1. Run an ongoing process that's tunneled through ProxyMan
2. Press the clear entire session button

## Current Behavior

Depending on the software you're running you'll get a different error message but they will also essentially say the connection was reset, e.g.:

raise ProxyError(e, request=request)
requests.exceptions.ProxyError: MyHTTPSConnectionPool(host='domain.com', port=443): Max retries exceeded with url: ...

## Expected Behavior

Connection should not be reset

## Environment

- App version: Proxyman 4.8.0
- macOS version: macOS Ventura v13.4

**Comment by NghiaTranUIT** [comment]
Yes, it's expected behavior. Clearing the session means closing all alive connections and wiping out the app memory.

If you'd like to ignore this domain from the app -> You can add it in the Bypass Proxy List in the Tools Menu -> SSL Proxying List.

**Comment by seidnerj** [comment]
Okay, how about if I just want to clear everything in ProxyMan'a interface, ui-wise, without resetting connections? Is it possible to so somehow? 

Many times when I start a new debugging session or during one, I want to delete everything that I've already captured so I so its easier to tell what happened starting from "now" (the moment where I clear the data")

**Comment by NghiaTranUIT** [comment]
Unfortunately, it's not possible for now. The only way is using the By-Pass Proxy list, so this domain never hits Proxyman.

Even though you're using Block List with "Hide, but not block" Option, "Clear Session" will close all connections.

**Comment by seidnerj** [comment]
Okay got it. Closing this for now. Thanks!

**Comment by mjnguyen** [comment]
@NghiaTranUIT: has there been a change on this stance?  it's one feature CharlesProxy has I find very useful to debug active connections by clearing all completed requests.  bypassing is too cumbersome and specific.

Thanks!

**Comment by NghiaTranUIT** [comment]
not yet, to make it simple, we decide to reset all active connections, so it can take effect if we have new active debugging tools.

May I ask what problem it causes? @mjnguyen
