### ISSUE TITLE
If an external socks server is used, where does hostname resolution happen?

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/Proxyman#1666]
In some software, there's a distinction between socks5 and socks5h. In my case, I suspect the DNS queries are being executed from my local machine and not from the socks server itself.

Would be great to get a clarification.

Thanks!

**Comment by NghiaTranUIT** [comment]
Yes, it's. The DNS is handled on your mac. If you'd like to change the DNS, you can do it in System Setting -> Wifi -> Detailed -> DNS.

**Comment by seidnerj** [comment]
But in the case of a socks proxy I want to be able to define that DNS resolution should be handled by the proxy server, is that not possible today?

**Comment by NghiaTranUIT** [comment]
yes, it's not implemented in the latest build.

**Comment by seidnerj** [comment]
Got it, can I open a feature request for this?
