### ISSUE TITLE
Map remote tool, add support for overriding method

### ISSUE THREAD

**Issue by webuniverseio** [ProxymanApp/Proxyman#1672]
## Description

<img width="854" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/911388/843e273e-a716-435e-a34d-00167eebfe61">

In map remote tool you can override schema, ports, host, etc but there is no option to override method

## Why this feature/change is important?

When you're working with graphql in dev you may be using POST method, but in prod, in order to use persistent queries you may be using GET method. When remapping dev to prod I currently can't use map remote tool in this case because I can't change method (so when request in browser is made as POST, it arrives as POST to mapped host).

Please consider adding support for this use case, thank you!

**Comment by NghiaTranUIT** [comment]
@webuniverseio 

Can you simply use the Scripting to achieve the same thing?

It's really simply to translate your Map Remote to the JS code: Here is the sample:
```js
function onRequest(context, url, request) {
    request.scheme = "https";
    request.host = "freshgrocery.com";
    request.port = 443;
    request.path = "graphql";
    return request;
}
```

All Snippet code: https://docs.proxyman.io/scripting/snippet-code#change-request-destination-scheme-host-port-path

**Comment by webuniverseio** [comment]
Hi @NghiaTranUIT , this is true I thought I could use scripting but I find it would be even simpler to have that option in map remote tooling since all other remapping are already present and that is the only one which I wish was there.

Thank you for the snippet!
