### ISSUE TITLE
Incomplete request list on license expiration

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ProxymanApp/Proxyman#1686]
## Description
Proxyman doesn't shows any errored connection after (?) license expiration.

## Steps to Reproduce

I have no idea whether it relevant or not, but that's the only guess I've got.

My license had expired just yet, and now there's some lost requests with proxyman that comes from within iOS Simulator.

I mean, i'm using internal logger and Little snitch, both shows me those requests (whether they're succeeded or not), but not proxyman. There's just nothing appears at that time.

In addition to that I can not say that it failed to handle Simulator requests completely. I mean it do show some of the requests to a server within the same app simulator session, even more — to the exact same gateway, but to a different url path.

## Current Behavior

Like here's the Proxyman log:
```log
https://hidden/path1y/path1ies?size=1000
https://hidden/client/questions?language=EN
https://hidden/path2y/path2ies/ssss?imageDataMode=BACKEND_RELATIVE_URL&size=1000
https://hidden/path2y/path2ies?imageDataMode=BACKEND_RELATIVE_URL&size=1000
https://hidden/path2y/path2ies/allowed?imageDataMode=BACKEND_RELATIVE_URL&size=1000
```

So by other logs I see that this log should be followed with the `https://hidden/path3` API call, but it doesn't get appeared in Proxyman.

## Environment

- App version: e.g Proxyman 4.8.0
- macOS version: e.g macOS 13.4 (22F66)

**Comment by NghiaTranUIT** [comment]
The expired license doesn't relate to how Proxyman captures the traffic.

Just wondering: Do these requests call from the Apple Simulator to Apple Server or from your app to your server?

**Comment by yaroslavyaroslav** [comment]
It started working again after phot laptop restart, still have no clue what happened with it back there, but I guess the issue could be closed now.

**Comment by NghiaTranUIT** [comment]
The iOS Simulator has a bug, we have some users, has confirmed the same issue: https://github.com/ProxymanApp/Proxyman/issues/1696#issuecomment-1614510972

If you use iOS 14, everything is working fine.
