### ISSUE TITLE
v4.8.1 hangs on launch for multiple minutes

### ISSUE THREAD

**Issue by raxityo** [ProxymanApp/Proxyman#1688]
## Description
The app hangs on launch and stays unresponsive for a while.

This has started happening recently and I have been using [this build](https://github.com/ProxymanApp/Proxyman/issues/1626#issuecomment-1558845502) to be able to toggle Proxyman programmatically.

I disabled all tools (breakpoints, map local/remote, etc.) but the hang still persists on launch. 

## Steps to Reproduce

1. Launch Proxyman

## Current Behavior
- The app hangs. Beach ball on the menubar icon, the UI shows an empty list of requests, and the status shows "Proxyman starting…"
- Disabling the proxy from the system settings makes the app responsive after some time.
- Attempted disabling all tools, but no luck.

## Expected Behavior
- App to function correctly without hanging on launch.

## Environment

- App version: e.g Proxyman 4.8.1
- macOS version: e.g macOS venture, Version 13.4 (22F66)

**Comment by NghiaTranUIT** [comment]
Hm, it's odd. Can you reproduce it when using the old beta build(v4.8.0)?

**Comment by raxityo** [comment]
Yes, actually, it also happens in 4.8.0.  Here's a video from 4.8.1 of the wait during the start-up.


https://github.com/ProxymanApp/Proxyman/assets/767683/30876247-ab0a-4192-b8cc-54fcf7c1f991


It may be some other tool interfering with Proxyman. Let me try to go further back in the builds to see if I can find anything helpful for you.

**Comment by raxityo** [comment]
No luck in finding the root cause, but I noticed that `mDNSResponder` jumped to 100% CPU usage when Proxyman started, and killing `mDNSResponder` would make Proxyman responsive again. The problem went away after rebooting the machine, so it must be due to some process triggering tons of DNS queries.

I will close this since it's not a bug in Proxyman.
