### ISSUE TITLE
Export Script List to a text format rather than binary

### ISSUE THREAD

**Issue by barbrzez** [ProxymanApp/Proxyman#1694]
## Description

We would like the ability to export the script list in text format, so that we can version it in source control.

## Why this feature/change is important?

We would like the development teams to build a repository with shared scripts used in Proxyman. 
We want to version control these, and provide one "source of truth" for all developers in our teams.
We would then be able to write a small build task which compiles all our scripts into a "config file", that can be imported by other developers.

In order to be able to do that, the exported/imported config would need to be in a text format rather than in a binary one. 

Please can we request an additional option of importing/exporting text based config?

Thanks
Bart

**Comment by NghiaTranUIT** [comment]
Hi @barbrzez, it's just a Zip file. You should add the `zip` extension, and unzip it. After all, it's just a JSON file.

You can modify the config -> Unzip it -> Import to Proxyman.

We zip it because the config can be large due to additional scripts, attachments, ...

**Comment by barbrzez** [comment]
OK, understood - I can see that the JSON config does not need to be zipped, so as long as it has the .config extension it can also be imported. It's a bit counterintuitive, but I can live with it :).
