### ISSUE TITLE
config the comment max length

### ISSUE THREAD

**Issue by dafong** [ProxymanApp/Proxyman#1695]
## Description

I have a requirement like this. we have a Game App and it communicate with our server with http protocol，and the content is encrypted,
we use Proxy Man to debug the communication procedure，so i write a addon to decrypt the content ,and put the result to the 
comment field,but it seem this field have a length limit,and the content is cutted off。
so if there is setting to config the max length of the comment limit or not have this resitric.

## Why this feature/change is important?

![image](https://github.com/ProxymanApp/Proxyman/assets/1400296/1beb1207-cbe7-4df3-88e3-0ae78ffc25e3)

**Comment by NghiaTranUIT** [comment]
You're right, we limit the number of character in the comment column.

I'm going to implement this similar feature: https://github.com/ProxymanApp/Proxyman/issues/1578 It allows you to:
```
request.preview.body = jsonStr
```

**Comment by NghiaTranUIT** [comment]
To workaround, you can write a decrypted body to a local file: https://docs.proxyman.io/scripting/snippet-code#write-export-to-a-local-file then previewing it with VSCode.

```js
// Write to single file
  writeToFile(response.body, "~/Desktop/body.json");
```

**Comment by dafong** [comment]
thx a lot, and any time schedule to release the 4.9
