### ISSUE TITLE
Customize proxy settings for ignored hosts and domains

### ISSUE THREAD

**Issue by XaoflySho** [ProxymanApp/Proxyman#1705]
## Description

I need to be able to customize "忽略这些主机和域的代理设置" in the proxy when ProxyMan is on.

Although I can manually modify it, poxyman will always override my settings.

## Why this feature/change is important?

Because some hosts or domains will not work properly under the proxy, I need to ignore them.

**Comment by NghiaTranUIT** [comment]
@XaoflySho You can use the Bypass Proxying: https://docs.proxyman.io/basic-features/bypass-proxy-list

**Comment by XaoflySho** [comment]
> @XaoflySho You can use the Bypass Proxying: https://docs.proxyman.io/basic-features/bypass-proxy-list

Thanks for your reply, I've found it, Proxyman is great!
