### ISSUE TITLE
Support for iOS 15.0 or older ?

### ISSUE THREAD

**Issue by nhandbunch** [ProxymanApp/Proxyman#1715]
Hi! 

I'm interested in using GitHub ProxyMan for iOS. 
I see it only supports iOS 16.0 and later.

<img width="285" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/2760183/868a035e-64ef-42f4-9be2-542670cec215">

I wanted to confirm its compatibility with different iOS versions.
Please let me know if GitHub ProxyMan supports iOS 15.0 or older ?

Thank you!

**Comment by NghiaTranUIT** [comment]
Sorry @nhandbunch since the latest update, which has Map Local + Breakpoint features, we decide to drop iOS 15 and only support iOS 16 or later.

We don't have any plan to support backward to iOS 15.

**Comment by nhandbunch** [comment]
Thank you for fast response.
