### ISSUE TITLE
Scroll lock of the queries pane

### ISSUE THREAD

**Issue by griffinreding** [ProxymanApp/Proxyman#1720]
## Description
If possible, it would be nice to have the option to enable auto-scroll of the queries pane to the bottom (newest), and have it locked at the bottom until manually scrolled up. 

## Why this feature/change is important?
It's cumbersome when I'm watching for a specific query to have to scroll all the way to the bottom of the pane when it's fired off, instead of having it locked when I'm already scrolled to the newest.

**Comment by NghiaTranUIT** [comment]
You can simply select the Auto-Select button at the bottom bar. It automatically selects the newest request.

![CleanShot 2023-07-21 at 07 19 24@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/0be87b59-b9e5-4a9a-9990-0f4a0aecbe3e)

-----------
Or you can simply click on the ID column to sort the latest request -> Then select the first request.

**Comment by griffinreding** [comment]
Oh you're a lifesaver - thank you!
