### ISSUE TITLE
BUG: Couldn't see the body from POST with x-www-form-urlencoded

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#173]
## 🐶 Brief
Some users report that the body is missing it's from POST request and content-type=application/x-www-form-urlencoded

We have to investigate it

## 👑 Criteria
- [ ] Able to capture the body

**Comment by jkyeo** [comment]
Cool, I just plan to create the issue about this, seems it solved now. Looking forward to the new build.

**Comment by NghiaTranUIT** [comment]
Only happen in HTTP 💥 

HTTPS works well

**Comment by NghiaTranUIT** [comment]
All done 

## 🤯 Changelogs 
- [x] Add missing header data for HTTP request
- [x] Fix incorrect scheme for HTTP Request

**Comment by NghiaTranUIT** [comment]
Hey @jkyeo. We've released the official Proxyman 1.4.2, which including the fix for this bug. Log: https://github.com/ProxymanApp/Proxyman/releases

If you're Setapp user, please wait a bit today. Setapp team is going to review and launch soon 🙌

**Comment by jkyeo** [comment]
@NghiaTranUIT  🙌Looking forward to the Setapp version.
