### ISSUE TITLE
Issues with 204 responses limiting the connectivity of an android emulator

### ISSUE THREAD

**Issue by GoodSir42** [ProxymanApp/Proxyman#1744]
## Description
When connected to a cisco anyconnect VPN and trying to make a call to https://www.google.com/gen_204 the connection seems to just be closed instead of delivering the 204 response to the client. If I bypass the proxy the issue goes away, same for if I disable the VPN.

I have already tried to track the issue down, but it would be nice if you could look into the code for any places that might lead to this behavior

## Steps to Reproduce

1. Enable a cisco VPN
2. Try to run `curl 'https://www.google.com/gen_204' --proxy http://localhost:9090`
3. See it fail with an ssl connection error

## Current Behavior

The connection is just closed

## Expected Behavior

The client should get a 204 response with no content so that the android connectivity check (which relies on such calls) does not fail

## Environment

- App version: 4.9.1 (49001)
- macOS version: macOS Ventura 13.5 (22G74)
- any android emulator / device using the proxy

**Comment by NghiaTranUIT** [comment]
Thanks. I don't use Cisco VPN, so I couldn't test it, but I will try to use different VPN to reproduce it 👍

**Comment by NghiaTranUIT** [comment]
@GoodSir42 just wondering:
- Are all HTTPS requests failed when using the VPN? 🤔 
- For example, if the VPN is enabled, can you run `curl -v "https://httpbin.proxyman.app/get" --proxy localhost:9090`

**Comment by GoodSir42** [comment]
The funny thing is that everything works except for the 204 requests. I even have a workaround where I map the http fallback requests locally to a file with a correct 204 response.

Let me know if I can help you with anything in terms of reproduction of the issue.

**Comment by NghiaTranUIT** [comment]
@GoodSir42 can you this Beta build: https://download.proxyman.io/beta/Proxyman_4.9.1_Fix_Android_emulators_connection_issue.dmg

It seems doesn't directly relate to your issue, but let's try:

Ref: https://github.com/ProxymanApp/Proxyman/issues/1746

**Comment by GoodSir42** [comment]
@NghiaTranUIT cool, I'll give it a try next week, when I'm back from my vacation 😁

**Comment by GoodSir42** [comment]
@NghiaTranUIT Unfortunately this build give me the same SSL error: curl 'https://www.google.com/gen_204' --proxy http://localhost:9090
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443

**Comment by GoodSir42** [comment]
@NghiaTranUIT Let me know if I can help in any way

**Comment by NghiaTranUIT** [comment]
I'm not sure how to reproduce it because I don't have Cisco VPN.

For now, I suggest just adding it to the ByPass Proxy List. I will keep investigate it 👍

**Comment by GoodSir42** [comment]
adding the URL www.google.com to the proxy bypass list (in proxyman) unfortunately does not help. Also I might have forgotten to mention: without the VPN and just proxyman everything works fine, with just the VPN and no proxyman everything works fine, proxying with charles proxy also seems to work well (except for the fact that charles is not that great by itself). It is just the combination of this VPN and proxy man that fails :/

**Comment by GoodSir42** [comment]
hi @NghiaTranUIT ! I finally found the cause if this issue. The VPN was apparently configured to block IPv6 traffic. I now have to disable IPv6 completely on my mac and all requests are forced to be v4. The upside is that the VPN now routes everything correctly and there was never an issue with Proxyman at all. Thanks fpr the great tool and keep up the good work :)

**Comment by NghiaTranUIT** [comment]
Thanks for letting me know ❤️
