### ISSUE TITLE
Creating Protobuf rules through Tools > Protobuf context menu.

### ISSUE THREAD

**Issue by jjmean2** [ProxymanApp/Proxyman#1747]
## Description

I always add Protobuf rules through  context menu "Tools > Protobuf" triggered by clicking right button on request log item. 
But today I found that menu disappears.

Maybe this functionality was removed in [v4.8.2](https://github.com/ProxymanApp/Proxyman/releases/tag/4.8.2)
> Remove some unused menu items in the Right Menu Context -> Tools (Code Generator, Protobuf)

I think this functionality is useful to make Protobuf rules quickly. Could you bring this functionality back into Proxyman? 
Is there a reason that you removed that?

## Why this feature/change is important?

Without that, I should more action to create a rule to match request that executed from Proxyman log.
Thank you for reading this!

**Comment by NghiaTranUIT** [comment]
Sure, I will bring the Protocol back 👍

**Comment by NghiaTranUIT** [comment]
@jjmean2 here is the Beta build: https://download.proxyman.io/beta/Proxyman_4.9.1_Add_protobuf_menu_items.dmg

I bring it back 😄 except the Code Generator.

**Comment by jjmean2** [comment]
Thank you 👍

**Comment by xzifan** [comment]
When will this feature be available on windows app? The current 2.11.0 does not have this menu in Tools

**Comment by NghiaTranUIT** [comment]
Sorry @xzifan, Windows hasn't supported the Protobuf yet.
