### ISSUE TITLE
Please support decode websocket msg with msgpack

### ISSUE THREAD

**Issue by yaotiancheng-ola** [ProxymanApp/Proxyman#1748]
## Description

When I proxy an websocket connection, the software can't decode msgpack in `Websocket` tab.
If i select `MsgPack`, it display empty
<img width="1436" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/113859954/1f385c6b-5e7b-48f3-8210-c7cf00c62b4a">
<img width="1440" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/113859954/0a11bc30-e336-4afb-865a-3ae119a6668d">

## Why this feature/change is important?
If WebSocket proxy is supported,  I think it is necessary to handle whether each message is in msgpack format.

**Comment by NghiaTranUIT** [comment]
@yaotiancheng-ola let's try this Beta build: https://download.proxyman.io/beta/Proxyman_4.9.1_support_msgpack_for_websocket.dmg

I don't have Websocket with Msgpack payload to test it yet, but it should work 👍 

Let me know if it works for you 👍

**Comment by yaotiancheng-ola** [comment]
@NghiaTranUIT Yes！ It's works! Thanks!
I hope it can be released as soon as possible.

![image](https://github.com/ProxymanApp/Proxyman/assets/113859954/3f6b9ed1-b47f-4fd1-92a0-ad2e39771d3f)
