### ISSUE TITLE
Android network config doesn't need `includeSubdomains`

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1751]
## Description
i think the advice here:
https://docs.proxyman.io/debug-devices/android-device

of
```
<!-- Make sure your URL Server here -->
        <domain includeSubdomains="true">your_production_domain</domain>
```

isn't actually needed. 

my security config looks like this from charles' recommendation and everything works fine
https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by NghiaTranUIT** [comment]
It's interesting. It's recommend by Android Developer at https://developer.android.com/training/articles/security-config

Let me see if it's needed or not. If not, we can remove this part 👍

**Comment by NghiaTranUIT** [comment]
Thanks @ColtonIdle I've tested and confirmed that it's necessary 😢 

It's fixed here: https://github.com/ProxymanApp/Proxyman/issues/1752#issue-1864349624

**Comment by ColtonIdle** [comment]
"it's necessary"

 it's *not necessary, right?

**Comment by NghiaTranUIT** [comment]
ah, my typo. Yes, these domain configs aren't needed.
