### ISSUE TITLE
[Scripting] Is there a way to remove standard onRequest/onResponse logging?

### ISSUE THREAD

**Issue by Mexator** [ProxymanApp/Proxyman#1753]
## Question

Each time my script executes callbacks I see this in log:
```
----------------------------------
12:01:51.092: [onRequest] with Request ID=10883
Run onRequest() func as normal (sync) mode
```

I don't want to see this unless i am debugging my script. How can I remove it?

## Background

I need to keep track of what my app sends in analytics (event name and parameters). 
Currently I do it with console.log(). Analytics events are batched so I do not care to which request an event belongs to.

**Comment by NghiaTranUIT** [comment]
Sure @Mexator I will add an option to hide these app logs 👍  Will send the Beta build this week 👍

**Comment by NghiaTranUIT** [comment]
@Mexator you can try this beta build: https://download.proxyman.io/beta/Proxyman_4.9.1_Hide_proxyman_scripts_logs.dmg

You can enable this option in the More Button 👍 

![Screenshot 2023-08-25 at 15 46 56](https://github.com/ProxymanApp/Proxyman/assets/5878421/918d4b1a-41df-4c5e-ab1e-2358e651dfbc)

**Comment by Mexator** [comment]
Works like a charm! Thank you!
