### ISSUE TITLE
POST data not properly escaped when exporting as cURL command

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/Proxyman#1763]
## Description

POST may not be properly escaped when exporting as cURL command.

## Steps to Reproduce

Take a request with the post take containing an apostrophe, copy as cURL and try to run from the command line.

## Current Behavior

If the post data of a request has an apostrophe in it, it is not escaped.

## Expected Behavior

An apostrophe should be escaped as the post data is already enclosed in apostrophes.

## Environment

- App version: 4.10.0 (49100)
- macOS version: Ventura 13.5.1

**Comment by NghiaTranUIT** [comment]
@seidnerj if you don't mind, can you provide an cURL example, so I can test it easily 🤔

**Comment by NghiaTranUIT** [comment]
Thanks for the detailed example. I'm going to fix it now 👍

**Comment by seidnerj** [comment]
Awesome, thanks!

**Comment by NghiaTranUIT** [comment]
@seidnerj it's fixed. Here is the Beta build: https://download.proxyman.io/beta/Proxyman_4.10.0_fix_escape_string_in_curl.dmg

**Comment by seidnerj** [comment]
Thanks! I am already using another beta for the webkit ssl issue, does the above version include both fixes?

**Comment by NghiaTranUIT** [comment]
Yes, it's included too @seidnerj
