### ISSUE TITLE
Cannot get the `Root Certificate` from Android client `X509TrustManager`

### ISSUE THREAD

**Issue by 4332weizi** [ProxymanApp/Proxyman#1772]
## Description
We check the last `X509Certificate` of the chain, which is passed to the `checkServerTrusted` function in client `X509TrustManager`. Then we import our `Root Certificate` into the proxy, it works fine on Charles but cannot work on Proxyman. When using Proxyman, the size of the `chain` passed is always 1, and doesn't contain the `Root Certificate

## Steps to Reproduce

1. Check root cert sha256 in `X509TrustManager`
```
    private final String CERT_SHA256 = "xxx...xxx"

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        X509Certificate signByRootCert = chain[chain.length - 1];
        MessageDigest sha256Digest = MessageDigest.getInstance("SHA-256");
        String sha256ForCert = toHex(sha256Digest.digest(signByRootCert.getEncoded()));
        if(!TextUtils.equals(CERT_SHA256, sha256ForCert)) {
            throw new CertificateException("xxx")
        }
    }
```
2. Import the `Root Certificate` into Proxyman and Charles
3. Send a request from Android client
4. When using Charles:
```
chain.lenght = 2
TextUtils.equals(CERT_SHA256, sha256ForCert) = true
authType = ECDHE_RSA
```
When using Proxyman:
```
chain.lenght = 1
TextUtils.equals(CERT_SHA256, sha256ForCert) = false
authType = GENERIC
```

## Current Behavior

The certificate chain doesn't contain `Root Certificate`

## Expected Behavior

The `Root Certificate` is the last element of the certificate chain

## Environment

- App version: Proxyman 4.11.0
- macOS version: macOS Ventura

**Comment by NghiaTranUIT** [comment]
Thanks. I will look on it 👍

**Comment by NghiaTranUIT** [comment]
Just wondering: If Proxyman Certificate doesn't contain the your custom Root Certificate in a certificate chain, are you able to decrypt HTTPS traffic without SSL errors 🤔 ?

**Comment by 4332weizi** [comment]
I can find the Root Certificate on Chrome Certificate Viewer, I don't know why `checkServerTrusted(X509Certificate[] chain, String authType)` receives only one X509Certificate.

**Comment by NghiaTranUIT** [comment]
if Proxyman can decrypt HTTPS traffic from your Android, it means the Proxyman Certificate is generated by your custom root certificate -> It also means that it's already in the Certificate Chain.

If it's not true, you get SSL Error on Android devices.

**Comment by 4332weizi** [comment]
Yes, maybe bugs in my app. I will look into it later.

**Comment by 4332weizi** [comment]
Proxyman:
![image](https://github.com/ProxymanApp/Proxyman/assets/5563945/b0246d32-0a46-4373-944e-f5ed2b23fe06)

Charles:
![image](https://github.com/ProxymanApp/Proxyman/assets/5563945/9f870294-06fe-40d4-a4cd-d13015923616)

It seems Proxyman does not send the root CA to the certificates list, the server can omit the root CA.

Reference ([RFC 5246 - TLS v1.2, sec. 7.4.2. - Server Certificate](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.2)):
```
certificate_list
    This is a sequence (chain) of certificates.  The sender's
    certificate MUST come first in the list.  Each following
    certificate MUST directly certify the one preceding it.  Because
    certificate validation requires that root keys be distributed
    independently, the self-signed certificate that specifies the root
    certificate authority MAY be omitted from the chain, under the
    assumption that the remote end must already possess it in order to
    validate it in any case.
```

**Comment by 4332weizi** [comment]
@NghiaTranUIT Can you include an option to send the root CA in the certificate chain?

**Comment by 4332weizi** [comment]
please

**Comment by NghiaTranUIT** [comment]
@4332weizi can you use Charles Proxy and print the Root CA ? `chain[0]` to see the name of the CA Certificate.

I'm not sure how to configure it when using TLSConfiguration.

One of these properties can be fixed:
- https://github.com/apple/swift-nio-ssl/blob/c05ca760bd3e3a593372e3beec15e3cb60703c35/Sources/NIOSSL/TLSConfiguration.swift#L278
- https://github.com/apple/swift-nio-ssl/blob/c05ca760bd3e3a593372e3beec15e3cb60703c35/Sources/NIOSSL/TLSConfiguration.swift#L325

**Comment by 4332weizi** [comment]
yes, `chain[0]` is the Root CA
![image](https://github.com/ProxymanApp/Proxyman/assets/5563945/52e753d5-1a01-4d1b-8c34-49ab8700ef2e)
<img width="550" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/5563945/f4ebbbf9-f2f9-47ee-aeca-50a32d3c85a2">

**Comment by NghiaTranUIT** [comment]
Can you print out the Alternative Subject Name and the Issuer Object?

**Comment by 4332weizi** [comment]
`chain[0]`:
```
Issuer: C=CN, ST=Shanghai, L=Shanghai, O=Anjuke, OU=Mobile, CN=QA-CN/emailAddress=bianwei02@58ganji.com
X509v3 Subject Alternative Name: DNS:*.fang.anjuke.com, DNS:anjuke.com, DNS:jikejia.cn, DNS:vip.58ganji.com, DNS:cloud-passport.58ganji.com, DNS:*.zu.anjuke.com, DNS:*.xzl.anjuke.com, DNS:*.sp.anjuke.com, DNS:*.news.anjuke.com, DNS:*.haiwai.anjuke.com, DNS:*.brand.anjuke.com, DNS:*.anjuke.com, DNS:*.jikejia.cn, DNS:*.xinfang.anjuke.com, DNS:zu.anjuke.com, DNS:xzl.anjuke.com, DNS:sp.anjuke.com, DNS:news.anjuke.com, DNS:haiwai.anjuke.com, DNS:brand.anjuke.com, DNS:xinfang.anjuke.com, DNS:fang.anjuke.com
```

**Comment by NghiaTranUIT** [comment]
May I ask: Are you using [Custom Certificate](https://docs.proxyman.io/advanced-features/custom-certificates) ? Or just use as normal (Use Proxyman CA Certificate).

**Comment by 4332weizi** [comment]
I am using a Custom Certificate

**Comment by NghiaTranUIT** [comment]
Sorry, 1 question: Are you using a Custom Root Certificate, or Server Certificate or Client Certificate ? 🤔

**Comment by 4332weizi** [comment]
Custom Root Certificate

<img width="754" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/5563945/bbd12554-2736-4f2c-98a5-ed7a187aa9cc">

**Comment by NghiaTranUIT** [comment]
Can you try this build: https://download.proxyman.io/beta/Proxyman_4.12.0_Add_to_rootTrusts.dmg

I add the Root Certificate to the `trustRoot` property. I can't test it because I don't have your setup.

**Comment by 4332weizi** [comment]
seem nothing changed

![image](https://github.com/ProxymanApp/Proxyman/assets/5563945/b2b44e4e-9691-43a4-8483-04f60d4d6f04)

**Comment by NghiaTranUIT** [comment]
How about this build: https://download.proxyman.io/beta/Proxyman_4.12.0_try_to_fix_rootTrusts_v2.dmg

**Comment by 4332weizi** [comment]
Nice, I can see the Root CA now, and SSL Proxying works. Thank you so much！

**Comment by NghiaTranUIT** [comment]
@4332weizi can you check this build again: https://download.proxyman.io/beta/Proxyman_4.12.0_Fix_Trust_Root_v3.dmg

I did some refactoring and I think it should work as intended. Sorry, I don't have your setup, so I can't verify it by my own.

**Comment by 4332weizi** [comment]
Just like the previous version!
