### ISSUE TITLE
Response pane has excessive minimum width, prevents resize of left sidebar and forces window to be wider than screen

### ISSUE THREAD

**Issue by manicminer** [ProxymanApp/Proxyman#1775]
## Description

After a recent update (not sure if it's the very latest one), I'm unable to resize various panes/bars in the Proxyman window due to an apparent minimum width of the response pane when docked at the bottom. The response pane will not shrink smaller than around 70-80% of my entire screen width when the window is maximized. My screen's horizontal effective pixel width is set to around 1905 pixels, this is on a Macbook Pro 14". This forces the request pane to be really small, and the sidebar to be effectively unusable. If I toggle the sidebar, often the window will be force-resized to be larger than the screen, seemingly to accommodate the minimally massive response pane.

## Steps to Reproduce

1. Open Proxyman on screen with effective pixel width of around 1905 pixels
2. Try to view the left sidebar whilst request/response dock is set to bottom
3. Try to increase width of left sidebar
4. Try to increase width of request pane / reduce width of response pane in bottom dock

## Current Behavior

When trying (2), the window is auto resized to be larger than the screen width.
When trying (3), cannot make it wide enough to see any domain labels
When trying (4), cannot enlarge request pane / shrink response pane

## Expected Behavior

To be able to fit everything on the screen and resize the response pane so that it's not 70% of the width of the screen

## Environment

- App version: Proxyman 4.11.0
- macOS version: Ventura 13.5.2

**Comment by manicminer** [comment]
This is the minimum width of the response pane:

<img width="1905" alt="Screenshot 2023-09-20 at 23 41 07 (2)" src="https://github.com/ProxymanApp/Proxyman/assets/251987/b8a92d32-df8a-48ea-bea0-2315824d48b7">

When toggling the sidebar, the window is forced larger than the screen:

<img width="1905" alt="Screenshot 2023-09-20 at 23 42 59 (2)" src="https://github.com/ProxymanApp/Proxyman/assets/251987/561ebd24-fcc2-4bc3-80fa-81b7dd4fe794">

**Comment by NghiaTranUIT** [comment]
It seems the Auto Constraint doesn't work well on small-screen devices.

Can you work around by:
1. Hide the Bottom Bar first
2. Resize the width of the left panel, and make it bigger.
3. Show the Bottom bar again.

----------
You can try to Factory Reset in the Help Menu -> Advance -> Don't check the "Include Use Data" -> It will reset the position of the apps, panels, default config, ...

**Comment by manicminer** [comment]
@NghiaTranUIT Thanks for the quick reply. I tried hiding the bottom bar and resizing the sidebar as per your suggestion, but when the bottom bar is re-enabled, it shrinks the sidebar width back down again and doesn't allow it to be enlarged.

I'll happily try a factory reset but I'd really like to save my Map Local settings and Scripts. Is there a config directory I can perhaps move elsewhere and move it back again later, or some other way?

**Comment by chilikasha** [comment]
same for me (1440*900)
this is the max width of response panel I can make.
![SCR-20230925-q2y](https://github.com/ProxymanApp/Proxyman/assets/3147449/84d52398-6144-45d2-80c9-b7e56351183c)


if I enable request panel as well, then proxyman window never fits display size and I can't adjust widths at all. make requests list more narrow for example.
![SCR-20230925-q3r](https://github.com/ProxymanApp/Proxyman/assets/3147449/1862fbb7-15aa-4aa7-ba3f-a845b74664fb)

**Comment by NghiaTranUIT** [comment]
> I'll happily try a factory reset but I'd really like to save my Map Local settings and Scripts. Is there a config directory I can perhaps move elsewhere and move it back again later, or some other way?

Factory Reset with `unchecked` "Include User Data" will not delete your rules. It just resets the app Preference Data.

@chilikasha Can you try Factory Reset in the Help Menu -> Advanced 🤔

**Comment by chilikasha** [comment]
hi @NghiaTranUIT, I just did and honestly don't see much difference. ideally I would like to have ability to resize request/response (both) body width, make wider that requests list for example. but seem it has some limit.

**Comment by NghiaTranUIT** [comment]
Can you try to detach the Request/Response Windows and see if you can resize the width freely?

![CleanShot 2023-09-28 at 14 59 28@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/dfc260d7-76de-4994-ad1e-5a1c9e1424fa)

Let me remove some constraints, so make it's easily resize.

**Comment by NghiaTranUIT** [comment]
I'm able to reproduce it @chilikasha. I'm fixing it now 😄

**Comment by NghiaTranUIT** [comment]
@chilikasha @manicminer let's try this Beta build: https://download.proxyman.io/beta/Proxyman_4.11.0_Fix_small_layout.dmg

I removed some fixed constraints that prevent the SplitView from resizing to a small size. Let me know if it fixes your bug 👍

**Comment by NghiaTranUIT** [comment]
Glad to know that it finally works 😄 I will ship this fix on the next update 🙇

**Comment by manicminer** [comment]
Updated today to 4.12.0 (49300), still no longer encountering this issue. Thanks again! 🎸

**Comment by manicminer** [comment]
Closing this out, thanks again
