### ISSUE TITLE
Can we fake IP address in requests?

### ISSUE THREAD

**Issue by takasurazeem** [ProxymanApp/Proxyman#1776]
## Description

Hi, I have to test an application that has geo restricted features and I cannot use VPN with proxy-man, is there a way to change the IP address for requests to a certain app in proxyman? It's an iOS app running in simulator.

**Comment by NghiaTranUIT** [comment]
Sorry, it's not what Proxyman can do. You might use other VPN that allows you to change the IP address.

**Comment by takasurazeem** [comment]
> Sorry, it's not what Proxyman can do. You might use other VPN that allows you to change the IP address.

No worries, just something possible with Charles. I thought would be possible with ProxyMan as well.

**Comment by NghiaTranUIT** [comment]
Just wondering @takasurazeem How can you do it with Charles Proxy? What debugging Tool from Charles do you use? 🤔

**Comment by takasurazeem** [comment]
> Just wondering @takasurazeem How can you do it with Charles Proxy? What debugging Tool from Charles do you use? 🤔

https://stackoverflow.com/a/73481078/3077444

**Comment by NghiaTranUIT** [comment]
Then, you can do the same thing with Proxyman.

1. Tools menu -> Scripting -> New Rule
2. In the URL: Use `*` to represent all requests
3. Use this script to add the header `X-FORWARDED-FOR`

```
function onRequest(context, url, request) {
    request.headers["X-FORWARDED-FOR"] = "<Your_IP_Address>";
    return request;
}
```

4. Make some request -> Right Click -> Enable SSL proxying -> Done.

Please note that only requests that are enabled SSL Proxying, will be modified by the Scriptping -> Has new Header.
