### ISSUE TITLE
JSON float round

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ProxymanApp/Proxyman#1782]
## Description

Proxyman rounds float values on JSON to 2 numbers in a fraction part. It's kinda confusing, thus it's unexpected that values of a response/request would be modified instead of just being formatted.

## Steps to Reproduce

```json
{"destLocationGroupId":"UUID","sourceLocationGroupId":"UUID","amount":99999.00999999999,"serviceId":"UUID","orderDirection":"DirectionType"}
```

1. Send the json above to any given server

## Current Behavior

In body tab `amount` field would be shown as `99999.01`

## Expected Behavior

To show in body tab exact number as it's stored within raw data.

## Environment

- App version: e.g Proxyman 4.8.0 (48000)
- macOS version: e.g macOS Sonoma 14.0

**Comment by NghiaTranUIT** [comment]
Do you use Scripting or other tools that modify the value ? By default, Proxyman only proxies the data without modifying any actual data.

**Comment by yaroslavyaroslav** [comment]
Nope, it's the actual case. I mean the very same response presented in `raw` tab in its full size as `99999.009999999`, but in body size it's not and it's rounded to 2 numbers in a fraction part. 

Ps: at first I was meant to write this issue as a question, but I've checked raw tab right before publication, and saw that there's unmodified value presented.

**Comment by NghiaTranUIT** [comment]
Just wondering: Does this issue affect your actual Request/Response on your server-side ?  Or just a display issue on the Body Tab 🤔

**Comment by yaroslavyaroslav** [comment]
> Does this issue affect your actual Request/Response on your server-side ?

It affects, that's how I faced it - I've got a server error that the fractional part are way too long in my request, and that I was struggling to understand why two decimal after a point is too much for it.

**Comment by invisible-debug** [comment]
Also relevant for me. The request is sent correctly to the backend. But the proxy does not display correctly. Because of this, it is impossible to debug traffic. It creates a false impression that the bug is on the backend.

**Comment by NghiaTranUIT** [comment]
May I ask: @invisible-debug can you see the bug in the Raw Tab?

and do you use any debugging tool?

**Comment by invisible-debug** [comment]
Oh. Raw displays correctly, my friend @NghiaTranUIT . Error is displays only on the Body tab
I don't use any debugging tool. Postman + Proxyman
I attach a screenshot with the original request in Postman and incorrectly displayed in Proxyman
<img width="2419" alt="bug_floating_point" src="https://github.com/ProxymanApp/Proxyman/assets/174007516/05bdb0c1-69da-41de-b54d-7722c82a96b7">

**Comment by NghiaTranUIT** [comment]
thanks @invisible-debug I'm able to reproduce this bug. Let me fix it and send a hotfix asap 👍

**Comment by invisible-debug** [comment]
@NghiaTranUIT We have some bureaucratic problems with paying for the license. Will I not be able to get this fix if my subscription expires?

**Comment by NghiaTranUIT** [comment]
Preliminary investigation shows that it's because our JSON Lib (nlohmann/json) doesn't support big numbers by default. I'm going to find a new solution to fix it

**Comment by NghiaTranUIT** [comment]
@invisible-debug let's try this Beta build: https://download.proxyman.io/beta/Proxyman_5.5.0_Try_to_fix_JSON_big_number.dmg

- Treat all big numbers as a raw value (Not parsing) -> Fix the big float number issue 👍 
- I will write some Unit Tests to make sure it doesn't break other things

<img width="710" alt="Screenshot 2024-06-28 at 09 57 49" src="https://github.com/ProxymanApp/Proxyman/assets/5878421/cb9e7d95-4e2d-47d7-889a-a7db29e3b055">

**Comment by invisible-debug** [comment]
Yes, I checked it out. This really solves the problem. Thanks!
<img width="548" alt="fixed" src="https://github.com/ProxymanApp/Proxyman/assets/174007516/efa9edc8-a295-4441-b694-8f70224607fb">

**Comment by NghiaTranUIT** [comment]
Awesome, I will write some Unit Tests and release it in the next update 👍

**Comment by invisible-debug** [comment]
@NghiaTranUIT Give me more information on this bug, please. It is very critical for my company and has not been fixed for a long time
https://github.com/ProxymanApp/Proxyman/issues/1569
