### ISSUE TITLE
Can not use proxyman in mac os sonoma 14.0 (23A344

### ISSUE THREAD

**Issue by nopparitP** [ProxymanApp/Proxyman#1787]
## Description
Can not use Proxyman in mac os Sonoma 14.0 because when enabling these options 

- Record traffic
- macOs Proxy Overiden

I can not access the internet e.g.: can not use Google search and so on.

## Steps to Reproduce

- Update mac OS to Sonoma
- use Proyman by enabling these options 
   - Record traffic
    - macOs Proxy Overiden

## Current Behavior

Can not use proxy man in Sonoma 14.0

## Expected Behavior

Must can use in Sonoma 14.0

## Environment

Production

- App version: Version 4.11.0 (49200)
- macOS version: Sonoma 14.0

**Comment by NghiaTranUIT** [comment]
Hm, I'm using Proxyman on macOS Sonoma 14 without any problems.

Can you double-check if the Helper Tool is installed in the Proxyman -> Setting -> Advance Tab 🤔

**Comment by nopparitP** [comment]
@NghiaTranUIT  I found That ProxyMan try to record traffic but seem not to work.

https://github.com/ProxymanApp/Proxyman/assets/47601384/805ba701-6c44-4637-98ee-6f21e7a11fc6

**Comment by NghiaTranUIT** [comment]
Can you do Factory Reset in Help Menu -> Advanced ?

**Comment by nopparitP** [comment]
@NghiaTranUIT I found the same issue after doing a factory reset.

**Comment by nopparitP** [comment]
@NghiaTranUIT I need to add more information, It seems Proxyman tracks a lot of traffic as you can see in this video, and broke my network connection.   

https://github.com/ProxymanApp/Proxyman/assets/47601384/1d492ab2-9961-4d80-aeb3-26e65b889970

**Comment by NghiaTranUIT** [comment]
Hmm, it's really strange. I haven't received any issue like this before.

Do you use any VPN apps at the same time? I suppose that it's conflicted with Proxyman.

**Comment by nopparitP** [comment]
I killed my VPN before using Proxyman.

**Comment by nopparitP** [comment]
@NghiaTranUIT As I checked this issue came from my anti-virus thank you for your support
