### ISSUE TITLE
Internal error when launching proxyman

### ISSUE THREAD

**Issue by Jonathan-Lequeux** [ProxymanApp/Proxyman#1800]
## Description
Since this week and for no apparent reason proxyman decided to not work anymore.
I'm using proxyman mainly on iOS simulator and currently when I launch it I'm unable to connect to the internet.

All my requests on iOS simulator and web browser have internal error as status with the 999 code.
<img width="800" alt="Capture d’écran 2023-10-06 à 16 24 44" src="https://github.com/ProxymanApp/Proxyman/assets/127201075/48ff9732-452b-4a02-98a0-ae498b5d991b">

I checked the proxyman settings and everything seems good. 

| General | Advanced |
| ------ | ----------- |
| <img width="500" alt="Capture d’écran 2023-10-06 à 16 20 22" src="https://github.com/ProxymanApp/Proxyman/assets/127201075/82f3c102-cedb-4623-b1b8-328e25c6157e">   | <img width="500" alt="Capture d’écran 2023-10-06 à 16 21 46" src="https://github.com/ProxymanApp/Proxyman/assets/127201075/6cfa29c5-1b1b-4567-ba5b-0ca4947d3578"> |

I have tried installing Charles proxy and I have the same issue.
I went deeper and it seems that when the `Secure web proxy` is checked, this is were I lost my internet connexion and I don't understand why.

Here is my proxy settings for my wifi network when proxyman is launched.
<img width="772" alt="Capture d’écran 2023-10-06 à 16 22 14" src="https://github.com/ProxymanApp/Proxyman/assets/127201075/d73dcaee-a5cb-49bd-af4b-c1863e5b0b70">

Hoping that it's just a little mistake.

## Steps to Reproduce

1. Installing proxyman 4.12.0
2. Installing certificate and Proxy helper tool
3. Launch Proxyman

## Current Behavior

I can't have access to internet

## Expected Behavior

I should have access to internet, seeing all request from my web browser.

## Environment

- App version:  Proxyman 4.12.0
- macOS version: MacOS Ventura 13.6

**Comment by NghiaTranUIT** [comment]
Your setting seems correct. I tested it on my own and it works fine.

I guess you're using a VPN app or have an Anti Virus app that is active at the same time with Proxyman ? 🤔  If yes, try to turn it off.

Just wondering: Can you open Google Chrome and try to intercept some website?, such as google.com

![CleanShot 2023-10-06 at 22 04 12@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/1d74241a-f69c-4cb9-b7bb-4f676f3ec3bb)

**Comment by Jonathan-Lequeux** [comment]
I've a VPN but it never works together with Proxyman.
So when I use proxyman, I always disable the VPN.

It seems that google.com does complete the request but it is very slow.
Some other websites does work but other doesn't and in every case it is very slow.

I've seen something interesting. It seems that proxyman is using a lot the CPU.

<img width="800" alt="Capture d’écran 2023-10-06 à 17 22 27" src="https://github.com/ProxymanApp/Proxyman/assets/127201075/2769d11d-e6a1-4073-8b42-4d9b80e8551f">

**Comment by NghiaTranUIT** [comment]
If you don't mind, can you try to open Charles Proxy, and check if it also happened? 

Meanwhile, you can do Factory Reset (Don't check the Include User data, so your rules are safe) in the Help Menu -> Advance -> Factory Reset.

**Comment by Jonathan-Lequeux** [comment]
I've found the issue, it was indeed my Anti virus app (Bitdefender).
It was working fine before but it is possible that an update of the antivirus provoked this.
Thanks @NghiaTranUIT for your time.
