### ISSUE TITLE
Real device Infinity reset loop

### ISSUE THREAD

**Issue by gikKid** [ProxymanApp/Proxyman#1802]
## Description
 device will enter to infinity reseting loop

## Steps to Reproduce

1. Install proxy certificate at real iphone X device ( IOS 16.7 )
2. Used proxyman at work day, everything was good
3. After iphone battery was dead, device was connected to power and starting enter to infinity reset loop
4. Real device starting, it spends several seconds before connecting to WIFI with proxy ( proxy certificate was on ), and at moment connecting to this WIFI, device started reseting
5. This was fixed by disable WIFI connecting, disabling certificate and remove proxy setting at the WIFI point

## Environment

- App version: e.g Proxyman Version 4.10.0 (49100)
- macOS version: e.g macOS Ventura 13.2

**Comment by NghiaTranUIT** [comment]
Hmm, I don't think it's what Proxyman can fix. It's definitely the Apple OS bug.

Then the device is restarted, it means the iOS is crashed.
