### ISSUE TITLE
Hangs when quitting application

### ISSUE THREAD

**Issue by dkocher** [ProxymanApp/Proxyman#1806]
## Description
Beachballing when quitting application for a long time.

## Steps to Reproduce

1. Quit Proxyman.app

## Current Behavior

Previously the application quit instantly.

## Expected Behavior

Instant quit.

## Environment

- App version: Version 4.12.0 (49300)
- macOS version: 14.0 (23A344)

[Sample of Proxyman.txt](https://github.com/ProxymanApp/Proxyman/files/12909694/Sample.of.Proxyman.txt)
[Proxyman_2023-10-15-153753_silverbullet.hang.zip](https://github.com/ProxymanApp/Proxyman/files/12909701/Proxyman_2023-10-15-153753_silverbullet.hang.zip)

**Comment by NghiaTranUIT** [comment]
May I ask If you installed the Helper Tool in Proxyman Setting -> Advanced Tab -> Helper Tool?

If it's not installed, Proxyman uses `networksetup` CLI to try reverting the HTTP Proxy when closing the app. This CLI might take a little bit longer and cause the beach ball.

Install the helper tool will fix it.

**Comment by dkocher** [comment]
> May I ask If you installed the Helper Tool in Proxyman Setting -> Advanced Tab -> Helper Tool?
> 
> If it's not installed, Proxyman uses `networksetup` CLI to try reverting the HTTP Proxy when closing the app. This CLI might take a little bit longer and cause the beach ball.
> 
> Install the helper tool will fix it.

The helper tool is installed (Version 1.4.0).

**Comment by dkocher** [comment]
Tried to delete the application state in `~/Library/Saved Application State/com.proxyman.NSProxy.savedState` but that does not resolve the problem.

**Comment by dkocher** [comment]
Related to this it also takes an unusually long time to launch the application since a few releases.

**Comment by NghiaTranUIT** [comment]
It's odd. Can you try to do Factory Reset in the Help -> Advance menu.

It's safe to do Factory Reset if you don't tick the "Include User Data". Your rules/config won't be wiped out.

**Comment by dkocher** [comment]
> It's odd. Can you try to do Factory Reset in the Help -> Advance menu.
> 
> It's safe to do Factory Reset if you don't tick the "Include User Data". Your rules/config won't be wiped out.

This resolved both startup and quit beachballing. Thanks for the super fast support 😎.

**Comment by NghiaTranUIT** [comment]
You're welcome. Let me investigate the root of the problem. The different I can tell is how Proxyman closes the SwiftNIO HTTP Server.
