### ISSUE TITLE
Support websocket

### ISSUE THREAD

**Issue by yisiqi** [ProxymanApp/Proxyman#182]
I am developing a chat app using WebSocket. It would be helpful if this could support WebSocket.

<img width="512" alt="Screen-Shot-2016-07-18-at-12 19 38-PM-1024x486" src="https://user-images.githubusercontent.com/1735804/59762965-0320ac00-92cb-11e9-8241-d9a45b1b6a1a.png">

**Comment by NghiaTranUIT** [comment]
Thank for the feature request. We're aware that there is large number of users, who requests this WebSocket debugging too.

It's in our roadmap. We will support it soon 👍 Stay tuned!

**Comment by ConfusedVorlon** [comment]
yup - that would be great. Specifically for me, I'd like to see websocket traffic on the local network (iOS device talking to TV - both connected to the mac via internet sharing)

**Comment by superandrew** [comment]
I'm adding my self to the list of the supporters, because React Native Debugger won't work if proxyman is active when application starts. However, is there any known workaround for this?

**Comment by NghiaTranUIT** [comment]
Hey, sorry for this. From what I see that there is no workaround for this issue until I fix this bug. The React Native debugger seems open the URI `"rndebugger://set-debugger-loc?host=localhost&port=8081"` and Proxyman doesn't recognize it properly.

I will fix this bug separately and notify you in this week @superandrew 👍

**Comment by NghiaTranUIT** [comment]
Bug #240

**Comment by NghiaTranUIT** [comment]
All done 👍 

## Changelogs
- [x] Support Websocket previewer 
- [x] Filter by All, Sent and Receive
- [x] Support Pretty message: JSON and TreeView
- [x] Filter Websocket on Filter Bar
- [x] Able to export websocket content

<img width="1792" alt="Screen Shot 2019-10-16 at 11 25 07" src="https://user-images.githubusercontent.com/5878421/66888247-feb19900-f007-11e9-8bf7-e79000abda13.png">

I will rollout the BETA soon 👍

**Comment by NghiaTranUIT** [comment]
Hey guys, Good news that here is the BETA build for the WebSocket debugger 🍺 

https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.2_Websocket_Debugger.dmg

Sorry for delay 1 day since there was an issues on Socket IO (https://github.com/ProxymanApp/Proxyman/issues/303) 🌮 

Some screenshot to visualize easier 😄 

<img width="1023" alt="Screen_Shot_2019-10-17_at_10_08_56" src="https://user-images.githubusercontent.com/5878421/66976514-692c0d00-f0cc-11e9-9dca-597b0009a67e.png">

I'm going to release in this week including with the Blog too 🍎

**Comment by NghiaTranUIT** [comment]
Hey @modestman, @endel, @drekka, @metabren, @ollitapa, and @yisiqi

Just friendly reminder that this Websocket feature has been done in the latest Proxyman 1.7.0 🎉 

- You can check out the tutorial at https://proxyman.io/blog/2019/10/WebSocket-Debugging.html
- Changelogs at https://github.com/ProxymanApp/Proxyman/releases/tag/1.7.0

Let give it a try and feel free to report any bugs 🐞 

Thank you guys in advance 💯

**Comment by drekka** [comment]
Awesome guys !

**Comment by akapitoha** [comment]
hey @NghiaTranUIT 
maybe any advice: same app, but on android I see both wss and https traffic, on ios - only https. what could be the reason?

**Comment by NghiaTranUIT** [comment]
Can you try on the latest version 1.12.0, which we released yesterday? 
Since I discovered a bug where some URLs don't appear on Proxyman app. You can update directly from Proxyman app.

Meanwhile, if it's still persisted, can you share me how the WSS URL look like? I would investigate it 👍

**Comment by madneal** [comment]
try to install as the tutorial, and I install slack app. But I can only see the https and http traffic, no websocket. @NghiaTranUIT 

the proxyman version is 2.1.0

**Comment by NghiaTranUIT** [comment]
Hi @madneal, if you mean Slack app on macOS, we couldn't see it because the Slack app uses SocketIO, and it automatically fallbacks to HTTP/HTTPS request.

You can try Slack on iOS, you can see the domain `wss-mobile.slack.com`. Enable SSL-Proxying for this domain and you can see it 👍

**Comment by NghiaTranUIT** [comment]
You can test by visiting github.com, enable `live.github.com`, then you can see WS on `wss://live.github.com`

<img width="1645" alt="Screen_Shot_2020-06-29_at_09_36_37" src="https://user-images.githubusercontent.com/5878421/85967206-20af4800-b9ec-11ea-8160-184601e11bc7.png">

**Comment by madneal** [comment]
@NghiaTranUIT Thanks for your quick reply. The app I installed is IOS, not for mac. And if I configured wss-mobile.slack.com in SSL proxying list, the status code was 999.
![image](https://user-images.githubusercontent.com/12164075/85970933-71c83780-b9fe-11ea-8ae4-d5bd98565b29.png)
![image](https://user-images.githubusercontent.com/12164075/85970939-7a207280-b9fe-11ea-853e-502c543abcc8.png)

And the websocket is empty.

**Comment by NghiaTranUIT** [comment]
Just wondering @madneal, do you able to see HTTP/HTTPS requests/responses from the Slack iOS app? Just to confirm that you're installed Proxyman CA on your iPhone properly. 

- If NOT, please checkout Certificate Menu -> Install Proxyman CA on iOS Device and trust Proxyman CA (the last steps)
- If YES, I will investigate it, since I tested on my machine and I'm able to see WSS from Slack iOS app

**Comment by madneal** [comment]
@NghiaTranUIT I was able to see HTTP/HTTPS requests/responses from the Slack IOS app if I did not configure SSL proxying list for the host. And I have installed the CA on my iphone.

**Comment by NghiaTranUIT** [comment]
Just check on the latest Slack iOS app and Proxyman 2.1.0 and it works. I'm able to see wss content.

Can you help me to reset all app by Help Menu -> Advanced -> Reset all and try again @madneal 

<img width="1645" alt="Screen_Shot_2020-06-29_at_13_04_21" src="https://user-images.githubusercontent.com/5878421/85979069-100dca80-ba0a-11ea-99be-850213925216.png">

**Comment by madneal** [comment]
The result is still same. The response code is 999 error if I config it in SSL proxying list. If I remove the host, the reponse code is 200. But I cannot see any websocket messages. I have reset all data.

![image](https://user-images.githubusercontent.com/12164075/85980212-8c0d1000-ba14-11ea-99a4-d3132d0a9a73.png)

Burp works for me. I'd move to burp.

**Comment by NghiaTranUIT** [comment]
can you share with me the version of your Slack app and macOS? I would like to investigate it 👍

**Comment by madneal** [comment]
My mac version is 10.14.6. I think it has nothing to do with the Slack version. As it didn't work for live.github.com either.
