### ISSUE TITLE
Whether the left side can be folded by default?

### ISSUE THREAD

**Issue by 1414044032** [ProxymanApp/Proxyman#1820]
## Description

 i need application list and that children application and url and children url  【default  put away 】Now he's unrolled by default, so it's hard to find。
## Why this feature/change is important?

I'm mainly concerned with someone I'm trying to catch one host, but all url and children url is default opened 。i can't first see I want to see host and it's children。
<img width="1067" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/33045977/4f70aa9b-ff58-41de-87a3-7c524fe3a738">

**Comment by NghiaTranUIT** [comment]
You can simply filter the domain by using the Filter at the end of the Left Panel.

![CleanShot 2023-10-20 at 13 38 07@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/c47fa74d-7cbe-4cf8-bfdd-940087c6373d)

**Comment by 1414044032** [comment]
good , It can meet my needs
