### ISSUE TITLE
Can Proxyman support dynamic environment variables?

### ISSUE THREAD

**Issue by Seayon** [ProxymanApp/Proxyman#1839]
## Description

In my case, I have some variables with fixed keys, but their values change frequently. Previously, I manually opened the script and wrote the new values, but it became tedious. So, I tried writing the variables to the ~/.zshrc file and changed the ENV in ~/.zshrc quickly. However, I found that Proxyman couldn't read the latest variables.

Is it possible to provide a hook for Proxyman to get the latest environment variables? Or, can Proxyman support a feature to save simple variables and let me choose one from the menu bar quickly?

Thank you! 

## Why this feature/change is important?

Proxyman is a very professional and easy-to-use tool. Adding such a feature doesn't feel very complicated, but it would provide higher customization options for professional users.

**Comment by NghiaTranUIT** [comment]
Proxyman Scripting can read your ENV from `~/.zshrc` ([docs](https://docs.proxyman.io/scripting/environment-variables#2.-environment-variables)).

Here is the example:
```js
async function onResponse(context, url, request, response) {
  console.log($PATH);
  console.log($ACCESS_TOKEN);
  console.log($PROXYMAN_PATH);
 
  // Done
  return response;
}
```

**Comment by Seayon** [comment]
> Proxyman Scripting can read your ENV from `~/.zshrc` ([docs](https://docs.proxyman.io/scripting/environment-variables#2.-environment-variables)).
> 
> Here is the example:
> 
> ```js
> async function onResponse(context, url, request, response) {
>   console.log($PATH);
>   console.log($ACCESS_TOKEN);
>   console.log($PROXYMAN_PATH);
>  
>   // Done
>   return response;
> }
> ```

Thank you for your reply!

I am able to use the ENV from ~/.zshrc, and I find that the Proxyman documentation is very comprehensive. However, my problem is whether Proxyman can automatically read the updated from  ~/.zshrc ?

**Comment by NghiaTranUIT** [comment]
It's not automatically load the env yet because it's an expensive operation. That's the reason why I introduced the "Reload env" button.

How often your ENV is changed that you need to reload the ENV automatically?

**Comment by Seayon** [comment]
> It's not automatically load the env yet because it's an expensive operation. That's the reason why I introduced the "Reload env" button.现在还不能自动加载环境，因为这是一项昂贵的操作。这就是我引入 "重新加载环境 "按钮的原因。
> 
> How often your ENV is changed that you need to reload the ENV automatically?需要自动重新加载 ENV 的 ENV 变更频率是多少？

Actually, The frequency of changes actually depends on how busy I am at the moment. I am working on multiple projects simultaneously, and each project has a fixed key. However, the value that determines the flow direction for each project is different. That's why I want to have a 'Quick Switch and Reload' feature. I usually  do it manually，which is why I would like to have a hook to inform Proxyman to reload the ENV ？

**Comment by Seayon** [comment]
By the way, I fully understand that automatically loading environment variables is also an expensive operation. Therefore, I'm wondering if it's possible to provide a hook or API for me to call?

**Comment by NghiaTranUIT** [comment]
I guess I can introduce a helper func, like:

```js
_reloadENV();
```

It runs synchronously and you can run it directly in your Scripts. How do you feel?

**Comment by Seayon** [comment]
> I guess I can introduce a helper func, like:
> 
> ```js
> _reloadENV();
> ```
> 
> It runs synchronously and you can run it directly in your Scripts. How do you feel?

Does this mean I have to call it within a script in Proxyman? Can I have my own program call it instead? Some external applications or shell scripts that I developed myself. If this is very difficult, then calling it within a Proxyman script is also good, at least I can use it.

**Comment by NghiaTranUIT** [comment]
@Seayon you can try this Beta build: https://download.proxyman.io/beta/Proxyman_4.14.0_Scripting:_Reload_Env_by_scripts.dmg

- Docs: https://docs.proxyman.io/scripting/environment-variables#3.-additions
- Sample code:
```js
async function onRequest(context, url, request) {
  // manually reload to get the latest changes
  _reloadEnv();
  
  // get env
  console.log($PROXYMAN_ID)
  
  // Done
  return request;
}

```

**Comment by Seayon** [comment]
> ```js
>  // manually reload to get the latest changes
>   _reloadEnv();
> ```

Thanks ! This very useful !
