### ISSUE TITLE
Getting It seems your host/port is invalid, please double check the Map Remote Config

### ISSUE THREAD

**Issue by rakeshkarkare** [ProxymanApp/Proxyman#1843]
## Description

Getting 403 for responses after mocking and using automation script

I am using Python script to automate mobile apps. I am trying intercept responses of server, by mocking responses using flask server and proxyman

Sometimes the proxyman is giving 403 status code If I run mobile app along with flask mock server through automation script
But, if I manually run the flask server and open mobile app manually same script is working. Looks like there is some delay from proxyman in order to mock responses through script bcoz I can see the response showing in proxyman is slow.

Note : I am trying to kill the proxyman app and relaunch again in order to import rule for specific endpoint to validate the use case on UI after response is mocked

## Current Behavior

Getting 403 for responses after mocking and using automation script
Also observed in response for the particular endpoint other than status code the headers in response showing as content-length -as 0 and Server as AirTunes/675.4.1

## Expected Behavior

It should work and send response with proper status which was used in mocking

## Environment

- Proxyman App version: 4.14.0 (49500)
- macOS version: macOS Ventura Version 13.2

**Comment by rakeshkarkare** [comment]
Please let me know if any settings needed to do in proxyman app bcoz same works  and gets mocked with proper response if I give time.sleep in my script

**Comment by rakeshkarkare** [comment]
I tried to google the problem did disable the Airplay receiver now getting 500 error with below response

 {
  "remote_url": "localhost.proxyman.io:5000",
  "error": "Request Timeout",
  "note": "It seems your host/port is invalid, please double check the Map Remote Config"
}

**Comment by rakeshkarkare** [comment]
I tried modifying the etc/hosts file but no luck, still facing same issue. Tried repeating the request with proxyman got below error 

<img width="260" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/55023c54-716c-4b0c-b449-023e01b48ef2">

<img width="423" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/f09726b5-b184-4c84-9064-7f9ae7a25e87">



{
  "remote_url": "localhost:5050",
  "error": "Request Timeout",
  "note": "It seems your host/port is invalid, please double check the Map Remote Config"
}

**Comment by rakeshkarkare** [comment]
I am using appium server listening on 4723 and localhost while running test alongwith above proxyman configuration

**Comment by NghiaTranUIT** [comment]
Can you illustrate how your config?

From your explanation, it's: Your mobile client -> Make a request to Proxyman -> Proxyman uses Map Remote and proxies to your Python Script? 🤔 If you're using Map Remote, can you share with me your config? and the URL it's mapped too.

**Comment by rakeshkarkare** [comment]
I am using flask as a mock server to mock responses in my mobile app script and proxyman to intercept the request and map the endpoint to my flask local host. Please find below map report config. Note: I modified the endpoint url from rule to share here

Same script works If I use flask directly with proxyman without appium server running. And Manually opening mobile app. But, If I start appium server it gives the error.

<img width="842" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/06216727-987c-4310-b763-9e82ec683d9a">

**Comment by NghiaTranUIT** [comment]
Can you try with two advanced settings?
- By default, If a request is mapped with Map Remote, the `Host` header and URL will be changed -> Your client can reject the Request because the `Host` is different than the actual URL

**Comment by rakeshkarkare** [comment]
But same is working if I am not running appium server to test mobile app through automation, and invoking mobile app manually and mocking the responses with flask via proxyman

**Comment by rakeshkarkare** [comment]
I tried advanced settings but it still gives me same error

<img width="647" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/36a993e1-90a2-4bb8-82aa-0c613ba08b27">

<img width="405" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/afa8b735-3008-41b7-bab3-cfba3d15f8b8">

**Comment by NghiaTranUIT** [comment]
This error means Proxyman can't connect to a localhost:5050, it's time-out.

Can you modify the /ect/host file and add new alias? for example: `127.0.0.1 proxyman.debug`, then opening your Map Remote rule -> Change the Map To: Host = `proxyman.debug` ?

**Comment by rakeshkarkare** [comment]
Still same error

<img width="433" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/31622548/b7242f78-5a9c-4331-82fa-b1a218b241d0">

![image](https://github.com/ProxymanApp/Proxyman/assets/31622548/e623a0aa-3b17-4e85-a07c-ca3081c4983d)

**Comment by NghiaTranUIT** [comment]
Then, it's your localhost:5050 server problem because Proxyman can't correct to it, it got the timeout after 30 seconds.

**Comment by rakeshkarkare** [comment]
But same script works if I stop appium server. Is there way to increase timeout in proxyman

**Comment by rakeshkarkare** [comment]
Still failing with same error but script works and mocks the responses as intended if appium server is stopped. @NghiaTranUIT Any idea what could be the reason ?

**Comment by rakeshkarkare** [comment]
I was able to resolve this issue, by launching flask in another module in script, and using the routes in same script. 
Now, able to mock responses as expected.
Thanks for  the support @NghiaTranUIT
