### ISSUE TITLE
Proxyman 4.14.0 with macOS 14.1.1 breaks the Internet

### ISSUE THREAD

**Issue by alek-womple** [ProxymanApp/Proxyman#1845]
## Description
With macOS 14.4.1 and Proxyman 4.14.0, I cannot access any page on the Internet.

## Steps to Reproduce
Open Proxyman. Even without any rules, with `macOS Proxy Overridden` enabled all websites respond with an error such as:
```
This site can’t be reached
www.google.com unexpectedly closed the connection.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_CLOSED
```

## Current Behavior
With Proxyman open, if I turn off `macOS Proxy Overridden` then I can use the web browser. Simply toggling this on breaks the Internet. This only affects web browsers. I can still use Slack, Outlook, etc.

## Expected Behavior
I should be able to get to any web page with Proxymann open if I don't have `macOS Proxy Overriden` turned on.
When I turn on rules, a regex match should be required to affect web browsing.

## Environment
Macbook Pro (M1 Pro)
macOS 14.1.1
Proxyman 4.14.0

**Comment by alek-womple** [comment]
My Certificate was missing. I regenerated the Trusted Proxyman Certificate in the Proxyman Settings > General, and it's working again.

**Comment by NghiaTranUIT** [comment]
Thanks for letting me know 👍
