### ISSUE TITLE
Proxyman 4.14.0 crashes on macOS 11.7.10 when proxy request with "Override macOS Proxy" or click "Response - Body"

### ISSUE THREAD

**Issue by DaysJan** [ProxymanApp/Proxyman#1846]
## Description
Proxyman 4.14.0 crashes on macOS 11.7.10 when proxy request with "Override macOS Proxy" or click "Response - Body"

## Steps to Reproduce

1. Open "Override macOS Proxy"
2. when some request come from local

OR

1. click "Response - Body" (some small size json body won't cause crashing, maybe)

## Current Behavior

Crash

## Expected Behavior

Work as old version.

## Environment

- App version: Proxyman 4.14.0
- macOS version: macOS Big Sur

## Attachment
[click_resp_body_log.txt](https://github.com/ProxymanApp/Proxyman/files/13324398/click_resp_body_log.txt)
[override_proxy_log.txt](https://github.com/ProxymanApp/Proxyman/files/13324399/override_proxy_log.txt)

**Comment by NghiaTranUIT** [comment]
@DaysJan May I ask:
1. Does the app crash at launch or it crashes when we do the `Step to reproduce` 🤔 

I don't have macOS 11 to test.

**Comment by DaysJan** [comment]
> @DaysJan May I ask:
> 
> 1. Does the app crash at launch or it crashes when we do the `Step to reproduce` 🤔
> 
> I don't have macOS 11 to test.

 It crashes when we do the `Step to reproduce`.

Proxyman has launched smoothly and other features works fine.

**Comment by DaysJan** [comment]
I will be pleasure to provide more information if you need it. @NghiaTranUIT

**Comment by DaysJan** [comment]
In my situation, it seems to work on 4.16.0.

Otherwise it's wise that stay on 4.11.0.

**Comment by NghiaTranUIT** [comment]
Thanks. I'm not sure which part fix the crash on macOS 11.7.10 since I can't reproduce it : /
