### ISSUE TITLE
Add support for sorting when pressing the column headers on "Map Remote"?

### ISSUE THREAD

**Issue by yberstad** [ProxymanApp/Proxyman#1850]
## Sorting in "Map Remote" view
It would have been nice to be able to sort the list of mappings, when pressing the headers. 

## Why this feature/change is important?
I'm starting to get a lot of mappings, and it would make it easier to find what I was looking for if the list could be sorted.

Thanks in advance!

**Comment by NghiaTranUIT** [comment]
Hi. You can find it by using the Command + F to open the Filter text field.

I'm afraid I can't support the "Column Sorting" because Map Remote Tools evaluates each rule from top to bottom when a new request comes. Sorting might cause a lot of problem and it's hard to identify.
