### ISSUE TITLE
Your Website is down

### ISSUE THREAD

**Issue by markusfassbender** [ProxymanApp/Proxyman#1851]
## Description
Your website is unavailable for days: https://proxyman.io

## Steps to Reproduce

Open https://proxyman.io in a browser

1.
2.
3.
4.

## Current Behavior

Safari can't find the server.

## Expected Behavior

Show website.

## Environment

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
It's odd. I'm still able to access https://proxyman.io/

I guess you're using Proxyman, enable SSL Proxying on this domain, but haven't installed or trusted Proxyman Certificate -> Get SSL Error 🤔

**Comment by markusfassbender** [comment]
Omg it was my network firewall blocking it. Sorry!
