### ISSUE TITLE
Add form view for Edit & Repeat window

### ISSUE THREAD

**Issue by neofight** [ProxymanApp/Proxyman#186]
When using Edit & Repeat with a POST I have to change the raw data. It would be good to have a key/value form view as per the main window. In fact the ideal situation would be if both windows had the same tabs.

<img width="395" alt="CleanShot 2019-06-24 at 23 30 07@2x" src="https://user-images.githubusercontent.com/221644/60056206-099e9180-96d8-11e9-93a3-5e415bc8d14d.png">

**Comment by NghiaTranUIT** [comment]
Hey, @neofight  thank for the feedback. it's legitimate and we will take it into account in next release 👍

**Comment by NghiaTranUIT** [comment]
All done in #188 👍

**Comment by neofight** [comment]
Great, thank you, looking forward to the next release!
