### ISSUE TITLE
Delete specific cookie in scripting

### ISSUE THREAD

**Issue by Agrailag** [ProxymanApp/Proxyman#1862]
## Description

Hello, not very familiar with js, but in snippets don't find any example - how i can remove some specific cookie in Cookie header?

`    delete request.headers["Cookie"] = "JSESSIONID";
`
Something like this delete whole header.

**Comment by NghiaTranUIT** [comment]
it deletes a part key-value of your cookie. You can use JS Playground on the Internet and test it.
