### ISSUE TITLE
After the latest version update, the Chinese language in the settings has changed to English.

### ISSUE THREAD

**Issue by jiayouzl** [ProxymanApp/Proxyman#1869]
After the latest version update, the Chinese language in the settings has changed to English.

**Comment by NghiaTranUIT** [comment]
Can you change again to the Chinese language?

**Comment by jiayouzl** [comment]
> Can you change again to the Chinese language?

No, even after switching to Chinese, English still cannot be displayed.

**Comment by jiayouzl** [comment]
When will it be fixed?
