### ISSUE TITLE
Does proxyman support m3?

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1873]
## Description

<img width="635" alt="Screenshot 2023-12-11 at 12 18 58 PM" src="https://github.com/ProxymanApp/Proxyman/assets/31751141/436ea157-5c2e-4b64-be7a-83a015809c10">

😂 

Saw m3 was missing and just thought it was funny. Cheers @NghiaTranUIT

**Comment by NghiaTranUIT** [comment]
Ah yes, it should support all Apple Chip 👍 I'm going to update it now 😄
