### ISSUE TITLE
Response Body as JSON shows as empty

### ISSUE THREAD

**Issue by shawnkc** [ProxymanApp/Proxyman#1874]
## Description
After updating to latest version: 4.15.0, the response body as JSON shows as empty pane now. Switching to Hex or Treeview mode has the proper data.

## Steps to Reproduce
All of my rest endpoints have the same behavior.

## Current Behavior
Doesn't show JSON data

## Expected Behavior
Show JSON data

## Environment

- App version: Proxyman 4.15.0
- macOS version: macOS Sonoma 14.1.2

**Comment by NghiaTranUIT** [comment]
@shawnkc does it happen with every JSON Body for all requests? Or just appear on your certain request/response 🤔 

If you don't mind, can you share with me your log (Right Click -> Export -> ProxymanLog) and share it with me at support@proxyman.io ?

You can censor your sensitive data (Rename to zip -> Unzip -> censor some data). I'd like to investigate it.

**Comment by shawnkc** [comment]
Shoot, I can't reproduce it anymore. It was with every JSON body for all requests, yes. Sorry.

**Comment by NghiaTranUIT** [comment]
So, just close and reopen the app and it works fine again 🤔

Look like in some circumstances, Proxyman could not the Body Preview (powered by Monaco Editor). I will keep an eye on it 👍

**Comment by ZhangQixiangChina** [comment]
It also happen to me
