### ISSUE TITLE
Out-out ""Share anonymous analytics data"" but data are still sent

### ISSUE THREAD

**Issue by van-tienhoang** [ProxymanApp/Proxyman#189]
As you can see on the image, I opt-out the option to send anonymous data to Proxyman, however, whenever the application starts, it connects to the proxyman.io and other. See the image for clarity.
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
1.4.3
### What OS Version are you using? (Ex. mac 10.13)
Mac 10.12
### Steps to reproduce this issue
Disable the options to send data but data are still sent out.
### Screenshots (optional)
![2019-06-27 at 11 07 AM](https://user-images.githubusercontent.com/40869791/60277850-5e0a6280-98cc-11e9-81fd-cc4153f4b975.png)

**Comment by NghiaTranUIT** [comment]
<img width="675" alt="Screen Shot 2019-06-28 at 09 19 37" src="https://user-images.githubusercontent.com/5878421/60312538-dda83800-9985-11e9-87be-7c1ff28101f2.png">

Hm you're right. After opting-out, the AppCenter still sent the first log, but the other events won't sent. I will check and stop it all.

**Comment by NghiaTranUIT** [comment]
Hey @van-tienhoang, thank 100x for pointing this issue. Technically, the TrackingService isn't initialized and enable/disable service until we do some tracking actions. Thus, sometime it updates, sometime not. I was my mistake 😨

I completely fixed it. Thank you so much 👍
