### ISSUE TITLE
Unable to modify response inside Paralles Desktop, how can I achieve it?

### ISSUE THREAD

**Issue by rockmandash** [ProxymanApp/Proxyman#1890]
## Description

I have Proxyman running with a script to manipulate API responses; everything works well on my Mac; but, I need to debug my website using Windows, so I launch a parallels desktop with Windows 11 to view it. But here's the issue: the API response isn't being modified within Paralles desktop; I'm guessing the proxyman didn't take effect inside the virtual machine; I've tried every network option in the Paralles network configuration, and I'm out of luck.

Is there anybody who knows how to do it? thank you very much

**Comment by NghiaTranUIT** [comment]
you're right @rockmandash Proxyman macOS doesn't take effect on Windows 11 (via Parallels)

You should try download the Proxyman Windows and install it on your Windows 11. Try installing the certificate and use the Breakpoint.
