### ISSUE TITLE
Is it possible to use Proxyman Windows 11 with only the SetApp subscription?

### ISSUE THREAD

**Issue by rockmandash** [ProxymanApp/Proxyman#1891]
## Description

I use Proxyman with a SetApp subscription on macOS; however, am I out of luck if I wish to use the Windows version of Proxyman? Because SetApp does not have a Windows version. Is there any way to do it?

Thank you.

**Comment by NghiaTranUIT** [comment]
Sorry, Setapp doesn't support Windows.
