### ISSUE TITLE
A Restore  LIST feature for IOS

### ISSUE THREAD

**Issue by lerKingtedy** [ProxymanApp/Proxyman#1903]
I believe it would be good for iOS smartphone version to have a import option to make restoration of SSL PROXYING and other features very easy.
I tend to get burned out having to manually add them one after another from a notepad. Thanks

**Comment by NghiaTranUIT** [comment]
Thank. I will port the Export/Import Rules to the iOS app.

You can simply export your SSL Proxying Rule to the iCloud, then import it later 👍

**Comment by lerKingtedy** [comment]
Thanks. I just got saw it got implemented on iPhone. Although a bit complex but it works perfectly♥️

**Comment by NghiaTranUIT** [comment]
Awesome, glad to know it works for you 😍
