### ISSUE TITLE
DNS spoofing with custom certificate doesn't work unless connecting before

### ISSUE THREAD

**Issue by nihaals** [ProxymanApp/Proxyman#1905]
## Description

When using DNS spoofing to map a HTTPS request to another IP with a certificate that is not normally trusted, Proxyman gives "Could not resolve the host name. Double check the domain or change DNS Setting might fix it.", even if the certificate is trusted. Disabling the spoof, sending a request to the host and then enabling the spoof again works.

## Steps to Reproduce

1. Run a HTTPS server with a custom CA-signed certificate (e.g. with Caddy and using `tls internal`) for `example.com`
    - This might also work with a self-signed certificate but I haven't tested it
2. Trust the CA certificate
3. Test that the certificate is trusted by e.g. editing the hosts file and notice you can connect
4. Set up a DNS spoof for `example.com` pointing to the IP of the HTTPS server
5. Restart Proxyman
6. Attempt to send a request to `example.com`
7. Notice the error "Could not resolve the host name. Double check the domain or change DNS Setting might fix it."
8. Disable the spoof (uncheck it)
9. Notice the request works
10. Enable the spoof
11. Notice the request works and correctly uses your own HTTPS server
12. Restart Proxyman
13. Notice the issue has returned

- To generate a CA certificate you can run `openssl genrsa -out root_ca_key.pem 2048` and `openssl req -x509 -sha256 -new -nodes -key root_ca_key.pem -days 365 -out root_ca_cert.pem`
- An example Caddyfile:
```caddyfile
{
  skip_install_trust
  pki {
    ca {
      root {
        cert "/etc/caddy/root_ca_cert.pem"
        key "/etc/caddy/root_ca_key.pem"
      }
    }
  }
}

https://example.com {
  tls internal
  respond "Hello, world!"
}
```

## Current Behavior

The request fails and requires disabling, connecting and re-enabling.

## Expected Behavior

The request just works (like it does outside of Proxyman).

## Environment

- App version: Proxyman 4.16.0
- macOS version: macOS 13.6.2

**Comment by NghiaTranUIT** [comment]
@nihaals Thanks for letting me know. If you're using v4.16.0, it's the latest version.
