### ISSUE TITLE
Documented list of proxy changes

### ISSUE THREAD

**Issue by patlux** [ProxymanApp/Proxyman#1908]
## Description

Hello, is there any type of documentation what changes proxyman does, when it sets the proxy?

E.g. a list of files which are changed and so on...

I just saw that my `~/.gradle/gradle.properties` had the proxy settings although proxyman is currently not running.

I'm on macOS.

I also have a long-running issue specially with chrome which constantly reports "NETWORK_CHANGED" when opening sites. Most of the time it works, but sometimes not.

It would be really helpful.

**Comment by NghiaTranUIT** [comment]
@patlux Proxyman doesn't change your file: `~/.gradle/gradle.properties`

### Physical Android
- If you're using this approach (https://docs.proxyman.io/debug-devices/android-device), you might modify: `res/xml/network_security_config.xml` and `AndroidManifest.xml`

### Using Adb for Android Emulator
- Then, Proxyman uses `adb` command line to override/revert your emulator proxy. It doesn't change the `gradle` file.

**Comment by NghiaTranUIT** [comment]
One more thing, Proxyman automatically overrides/reverts the system proxy, but never modifies the `gradle` file.

I'm not sure if the Android Studio might observe the system proxy changes, and override it 🤔

**Comment by NghiaTranUIT** [comment]
I'm not sure if it's related to Proxyman 🤔 

Proxyman only overrides/reverts the system proxy in Wifi -> Your wifi -> Details -> Proxies Tab. I haven't encountered this issue.

**Comment by patlux** [comment]
For anyone crossing this thread and have the same issue: It's not related to proxyman. It's a chrome issue. See https://issues.chromium.org/issues/40939844

**Comment by NghiaTranUIT** [comment]
@patlux I sometimes encounter this issue too, and Proxyman doesn't open. Just quit the Safari app will fix the issue 👍
