### ISSUE TITLE
Auto break of URL and fill for fields (like we had in Charles Proxy)

### ISSUE THREAD

**Issue by nisimjoseph** [ProxymanApp/Proxyman#1918]
## Description
when adding new URLs for the proxy as source from or target to, we take a whole URL and paste it in the Host field. in Charles Proxy it was detected the it a URL and split the value for all the different fields, so we didn't need to copy paste each URL part.

do you have this feature? or can you add it?
it will save us so much time when heavy proxying thing.

## Why this feature/change is important?

save time and errors for developers and QA. just use the URL and not need to "work" to split it.

**Comment by NghiaTranUIT** [comment]
Can you share the video or screenshot? and what tool you're talking to 🤔

**Comment by nisimjoseph** [comment]
sure.
lets take the current issue URL with additional query params:
"https://github.com/ProxymanApp/Proxyman/issues/1918?key1=1&key2=2#issuecomment-1906084196".

when pasting it in the UI we currently see this:
<img width="1244" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/2305992/8d467fc9-6334-48fa-88b6-92f2728e76be">

now, in Charles when you do it and it a URL and doing Keyboard Tab or approving it, you will see this:
<img width="1244" alt="Screenshot 2024-01-23 at 16 49 34" src="https://github.com/ProxymanApp/Proxyman/assets/2305992/4798b0d9-5420-4ae3-856a-2f14284941d7">

as you see the URL auto split to the different fields so it keep us from doing mistakes.

**Comment by NghiaTranUIT** [comment]
Thanks, I understand. I'm not aware of this hidden feature from Charles Proxy. I'm going to support it now 👍

**Comment by NghiaTranUIT** [comment]
@nisimjoseph you can try this beta build: https://download.proxyman.io/beta/Proxyman_4.16.0_Support_auto_parse_the_URL_from_Map_Remote.dmg

Just paste your URL (must has prefix http, https, ws or was) into the host field, Proxyman will parse it 👍 

https://github.com/ProxymanApp/Proxyman/assets/5878421/3610c636-ca12-4065-94bc-bc64353e26ca

**Comment by nisimjoseph** [comment]
work great!
when the release?

**Comment by nisimjoseph** [comment]
Found one issue. when you set the URL and click Done, so it doesn't do the split. only when doing Tab to pass the next field.

**Comment by NghiaTranUIT** [comment]
THanks. I will fix this issue 👍 

It will be included in v4.17.0 (maybe release in 1-2 weeks)

**Comment by NghiaTranUIT** [comment]
@nisimjoseph here is the update: https://download.proxyman.io/beta/Proxyman_4.16.0_Fix_auto_pares_URL_on_Map_Remote.dmg

### Changelog
- Fix the issue when Map Remote doesn't parse the URL if we hit the Done button immediately without leaving the Host Text Field
