### ISSUE TITLE
Url path in blocked list is ignored, if domain is listed in allowed wildcard

### ISSUE THREAD

**Issue by podolinek** [ProxymanApp/Proxyman#1920]
Hi ppl,

I have in Block list url with path https://domain.com/test.html an in Allow list url *.domain.com and test.html is still in listed requests.

Allow list is working ok, filter by wildcard, but rule in Block list is ignored.

Regards,
Ondrej

**Comment by NghiaTranUIT** [comment]
It's a known issue. One request can be matched with either the Allow List or Block List.

Let me see how to fix it 👍

**Comment by NghiaTranUIT** [comment]
@podolinek it's fixed with this Beta build: https://download.proxyman.io/beta/Proxyman_4.16.0_Fix_Block_List_and_Allow_List.dmg

**Comment by podolinek** [comment]
@NghiaTranUIT It works, thank you.
