### ISSUE TITLE
proxyman-cli import does not enable SSL proxying rules

### ISSUE THREAD

**Issue by samybenatt** [ProxymanApp/Proxyman#1924]
## Description
SSL Proxying rules are correctly imported to Proxyman with proxyman-cli but not enabled.
Extract of the JSON configuration file:
```json
{
...
    "sslProxyingData": {
...
        "isEnabled": true
    }
...
}
```
isEnabled is correctly set to true.

## Steps to Reproduce

1. Add SSL Proxying rules
![image](https://github.com/ProxymanApp/Proxyman/assets/24391573/c1a8db5e-1816-41a2-94de-7d46b8588f2b)
2. Export Proxyman configuration with Proxyman CLI
`/Applications/Proxyman.app/Contents/MacOS/proxyman-cli export -o proxyman_test.json`
![image](https://github.com/ProxymanApp/Proxyman/assets/24391573/82142807-089e-4c78-9b64-f8ffa3c26090)
3. Remove and disable the SSL Proxying rules to "restore" to factory state
![20240202212522_rec_](https://github.com/ProxymanApp/Proxyman/assets/24391573/51c8284f-6a90-4b25-87a7-363d62a1c48c)
4. Close Proxyman
5. Import proxyman generated JSON configuration with proxyman-cli import
`/Applications/Proxyman.app/Contents/MacOS/proxyman-cli import -m override -i /tmp/proxyman_test.json`
![image](https://github.com/ProxymanApp/Proxyman/assets/24391573/f84bc02f-9f7a-4a3d-a93f-158717c0a707)
6. Open Proxyman and check SSL Proxying rules
![image](https://github.com/ProxymanApp/Proxyman/assets/24391573/2ccfa025-a490-4fbb-a283-d5cd7abd7f9e)

SSL Proxying rules are correctly imported but not enabled.

Tried with other tools (Allow List, Scripting, ...), isEnabled is correctly taken into account.
Seems to be specific to sslProxyingData.

## Current Behavior

SSL Proxying rules are successfully imported but without being enabled while "isEnabled" is true

## Expected Behavior

SSL Proxying rules should be imported and enabled

## Environment

- App version: Proxyman 4.16.0
- macOS version: macOS Monterey 12.6

**Comment by NghiaTranUIT** [comment]
Thanks. It's a bug. I will fix it and send you a Beta build 👍

**Comment by NghiaTranUIT** [comment]
It's fixed with this Beta build: https://download.proxyman.io/beta/Proxyman_4.16.0_Fix_ssl_proxying_import_from_proxyman-cli.dmg

**Comment by samybenatt** [comment]
@NghiaTranUIT 

> It's fixed with this Beta build: https://download.proxyman.io/beta/Proxyman_4.16.0_Fix_ssl_proxying_import_from_proxyman-cli.dmg

Confirmed working with the above build, thanks for your help! 🙏

**Comment by samybenatt** [comment]
@NghiaTranUIT it worked but somehow broke the script tool, especially when trying to use env variables
