### ISSUE TITLE
Invalid Base64 String

### ISSUE THREAD

**Issue by fardage** [ProxymanApp/Proxyman#1934]
## Description

Trying to Base64 decode the following string results in "Invalid Base64 String"
```
eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5zbm93cGxvd1wvdW5zdHJ1Y3RfZXZlbnRcL2pzb25zY2hlbWFcLzEtMC0wIiwiZGF0YSI6eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5tb2JpbGVcL2FwcGxpY2F0aW9uX2luc3RhbGxcL2pzb25zY2hlbWFcLzEtMC0wIiwiZGF0YSI6e319fQ
```
However the string seems to be fine and can be decoded via https://www.base64decode.org/

## Steps to Reproduce

1. Decode the string in the Request Body Window with right click

![image](https://github.com/ProxymanApp/Proxyman/assets/48010396/4ae9b746-7947-434f-902b-6ea29e1e1af7)

## Current Behavior

 - "Invalid Base64 String"

## Expected Behavior

- Decode String like https://www.base64decode.org/ does
- Should result in:

```
{"schema":"iglu:com.snowplowanalytics.snowplow\/unstruct_event\/jsonschema\/1-0-0","data":{"schema":"iglu:com.snowplowanalytics.mobile\/application_install\/jsonschema\/1-0-0","data":{}}}
```

## Environment

- App version: Proxyman 4.16
- macOS version: Sonoma 14.2.1

**Comment by NghiaTranUIT** [comment]
Thanks, let me investigate and fix it asap 👍

**Comment by NghiaTranUIT** [comment]
@fardage it's fixed: https://download.proxyman.io/beta/Proxyman_5.0.0_Fix_base64_from_Java.dmg

The problem is your Base64 string is encoded by a Java-implementation algo, so it doesn't have suffix padding `=`. The Beta fix it 👍

**Comment by fardage** [comment]
Great! I can confirm that it works with the beta. Thank you for fixing it so quickly!
