### ISSUE TITLE
Unable to capture logs of specific Xamarin iOS App on device or in the Simulator.

### ISSUE THREAD

**Issue by clawesome** [ProxymanApp/Proxyman#1935]
I'm debugging a Xamarin iOS app and the traffic for a specific project won't show up at all in the Proxyman traffic logs on the desktop app with the iOS Simulator nor will it show up in the mobile app on my device.  I'm capturing traffic from other Xamarin apps without issue on both the desktop and mobile app.  Is there potentially something in the app's configuration that would prevent it the traffic from showing up in the Proxyman logs?

**Comment by NghiaTranUIT** [comment]
@clawesome by default, Xamarin iOS doesn't respect the system proxy on your Simulator, so Proxyman can't capture traffic.

You need to find a solution to manually set the proxy to Proxyman in your source code. Here is what we can found: https://github.com/xamarin/xamarin-macios/issues/18635

For the IP and port, you can find it in the Status Bar.

<img width="427" alt="Screenshot 2024-02-15 at 11 39 24" src="https://github.com/ProxymanApp/Proxyman/assets/5878421/e1c048cb-fee8-4f3c-af4f-f20cc9dcf0da">
