### ISSUE TITLE
Real device connection issue

### ISSUE THREAD

**Issue by onuroktay16** [ProxymanApp/Proxyman#1936]
## Description
I can't see any logs from android and ios real device. When I change wifi settings, I cant connet wifi and I cant open proxy.man/ssl.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
@onuroktay16 can you follow this [troubleshooting page](https://docs.proxyman.io/troubleshooting/my-ios-devices-couldnt-connect-to-proxyman-via-proxy) and find a solution?

I could be your Firewall Setting, a active VPN on your iPhone, ...

**Comment by onuroktay16** [comment]
I tried them but it does not work.
