### ISSUE TITLE
Some apps cannot fetch information, what's going on?

### ISSUE THREAD

**Issue by jiayouzl** [ProxymanApp/Proxyman#1948]
iterm2，macos Own terminal，pycharm。。。。The network communication information of these applications cannot be obtained through Proxyman. What's going on?

**Comment by NghiaTranUIT** [comment]
@jiayouzl  It's not a bug from Proxyman, it's how macOS/Python works. Traffic from these apps doesn't respect the system HTTP Proxy, so Proxyman can't capture it automatically.

To capture your Python traffic, you should open the pre-configured Terminal from the Automatic Setup: https://docs.proxyman.io/automatic-setup/automatic-setup

Works with Python, cURL, Ruby, NodeJS too 👍

**Comment by jiayouzl** [comment]
> @jiayouzl It's not a bug from Proxyman, it's how macOS/Python works. Traffic from these apps doesn't respect the system HTTP Proxy, so Proxyman can't capture it automatically.
> 
> To capture your Python traffic, you should open the pre-configured Terminal from the Automatic Setup: https://docs.proxyman.io/automatic-setup/automatic-setup
> 
> Works with Python, cURL, Ruby, NodeJS too 👍

Thank you very much, the terminal works according to your method, but how can I capture the communication content of these apps like PyCharm? Thank you.

**Comment by NghiaTranUIT** [comment]
Like as said, let's open the Pre-configured Terminal in the Auto Setup from Proxyman -> Then start your PyCharm app on this Terminal -> Proxyman will capture all HTTP/HTTPS from your app.

**Comment by jiayouzl** [comment]
> Like I said, let's open the Pre-configured Terminal in the Auto Setup from Proxyman -> Then start your PyCharm app on this Terminal -> Proxyman will capture all HTTP/HTTPS from your app.

So that's how it is, thank you for letting me know.
