### ISSUE TITLE
Trouble triggering scripts from iOS simulator

### ISSUE THREAD

**Issue by ben-codes-five** [ProxymanApp/Proxyman#1950]
## Description
I am doing iOS development and monitoring network traffic using Proxyman.
I can see the network calls in Proxyman, suggesting I have the certificates set up correctly, however, I am trying to modify the response for an endpoint using scripts but the scripts aren't being triggered.

For context, the endpoint is a graphql endpoint and below is my script: 

```javascript
const file = require("mockdata.json");

async function onRequest(context, url, request) {
  // console.log(request);
  console.log(url);

  // 1. Extract the queryName from the request
  var queryName = request.body.query.match(/\S+/gi)[1].split('(').shift();

  // 2. Save to sharedState
  sharedState.queryName = queryName

  // Done
  return request;
}

async function onResponse(context, url, request, response) {

  // 3. Check if it's the request we need to map
  if (sharedState.queryName == "myQuery") {

    // 4. Import the local file by Action Button -> Import
    // Get the local JSON file and set it as a body (like Map Local)
    response.headers["Content-Type"] = "application/json";
    response.body = file;
  }

  // Done
  return response;
}
```

I can confirm the script works because I am able to trigger the script by rerunning the request within Proxyman, however, I am unable to trigger the script from sending a request from my iOS app.

Any idea what the issue is? Smells like either an internal bug or a configuration issue.

## Environment

- App version: Proxyman 5.0.0
- macOS version: macOS Sonoma 14.3.1
- Xcode version: Xcode 15.1
- Simulator version: Simulator 15.1

**Comment by NghiaTranUIT** [comment]
> however, I am trying to modify the response for an endpoint using scripts but the scripts aren't being triggered.

If you don't see any log, it means the Script URL doesn't match your URL.

Can you show me the script URL Rule you're using?

----------
Your script is an old way to match with a GraphQL Query Name. If you're using v5.0.0, there is an easier way:
1. Call your GraphQL on iPhone -> Make sure you can see the traffic on Proxyman macOS
2. Right Click on this request -> Tools -> Scripting
3. ✅ Proxyman automatically creates a matched rule with a given GraphQL QueryName.
4. Use your new script

```js
const file = require("mockdata.json");

async function onResponse(context, url, request, response) {

response.headers["Content-Type"] = "application/json";
    response.body = file;

  // Done
  return response;
}
```

![Screenshot 2024-02-28 at 08 29 53](https://github.com/ProxymanApp/Proxyman/assets/5878421/3cc97d2d-d5ee-40b5-9178-4130dbd937a0)

**Comment by NghiaTranUIT** [comment]
Or you can map to a local file directly:

```
async function onResponse(context, url, request, response) {
  // console.log(response);
  response.headers["Content-Type"] = "application/json";
  response.bodyFilePath = "~/Desktop/my_response.json"
  
  // Done
  return response;
}
```

**Comment by ben-codes-five** [comment]
I was able to get it to work! However, not by importing my json file. I had to map the local file directly.
Thanks for your help!

**Comment by NghiaTranUIT** [comment]
@ben-codes-five Glad to know you made it. The Map Local Tool works fine too 👍

**Comment by ben-codes-five** [comment]
Reopening because a colleague of mine is having the same issue but can't seem to figure out what the issue is.

**Comment by jmittelstaedt12** [comment]
Hi 👋 , similar to @ben-codes-five , I have an issue where my script does not get executed for requests made from my simulator, only when I repeat the request in the proxyman window does the script get executed. One thing Ben and I noticed is that for my Raw request, the URL is different when I use repeat. See the screenshots for the discrepancy. The screenshot for the request made from iOS simulator is the `https://staging-app.thumbtack.com/graphql` one

![image](https://github.com/ProxymanApp/Proxyman/assets/20647665/ba1a8f42-4a98-4536-938c-5338aa2f3d90)
![image](https://github.com/ProxymanApp/Proxyman/assets/20647665/07b56ab2-beae-4544-a7bf-ca55ce88b9ef)


Environment
App version: Proxyman 5.0.0
macOS version: macOS Sonoma 14.3.1
Xcode version: Xcode 15.2
Simulator version: iPhone 15 (iOS 17.2)

**Comment by jmittelstaedt12** [comment]
Similar to @ben-codes-five I'm unable to execute my script through requests made from simulator. Only on repeat requests through the proxyman window can I get the script to run. Heres my match:

![image](https://github.com/ProxymanApp/Proxyman/assets/20647665/f68a7c4f-b093-4f1a-ac8c-352c926f4f09)

**Comment by NghiaTranUIT** [comment]
@jmittelstaedt12 can you follow this steps:
1. Make a HTTP Request first on your iOS Simulator -> Verify you can see the request on Proxyman first 
2. Right Click on this request -> Tools -> Scripting (No need to change any thing, it already works)
3. Re-sent your request again -> Check if you can see the `console.log()` from the Scripting ?

**Comment by NghiaTranUIT** [comment]
Here is the video: It works fine.

https://github.com/ProxymanApp/Proxyman/assets/5878421/93e79918-4189-4815-b846-56797721f4b8

**Comment by jmittelstaedt12** [comment]
@NghiaTranUIT resolved the issue. My problem seemed to be that I had my VPN on, as its now working with it turned off
