### ISSUE TITLE
No Internet connection on the network that I installed Proxyman

### ISSUE THREAD

**Issue by decidev22** [ProxymanApp/Proxyman#1951]
## Description
No network connection as written in the title (WiFi) that I have initially installed the Proxyman on.
I can connect to the other network and confirm that Proxyman and other applications working.
However, the network will no longer work, just for me, and fine for everyone else in the building.
I concluded something went wrong in the installation of the proxy man on my machine.

My Proxy setting has everything turned off, I tried both on for HTTP and HTTPS proxy and off as well to the port 9090, but no luck.

I am having bit of hard time doing the work without being able to use my secure network.

I tried uninstalling the Proxyman but that did not resolve the issue, surprisingly.

## Steps to Reproduce

1. Install Proxyman and Helper on MacOS 14.1.1
2. Soon lost WiFi (nothing done in between)
3. Cannot perform any activity on the Internet. 

## Current Behavior

Status on Proxyman states 'Internal Error', but gives no further details.
only on the network that I have initially installed Proxyman is not working.

## Expected Behavior

Internet working.

## Environment

- App version: Proxyman 5.0.0
- macOS version: Sonoma 14.1.1

**Comment by NghiaTranUIT** [comment]
Hi,

Can you double check if the Helper Tools is installed? (In Settings -> Advanced tab -> Helper tool)

And do you use any VPN at the same time? If yes, just turn off the VPN might fix it

**Comment by decidev22** [comment]
Hello @NghiaTranUIT Thank you for responding!

Helper is installed and VPN is turned off as in corporate environemtn for mine does not require one.
Is there anything else I can try?

**Comment by NghiaTranUIT** [comment]
@decidev22 can you do Factory Reset in the Help menu -> Advanced -> Factory Reset?

and when Proxyman is running, can you open System Setting -> WiFi -> Your Wifi -> Details -> Proxies Tab -> Check if the HTTP and HTTPS Proxy is checked ✅  ?

It should be overridden automatically with the Helper Tool when the app launches and Proxyman can capture traffic

**Comment by decidev22** [comment]
Hello @NghiaTranUIT, interestingly I think it came back after reinstalling the helper and manually turning on the HTTP and HTTPS proxy again. Perhaps last time it didn't sync as it should have. 🤔 
It seems to be resolved now! Thank you for your quick response!

**Comment by NghiaTranUIT** [comment]
@AnnaKhamylova can you do Factory Reset in the Help menu -> Advance ?

May I ask what Proxyman and macOS version you're using?

**Comment by AnnaKhamylova** [comment]
@NghiaTranUIT of course, macOS Sonoma 14.76 Proxyman 5.12.2
