### ISSUE TITLE
Changing URL in scripting

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1955]
## Description
When making a script, and in `onRequest` doing `request.url = "https://mynew.url/"`, the URL of the request doesn't change. Is it normal ?

## Current Behavior
Url not changed

## Expected Behavior
Url changed to the new one

## Environment

- App version: Proxyman Version 5.0.0
- macOS version: 14.2.1

**Comment by NghiaTranUIT** [comment]
It's because `request.url` is read-only. 

To change the URL components, please use the code:
```js
function onRequest(context, url, request) {
    request.scheme = "http";
    request.host = "proxyman.dev";
    request.port = 9090;
    request.path = "v1/data/user";
    return request;
}
```

Snippet Code: https://docs.proxyman.io/scripting/snippet-code#change-request-destination-scheme-host-port-path
