### ISSUE TITLE
No longer able to see image requests in proxyman

### ISSUE THREAD

**Issue by MichaelGofron** [ProxymanApp/Proxyman#1957]
## Description
Previously when I'd make image requests in my app I'd see them display along with other API calls in the `All` tab. Now I'm no longer seeing them when I upgraded to the latest proxyman version (5.0)

Has something changed? Is there a way to see them? I tried filtering by media but it doesn't show. I also tried in two separate apps to make an image request and none registered in either app.

## Steps to Reproduce

1. Launch app 
2. Make image request in app
3. See in the main tab with id, url, etc. that there is no image request

## Current Behavior

No image request captured by proxyman

## Expected Behavior

Expected image requests to be captured as in old version of proxyman.

## Environment

- App version: Proxyman 5.0.0
- macOS version: Sonoma 14.3.1

**Comment by NghiaTranUIT** [comment]
@MichaelGofron it seems your image domain isn't enabled to intercept its HTTPS? So, Proxyman just proxies the data without decrypting it, so Proxyman doesn't know if it's an image or not => The filter doesn't show it too

You should Command+F to find your image domain -> Right Click -> Enable SSL Proxying -> Re-try your Image URL again -> It will work 👍

**Comment by MichaelGofron** [comment]
Hm, I'm not sure what you mean by image domain isn't enabled to intercept its HTTPS. 
Originally on older versions of proxyman I'd filter for `pictures` which was the domain for images I'd be requesting but now it shows no images are loading as seen in the attached image. 

<img width="739" alt="Screenshot 2024-03-06 at 08 12 30" src="https://github.com/ProxymanApp/Proxyman/assets/4534318/70c5956a-19fb-4b16-8a8c-809540f39f83">

I'm not sure where to follow these steps: `Command+F to find your image domain -> Right Click -> Enable SSL Proxying -> Re-try your Image URL again`. Am I CMD+F'ing in the main window for proxyman? Where would I right click / enable ssl proxying? 


From the help menu it looks like I've enabled SSL proxying: 
<img width="671" alt="Screenshot 2024-03-06 at 08 15 54" src="https://github.com/ProxymanApp/Proxyman/assets/4534318/399686fc-7cd9-4f5f-9f3d-d048954b335b">

**Comment by NghiaTranUIT** [comment]
here is the step:
1. On the main table view
2. Command + F to show the Filter
3. Seach your image domain 
4. Right click on this domain -> Enable SSL Proxying
5. Re-sent your request -> At this point, you can see the Image Body and the Image Filter will work 

-------------
Video: My image domain is: `ph-files.imgix.net`

https://github.com/ProxymanApp/Proxyman/assets/5878421/8129e297-8de2-471e-9274-16f5b1b779bb

**Comment by MichaelGofron** [comment]
I'm seeing them now! I'm not sure what actually changed. I think the only think I had done was to toggle the SSL proxying option from the menu in the image I'd listed above and restarted proxyman. 

Thanks for the support @NghiaTranUIT !

**Comment by MichaelGofron** [comment]
Another possibility might be that I was using an endpoint on my client app that was attached to a devserver. 
I had switched this to production server which might have caused it to display the images I wasn't seeing before.

**Comment by NghiaTranUIT** [comment]
Yes, or your Image is cached on your client, so the actual URL never hits the server and Proxyman too.

If it's a case, just use the Tools -> No caching. It forces your client will always get new image 👍
