### ISSUE TITLE
SSL error and a secure connection to the server cannot be made when AnyConnect VPN open

### ISSUE THREAD

**Issue by ahmetengingokce** [ProxymanApp/Proxyman#1960]
## Description

I installed Proxyman and installed Helper Tool. 
Then I realized I cannot access our company test servers with AnyConnect VPN.
I remove all config files and reinstall AnyConnect again but no.
I checked old issues and did what they say but it didn't work for me.
Now I uninstall Helper Tool and Proxyman but the issue is still with me :(
Please help me.
## Steps to Reproduce

1.
2.
3.
4.

## Current Behavior

<img width="749" alt="Screenshot 2024-03-07 at 11 37 46" src="https://github.com/ProxymanApp/Proxyman/assets/40921342/3c099463-fd66-4da2-a470-877fe016f2dc">
<img width="458" alt="Screenshot 2024-03-07 at 11 38 13" src="https://github.com/ProxymanApp/Proxyman/assets/40921342/7ffa3b3f-9df9-4d47-8f2a-033e0bb2c866">

## Environment

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
@ahmetengingokce it's because AnyConnect might conflict with Proxyman/Charles Proxy. 

> Now I uninstall Helper Tool and Proxyman but the issue is still with me :(

If you already these, I guess the problem is from AnyConnect, not Proxyman anymore.

**Comment by ahmetengingokce** [comment]
> @ahmetengingokce it's because AnyConnect might conflict with Proxyman/Charles Proxy.
> 
> > Now I uninstall Helper Tool and Proxyman but the issue is still with me :(
> 
> If you've already removed these, I guess the problem is from AnyConnect, not Proxyman anymore.

But I am working with that VPN for so so so many years. And after I installed Proxyman it happened.
Even I uninstall Proxyman there should be a override proxy in somewhere else or not? :(

**Comment by ahmetengingokce** [comment]
> > @ahmetengingokce it's because AnyConnect might conflict with Proxyman/Charles Proxy.
> > > Now I uninstall Helper Tool and Proxyman but the issue is still with me :(
> > 
> > 
> > If you've already removed these, I guess the problem is from AnyConnect, not Proxyman anymore.
> 
> But I am working with that VPN for so so so many years. And after I installed Proxyman it happened. Even I uninstall Proxyman there should be a override proxy in somewhere else or not? :(

For example after I uninstall Proxyman I found some hidden files in my user path.

**Comment by NghiaTranUIT** [comment]
Sorry, but It's not related. May be just try to restart your Mac or quit the VPN and launch again

**Comment by ahmetengingokce** [comment]
> Sorry, but It's not related. May be just try to restart your Mac or quit the VPN and launch again

is this Bill Gates speaking? :)
If I didn't uninstall Proxyman, what should you guys suggest me for that issue?
Let me guess, nothing
