### ISSUE TITLE
How to capture packets for macOS applications developed in Java? I found that the normal methods cannot capture applications developed in Java.

### ISSUE THREAD

**Issue by jiayouzl** [ProxymanApp/Proxyman#1975]
How to capture packets for macOS applications developed in Java? I found that the normal methods cannot capture applications developed in Java.

For example:pycharm,phpstorm

**Comment by NghiaTranUIT** [comment]
@jiayouzl there is no ultimate solution. It depends on if your Java apps have HTTP Proxy in their setting.

By default, all Java apps don't respect the system proxy, Proxyman can't capture it unless we configure it.

Let's open your Java app -> Setting -> Find any HTTP Proxy Setting -> Point to Proxyman at localhost, port 9090
