### ISSUE TITLE
Proxyman raw response doesn't seem to show new line character?

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1977]
I'm hitting an issue where new line chars are important but i can't seem to tell if the response body is empty or if the response body has a new line character.

**Comment by NghiaTranUIT** [comment]
You can show the Invisibles (New line and whitespace) in the Setting -> Appearance 👍 

![Screenshot 2024-03-21 at 8 16 33 AM](https://github.com/ProxymanApp/Proxyman/assets/5878421/767faaf0-4c05-47cb-aace-48877ec36ca4)

**Comment by ColtonIdle** [comment]
Amazing
