### ISSUE TITLE
External Proxy Setting

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#199]
## 🐶 Brief
Few users request that Proxyman should support External Proxy Setting like Charles does, since some companies require all traffic must go through their Proxy Server.

We should take it into account soon.

## 👑 Criteria
- [ ] External Proxy Config 
- [ ] UI to config those settings (http and https) and username/password if need
- [ ] By-pass list

**Comment by NghiaTranUIT** [comment]
All done @vrutin and @zeropointer11. I will officially release this weekend 🎉 

## 🤯 Changelogs 
- [x] Support External Proxying in Proxyman Core
- [x] Make a Proxy connect to external proxy instead of connecting to destination server
- [x] Support Proxy-Authentication 
- [x]  Store external proxy Setting locally (encrypted username/password of authentication)
- [x] External Proxy Setting UI
- [x] Update Response panel to present the invalid Proxy Server if need
- [x] Add External Proxy Btn in bottom bar

<img width="660" alt="Screen Shot 2019-07-18 at 19 23 40" src="https://user-images.githubusercontent.com/5878421/61458147-083d4d80-a994-11e9-9060-96fe6d77866c.png">

**Comment by NghiaTranUIT** [comment]
Hey @Vrutin and @Zeropointer11. This feature has been rolled out in the last Proxyman 1.4.6: https://github.com/ProxymanApp/Proxyman/releases/tag/1.4.6

Thank you in advance 🎉

**Comment by rickyking** [comment]
It seems super good. However how do I set up the domain?

**Comment by NghiaTranUIT** [comment]
Unfortunately Proxyman doesn’t support External Proxy for particular domains. If we setup, all traffic will go through the external proxy server, which is useful for companies has central proxy sever.

But why is the reason behind the external proxy for domain? Why not all traffic?

**Comment by rickyking** [comment]
Hi,

Thanks for your anwser. I might wrongly express the question. Actually it's for input corporate domain to put to log into proxy. I don't see the field domain. I put it as domain\username.

I am not sure it's working. I previously used Charles Proxy, while it has problem of certificat in Catalina, I wanted to try proxyman.

My usecase is not for testing. I used it as proxy manager in mac os as company only support windows. (majorly certificats issues)

**Comment by NghiaTranUIT** [comment]
Hey, if we put a domain/username on the External Proxy, it won't work unfortunately.

If you've encountered the certificate issue on Catalina, let check Proxyman since Proxyman would generate a proper certificate, which meet new Apple requirements (https://support.apple.com/en-us/HT210176) 👍
