### ISSUE TITLE
Snippet Code encrypt/decrypt aes-128-cbc and aes-256-cbc

### ISSUE THREAD

**Issue by Amiflon** [ProxymanApp/Proxyman#2017]
## Description

CryptoJS.js does not support aes-128-cbc and aes-256-cbc. It is necessary to add the ability to encrypt/decrypt aes-128-cbc and aes-256-cbc. Example working code for aes-128-cbc that works for me (iv and key as strings):

```
const crypto = require('crypto'); // Node.js

function encrypt(key, iv, data) {
    const cipher = crypto.createCipheriv('aes-128-cbc', Buffer.from(key), Buffer.from(iv));
    let encrypted = cipher.update(data, 'utf-8', 'base64');
    encrypted += cipher.final('base64');
    return encrypted;
}

function decrypt(key, iv, data) {
    const decipher = crypto.createDecipheriv('aes-128-cbc', Buffer.from(key), Buffer.from(iv));
    let decrypted = decipher.update(data, 'base64', 'utf-8');
    decrypted += decipher.final('utf-8');
    return decrypted;
}
```

Proxyman for Windows.

**Comment by NghiaTranUIT** [comment]
Crypto.js supports `aes-128-cbc and aes-256-cbc`

Code: https://docs.proxyman.io/scripting/snippet-code#aes-encryption-decryption

Ref: https://cryptojs.gitbook.io/docs#the-cipher-algorithms
