### ISSUE TITLE
为什么不公开源代码？

### ISSUE THREAD

**Issue by changsen-dev** [ProxymanApp/Proxyman#2024]
为什么不公开源代码？

**Comment by wangzhizhou** [comment]
> 为什么不公开源代码？
你为什么不把自己的收入捐出来

**Comment by wangzhizhou** [comment]
> 为什么不公开源代码？

你是怎么问出这种问题的，经过大脑了吗

**Comment by wangzhizhou** [comment]
> 为什么不公开源代码？

![image](https://github.com/ProxymanApp/Proxyman/assets/8174538/03a87545-6ea3-4e61-aa31-bb96b6ec1645)
