### ISSUE TITLE
Add "external proxy" option to quick tool panel

### ISSUE THREAD

**Issue by chernodub** [ProxymanApp/Proxyman#2040]
## Description

Currently, it seems to only be possible to enable the "use external proxy" option via the following steps:

1. Open proxyman window
2. Tools -> Proxy Settings -> Use External Proxy

This takes quite some time for scenarios where external proxy needs to be toggled from time to time.  It would be great to add the button to the quick menu too. Thanks!

![Screenshot 2024-05-29 at 07 48 37](https://github.com/ProxymanApp/Proxyman/assets/37013688/a1a1098e-0dc2-4eb7-a2ab-5a0c31d6fee4)

## Why this feature/change is important?

The change minor and not necessary, but more of a nice-to-have feature.

**Comment by NghiaTranUIT** [comment]
thanks, it made sense to have this. I'm on it 👍

**Comment by NghiaTranUIT** [comment]
@chernodub you can use this beta build: https://download.proxyman.io/beta/Proxyman_5.3.0_Add_External_Proxy_to_system_menu_bar.dmg

<img width="490" alt="Screenshot 2024-05-29 at 8 05 58 PM" src="https://github.com/ProxymanApp/Proxyman/assets/5878421/b835c0e3-4a3b-4ea5-9ecd-a72c2b79643b">

**Comment by chernodub** [comment]
Great to hear, thank you so much for your work @NghiaTranUIT!

**Comment by chernodub** [comment]
I see it's already in the stable version! You ship crazy fast @NghiaTranUIT, thanks! 

![Screenshot 2024-05-31 at 07 57 59](https://github.com/ProxymanApp/Proxyman/assets/37013688/32837441-3410-43f7-b4ec-83c816bf745c)

Everything works just as expected, so I'm closing the issue :)
