### ISSUE TITLE
[New feature] Blacklisting of URLs

### ISSUE THREAD

**Issue by wrednamalpa** [ProxymanApp/Proxyman#205]
Proxyman 1.4.4
Mac 10.14.5

It should be possible to create a list of blaclist domains / URLs (something like in Charles proxy). This feature is very useful, once you use the Lighthouse in DevTools in Chrome to track a script, which slows down the whole webpage.

**Comment by NghiaTranUIT** [comment]
Good news is that I'm going to implement this feature since I could heavily many reusable components from Local Map 👍 🥇

**Comment by NghiaTranUIT** [comment]
For anyone concern, here is the BETA build for the Blacklist 🍺 (https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.0_blacklist.dmg)

We can access the Blacklist from Tool Menu -> Blacklist and set the rule (wildcard supported) 👍 

I'm going to officially release today.

**Comment by NghiaTranUIT** [comment]
Hey @wrednamalpa, let check the [Proxyman 1.6.1](https://github.com/ProxymanApp/Proxyman/releases/tag/1.6.1), which includes the Blacklist. You can access it by Tool menu or from Option+Command+X key 🎉 

You can update directly from the app or download in the Release page. Thank you a lot 💯

**Comment by wrednamalpa** [comment]
Hi!

This is a great news. Can I back to you with the feedback on Monday?

Pozdrawiam
Dymitr Mażar

**Comment by NghiaTranUIT** [comment]
Yes, absolutely. We're welcome all feedback @wrednamalpa 👍
