### ISSUE TITLE
Crash in Proxyman HTTP/2.0 on close mobile application

### ISSUE THREAD

**Issue by holdbetter** [ProxymanApp/Proxyman#2068]
## Description

Hi. I am using Proxyman with HTTP/2.0 feature. I have last 5.5.0 version.
It constantly crashes if you proxying your mobile app.

## Steps to Reproduce

1. Connect Android app to Proxyman
2. Open application, start proxy data
3. Close application through Force Stop or using Recent Apps

## Current Behavior

Crash

## Expected Behavior

No crash

## Environment

Check crashlog
[crashlog.txt](https://github.com/user-attachments/files/16031909/crashlog.txt)

**Comment by achirkof** [comment]
Same here but on iOS. Proxyman crashes when restart the app on **iOS simulator**. 
Proxyman version 5.6.0
iOS 17.4
[crashlog.txt](https://github.com/user-attachments/files/16141967/crashlog.txt)

**Comment by NghiaTranUIT** [comment]
Thanks @achirkof for the crashlog.
```
-[NSMutableAttributedString addAttributes:range:] + 138
```
This bug is fixed on the 5.6.1, let me update the HTTP/2 build

**Comment by achirkof** [comment]
Thanks @NghiaTranUIT. It's fixed now.

**Comment by holdbetter** [comment]
@achirkof Where did you get 5.6.1 with HTTP/2? If you just updated it it will not support HTTP/2 via "Check for updates"

**Comment by NghiaTranUIT** [comment]
Sorry, I'm still working on the HTTP/2 with update 5.6.1

Will available this weekend

**Comment by NghiaTranUIT** [comment]
@holdbetter @achirkof here is the new Beta HTTP/2: https://github.com/ProxymanApp/Proxyman/issues/416#issuecomment-2232371701

**Comment by holdbetter** [comment]
Thank you, I will check next week and close if everything ok!

**Comment by holdbetter** [comment]
@NghiaTranUIT Sorry, it's still not fixed
[crashlog.txt](https://github.com/user-attachments/files/16330210/crashlog.txt)

**Comment by NghiaTranUIT** [comment]
Thanks for the crash log @holdbetter 

Let's try this new build: https://download.proxyman.io/beta/Proxyman_5.6.1_Support_HTTP_2_v17.dmg

- Fixed some crashes from your crash log

**Comment by holdbetter** [comment]
I checked. Looks stable. Thank you!
