### ISSUE TITLE
Support tree view for requests

### ISSUE THREAD

**Issue by Schaefers** [ProxymanApp/Proxyman#207]
Allow the user to show requests grouped by their url components. 

e.g. 
* https://url.com/api/users/all
* https://url.com/api/users/active
* https://url.com/api/customers/all

shows up as 

* https://url.com/api
  * users
         -> all
         -> active
   * customers
      -> all

**Comment by NghiaTranUIT** [comment]
Hey, there are many user request this killer feature from Charles too. We're gonna support in Proxyman 1.4.6. Stay tuned! 💎

**Comment by NghiaTranUIT** [comment]
Hey, just friendly remind that this feature has been implemented 🎉 at #208 

We're running some tests since it affects entire our app. 

Stay tuned for the next official release @Schaefers 👍 😄

**Comment by NghiaTranUIT** [comment]
Some screenshots:

![Screen_Shot_2019-07-10_at_22_08_44](https://user-images.githubusercontent.com/5878421/60981728-0e627700-a361-11e9-937d-f8c7ea228b0c.jpg)

**Comment by NghiaTranUIT** [comment]
@Schaefers, the [Proxyman 1.4.5](https://github.com/ProxymanApp/Proxyman/releases/tag/1.4.5) has been out. It includes the Tree View by default. Let give it a try 👍

**Comment by Schaefers** [comment]
Looks great, thanks!
