### ISSUE TITLE
SSL Handshake Failed for Requests to `ppq.apple.com`

### ISSUE THREAD

**Issue by jasonquache** [ProxymanApp/Proxyman#2080]
## Description

I am getting SSL Handshake Failed for all requests to `https://ppq.apple.com`. This is problematic because I cannot install apps onto my iPhone/iPad devices from Xcode whilst Proxyman is running. 

I have checked my certificate setup and everything looks fine, other requests go through fine (e.g. `https://google.com`) and I can enable SSL proxying on other domains with no issue. I have enabled SSL proxying for `https://ppq.apple.com` too. 

I don't think it's an issue with SSL pinning because the same requests go through fine when using Charles Proxy. 

![image](https://github.com/ProxymanApp/Proxyman/assets/59347744/16b7587b-881f-4850-9aae-49fa1ad7da25)

## Steps to Reproduce

1. Enable proxy on iPhone or iPad device
2. Verify that requests are showing up in Proxyman
3. Install an app onto the iPhone/iPad from Xcode
4. Observe that in Proxyman, requests to `https://ppq.apple.com` fail - in the response box, it says "SSL Handshake Failed"

## Current Behavior
Requests to `https://ppq.apple.com` fail - in the response box, it says "SSL Handshake Failed"

## Expected Behavior
Requests to `https://ppq.apple.com` should succeed.

## Environment

- App version: Proxyman Version 5.6.1 (50601)
- macOS version: Version 14.5 (Build 23F79)

**Comment by NghiaTranUIT** [comment]
It's expected results because all Apple traffic is protected and it doesn't accept any self signed certificate.

Therefore, you get SSL errors.

To fix it, please remove the apple traffic from the Tool menu -> SSL Proxying tool. So it proxies the data without decrypting the HTTPS data

**Comment by NghiaTranUIT** [comment]
I don't think Charles Proxy can decrypt this Apple traffic. I might work if you don't intercept it
