### ISSUE TITLE
Android Emulator Automatic Setup script installs wrong CA certificate when custom certificate specified

### ISSUE THREAD

**Issue by TomBell-Trove** [ProxymanApp/Proxyman#2083]
## Description
When a custom certificate has been set up in Proxyman, the Android Emulator automatic script does not install it; instead, it appears to install the original bundled/default certificate.

## Steps to Reproduce

1. Set up a custom certificate in proxyman settings
![image](https://github.com/user-attachments/assets/91cf233f-edc4-41bf-8298-916c3e6fb2a8)

2. Go through the emulator set up guide and use the automatic script
![image](https://github.com/user-attachments/assets/85f4368c-aba4-4729-9c71-5421145935e0)

3. SSL calls will fail in emulator as using wrong certificate

## Current Behavior

Installed CA certificate is the default proxyman cert.
![Screenshot_1720994242](https://github.com/user-attachments/assets/cae3a460-175d-407c-8d56-384a4d3dec1f)

Here's a screenshot when the certificate is installed manually (via navigating to proxy.man/ssl), showing the correct cert in use.
![Screenshot_1720994447](https://github.com/user-attachments/assets/a78c0a63-59ed-4f57-a6dc-a84135ff7cbc)

## Expected Behavior

The automatic script should install the custom cert specified in proxyman settings, if one exists.

## Environment

- App version: Proxyman 5.6.1
- macOS version: macOS Sonoma 14.5 (23F79)

**Comment by TomBell-Trove** [comment]
**Workaround** 
1. Only override proxy
![image](https://github.com/user-attachments/assets/5e0aa67a-10ee-4e7d-b3d1-269b87631e5a)
2. Nav to proxy.man/ssl in emulator to download cert
3. Install cert manually

**Comment by NghiaTranUIT** [comment]
Thanks, let me fix it 👍

**Comment by NghiaTranUIT** [comment]
It's fixed: https://download.proxyman.io/beta/Proxyman_5.6.1_Fix_custom_cert_with_Emulator.dmg

![Screenshot 2024-07-15 at 9 35 32 AM](https://github.com/user-attachments/assets/06c9ff20-e4df-4cb9-8420-0dfd9863aa85)

**Comment by TomBell-Trove** [comment]
Nice turnaround :)

**Comment by TomBell-Trove** [comment]
✅ With a fresh emulator, the automatic script is installing the correct custom cert and all seems well. Thank you!

<img width="494" alt="image" src="https://github.com/user-attachments/assets/15997706-7960-4928-92d6-815a4a2f2cde">
