### ISSUE TITLE
No more copy as cURL? version 5.7.0

### ISSUE THREAD

**Issue by EdgarDegas** [ProxymanApp/Proxyman#2108]
Since when did _copy as cURL_ get replaced by _copy as HTTPie_? I didn't see this change in the change log. 

HTTPie is great but its GUI httpie/desktop won't support importing the HTTPie string. Would be great if I choose between cURL and HTTPie. What about press the option key to switch between, like many other macOS app do in their menus.

**Comment by NghiaTranUIT** [comment]
You can switch to cURL in the Setting -> Tools -> Copy as cURL (default)

Not sure but I guess you accidentally change it to HTTPie.

**Comment by NghiaTranUIT** [comment]
It's in the Tool Tab from the Setting 👍 

![Screenshot 2024-08-15 at 07 40 08](https://github.com/user-attachments/assets/94a32d34-49d2-4cb6-9901-0c866a883e54)

**Comment by EdgarDegas** [comment]
My fault. Thank you so much.
