### ISSUE TITLE
After purchasing, I was not satisfied with the functionality I experienced. I applied for a refund but no one replied, which is really bad.

### ISSUE THREAD

**Issue by liubin595338764** [ProxymanApp/Proxyman#2109]
## Description
After purchasing, I was not satisfied with the functionality I experienced. I applied for a refund but no one replied, which is really bad.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
Hi, Sorry for the reply, we've submitted for a full refund. It will proceed in the next 1-2 days.

Sorry for the inconvenience.
