### ISSUE TITLE
Missing multiple "Set-Cookie" key in Header 

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#213]
## 🐶 Brief
Some users reported that if the header has many `Set-Cookie`, Proxyman only captures the last one. It happens in Request and Response too.

Technically, Proxyman store key-value of header as a Dictionary, so it overrides if it's same key. We should fix it.

## 👑 Criteria
- [ ] The header shouldn't be override 
- [ ] Retain the order of key when sending (current behavior)

**Comment by NghiaTranUIT** [comment]
All done 🎉 

## 🤯 Changelogs 
- [x] Support duplicated header in HTTP Message: Ex: Set-Cookie
- [x] When parsing Header when composing/repeating -> Should compose those duplicated values by `,`
<img width="789" alt="Screen Shot 2019-07-13 at 15 12 36" src="https://user-images.githubusercontent.com/5878421/61169000-ac805800-a580-11e9-872d-11c9c17140ab.png">

**Comment by Demmy27** [comment]
Set-Cookie: JSESSIONID=9d4fcef1-4617-43c8-****-d4054136fafc; Domain=.****.ru; Path=/; Secure; HttpOnly
Set-Cookie: auid=60ad9ed5-36a5-43a4-****-20961c7e810f; Domain=.****.ru; Expires=Tue
Set-Cookie:  25-Aug-2020 08:13:41 GMT; Path=/
Set-Cookie: srv_id=hbs-front04-prod; expires=Mon
Set-Cookie:  26-Aug-19 16:13:41 GMT; max-age=28800; domain=.****.ru; path=/
Set-Cookie: ****_uid=aa8649c7-452d-4b25-****-b428a69bbe9e; Path=/; Domain=.****.ru
Set-Cookie: ****_sid=s%3Ac6EzwiUTdJFxa_****tRtz77fXhAY6hp.PagGl2OXcyMmSyoqpuYWCxJDtXWxaEEc23FQ0qNhtns; Domain=.****.ru; Path=/; HttpOnly; Secure

**Comment by Demmy27** [comment]
wrong word wrap - "Set-Cookie: 25-Aug-2020 08:13:41 GMT; Path=/"

**Comment by NghiaTranUIT** [comment]
Thank for the report @Demmy27. I open this ticket again and look on it today 👍

**Comment by NghiaTranUIT** [comment]
Hey @Demmy27, please download the latest version 1.5.1 Proxyman at https://github.com/ProxymanApp/Proxyman/releases/tag/1.5.1 since I couldn't reproduce it bug anymore.

**Comment by NghiaTranUIT** [comment]
Closed because we couldn't reproduce it anymore in latest version 👍
