### ISSUE TITLE
Unable to save proxy settings

### ISSUE THREAD

**Issue by sunmingyang** [ProxymanApp/Proxyman#2140]
## Description

The setting of Override macOS Proxy cannot be canceled. After modification, restarting Proxyman is still selected.

## Steps to Reproduce

1. Start Proxyman
2. Click tools on the toolbar
3. Click proxy settings
4. Reverse/uncheck Override macOS Proxy
5. Restart Proxyman
6. Toolbar -> tools -> proxy settings -> Override macOS Proxy or selected

## Current Behavior

After setting, it will return to the selected state every time you reboot.

## Expected Behavior
Save settings

## Environment

- App version: e.g. Proxyman Version 5.8.0 (50800)
- macOS: Version 12.7.6 (Build 21H1320)

**Comment by NghiaTranUIT** [comment]
It's expected behavior @sunmingyang this setting is auto turned ON at launch, unless you disable this feature in the Setting -> Auto override macOS Proxy at launch time.

![Screenshot 2024-09-24 at 14 44 27](https://github.com/user-attachments/assets/ea7ce83d-1715-4d4e-9f0a-da3938f56beb)
