### ISSUE TITLE
After update, Proxyman intermittently drops traffic and hangs when trying to quit

### ISSUE THREAD

**Issue by TomBell-Trove** [ProxymanApp/Proxyman#2163]
## Description
After updating to 5.9.0 (not sure what version I was on sorry, wasn't that old), occasionally I'll notice that requests stop going through and time out. The solution is to restart proxyman and then everything works again, but about half the time, proxyman hangs when trying to quit and I have to force quit it. 

## Steps to Reproduce

I don't know how to reproduce it, I've never had it happen "same day" though, usually happens after at least a day of running.

## Current Behavior

As description

## Expected Behavior

- Proxyman does not interfere with normal network operations/quality (unless told to)
- Proxyman can be quit without needing force-quit

## Environment

- App version: Proxyman 5.9.0
- macOS version: macOS 15.0.1 (24A348)

---

Before I try reinstalling etc, are there any logs or such that would be useful to supply?

**Comment by NghiaTranUIT** [comment]
@TomBell-Trove sorry to hear that. Maybe some data is conflicted when upgrading from a very old build.

You can open Proxyman -> Helps menu -> Advanced -> Factory Reset -> Ticked on the "Included User data". 

Let give it a try and share with me the result 👍
