### ISSUE TITLE
How to replace the file in multipart/form-data

### ISSUE THREAD

**Issue by sunmingyang** [ProxymanApp/Proxyman#2174]
Proxyman Version 5.10.0 (51000) | macOS: 版本12.7.6（版号21H1320）

I'm sorry, I'm a novice in JavaScript and I can't solve this problem, so I'm asking for help.

How can I modify the file field inside multipart/form-data? For example, if the file is currently a cat picture, and I want to change it to a dog picture, please provide the code. Thank you.

**Comment by NghiaTranUIT** [comment]
You can use the Breakpoint to modify the Request multipart/form-data.

1. Make your first multipart request
2. Right click on it on the main table -> Tools -> Breakpoint ->Create a new rule with Request checkbox is on. Disable the Response.
3. Re-sent your request again -> At this point, new Breakpoint will will appear 
4. Select the request on the new windows -> In the Request Panel -> Multipart Tab -> Click on the Edit Button on the selected part -> You can select your local file to change the part 
5. Click Execute to complete the breakpoint
6. Done.
