### ISSUE TITLE
Please support exporting network logs via proxyman-cli

### ISSUE THREAD

**Issue by ponienchen** [ProxymanApp/Proxyman#2180]
## Description
In one of my automation suites, I would like the ability to export the network logs via proxyman-cli in order to check something.   

## Why this feature/change is important?
Some of my tests are making some api calls to report user interactions with the app, and it will be helpful to be able to test the payload of those calls as part of the automation.

Please support this use case.
Thank you so very much.

**Comment by NghiaTranUIT** [comment]
@ponienchen please use this Beta build https://download.proxyman.io/beta/Proxyman_5.10.0_Support_export-log_in_the_proxyman-cli.dmg

- Export all (ProxymanSession)
```sh
/Applications/Proxyman.app/Contents/MacOS/proxyman-cli export-log -m all -o "~/desktop/all"
Export certain domains (Only Host, no scheme, no port, no paths, and no Query)
```

- Export certain domains
```sh
/Applications/Proxyman.app/Contents/MacOS/proxyman-cli export-log -m domains -o "~/desktop/twitterlog" --domains 'api.twitter.com' --domains 'www.producthunt.com
```

You can find the example command line at https://docs.proxyman.io/command-line#export-proxyman-log

**Comment by ponienchen** [comment]
Thank you so much Noah!
I will check it out!


Peter

**Comment by ponienchen** [comment]
hi, @NghiaTranUIT 
I checked out the export.

1. 
The output is a binary file.
And I was wondering how I may view the contents.
Any way I can export the the network logs in json format ?

2.
Also, is it possible to allow for specifying path ? 
Or better yet, export network logs that contain certain queries ?
Like if I have 
`https://www.google.com/somePath?name=aaa&hobby=climbing`
`https://www.google.com/somePath?hobby=swimming&name=aaa`

And by specifying query `name=aaa`. it allows me to find the above two records ?

**Comment by NghiaTranUIT** [comment]
These files can be opened by Proxyman app.

If you want to open it as a JSON: -> Rename to zip -> Unzip -> Bunch of JSON

> Also, is it possible to allow for specifying path ?

Not yet, this version only works with domain and all mode

**Comment by ponienchen** [comment]
Thank you, @NghiaTranUIT 
I could see the json files now.

The bodyData is encrypted for both request and response, and so I am not able to use this data.

Can we by default show encrypted bodyData, but add a flag for optionally showing decrypted bodyData for both request & response ?

**Comment by NghiaTranUIT** [comment]
> The bodyData is encrypted for both request and response, and so I am not able to use this data.

It's not encrypted. It's encoded as a Base64 string. You should decode it to to JSON or binary data.

**Comment by ponienchen** [comment]
Thanks for the info on the base64 encoding, @NghiaTranUIT 
I will check it out.
Have a nice long weekend.

**Comment by ponienchen** [comment]
Hi, @NghiaTranUIT 
I am able to see decode the bodyData and see the data.
Thanks for letting me know that it is encoded using base64.

**Comment by ponienchen** [comment]
I will play with this for a few days and if I see any issues, I will report it here.
Thanks again, @NghiaTranUIT

**Comment by ponienchen** [comment]
Hi, @NghiaTranUIT 

Question.
Will this ability to export network logs be available to pro version or the free version ?

**Comment by NghiaTranUIT** [comment]
It's available in both versions. I will release this update on the next release 👍

**Comment by ponienchen** [comment]
Thank you, @NghiaTranUIT

**Comment by ponienchen** [comment]
Appreciated you working on this feature!

**Comment by ponienchen** [comment]
@NghiaTranUIT 
Will there be enhancement to this feature, to allow for specifying path or domain with regex when exporting network logs ?

**Comment by NghiaTranUIT** [comment]
Yes, soon, but not this version

**Comment by ponienchen** [comment]
Hi, @NghiaTranUIT 
I will close this issue since it has been working great for me.
I will log another ticket about the enhancement to allow for specifying path or params to be matched.
