### ISSUE TITLE
High Bandwidth Consumption with Proxyman on macOS 15.0 - Network and Websites Not Loading

### ISSUE THREAD

**Issue by MilindWebEngage** [ProxymanApp/Proxyman#2188]
## Description
When I open Proxyman and start it, my entire Mac network stops working, including loading websites. When I stop Proxyman, all websites start working fine again. This issue did not occur before and started happening after I updated to the latest version of Proxyman (5.10.0) and macOS 15.0.

I’ve already removed all the SSL proxying lists, but the issue persists. I’m unable to use Proxyman due to this issue. Please provide a solution for resolving this problem.

## Steps to Reproduce

1. Open Proxyman version 5.10.0 on macOS 15.0.
2. Start Proxyman.
3. Observe that the network on the Mac stops working, including websites not loading.
4. Stop Proxyman.
5. Observe that the network and websites resume working.

## Current Behavior

When Proxyman is started, my Mac network stops functioning, and websites do not load. This is a new behavior since upgrading to Proxyman version 5.10.0 and macOS 15.0.

## Expected Behavior

The network should work normally when Proxyman is running, and websites should load without issue.

## Environment

App version: Proxyman 5.10.0
macOS version: macOS 15.0 (Build 24A335)

**Comment by NghiaTranUIT** [comment]
@MilindWebEngage can you try to Factory Reset in the Help menu -> Advanced -> Factory Reset?

I assume that you have a lot of SSL Proxying (e.g. Google Chrome) in the SSL Proxying Tool, so Proxyman tries to capture and decrypt all network data.

Do factory reset will fix it
