### ISSUE TITLE
Feature Request: Vertical layout for main window

### ISSUE THREAD

**Issue by florianbuerger** [ProxymanApp/Proxyman#220]
Hey there, 

I would love to see a vertical layout for the main window. On a small display (screenshot is from a 13" MacBook Pro) it would be easier to see the full URL and response. 

![Screen Shot 2019-07-15 at 6 17 32 PM](https://user-images.githubusercontent.com/119219/61231898-5ac90080-a72d-11e9-9ef0-bfd651048647.png)

I fully understand if that is not something you'd consider. I am happy using it as it is so it is not that big of a deal.

Thanks!

**Comment by NghiaTranUIT** [comment]
Hey, I'm not sure if it's suitable for us since it breaks our intentions. However, I will support multiple URL text field, so you can see all full URL easily 😄

**Comment by florianbuerger** [comment]
That is fine and absolutely understandable. Thanks for the fast reply! Keep up the good work.
