### ISSUE TITLE
"SSL Handshake Failed" on iOS 18 device, but works with simulator (profiles are set up)

### ISSUE THREAD

**Issue by psi-gh** [ProxymanApp/Proxyman#2203]
So, for iOS 18 simulator everything works as expected. I can look into the traffic.
But for iOS 18 device I have "SSL Handshake Failed" for the same app.
In the same time, I can intercept queries to google.com on this device and see responses -> I believe there is not problem with certs.
I rebooted device, restarted Proxyman, but it didn't help.

Can you give me some advice where I can look to resolve this issue?

**Comment by NghiaTranUIT** [comment]
> In the same time, I can intercept queries to google.com on this device and see responses -> I believe there is not problem with certs.

If you can confirm that you've already installed & trusted the Proxyman certificate on your iPhone, it's great.

> But for iOS 18 devices I have "SSL Handshake Failed" for the same app.

Do you open the app with Xcode? Can you look at what errors on your app?

Maybe your app detect that it's running on a real devices, so it enables SSL Pinning to prevent Proxyman to decrypts its HTTPS data. Check your code and see try to turn it off.

**Comment by csingh9085** [comment]
@NghiaTranUIT Thanks, it worked for me after switch ON

**Comment by psi-gh** [comment]
@NghiaTranUIT it worked and I feel ashamed 🥲 I accidentally skipped step 4.2 in iOS Setup Guide window because I didn't notice it wasn't about profile installation. 
Sorry for disturbing and thanks again!

**Comment by developerJuiceLozzoc** [comment]
shit is not working. pretty sure its working on my iOS 16 device that I use for min version testing.
