### ISSUE TITLE
protobuf mapping rules don't trigger for custom content-types

### ISSUE THREAD

**Issue by tmm1** [ProxymanApp/Proxyman#2208]
## Description

a service that uses https://buf.build may use `Content-Type: application/connect+proto`

even after adding `.desc` file and mapping rules, protobuf request/responses are not decoded

is there a way to force protobuf parsing for custom content types?

**Comment by tmm1** [comment]
here's how it looks now. i have no way to force it to use protobuf mode

<img width="535" alt="Screenshot 2024-12-07 at 3 42 02 PM" src="https://github.com/user-attachments/assets/37a64a60-ab27-4afa-b3d1-ecc1136831de">

**Comment by NghiaTranUIT** [comment]
@tmm1 Proxyman didn't support a custome Protobuf content-type atm, please use the office one: `application/protobuf`

**Comment by tmm1** [comment]
It's not possible for me to change. The connect/bufbuild SDK implements the server and client.

Can you add the content-type to protobuf whitelist?

**Comment by tmm1** [comment]
proxyman already supports `application/protobuf` and `application/x-protobuf`

please add `application/connect+proto` 🙏🙏🙏

**Comment by NghiaTranUIT** [comment]
@tmm1 can you try to add the Protobuf Tab in the Custom Previewer Tab?

From what I checked the code, it auto parse the Protobuf if the Content-Type contains a string `protobuf`, so it should work with your case. 

![Screenshot 2024-12-11 at 10 28 32 AM](https://github.com/user-attachments/assets/71357b2e-87b7-42fa-8423-ef30cdea47bd)


If it doesn't work, can you share with me your Protobuf Setting? Maybe the rule doesn't match your URL, so protobuf is not applied 

<img width="929" alt="Screenshot 2024-12-11 at 10 31 19 AM" src="https://github.com/user-attachments/assets/c72ac41d-bb2e-4cc4-b801-efb5fa2fb875">

**Comment by tmm1** [comment]
That worked, thank you for the pointer!
