### ISSUE TITLE
Edit and Repeat: Editing a call with encoded query parameters causes double-encoded parameters to be sent

### ISSUE THREAD

**Issue by carstenhag** [ProxymanApp/Proxyman#2211]
## Description
Edit and Repeat: Editing a call with encoded parameters causes double-encoded parameters to be sent

## Steps to Reproduce

1. Make a GET call to https://example.org/test?query=%5B%7B%22lat%22%3A4&exampleBoolean=false
2. Click on "Edit and Repeat" on this call, inside Proxyman
3. Change the value of "exampleBoolean" to true
4. Send the call
5. Call now contains "https://example.org/test?query=%5B%257B%2522lat%2522%253A4&parameter=true"

## Current Behavior

`%5B%7B%22lat%22%3A4` got erroneously changed to `%5B%257B%2522lat%2522%253A4`

<img width="569" alt="Screenshot 2024-12-09 at 17 00 13" src="https://github.com/user-attachments/assets/cbdf0c35-9ace-40e0-a5c2-e0f6bff1dce0">

## Expected Behavior

`%5B%7B%22lat%22%3A4` should stay as is.

It does stay as is when you click "Edit and Repeat" and don't modify any of the query parameters.

## Environment

- App version: Proxyman 5.11.0
- macOS version: 15.1 (24B83)

**Comment by NghiaTranUIT** [comment]
@carstenhag it's fixed on this Beta build: https://download.proxyman.io/beta/Proxyman_5.11.0_Fix_compose_with_query.dmg

- If you modify the URL in the Repeat & Compose View, the bug doesn't occur
- If you modify the query in the Query Tab -> It's a bug -> Fixed 👍

**Comment by carstenhag** [comment]
Amazing, it's fixed :)
