### ISSUE TITLE
Android Emulator stops work on OSX

### ISSUE THREAD

**Issue by TomasKuhn** [ProxymanApp/Proxyman#2220]
Hello,

A couple of months ago, the Android Emulator stopped working. I tried everything I could find and spent hours troubleshooting. Unfortunately, I can’t see any traffic from the device in Proxyman, neither from the browser nor from any other application. Have you recorded any issues with the Android Emulator in the past few months? Previously, it had been working perfectly.

Best regards,
Tomas

## Environment

- App version: Proxyman 5.12.2 (51202)
- macOS version: macOS Sequoia 15.1.1 (24B91)

**Comment by NghiaTranUIT** [comment]
@TomasKuhn There is no major change on Android Emulators

May I ask if you use [Automatic Script ](https://docs.proxyman.io/debug-devices/android-device/automatic-script-for-android-emulator) to override your Android Emulator?

Make sure to use Google APIs Emulator (not a Play Store version) to make it works

**Comment by NghiaTranUIT** [comment]
>  Unfortunately, I can’t see any traffic from the device in Proxyman, neither from the browser nor from any other application.

**Comment by TomasKuhn** [comment]
Hello,
I've checked that I don't have any VPN client running. I can't normally see traffic from Safari.
I also run the script successfully. See the screenshots.
![Screenshot 2024-12-23 at 20 41 00](https://github.com/user-attachments/assets/1b646d94-f272-48a5-803f-3399711addec)
![Screenshot 2024-12-23 at 20 41 04](https://github.com/user-attachments/assets/46b5d03a-9648-4ebd-bf66-66e03aa29353)
![Screenshot 2024-12-23 at 20 41 23](https://github.com/user-attachments/assets/293847ed-0a23-4767-ad0a-e8129bf92935)

**Comment by NghiaTranUIT** [comment]
> I can't normally see traffic from Safari.

It's odd. From what I know, this only happens if you have Va PN on your MacOS so that all traffic will go through the VPN, instead of Proxyman.

If you don't mind, try to do Factory Reset in the Help menu -> Advanced.

and turn off all VPN on your Mac too.

**Comment by TomasKuhn** [comment]
You are right! I discovered leftover configuration files from ProtoVPN. After deleting them and rebooting my PC, everything is functioning properly.

Thank you very much for your advice.

Best regards,
Tomas
