### ISSUE TITLE
ws connection close

### ISSUE THREAD

**Issue by akapitoha** [ProxymanApp/Proxyman#228]
### Proxyman version?
1.4.6

### macOS Version?
10.14

### Steps to reproduce 
With recent update I noticed the following behavior:
1. I have a remote device connected
2. I send login request and get response (200)
3. Right after this response app sends `init` socket event, but in logs (android) I see the following:
```
start connecting to ws
OkHttpWebSocket$connect  D  connection open
serveInternetConnection  D  ServerConnectionState.CONNECTED
send request: {%request_body%}
Subscribed for response, token = 2706261b-b54b-474d-95dd-3f3fe9cc309d
serveInternetConnection  E  ServerConnectionState.ERROR
 WrappedOkHttpWebSocket  I  close connection to web socket
OkHttpWebSocket$connect  D  on failure
             System.err  W  java.io.EOFException
```
Thus I can't login.
Everything works fine when proxy is disabled, or if to use another proxy tool.

### Expected behavior
Get ws response

**Comment by NghiaTranUIT** [comment]
Hey @akapitoha, Proxyman hasn't supported WS or WSS yet, so it causes your issues.

We're planning that Socket Previewer #182 will support in next 2 versions. The next one is remap feature 🎉 ETA could be 3 weeks.

Thank you a lot

**Comment by akapitoha** [comment]
hi @NghiaTranUIT 
but why did it work fine in previous releases of Proxyman?
I didn't mean previewing sockets events (I use just for https for now). I mean that it looks like Proxyman closes socket events (I may be wrong, please correct me) and I can't use the app which I'm testing, can't login, though it worked before 1.4.6 update

**Comment by NghiaTranUIT** [comment]
Hey, sorry to hear that this updated version break your workflow. 

As Proxyman 1.4.6 changes the way of handling HTTP socket, so it affect the WS connection too and I wasn't aware of this socket case.

Here is the hotfix for your issue. I deleted the code to disconnect the connection. https://www.dropbox.com/s/vqfiedfhu97rap8/Proxyman_1.4.6.dmg?dl=0

@akapitoha let try 🍺

**Comment by akapitoha** [comment]
hey @NghiaTranUIT 
just tried this build but still experience same issue (see the same log)
is there anything I can do to help you?

**Comment by NghiaTranUIT** [comment]
For now, please use Proxyman 1.4.5.1 (old version) temporary https://proxyman.s3.us-east-2.amazonaws.com/1451/Proxyman_1.4.5.1.dmg

I will take a look closer this tonight. Thank you for patient.

**Comment by NghiaTranUIT** [comment]
Hey @akapitoha, I've released the Proxyman 1.5.0 https://github.com/ProxymanApp/Proxyman/releases/tag/1.5.0

with the fix on WS/WSS socket too. Basically, the WS/WSS socket is still alive and handle properly. Let check it out 🥇 Thank you in advance 👍

**Comment by akapitoha** [comment]
Hey @NghiaTranUIT 
thanks a lot for the update! Everything seems to be fine now :)

**Comment by NghiaTranUIT** [comment]
That's awesome man 😍. Thank you @akapitoha
