### ISSUE TITLE
Cleanup Certificates on close?

### ISSUE THREAD

**Issue by psimoneau22** [ProxymanApp/Proxyman#231]
### Proxyman version? (Ex. Proxyman 1.4.3)
- 1.4.6

### macOS Version? (Ex. mac 10.14)
10.13.6 (High Sierra)

### Steps to reproduce 
Open proxyman.  Navigate to any url with browser.  Select Enable for All Domains in Proxyman.

Close proxyman.   Check Keychain.  Proxyman CA issued certificates for every domain accessed still exist

### Expected behavior

Keychain certificates should be left in the same state they were before the app was opened, removing all Proxyman issued certs.

I would have expected the app to clean up the system when it is done.  Its not a big deal, but I am just wondering if it is possible, and why it works the way it does.

### Screenshots (optional)
- none

**Comment by NghiaTranUIT** [comment]
Hey, that's really valid point. Thank you for pointing it out 👍 

I will take it into account in Proxyman 1.5.0. Right now, the `re-mapn response from file` is on the way.

**Comment by NghiaTranUIT** [comment]
So, I figured out how we solve this issues.

Technically, Proxyman is using `SecPKCS12Import` from `Security` framework to read the p12 files , then extracting the pubic and private keys. It's crucial for SSL Handshaking between Proxyman and the client. However, `SecPKCS12Import` import the cert to the KeyChain by default.

I researched `SecItemImport`, and the result is same without touching to the KeyChain. I will release the fix in next release 1.9.0 👍 

Thank you for pointing it out 😄 

Ref: 
- https://forums.developer.apple.com/thread/31711
- https://developer.apple.com/documentation/security/1396915-secpkcs12import

**Comment by psimoneau22** [comment]
this is great, thank you!

**Comment by NghiaTranUIT** [comment]
All done 🎉 

## 🤯 Changelogs 
- [x] Create new private keychain for each app, Proxyman or Setapp
- [x] Store the p12 
- [x] Remove when the app quits

Here is the BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.8.0_Keychain_issues.dmg

I will officially release in this weekend or next week at least 👍 😄
