### ISSUE TITLE
Proxyman Document website

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#238]
## 🐶 Brief
It's time to implement the Documentation page for Proxyman, which is the Proxyman's knowledge-based.

## 👑 Criteria
- [x] Setup account in https://www.gitbook.com https://docs.proxyman.io
- [x] List all features, debugging tools and the overview.
- [x] Should work

**Comment by shirshak55** [comment]
I think we can use markdown approach version
