### ISSUE TITLE
Multiple selection on Source List (Left Panel)

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#247]
### Description
Some users request that Proxyman should be capable of selecting multiple domain and do bulk action (delete, enable SSL Proxyman ...)

We should do it

### Acceptance Criteria
- [ ] Multiple selection on Source List
- [ ] Able to do bulk actions

**Comment by shirshak55** [comment]
@NghiaTranUIT 
Also it would be great if u add clear button that will clear all the domains, as well as all the request on middle box. Currently it clear only middle one. Its because most of the app i debug has large number of domains and Its not feasible to delete one by one.

**Comment by NghiaTranUIT** [comment]
Sure, I will put "Action" button in bottom of the Left Panel, or I won't do it, since it's make the Left Panel is more complicated.

I suppose that support multiple selection, so we can delete all by Cmd+A for all selection, and hit Delete button 👍

**Comment by NghiaTranUIT** [comment]
All done 👍 

## 🤯 Changelogs 
- [x] Multiple selection on Source List (Left-Panel)
- [x] Improve: Cmd+A will only select all items (except Folder and Group) -> Able to delete or do quick right menu
- [x] Hotkey for deleting (CMD+Delete)
- [x] Support array on menu context
