### ISSUE TITLE
[Docs] SSL Proxying Using Rooted Andriod

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#248]
If your Android version is below 7 you don't need to do this step. Google added extra security that don't allow man in middle to attack after  Android 6. i.e unable to do mitm attack to android app. 

We don't bear any responsibility for problems due to rooting phone. So please follow guide at your own risk.

1. Root your phone with magisk framework.
2. Install Root file browser so you can copy and paste file in restricted system folder.
3.  Type following script in command line
```bash
$ cd ~/.proxyman
// We copy certificate to another file name just so we may need it later
$ cp proxyman-ca.pem temp.pem
$ hash=$(openssl x509 -inform PEM -subject_hash_old -in temp.pem | head -1)
$ mv temp.pem "$hash.0"
```

4. If you go to ~/.proxyman folder you must notice a file name starting with numbers with extension .0 . Copy that file to andriod.
5. Using root file browser transfer that file to /system/etc/security/cacerts/
6. Enjoy proxing.

Tips:

1. When using andriod phone set gateway to wrong ip just so you can be sure all your traffic goes from proxy man proxy only.
2. We can use mac sharing feature to create a mobile hotspot. And From android phone you can use Proxy man proxy easily. It is much better because sometime router can block request between mobile and macos.

-------
Thanks Proxyman for such a beautiful proxy :) I am using trail version as of now and will be waiting for currency exchange to drop so I can buy this beautiful proxy. I have tried charles, proxie and all but this one is really good.

**Comment by NghiaTranUIT** [comment]
Thank for the contribute 😍. I will update it in our Doc (https://docs.proxyman.io) and credit you 👍 💯

**Comment by NghiaTranUIT** [comment]
All done. Thank you so much 💯 

@shirshak55 btw, Breakpoint feature is supported in Proxyman 1.5.0 https://github.com/ProxymanApp/Proxyman/releases/tag/1.5.0

Let check it out. You will love it 👏
