### ISSUE TITLE
[Feature] Allow to use proxyman proxy only after grant

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#249]
I noticed that when i tried to connect proxy using android phone it didn't asked me like whether the phone should be allowed to use proxy or not. It can be security risk. It would be better if it explicitly ask permission or there is some checkbox like allow anybody to use this proxy etc.?

**Comment by NghiaTranUIT** [comment]
Hey @shirshak55, By default, Proxyman would minimize the number of steps in order to debug, so I deliberately removed the permission alert like Charles Proxy does.

I suppose that I could bring it back, and have the option in Preference. So savvy users like you could enable it, and keep the minimalism for ordinary users 👍 

Do you agree?

**Comment by shirshak55** [comment]
yea there can be option at least like only allow users with explicit grants
etc. yea minimalist is one point but security shouldnot be ignored too.

**Comment by NghiaTranUIT** [comment]
I see your point. Will bring it back in next release 👍

**Comment by jamesdixon** [comment]
@NghiaTranUIT similar issue -- I don't want to enable the proxy for my entire system. Just interested in proxying between iOS simulator and the internet. Is this possible?

**Comment by NghiaTranUIT** [comment]
Hey @jamesdixon,

Unfortunately, iOS Simulator is still using System HTTP Proxy, so there is no way to do it.

If you're working on iOS device (iphone, ipad), you could archive it (Only proxy on device, not entire system) by doing the following steps:

1. Proxyman -> Preference: Turn OFF "Auto Override the Proxy Config".
2. Stop and **Start** the Proxyman again: At this time, Proxyman is started, but System HTTP Proxy isn't overridden => The requests from mac aren't recored.
3. Follow the guideline on Certificate -> Install Certificate on iOS device, and config the Wifi HTTP Proxy on your iPhone to Proxyman (9090)
4. All requests from iOS are recored in Proxyman, but mac app isn't. Ping go 😄

I will officially support it by introduce the button to only turn off HTTP Proxy later.

**Comment by shirshak55** [comment]
@NghiaTranUIT we can change ios simulator proxy using proxy settings inside simulator .

**Comment by NghiaTranUIT** [comment]
Nice, I don't know that. Thank you @shirshak55 😄 

Okay. You can do it @jamesdixon by doing the first and second steps in above instruction 👍

**Comment by jamesdixon** [comment]
@NghiaTranUIT perfect! I was missing the "Auto Override the Proxy Config"

**Comment by NghiaTranUIT** [comment]
@shirshak55 @jamesdixon let check the new build. 

From now we can proxy on your mobile phone and ignore the requests from macOS. Just simple turn OFF the Proxy System Setting

<img width="528" alt="Screen Shot 2019-09-05 at 22 49 34" src="https://user-images.githubusercontent.com/5878421/64357753-78309180-d02f-11e9-9b69-a9914b9fc842.png">

**Comment by NghiaTranUIT** [comment]
Done
