### ISSUE TITLE
[Feature] Universal SSL

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#250]
All the websites or api except locally developed we browse have ssl enabled. Even most of the staging server uses ssl. So it will be useful instead of going to left sidebar and clicking enable https one by one we can enable "Turn on Universal SSL" from any checkbox or something like that :)

In charles we can use * wildcard and it will apply ssl to every request.

**Comment by NghiaTranUIT** [comment]
I suppose that I should support Wildcard in SSL Proxying List like Charles does, since it's straightforward and I don't need to introduce more buttons. 

More button is more complex and more bug 😄

**Comment by NghiaTranUIT** [comment]
@shirshak55 I will push bunch of minor improvement tickets, which you open recently to Proxyman 1.6.0 milestone 👍 Next version is for Breakpoint feature, which is the huge feature I'm working on 😍

**Comment by NghiaTranUIT** [comment]
All done 🥇 

## 🤯 Changelogs 
- [x] Logic for SSL Wildcard 
- [x] Improve UI on SSL Proxying list: Introduce Menu context, hotkey, ...
- [x] Small tweak: If enable universal wildcard (*), we should close all alive connection in order to open new socket and do ssl proxing
