### ISSUE TITLE
Add HTTP Proxy to cURL

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#252]
## 🐶 Brief
After copying the cURL from the selected request and executing into iTerm or Terminal, the flow isn't recored in Proxyman since cURL doesn't respect the HTTP Proxy by default.

We should add the `-x http://localhost:9090` and the option in Preference.

## 👑 Criteria
- [ ] Add `-x http://localhost:9090` to cURL
- [ ] Add options to Preference -> Advances

**Comment by shirshak55** [comment]
by the way you should remember to not use port 9090 hard coded. Seems like changing port don't work atm its bug.

**Comment by NghiaTranUIT** [comment]
You're right. I don't hard code 9090 as the port :D.

I just test the Port Change in Preference. It's a bug indeed, after filling the new port, we have to hit Enter in order to execute. If we tab or move another tab, it won't. I will fix it now 👍

**Comment by shirshak55** [comment]
@NghiaTranUIT  by the way I think upto 1024 port we will need admin right. So if user try to use port like 8 and and tab it whether it should show error message and stop proxy and not let user to switch proxy using previous port.

**Comment by NghiaTranUIT** [comment]
Understood, I haven't aware of this case. Thank for the hint. Proxyman 1.6.0 milestone will come with bunch of your minor feature 👍 

Thank you so much 🥰

**Comment by NghiaTranUIT** [comment]
All done 🎉 

## 🤯 Changelogs 
- [x] Add "Include HTTP Proxy in cURL" in Preference -> Advance tab
- [x] Add hotkey for cURL: Shift+Command+C
- [x] Able to add --proxyy
<img width="672" alt="Screen Shot 2019-09-02 at 12 06 03" src="https://user-images.githubusercontent.com/5878421/64091427-48a52f00-cd7a-11e9-8f98-bc701aa57eb2.png">

**Comment by shirshak55** [comment]
@NghiaTranUIT typo should be include instead of Inlcude

**Comment by NghiaTranUIT** [comment]
Wow. My terrible mistake 😮

That for the point 😅
