### ISSUE TITLE
[Feature] Easy way to export certificate

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#257]
Currently we need to browser ~/.proxyman/proxyman-ca.pem. And most user don't even know it ca exists in that folder. It would be nice if we can directly export from app.

**Comment by NghiaTranUIT** [comment]
I devote myself to do it in Proxyman 1.6.0. Stay tuned man ⚡️

**Comment by shirshak55** [comment]
Thanks :)

**Comment by NghiaTranUIT** [comment]
## 🤯 Changelogs 
- [x] Logic for export pem file
- [x] Support export in Preference and Menu
