### ISSUE TITLE
Slack (and other ws connection related software) doesn't update

### ISSUE THREAD

**Issue by superandrew** [ProxymanApp/Proxyman#258]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.4.7
### macOS Version? (Ex. mac 10.14)
10.14
### Steps to reproduce 
Open Proxyman, Open Slack. When proxyman is open, while slack can do http traffic, it seems not to be updating the chat probably because of the websocket connection. When I refresh manually, the chat gets updated via http. It's a bit annoying because while proxyman is active you don't receive any new chats. Maybe is there some configuration issue/step I should take?
### Expected behavior
Proxyman should either pass through the websocket connection or proxy it
### Screenshots (optional)
![CleanShot 2019-08-19 at 09 56 37](https://user-images.githubusercontent.com/71364/63248476-a6f4ec80-c267-11e9-841e-4264a541c714.png)

**Comment by NghiaTranUIT** [comment]
Hey, thank for the report @superandrew. I'd clarify that:
- Do you enable SSL Proxying for the Slack app? Since I'm still receiving new notification on Slack when the Proxyman is opening, and no enable SSL Proxying on Slack.

**Comment by superandrew** [comment]
That was definitely the problem! Probably I did some experiment while enabling ssl for Slack. Is it possible to bypass it also for React Native Debugger the same way?

**Comment by NghiaTranUIT** [comment]
If we enable SSL Proxying in entire app in 1.4.7 Proxyman, it probably causes some unexpected behavior since I haven't properly supported SSL Proxying for websocket yet : /

I will take it into account in next version by forwarding them. You the WS will work regardless of SSL Proxying 👍
