### ISSUE TITLE
Traffic Not Captured While on VPN

### ISSUE THREAD

**Issue by aaronvegh** [ProxymanApp/Proxyman#264]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.5.0 (1500)

### macOS Version? (Ex. mac 10.14)
10.14.6

### Steps to reproduce 
I have tried this with TunnelBear as the VPN. When the VPN is active, ProxyMan doesn't capture traffic. I have seen it work sometimes, but it's not reliable at all. 

I've tried it both with Proxyman started before the VPN, and vice versa. When on VPN, no traffic is logged. As soon as you jump off the VPN, it works normally again. 

### Expected behavior
I would love to see traffic logged while on VPN!

**Comment by shirshak55** [comment]
u can just change application to use proxy.

App -> Proxy -> VPN

**Comment by NghiaTranUIT** [comment]
Hey @aaronvegh can you double check whether the TunnelBear overrides the System HTTP/HTTPS Proxy in Network.prefPanel to different port when it starts?

Technically, Proxyman only captures if the System Proxy is pointing to port 9090.

From my case, I tested with Private Network Access (PNA) VPN app.
1. When open PNA -> The System Proxy isn't overridden -> Able to access the Internet via VPN
2. Open Proxyman -> The system Proxy is overridden and point to 9090 -> Proxyman is able to capture requests

<img width="780" alt="Screen Shot 2019-08-27 at 09 54 00" src="https://user-images.githubusercontent.com/5878421/63737433-9ddfcd00-c8b0-11e9-8777-45ac1810c312.png">

<img width="1415" alt="Screen Shot 2019-08-27 at 09 46 50" src="https://user-images.githubusercontent.com/5878421/63737383-712bb580-c8b0-11e9-9954-b1736e8efd4a.png">

**Comment by NghiaTranUIT** [comment]
My Private Internet Network app does't install any VPN setting in Network.prefPanel. I will check the Tunnel Bear and give you the update soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @aaronvegh I just installed TunnelBear, and what I see that TunnelBear doesn't install any VPN setting in Network.prefPanel, and Proxyman just works as usual.

I googled but couldn't find the way to setup the VPN connection for TunnelBear like you. How can you do that? 🤔

**Comment by NghiaTranUIT** [comment]
Hey, Tunnel Bear just prompts to install the VPN Config to my Network after three time quit.

I will check it out now 👍 Thank for quick reply

**Comment by NghiaTranUIT** [comment]
I just investigated and it turns our that the TunnelBear VPN Config works different way and it doesn't respect the HTTP Proxy config.

I'm not sure how TunnelBear install the VPN config, but I couldn't list it out by running `networksetup -listallnetworkservices` or relevant CLIs. As I couldn't find it, I couldn't override the Proxy of Tunnel Bear to 9090.

Ref: https://github.com/ProxymanApp/Proxyman/issues/211#issuecomment-511768750

--------------

The interesting is that I `SystemConfiguration` to list out all conneciton, but no Tunnel Bear VPN, but it still shows other VPN 😮

--------------
I will keep investigating and update you later. For now, please turn off Tunnel Bear for temporary.

Thank you in advance 👍

**Comment by shirshak55** [comment]
it depends on vpn. like in firefox there is way to not choose systemproxy
etc. if u want to make sure all traffic must use proxy i recommend using
firewall. On osx i use iptables directly .

**Comment by NghiaTranUIT** [comment]
Thank you @aaronvegh and @shirshak55. I will keep taking it into account 👍

**Comment by shirshak55** [comment]
I think we can close the issue as vpn is very complex issue. We will need to use firewall which is not related to this proxy :)

**Comment by NghiaTranUIT** [comment]
I suppose that we just keep it opens since it's opened by @aaronvegh.
He will close when he's satisfied. 👍

**Comment by aaronvegh** [comment]
I'm satisfied from the perspective that some VPNs do work with Proxyman. The provider I moved to isn't as good as TunnelBear, but it's more important that I be able to monitor traffic, so here we are. Thank you all for your assistance!

**Comment by andersonalex** [comment]
@NghiaTranUIT It looks like Proxyman does not capture traffic when I use my employer's VPN through NordVPN, and I need to be connected to this VPN to test my iOS application in the development environment. Is there any way I can get Proyman to work with NordVPN?

**Comment by NghiaTranUIT** [comment]
Hey @andersonalex, VPN is notorious that it doesn't work well with any Man-in-the-middle apps because all traffic forcibly goes through the VPN rather than going to Proxyman's port at 9090. Thus, traffic doesn't appear on the app.

Here are some solutions that might work:
1. Find the way to config the HTTP Proxy on NordVPN to Proxyman.
2. If not, let try this approach by using HTTP Proxy NordVPN (https://support.nordvpn.com/Connectivity/Proxy/1049306672/Proxy-setup-on-Safari.htm)

It means that we don't use the NordVPN app on macOS, but we use External Proxy on Proxyman to forward all traffic to your VPN. Here is how to setup:
1. Stop all NordVPN on macOS
2. Start Proxyman app, make sure you can see some traffics on the app
3. Tools -> Proxy -> External Proxy
4. Config the HTTP/HTTPS Proxy to your Nord VPN (Make sure the username/pass is correct. You can above link)

<img width="733" alt="Screen Shot 2020-06-11 at 08 31 01" src="https://user-images.githubusercontent.com/5878421/84335022-0c7ee480-abbe-11ea-8bd4-dfbc3a4dc17a.png">

Thus, Traffic on macOS or iOS Simulator -> Go to Proxyman 9090 -> Then forwarding to NordVPN (External Proxy).

Let try it.

Disclaimer: I haven't had any change to test it 😄

**Comment by shirshak55** [comment]
@NghiaTranUIT i don't think that will work because most software can use no proxy setup. There should be way to capture before packets leave nic? 

Like good way to test is how to make mozilla firefox work with proxy man in no proxy setup.

**Comment by NghiaTranUIT** [comment]
@shirshak55 It’s possible if I create a dummy proxyman VPN, to navigate traffic to proxyman port. This setup could work with Firefox (even though we set no Proxy in preference).

But I’m not sure if it works with another VPN (Nord)

**Comment by shirshak55** [comment]
@NghiaTranUIT that will at least solve the issue related to app that don't obey system proxy etc. 

Regarding vpn i think most of them create their own adapter. So if we can hook proxyman in the adapter may be it is possible. Sorry i don't know to much in detail.

**Comment by NghiaTranUIT** [comment]
Thanks for the hint 🙌 

To summary what I tried with a dummy VPN. If Proxyman adds a dummy VPN to the Network system. It will forward all traffic to Proxyman Proxy Server (port 9090), so, all traffic will appear on Proxyman, including traffic from apps that don't obey the HTTP Proxy config (ex: curl, ...). It's really good

However, the traffic won't go through the first VPN anymore. For instance, if I use the Cisco VPN, then opening Proxyman and set up a dummy VPN, the traffic will go from Client -> Dummy VPN -> Proxyman -> the Internet. As a result, users might not be able to access the Internet anymore since it doesn't go through Cisco VPN.

**Comment by NghiaTranUIT** [comment]
I also did try to create a virtual network interface (tun/tap), but the result is the same. 

There is no way that could achieve Client -> [Middlewares] -> Proxyman HTTP Proxy Server -> cooperated VPN -> the Internet. 

I'm still looking for a solution.

**Comment by tgeorgiop** [comment]
Hello, I have cisco anyconnect too from my company and proxyman does not work. According to previous comments, 
@calendee had success. Is there any way to Proxyman to work?

**Comment by calendee** [comment]
My trick above did work for a while. Then, somehow Cisco Anyconnect started blocking it again. 

Fortunately, I don't work there anymore; so, I don't have to deal with it 🤣!

**Comment by NghiaTranUIT** [comment]
Unfortunately, there is no feasible solution to make VPN apps work with Proxyman or other web debugging apps, like Charles and Fiddler : <

VPN and HTTP Proxy usually have not cooperated well

**Comment by NghiaTranUIT** [comment]
For the tun/tap virtual interface, I tried and I'm able to reroute all traffic from the system to Proxyman app. 

However, I couldn't achieve this: macOS -> my tun/tap interface -> your VPN -> Proxyman -> the Internet.

Because the VPN app is actually a tun/tap interface (behind the scenes) and the system only allows one tun/tap interface at one time. Therefore, it doesn't work

**Comment by shirshak55** [comment]
well i think its the vpn issue so i think its easy if user connect vpn using another pc / router while testing ? If VPN doesn't obey can we do anything?

**Comment by NghiaTranUIT** [comment]
If the VPN doesn't have any option to set HTTP Proxy, it seems like there is no way to make Web debugging proxy apps work with VPN apps :/

**Comment by koryhutchison** [comment]
My employer also uses Cisco AnyConnect, but I was able to find a work around! In my case at least, when I had Proxyman open and then tried to connect to my VPN, the connection would fail, but Proxyman would at least show me the host where the connection did fail. So what I did to get around it was to enter in that host into the "Bypass proxy settings for these Hosts & Domains" section in System Preferences -> Network -> Wi-Fi > Advanced -> Proxies. Once I added it in, and applied the changes, Cisco was able to connect without any issues. Hopefully this helps people!

**Comment by NghiaTranUIT** [comment]
Thank you so much @koryhutchison . I've shared your solution to some Proxyman users, who are struggled with Cisco AnyConnect VPN 🙌

**Comment by Tymoteusz24** [comment]
> What a revelation! TunnelBear is doing something weird! I just tried a different VPN provider and I'm able to see my traffic through ProxyMan. Thank you so much! I'm sure others will appreciate a solution to this provider, but I'm taken care of for now, at least.
> 
> A.

@aaronvegh You said that it starts working with a different VPN provider. Can you share what provider are you using? I have the same problem with NordVPN.

**Comment by NghiaTranUIT** [comment]
@Tymoteusz24  If you can find a Proxy Config in NordVPN's Preference, it means you can set HTTP/HTTPS Proxy to Proxyman (at localhost:9090). Then Proxyman and other Proxy tools will work.

Otherwise, there is no solution because VPN would force all traffic to go the VPN, instead of the Proxy Server (Proxyman)

**Comment by haphanquang** [comment]
Workaround with Cisco VPN
- start Cisco VPN first, press Connect but not enter password
- start Proxy man
- go back to Cisco VPN and enter password
- start simulator
Enjoy magic.

**Comment by ganjarpanji** [comment]
im also facing problem using pulsesecure vpn. 
its stated [here](https://docs.proxyman.io/troubleshooting/proxyman-does-not-work-with-vpn-apps#4-pulse-secure-and-global-protect-vpn) but i couldn't make it work

**Comment by NghiaTranUIT** [comment]
Hey @ganjarpanji please try this [Document](https://docs.pulsesecure.net/WebHelp/PCS/8.3R1/Content/PCS/PCS_AdminGuide_8.3/Specifying_Web_Proxy_Servers.htm) from Pulse Secure VPN

It guides you on how to set HTTP/HTTPS proxy to a Proxy Server. Then you can set IP=127.0.0.1, port=9090

**Comment by Calvincac** [comment]
Hello,
[koryhutchison](https://github.com/koryhutchison) which host do you mean? When i check proxyman doc it just mentions "your host". Is it the host of my machine? is it the host that i want to run some tests? I didn't quite follow. I would be great if there was an example. I also use Cisco AnyConnect

Thanks in advance.

**Comment by NghiaTranUIT** [comment]
@calendee it's the host (domains) that failed when using Proxyman + Cisco VPN. By adding them to the "Bypass", this host (domain) will use the VPN without going to Proxyman -> Not failed.

Maybe you should try the solution from https://github.com/ProxymanApp/Proxyman/issues/264#issuecomment-854390481

**Comment by koryhutchison** [comment]
Yeah @Calvincac when I use Cisco Anyconnect with my company, there’s an initial domain that’s in the box that you connect to. So all you would do is put that domain in the box like I described.

**Comment by 3257** [comment]
A bit late to the party but I used Tunnelblick and it worked great. These are the instructions  I followed and it worked https://support.nordvpn.com/hc/en-us/articles/19924903986961-Manual-connection-setup-with-Tunnelblick-on-macOS.

**Comment by InderKumarRathore** [comment]
For Cisco VPN this solution worked for me.
1. Disconnect your VPN
2. Open Proxyman
3. Go to Tools → Proxy Settings → Bypass Proxy Settings…
4. Add vpn server domain (e.g., vpn.yourcompay.com etc). Tap on Done
5. Connect your VPN now

**Comment by seidnerj** [comment]
For NordVPN you can use the below to set up a local http/https proxy that will router through NordVPN and then use that proxy server as an external proxy in Proxtman.

https://github.com/edgd1er/nordlynx-proxy

**Comment by NghiaTranUIT** [comment]
> For NordVPN you can use the below to set up a local http/https proxy that will router through NordVPN and then use that proxy server as an external proxy in Proxtman.
> 
> https://github.com/edgd1er/nordlynx-proxy

Thanks, I added to the VPN Troubleshooting doc: https://docs.proxyman.io/troubleshooting/proxyman-does-not-work-with-vpn-apps#nord-vpn

**Comment by MojtabaHs** [comment]
I think Proxyman should be able to capture traffic and work properly without requiring users to manually configure a proxy for every VPN app.
[Charles](https://www.charlesproxy.com) can proxy traffic from any VPN as long as it is running before the VPN connection is established.
[Little Snitch](https://www.obdev.at/products/littlesnitch) can monitor all network traffic, even when it goes through a VPN.
So why can’t Proxyman do the same?

**Comment by NghiaTranUIT** [comment]
@MojtabaHs it's because some VPNs app officially support Charles Proxy. For example, Zscaler VPN detects if you're using Charles Proxy, and it automatically configs to make it works.

Proxyman is working with Zscaler Team to do the same thing too. Will release soon 👍
