### ISSUE TITLE
Global filter content

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#266]
## 🐶 Brief
Even though we support node to narrow down the requests in specific domain, path, but sometime, there are many irrelevant request are still there. Ex, image, css, html, ....

We need to better solution to quickly filter down it.
The UI is a tool bar: [HTTP] - [HTTPS] -|- [JSON] [XML] [HTML] [Image]....

Thus, we can quickly select the type of content we would to see.

## 👑 Criteria
- [x] Small filter in toolbar
- [x] Able to to select and filter down the content-type

**Comment by NghiaTranUIT** [comment]
Related #263 #251

**Comment by NghiaTranUIT** [comment]
All done 💯 

Some screenshot 😄 

https://twitter.com/proxyman_app/status/1167111706058715136/photo/1

<img width="1136" alt="Screen Shot 2019-08-29 at 23 24 17" src="https://user-images.githubusercontent.com/5878421/63958546-c59f8280-cab4-11e9-84df-c8cc5fac150f.png">

**Comment by shirshak55** [comment]
wow
