### ISSUE TITLE
Doesn't restore proxy settings correctly.

### ISSUE THREAD

**Issue by drekka** [ProxymanApp/Proxyman#272]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.5.1

### macOS Version? (Ex. mac 10.14)
10.14.6

### Steps to reproduce
1. Setup a "Automatic Proxy Configuration" with a URL to a pac file on a server.
2. Start Proxyman
3. Stop Proxyman.
4. Inspect the proxy settings.

### Expected behavior
At step 2 Proxyman should disable the current proxy setup and enable itself ✔️
At step 3 Proxyman should remove itself ✔️
Also at step 3 Proxyman should restore the previous settings. ❌ 

### Discussion

When I look at the settings after Proxyman has stopped, I can see that the URL is still present, but Proxyman has not activated it again. All I have to do is to tick the setting and apply it. So I'm thinking this is probably not a hard thing to fix given Proxyman already manipulates the settings to start with.

**Comment by NghiaTranUIT** [comment]
Thank for detail report. I'm able to reproduce it too 👍 

I'm going to fix and send you a hotfix soon.

**Comment by NghiaTranUIT** [comment]
Hey @drekka, here is hot-fix build for this bug: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.0_Helper_Tool_1.0.3.dmg

Basically, I save the original proxy config before overriding, and reverting the setting back later. 

Let check it out and give me a 👍 if it works for you ☕️

**Comment by drekka** [comment]
Awesome. It's now correctly setting and unsetting the proxy settings include restoring the setting of the Automatic Proxy Configuration. Thanks. 👍👍👍👍

**Comment by NghiaTranUIT** [comment]
Glad to hear that @drekka 🌮 . I will officially ship the fix in next release 👍

**Comment by NghiaTranUIT** [comment]
I would close this ticket and prepare for next release 👍

**Comment by mazgajmaciek** [comment]
@NghiaTranUIT this somehow doesn't work for me still (it doesn't revert Automatic Proxy Configuration when I turn Proxyman off). I'm using:

- Proxyman Version 3.5.2 (30520)
- Monterrey 12.4
