### ISSUE TITLE
Feature: Button to open network proxy settings

### ISSUE THREAD

**Issue by drekka** [ProxymanApp/Proxyman#276]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.6.0

### macOS Version? (Ex. mac 10.14)

10.14.6

Whilst I'm raising issues :-) I'd like to add a feature request. That is - to have an additional button to the tool bar. This new button will option the system network settings, and the proxy configuration. It's just a convenience thing to save us poor developers from having to do a little extra clicking when we want to check something :-)

**Comment by NghiaTranUIT** [comment]
Totally agree with it. Some users request the button on Toolbar to make it visible and we don't need to open the Menu to check it.

I will push in in next release 👍

**Comment by drekka** [comment]
Thank you for all your prompt replies. I'm looking forwards to seeing how they work out 👍
