### ISSUE TITLE
Over-scroll of the Response Body is white on Dark Mode

### ISSUE THREAD

**Issue by avario** [ProxymanApp/Proxyman#278]
### Proxyman version?
Proxyman 1.6.0

### macOS Version? 
mac 10.14.6

### Steps to reproduce 
1. Set macOS to use Dark Mode
2. Select any request
3. Open the right inspector pane
4. Under Request, select Body
5. Scroll the Body content area up and down beyond the limits of the content (over-scroll)
6. A white area bounces into visibility with the over-scroll

### Expected behavior
The over-scroll area should be dark grey in Dark Mode to match the background of the rest of the view and the behaviour of all other scrollable sections.

### Screenshots (optional)
<img width="548" alt="Screen Shot 2019-09-12 at 2 32 04 PM" src="https://user-images.githubusercontent.com/2192944/64749563-25446600-d56a-11e9-897b-1bddf786b7f0.png">

**Comment by NghiaTranUIT** [comment]
Thank for quick report  @avario. It's a noticeable drawback when using Webpage [Code Mirror](https://codemirror.net) as a syntax highlighter and its background doesn't respect the Proxyman's theme 😅

Let me find better solution to override it 👍

**Comment by NghiaTranUIT** [comment]
Hey @avario. Here is the BETA includes the fix on your issues (https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.0_background_webview.dmg).

Just clarify that this build has new update Helper Tool 1.0.3, which fixed this https://github.com/ProxymanApp/Proxyman/issues/272

I will officially release in next version ☕️ 

Thank you in advance 👍
