### ISSUE TITLE
Update from UI?

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#289]
I think there is delay for updates which we receive by clicking Check for Updates? 

I don't know why but i have not seeing latest update that u push to your GitHub releases?

If its beta update can u make a checkbox like "Beta Update" so we can update it easily from interface rather than downloading, installing etc?

**Comment by NghiaTranUIT** [comment]
Sorry about that. It delayed because I released on Github first, then on the app later 😅

In the next release, I will update on database first, then the Github. So, we can get the update immediately when receiving the Github's releases 🙌 

Thank for raise it 🌮

**Comment by shirshak55** [comment]
Hmm I think you can use CI for releasing so you don't need to do database, github etc right? Something like continuous deployment.
