### ISSUE TITLE
[Feature] Display serverIPAddress field contained in HAR file when available

### ISSUE THREAD

**Issue by Robert-Saiter** [ProxymanApp/Proxyman#293]
The HAR viewer is great already (Thank you!). I would benefit greatly from a column option that displays the serverIPAddress field when available. 

serverIPAddress is part of the 1.2 spec.
https://w3c.github.io/web-performance/specs/HAR/Overview.html

> serverIPAddress [string, optional] (new in 1.2) - IP address of the server that was connected (result of DNS resolution).

**Comment by NghiaTranUIT** [comment]
That's cool. I will add this field now 👍 and update bunch or HAR 1.2 fields.

**Comment by S8ER01Z** [comment]
Thank you!!!

**Comment by NghiaTranUIT** [comment]
Hey @S8ER01Z please check the hot-fix here https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.2_fix_har_export.dmg

From now, serverIPAddress and many HAR 1.2 are supported with correct data. Let check it out 👍

**Comment by S8ER01Z** [comment]
> Hey @S8ER01Z please check the hot-fix here https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.2_fix_har_export.dmg
> 
> From now, serverIPAddress and many HAR 1.2 are supported with correct data. Let check it out 👍

I tested this but did not see the field.  Just wanted to verify the hot-fix is in the dmg provided. 

Thank you for the quick action here.

**Comment by NghiaTranUIT** [comment]
Just wondering that which HAR Previewer you are using?

If it's possible, please open your HAR file with Sublime app, and search for the `serverIPAddress`.

I checked and this HAR file: https://pastebin.com/0z1qQkt5 includes ```"serverIPAddress":"52.41.157.85"```

**Comment by S8ER01Z** [comment]
Currently I view HAR files in VSCode as raw text.  I've not found a good HAR Previewer which is why these additions in your product will prove to be so valuable.  My HAR file contains the field as expected but I didn't see it in the ProxyMan.  
"serverIPAddress": "xxx.xxx.xxx.xxx",

I downloaded the pastebin you included and I do not see the field displayed in the Proxyman application.   I am not sure if the hotfix is in the linked version or if I am doing something wrong.
https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.6.2_fix_har_export.dmg

![proxyman-hotfix-test](https://user-images.githubusercontent.com/1056227/66274400-3b350600-e84c-11e9-8e15-949d04df06a7.jpg)

**Comment by NghiaTranUIT** [comment]
I understood your mean @S8ER01Z, since I haven't support the Server IP Address as a column in the Flow List (Middle Panel) 😄 

In the hot-fix build, I includes the fix on `serverIPAddress` to present the IP (the old build is the address, which is incorrect) and include new 1.2 HAR fields.

I will add the Server IP column this week and sent you the build soon 👍

**Comment by S8ER01Z** [comment]
@NghiaTranUIT I do not believe this was added yet?  I can add a feature request if it helps for tracking the flow list change. 

I would still love to have the ipAddress visible in the Flow List.

**Comment by NghiaTranUIT** [comment]
Hey there, sorry for this. I complete forgot to finish the remaining task 😱

I just added this ticket to Milestone 1.10.0 and I will sort it out soon 👍

**Comment by S8ER01Z** [comment]
No problem at all. Thank you Sir

**Comment by NghiaTranUIT** [comment]
Hey @S8ER01Z, Here is the BETA build for you: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_ServerIP.dmg

Basically, this build ships the Server IP column. You can also see this column when importing the HAR file too.

<img width="240" alt="Screen Shot 2019-11-25 at 13 44 57" src="https://user-images.githubusercontent.com/5878421/69518309-ccda0d80-0f89-11ea-897c-69353f82ba61.png">

<img width="1547" alt="Screen Shot 2019-11-25 at 13 29 48" src="https://user-images.githubusercontent.com/5878421/69518243-a61bd700-0f89-11ea-8384-51342418d4c2.png">

**Comment by S8ER01Z** [comment]
I see this column in new builds and it works perfect!!! Thank you!

**Comment by NghiaTranUIT** [comment]
@S8ER01Z Glad to heard that 🎉

**Comment by Robert-Saiter** [comment]
Possible regression?  When viewing HAR that clearly has "serverIPAddress" values the "Server IP" field is blank.  

When I open the same HAR file using the older build you provided I can see the data populated as expected. 
https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_ServerIP.dmg

**Comment by NghiaTranUIT** [comment]
Thanks for the report. Look like the `serverIPAddress` is gone from the v2. I'm looking on it now 🙌

**Comment by NghiaTranUIT** [comment]
Hi @Robert-Saiter , this BETA build would fix your issue: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.2.0_Fix_Missing_Server_Ip_From_HAR.dmg

I will present the Server IP from HAR file correctly 💯 

<img width="1261" alt="Screen Shot 2020-07-22 at 22 32 09" src="https://user-images.githubusercontent.com/5878421/88197970-61a61f80-cc6d-11ea-80f0-9652366e4d62.png">

Sorry for the bug when I migrate Proxyman to v2 with a minor bug 🐞

**Comment by NghiaTranUIT** [comment]
Hey @Robert-Saiter , if you find that the Server IP column has missing data in some requests. Here is the fix 🎉 #560 

Thank you in advance 🙌

**Comment by Robert-Saiter** [comment]
Thank you for looking into this...I still seem to have trouble with data exported from Chrome.  This is a very basic export to keep it clean / easy to see.  When I open this HAR I do not see the serverIPAddress field populate but the data is present in the HAR file.   Perhaps I am doing something wrong on my end?  


[test.har.zip](https://github.com/ProxymanApp/Proxyman/files/5003448/test.har.zip)

**Comment by NghiaTranUIT** [comment]
I'm sorry, my fault to forget checking this case 😯

Please check out this fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.3.0_Missing_ServerIP_In_HAR.dmg

<img width="1480" alt="Screen Shot 2020-07-31 at 11 16 58" src="https://user-images.githubusercontent.com/5878421/89001760-52863800-d325-11ea-8b87-41f1ef15ebcb.png">

<img width="1497" alt="Screen Shot 2020-07-31 at 11 22 16" src="https://user-images.githubusercontent.com/5878421/89001775-5a45dc80-d325-11ea-8934-cedea59af60c.png">

This build will present the Server IP in the HAR file if it's available.

Thank you so much 🌮

**Comment by Robert-Saiter** [comment]
Confirmed this fixed the issue and serverIPAddress is now displayed when opening HAR files. Thank you!

**Comment by NghiaTranUIT** [comment]
Nice to hear that 👍 🙌
