### ISSUE TITLE
[BUG] Too many digits on Request / Response Body Size

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#301]
## 🐶 Brief
In the latest version, they request and response body size have many redundant digits.

<img width="1496" alt="Screen Shot 2019-10-14 at 23 03 26" src="https://user-images.githubusercontent.com/5878421/66765817-e857f000-eed6-11e9-866a-5c281aa06e16.png">

## 👑 Criteria
- [ ] Should be round to 1 floating digit

**Comment by shirshak55** [comment]
haha this floating point digit is always pain in ass :)

**Comment by NghiaTranUIT** [comment]
In the past, I encountered this floating pain when parsing the number in JSON too (https://github.com/ProxymanApp/Proxyman/issues/169). It's weird that the JSONSerialization class in Foundation framework doesn't handle it properly and our developer have to fix it manually. 😅

**Comment by NghiaTranUIT** [comment]
All done 🎉 

## Changelogs
- Fix `formatter.maximumFractionDigits` in `NSNumberFormatter`

**Comment by shirshak55** [comment]
@NghiaTranUIT what will happen if the data was actually 70.000000001?

**Comment by NghiaTranUIT** [comment]
We round it up to 70 (Bytes) 😄

**Comment by shirshak55** [comment]
hmm i am that is problem right? Lets say I am working on money endpoint and supplied 70.00001 and proxyman made it 70 and i mock that response to test api server now it will fail because my api server consumer expects it to be 70.00001 not 70 . SO I think proxy man should serve same response given by server and should not roundup etc.

**Comment by NghiaTranUIT** [comment]
The size of the response remains as it is (70.00001) and your Test API server won't be failed. It only rounds up for the presenter on the flow panel.

If we need the precise value, I suppose that I would implement the Summary tab, which presents all essential data without round up.

**Comment by shirshak55** [comment]
i mean if i save response to disk will it modify according to presenter or it will save response as it should?
