### ISSUE TITLE
1.7.0 bug with http

### ISSUE THREAD

**Issue by superandrew** [ProxymanApp/Proxyman#306]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.7.0

### macOS Version? (Ex. mac 10.14)
10.15
### Steps to reproduce 
Launch proxyman, connect in http to a localhost address

e.g. 

http://something.dev:8000 (where something.dev is mapped to 127.0.0.1)

Throught proxyman the connection gets converted to https://

[19/Oct/2019 12:12:38] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00§\x01\x00\x00£\x03\x03]ªý¶Q\x07\x15óÁ\x83¾ÊÉÊÁ¸~ftEzÄþÇ\x1aö')
[19/Oct/2019 12:12:38] You're accessing the development server over HTTPS, but it only supports HTTP.

### Expected behavior

navigate as previous versions

### Screenshots (optional)

<img width="1434" alt="CleanShot 2019-10-19 at 14 15 37@2x" src="https://user-images.githubusercontent.com/71364/67144784-02008b00-f27b-11e9-9ab0-1e8d81d761e0.png">

**Comment by superandrew** [comment]
I forgot to say, that if I shut down proxyman the request goes through http as usual.

**Comment by NghiaTranUIT** [comment]
Thank for the quick report. I'm investigating it and sent you a BETA today 👍

**Comment by NghiaTranUIT** [comment]
Hey there @superandrew 

In the latest build, I mismatch the HTTP -> HTTPS when connecting to a local server.

Here is hot-fix https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.7.0_Fix_HTTP_Localhost.dmg

I'm going to officially release the hot-fix in this today. Thank you a lot for a bug report 🎉

**Comment by NghiaTranUIT** [comment]
@superandrew Let update to Proxyman 1.7.1 (https://github.com/ProxymanApp/Proxyman/releases/tag/1.7.1) 

Thank you a lot 🎉
