### ISSUE TITLE
1.7.0 bug with ios simulator certificates

### ISSUE THREAD

**Issue by superandrew** [ProxymanApp/Proxyman#307]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.7.0

### macOS Version? (Ex. mac 10.14)

10.15

### Steps to reproduce 

Launch simulator, create a request. Every time I try to install the simulator says it is ok,  but then the request fails. Tried resetting the simulator as well

### Expected behavior

As it worked before

### Screenshots (optional)

<img width="1434" alt="CleanShot 2019-10-19 at 14 15 37@2x" src="https://user-images.githubusercontent.com/71364/67144800-4a1fad80-f27b-11e9-9924-27eab2f8ff84.png">

**Comment by superandrew** [comment]
back to 1.6.2 everything is normal

**Comment by NghiaTranUIT** [comment]
It seems to relate to #306. It's the same issue that Proxyman make an incorrect connection to HTTP Local server.

**Comment by NghiaTranUIT** [comment]
Let try a new build (https://github.com/ProxymanApp/Proxyman/issues/306#issuecomment-544219112).

If you're still encountering these issues:
1. Reset the iOS Simulator again
2. Preference -> Delete the current Proxyman CA
3. Install Proxyman CA again.

If new build, I update some security for this Certificate, which could cause this problem.

**Comment by superandrew** [comment]
it works with 1.7.1. Thanks!
