### ISSUE TITLE
[Enhancement] Open requests/ responses in new window

### ISSUE THREAD

**Issue by 8bitzz** [ProxymanApp/Proxyman#314]
### Steps to reproduce 
- Select an URL to observe content of requests/responses
- Toggle `Vertical/Horizontal` button to see more content 

### Expected behavior
- Click `Toggle` button would see content of requests/ responses in new window

### Screenshots (optional)
<img width="1440" alt="Screen_Shot_2019-11-01_at_09_30_38" src="https://user-images.githubusercontent.com/23531403/67998827-69abd280-fc8c-11e9-9461-08262949fd98.png">

**Comment by NghiaTranUIT** [comment]
The idea to open the Request / Response panel as a new Windows is really decent. I means that we can leverage the huge space in the external monitor and easier to see big JSON Responses 👍 

Thank for this idea. I'm working on the #310, so I could take it into account too 🌮

**Comment by NghiaTranUIT** [comment]
All done 👍 

## Changelogs
- [x] Able to view Request / Response a separate windows -> Become fullscreen in the external monitor 
- [x] Able to resize and get spacious content.
- [x] Easily to go back to normal mode

<img width="1680" alt="Screen Shot 2019-11-04 at 21 44 36" src="https://user-images.githubusercontent.com/5878421/68129645-7b230200-ff4c-11e9-8334-a51e0f0a3b96.png">
<img width="1449" alt="Screen Shot 2019-11-04 at 21 45 06" src="https://user-images.githubusercontent.com/5878421/68129646-7b230200-ff4c-11e9-9427-0deca6e44b23.png">
