### ISSUE TITLE
Changing port don't work

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#327]
Changing port don't work
Switched to 8123 from 8124 now proxy man just says stopped.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8097377/68988547-47f04500-0861-11ea-8169-84248956d588.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8097377/68988549-52aada00-0861-11ea-85b8-314c0f21568f.png">

Tried clicking play and pause

**Comment by shirshak55** [comment]
and every time i start proxyman I see license check related api code . Can we ignore those request permanently?

**Comment by NghiaTranUIT** [comment]
Hey there, confirmed that there is a bug when switching the port in the latest build. To workaround, please change the port and re-open the app. It should work.

Regarding the API License checker, I will add the option in advance to ignore all Proxyman requests 👍

**Comment by NghiaTranUIT** [comment]
Here is the Fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.2_Change_Port.dmg

I will officially release in the next build 👍 Thank for you report 😄

**Comment by NghiaTranUIT** [comment]
Just reminder that this fix is included in the new release Proxyman 1.9.3. Let check it out 👍
