### ISSUE TITLE
Execution request when using breakpoint always injects "?" to query param

### ISSUE THREAD

**Issue by leapful** [ProxymanApp/Proxyman#328]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 1.9.2
### macOS Version? (Ex. mac 10.14)
macOS 10.16
### Steps to reproduce 
1. Open Proxyman then open https://www.google.com/ in Chrome.
2. Set breakpoint rule for https://www.google.com/ in Proxyman.
3. Refresh https://www.google.com in Chrome.
4. Breakpoint window in Proxyman will be prompted, then click execute to send request.
5. The response url from google.com is now https://www.google.com/?
### Expected behavior
Execution request from breakpoint should not inject any unexpected query param and response url for the steps to reproduce should be https://www.google.com/ .

This issue affects use case when testing caching for a website when server-side handling is using URL to get cache which should be, for example: "https://google.com" but now is "https://google.com/?" and causes cache not found.

**Comment by NghiaTranUIT** [comment]
Hey, thank for raising these issues. I'm able to reproduce it and it definitely affects the caching mechanism.

I will investigate and send you a hotfix build soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @leapful, here is the Fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.2_Invalid_char_breakpoint.dmg

Please let me know if it works and I will release in the next build 👍

**Comment by leapful** [comment]
@NghiaTranUIT Thanks for your fix. I'm able to finish my test scenario on caching.

**Comment by NghiaTranUIT** [comment]
Glad to hear that @leapful 👍

**Comment by NghiaTranUIT** [comment]
@leapful This bug is fixed in the latest release [Proxyman 1.9.3](https://github.com/ProxymanApp/Proxyman/releases/tag/1.9.3). Thank you so much 👍
