### ISSUE TITLE
Content layout settings are not persisted

### ISSUE THREAD

**Issue by DennisDreissen** [ProxymanApp/Proxyman#334]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.9.3

### macOS Version? (Ex. mac 10.14)

10.14.6

### Steps to reproduce 

1. Open Proxyman
2. Open settings
3. Change content layout to horizontal or vertical
4. Close the app completely or close the window
5. Re-open the app or open a new window

### Expected behavior

When re-opening the app/opening a new window, the content layout setting should be restored.

**Comment by NghiaTranUIT** [comment]
Thank for the report. I'm fixing it now 🐞

**Comment by NghiaTranUIT** [comment]
Hey there, here is the hot-fix for you https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_layout_content.dmg

I will officially release it in a next build 👍

**Comment by DennisDreissen** [comment]
That's really fast! Thank you!
