### ISSUE TITLE
Source List Panel - Duplicate Entry for Breakpoints (one leads to Blacklist)

### ISSUE THREAD

**Issue by jeanetienne** [ProxymanApp/Proxyman#339]
### Proxyman version?
1.9.3 (`1930`)

### macOS Version? (Ex. mac 10.14)
10.14.6 (`18G1012`)

### Steps to reproduce 
1. Open Proxyman
1. Start recording some network traffic
1. In the source list panel, right click on a domain under an app
1. Navigate to "Tools"

### Expected behavior
See Blacklist **and** Breakpoints

### Actual behavior
See **duplicated** Breakpoints (tooltip isn't duplicated)

### Screenshots (optional)

![Screen Shot](https://user-images.githubusercontent.com/1822562/69769911-081f4b00-11db-11ea-86e5-6a00a7535476.png)

**Comment by NghiaTranUIT** [comment]
Hey there, it's a mislabel bug. It's actually a BlackList.

I'm fixing it now 👍 Thank for the report.

**Comment by jeanetienne** [comment]
That's what I imagined, thanks for the reactivity!

**Comment by NghiaTranUIT** [comment]
Here is the BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_Mislabel_Blacklist.dmg

I will officially release in next weeks, when Proxyman 1.10.0 comes out 🎉

**Comment by jeanetienne** [comment]
That was fast! Well done!
