### ISSUE TITLE
curl copying should quote the URL

### ISSUE THREAD

**Issue by juri** [ProxymanApp/Proxyman#341]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.9.3

### macOS Version? (Ex. mac 10.14)

10.15.1 (19B88)

### Steps to reproduce 

1. Make a request with query parameters
2. View it in Proxyman
3. Select "Copy cURL" from the context menu
4. Paste the curl command line into [fish] shell

### Expected behavior

The shell executes the command.

### Actual behavior

You get an error: `fish: No matches for wildcard` because fish considers the `?` in the URL a wildcard character.

Proxyman can't go out of its way to accommodate all possible shells, but quoting the URL should be safe with all major shells and would help with fish.

[fish]: https://fishshell.com

**Comment by NghiaTranUIT** [comment]
Hey there, here is the BETA build for this issue: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_cURL_Issues.dmg

The reason why we haven't discovered this trivial bug because we use zsh and it automatically fix it 😱

I will officially release in this week 👍

**Comment by NghiaTranUIT** [comment]
Hey @juri , Proxyman 1.10.0 is out, which includes this fix too 👍 https://github.com/ProxymanApp/Proxyman/releases/tag/1.10.0

Thank you for raising the bug 🐛

**Comment by juri** [comment]
Awesome, thank you! That's a pretty excellent turn around time :-)

**Comment by NghiaTranUIT** [comment]
Glad to hear that ❤️
