### ISSUE TITLE
HTTPS enabled proxying removes whitespace percent encoding from URL Paths

### ISSUE THREAD

**Issue by joshuafinch** [ProxymanApp/Proxyman#342]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 1.9.3

### macOS Version? (Ex. mac 10.14)
macOS 10.15.1

### Steps to reproduce 
1. Enable HTTPS Proxying for a domain
2. Make request with the path containing a whitespace, e.g. `https://example.com/products/Product%20Name`
3. Observe the request URL is rewritten to `https://example.com/products/Product Name` and will be handled differently on the server compared to a normal `%20` encoding for whitespace in endpoint paths.

### Expected behavior
URL to not be rewritten, and to not remove the provided percent encoding when performing requests with HTTPS proxying enabled for a domain.

**Comment by NghiaTranUIT** [comment]
Thank for the report. Let me investigate and sent you a hot fix soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @joshuafinch, @zagahr, Here is the Beta fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_Percent_encoded_path.dmg

Basically, we accidentally remove the percent encoded in the path. We fixed it and will officially release in this week 👍

**Comment by NghiaTranUIT** [comment]
In the meantime, I would keep all Percent-encoded in URL and query in entire the app too, because it makes sense and easier to deal with when we repeat or compose new URL 🌮

**Comment by joshuafinch** [comment]
Thank you @NghiaTranUIT, that appears to be working for us now!

**Comment by NghiaTranUIT** [comment]
Glad to know that work for you 🎉

**Comment by NghiaTranUIT** [comment]
Proxyman 1.10.0 is out, which includes this fix too 👍 https://github.com/ProxymanApp/Proxyman/releases/tag/1.10.0

Thank you for raising the bug 🐛
