### ISSUE TITLE
[BUG] Response in Breakpoint is dismisses immediately when editing

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#344]
## 🐶 Brief
A user reports that the Breakpoint panel is dismisses as soon as the Response Breakpoint occurs.
Let investigate it.

- axios in react.  

## 👑 Criteria
- [ ] The Breakpoint should keep until the message executes.

**Comment by ergunpp** [comment]
Need it asap :)

**Comment by NghiaTranUIT** [comment]
Hey @ergunpp 

Here is the hot-fix BETA build for you: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_Breakpoint_Issues.dmg

Technically, the request has `connection: close` so it close the connection immediately during editing the breakpoint => I override it to `keep-alive` and it works as we expected 🌮 

 Please let me know that if it works for you 👍

**Comment by NghiaTranUIT** [comment]
Hi @ergunpp 

Thank for your support to help me reproduce this issues again. Here is the fix https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.10.0_Fix_Breakpoint_Timeout.dmg

Technically, the response connection is closed due to the timeout from the destination server and make the Breakpoint closes unexpectedly.
