### ISSUE TITLE
[Feature] Vertical Layout

### ISSUE THREAD

**Issue by casperriboe** [ProxymanApp/Proxyman#351]
Hi,

So far using Proxyman is great, especially coming from Charles Proxy.

But one nice feature from Charles that I really miss is the vertical layout aka `Sequence`.

Currently if I'm filtering on a specific endpoint I don't really care about the others in the list, especially since there will be very few (similar) URLs in the list. At this point all I care about is the data that I need to inspect and debug.
With the current horizontally stacked layout there is a lot of space left unused since there is very few URLs because of my filtering. While I realise I can click the Book icon in the upper right-hand corner I still have to arrange the Proxyman windows and don't have both active at the same time. The "master" window will also go into the background and the popup will cast a shadow on the below window.
Another option is to expand the content view on the right, but then I lose valuable information shown for each URL in the rows because the content view goes over the rows.

Looking at this screenshot there is quite a lot of space that could be used for viewing data:
<img width="2672" alt="Screenshot 2019-12-11 at 16 36 01" src="https://user-images.githubusercontent.com/27224040/70636643-2ef76b80-1c36-11ea-8810-842ca65b569d.png">

This is essentially my previous setup with Charles where all the available space can be used for browsing the response.
<img width="2672" alt="Screenshot 2019-12-11 at 16 51 29" src="https://user-images.githubusercontent.com/27224040/70636958-b6dd7580-1c36-11ea-9670-4d27a07c831e.png">

What are your thoughts about this?

Best regards, and thanks for a great app 🙂

**Comment by NghiaTranUIT** [comment]
That's totally make sense. 

I'm working on it (https://github.com/ProxymanApp/Proxyman/issues/348) to bring the Right Panel (Request and Response) to bottom, and it's possible to switch the layout to fit your desires. It's same behavior with Inspector Element view in Google Chrome and Safari where we can optimize the space wisely 👍 

Please Stay tuned in the next release 😄

**Comment by casperriboe** [comment]
Oh, didn't see that one. But sounds great, thanks a lot!

Let me know if you'd like some feedback on it 🙂

**Comment by NghiaTranUIT** [comment]
It's almost done but I have to move it to next release since we have to double check all cases before release 👍 as we revamp some internal components to make it better.

**Comment by casperriboe** [comment]
No worries, we don't want any bugs do we 😉 But its cool that its on its way 🙂

**Comment by NghiaTranUIT** [comment]
Hey @casperriboe, 

Here is the beta build for this layout.

<img width="2032" alt="Screen Shot 2019-12-27 at 21 07 43" src="https://user-images.githubusercontent.com/5878421/71520072-f372c780-28ec-11ea-9657-c7417f6d9cbb.png">

It's possible to switch between "Dock to Bottom" and "Dock to Right" or become Detachable Windows like Google Chrome does for the Inspector tool 🌮 

Give it a try and it would be release in the first week of 2020 🎉

**Comment by NghiaTranUIT** [comment]
Hi there, @casperriboe @bowencool @yauheniprakapenka

Proxyman 1.12.0 is out. Let update directly from the app or download from https://proxyman.io/release/osx/Proxyman_latest.dmg

Thank you guys a lot 👍

**Comment by casperriboe** [comment]
Hi @NghiaTranUIT, sorry for not getting back to your sooner, holidays had me offline 🙂 

This looks fantastic! Exactly what I was missing! Thank you so much for your work 🙏🏻

**Comment by NghiaTranUIT** [comment]
Glad to know that you love it 👍 😄 Enjoy working day 🏊‍♀️
