### ISSUE TITLE
Proxy not switching

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#352]
Hmm i usually don't enable system proxy but today i needed to debug something from firefox.

Firefox is set to use system proxy.

I went to proxyman setting and ticked on Allow  Override in network config

But it is not working

I clicked pause on top left and reenable but still not working.

**Comment by shirshak55** [comment]
i don't see proxy man changing settings in system preference too.

**Comment by shirshak55** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8097377/70707129-90cfd800-1cff-11ea-95c3-1642cd3f9e70.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8097377/70707160-9f1df400-1cff-11ea-9a87-52578b49851d.png">

**Comment by shirshak55** [comment]
and alas suddenly after 5 minute it switches it should be really weird bug lol

**Comment by NghiaTranUIT** [comment]
"Auto override the Proxy Config in Network Preference" -> It doesn't mean that it will override immediately when you enable it. It will enables at the time you launch the app.

I suppose I should improve the text, so there is no mis-understand 😄 

On the other hand, if you would override Proxy, you can do it by Enable Override Setting

![Screen Shot 2019-12-12 at 21 46 51](https://user-images.githubusercontent.com/5878421/70721869-ecfb2200-1d28-11ea-99ba-f1fd37e51ecd.png)

**Comment by shirshak55** [comment]
hmm thats a weird place to place such settings haha :D can u add all settings in one place like IINA etc does haha.

**Comment by shirshak55** [comment]
I think i can close the issue as it seems that was problem and may be i have restarted proxyman and it again overridden the proxy
