### ISSUE TITLE
[BUG] Keep the Connection Alive when intercepting the Response in Breakpoint mode

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#354]
## 🐶 Brief
There is an issue that the server drop the connection after short timeout (2 seconds) and it make the Response Breakpoint disappears.

We should keep the connection even thought the destination connection is closed.

## 👑 Criteria
- [x] The connection should keep alive during intercepting Request/Response (Breakpoint)

**Comment by NghiaTranUIT** [comment]
All done

**Comment by vrnvorona** [comment]
This is old, but I have issue that connection is dropped when intercepting request. When i stop response, it works fine, but when i stop request - my app throws error that connection is closed after ± 2 seconds.
