### ISSUE TITLE
[Feature] Support WebP?

### ISSUE THREAD

**Issue by xuchunyang** [ProxymanApp/Proxyman#356]
When receiving a webp picture, proxyman doesn't show it and says

> Unsupport this image image/webp

so it's likely a known issue.

**Comment by NghiaTranUIT** [comment]
Thank for that. It would be great to support WebP and Binary Hex Previewer together since they're essential tools for debugging. Stay tuned.

**Comment by NghiaTranUIT** [comment]
For now, you can right click on the flow to export the Response body to a Desktop -> Able to see the content.

**Comment by NghiaTranUIT** [comment]
@xuchunyang Here is the BETA build for WebP Support: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.12.0_WebP_Support.dmg

It would be officially released soon 👍 Thank you and Happy New Year 🎆
