### ISSUE TITLE
 Cannot distinguish between 1 and true(or 0 and false) in tree view mode

### ISSUE THREAD

**Issue by yangtaooo** [ProxymanApp/Proxyman#358]
### Proxyman version? 
version 1.11.0

### macOS Version? 
mac OS catalina Version 10.15.1

### Steps to reproduce 
request a Json based Api and view as tree mode.

### Expected behavior
Distinguish numbers from booleans

### Screenshots
![image](https://user-images.githubusercontent.com/9821034/71345596-c054cf00-25a0-11ea-9d01-624ffd3dd5cf.png)

![image](https://user-images.githubusercontent.com/9821034/71345626-dcf10700-25a0-11ea-923b-b4f477dd2c38.png)

**Comment by NghiaTranUIT** [comment]
Thank for report @yangtaooo. I'm on it 🐛

**Comment by NghiaTranUIT** [comment]
Here is the fix @yangtaooo  https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.11.0_Fix_boolean_int.dmg

<img width="563" alt="Screen Shot 2019-12-24 at 10 57 11" src="https://user-images.githubusercontent.com/5878421/71393201-1461c100-263e-11ea-9f01-a6fad2401d5d.png">
<img width="565" alt="Screen Shot 2019-12-24 at 10 57 03" src="https://user-images.githubusercontent.com/5878421/71393202-14fa5780-263e-11ea-8045-eded15cd9db4.png">

We will officially release soon. Thank you in advance 🎄

**Comment by yangtaooo** [comment]
@NghiaTranUIT Nice! And Merry Christmas! 🎄
