### ISSUE TITLE
Breakpoint does not work when answering

### ISSUE THREAD

**Issue by yauheniprakapenka** [ProxymanApp/Proxyman#360]
Proxyman 1.11.0
macOS 10.15.2

**Steps to reproduce** 

1. Right-click on a request
2. In the context menu - Tools - Breakpoint
3. Checkboxes should be: Request, Response and Include subdirectories 
4. Resend the request
5. Breakpoint is triggered, click Execute to request
6. Click Execute to answer
7. Send the request again
8. Breakpoint is triggered, click Execute to request

**Result**: Breakpoint is not triggered to response
**Waiting**: Breakpoint is triggered to response

Video is here:
https://drive.google.com/open?id=1fnHJHcXGeBCgZwtgG7ykwBuF76kGrPdz

**Comment by NghiaTranUIT** [comment]
Thank you for the report 👍 I'm looking on it, it's odd that the response doesn't trigger at the second time.

**Comment by NghiaTranUIT** [comment]
Hey @yauheniprakapenka.

Good news that I fixed your issues in Proxyman 1.13.0 (https://github.com/ProxymanApp/Proxyman/releases/tag/1.13.0). 

Please update it 🥇 Happy New Year 🎆
