### ISSUE TITLE
Decode the value in FormData

### ISSUE THREAD

**Issue by bowencool** [ProxymanApp/Proxyman#362]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.11.0

### macOS Version? (Ex. mac 10.14)
10.15.1

### Steps to reproduce 
send something encoded with `application/x-www-form-urlencoded` content-type

### Expected behavior
![image](https://user-images.githubusercontent.com/20217146/71511132-34a6af80-28cc-11ea-98a4-7f62b4b61f82.png)

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/20217146/71511041-e396bb80-28cb-11ea-98e5-0329b357cfc6.png)

**Comment by NghiaTranUIT** [comment]
Thank for this hidden feature from Charles, I'm on it 👍

**Comment by NghiaTranUIT** [comment]
Here is the Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.11.0_Decode_Precent_Form.dmg

I'm going to officially release in next release in the first week of 2020 🎉

<img width="459" alt="Screen Shot 2019-12-27 at 21 01 59" src="https://user-images.githubusercontent.com/5878421/71519965-56179380-28ec-11ea-9c9a-8ab03143181d.png">
<img width="463" alt="Screen Shot 2019-12-27 at 21 01 34" src="https://user-images.githubusercontent.com/5878421/71519967-56179380-28ec-11ea-84c4-9868056e6bdc.png">

**Comment by shirshak55** [comment]
by the way chrome also support this.

**Comment by NghiaTranUIT** [comment]
All done 👍 

@shirshak55 @bowencool It's has been released 😱
