### ISSUE TITLE
Repeat doesn't preserve query items

### ISSUE THREAD

**Issue by cameroncooke** [ProxymanApp/Proxyman#370]
### Proxyman version? (Ex. Proxyman 1.4.3)

`1.13.1`

### macOS Version? (Ex. mac 10.14)

10.15.3 Beta (19D49f)

### Steps to reproduce 

Repeat a request which has query items.

### Expected behavior

Repeated request should have identical payload and query string as original.

**Comment by NghiaTranUIT** [comment]
Hi @cameroncooke, so far from what I testing with complex Query item and the repeated request:
- They are the same Query item
- Has additionally Header key (Alamofire adds)
- Same Response
=> It's correct behavior 

I'm not sure how can I reproduce your case. Can you give me an example how the Query look like that cause the bug? 🤔

**Comment by cameroncooke** [comment]
I think I've narrowed down the issue, it seems to occur when repeating a
`POST` requests which have query items.
When repeating the query items are converted into form values i.e.
key/value pairs and are moved to the HTTP body and the `Content-Type` is
changed to `application/x-www-form-urlencoded; charset=utf-8`.

I would expect to repeat the request in an identical format. Also, query
items on POST requests are perfectly valid. If you're using `Alamofire` it
would appear it's conveniently or not conveniently trying to be cleaver and
rewrite the request. As a proxy tool for debugging, I would not expect my
requests to be changed in this way.

When testing with Charles it works as expected an identical request is
repeated.

Thanks.

Cameron.

**Comment by NghiaTranUIT** [comment]
Thank for the valuable hint. I'm on it now 👍 Will send you a hot-fix build this weekend 🌮

**Comment by cameroncooke** [comment]
Amazing thank you.

**Comment by NghiaTranUIT** [comment]
Hey @cameroncooke, here is the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.13.1_Repeat_Request_Bug.dmg

I will officially roll out in a next release 👍

**Comment by cameroncooke** [comment]
Hi Nghia, worked a treat, thanks so much for the quick fix.

Cameron.

**Comment by NghiaTranUIT** [comment]
Glad to hear that 👍

**Comment by NghiaTranUIT** [comment]
Just friendly reminder that Proxman 1.14.0 is released https://github.com/ProxymanApp/Proxyman/releases/tag/1.14.0.

Let update it 👍
