### ISSUE TITLE
Couldn't access to proxy.man/ssl

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#371]
## Description
There is a user who reports that his iPhone couldn't access to http://proxy.man/ssl to get the Proxyman certificate after configuring the Proxy in Setting.

Here is the summary:
- iOS 13, macOS 10.14, latest Proxyman 1.13.1
- Proxy settings are correct (from the screenshot)
- **Able to access to the Internet after config Proxy** 
- There is no Remote Device in app 
- Couldn't access to proxy.man/ssl

Since it works on 10.15 so far (tested), we should investigate it, especially, macOS 10.14

## Acceptance Criteria 
- [ ] Double check the root of problem and make sure it works

**Comment by NghiaTranUIT** [comment]
It turns out that his iPhone is automatically connected to NordVPN and it implicitly navigates all traffic to a different road rather than Proxyman's port 9090.

It works again if we disable the VPN.

Glad to close this ticket 👍

**Comment by flyer2001** [comment]
sorry to bother you, the problem was due to a third party Endpoint Security VPN app

**Comment by longhoangwkm** [comment]
I can't connect too, I don't have any VPN setup. 
- My phone able to access to the Internet after config Proxy
- IP config is as same as Mac IP

**Comment by NghiaTranUIT** [comment]
Hey @longhoangwkm there are various reasons why you couldn't access Proxyman. Please check out troubleshooting https://docs.proxyman.io/troubleshooting/my-ios-devices-couldnt-connect-to-proxyman-via-proxy 

From what you're described, can you check the Firewall?

**Comment by NghiaTranUIT** [comment]
If you're able to access the Internet after config Proxy to Proxyman: Do you see the traffic in Proxyman app (for instance: Open Safari on iPhone and visit google.com)?

**Comment by longhoangwkm** [comment]
@NghiaTranUIT Yes, I saw it
![Image from iOS (3)](https://user-images.githubusercontent.com/34698136/106411967-20db5e80-6479-11eb-8bb9-7d6d71c81ba7.jpg)
![IMG_6945](https://user-images.githubusercontent.com/34698136/106411998-305aa780-6479-11eb-9071-7b2f276a04e7.jpg)
![IMG_6946](https://user-images.githubusercontent.com/34698136/106412003-32bd0180-6479-11eb-9524-e7a3b0ee6cc6.PNG)
![IMG_6947](https://user-images.githubusercontent.com/34698136/106412006-351f5b80-6479-11eb-8a1b-b1d82d12c3fb.PNG)
<img width="621" alt="iPhone_Setup_Guideline" src="https://user-images.githubusercontent.com/34698136/106412008-35b7f200-6479-11eb-85c1-01fdad25b546.png">

**Comment by NghiaTranUIT** [comment]
Thanks for the detailed screenshots.

It's odd that you're able to proxy to Proxyman, but couldn't open http://proxy.man/ssl

To workaround, please help me:
1. Open Proxyman macOS app
2. Open Safari on macOS, and try to open http://proxy.man/ssl => To see if you're able to access it on your macOS machine
3. If it's possible, you can download the certificate 
4. Right-click on the downloaded certificate -> Share -> AirDrop -> Select your iPhone
5. At the stage, the certificate will appear in the Setting app -> Downloaded Profiled and you can proceed (Trust the certificate in General Tab)

**Comment by NghiaTranUIT** [comment]
I just tested it on my iPhone, and I'm able to download the certificate in http://proxy.man/ssl . I'm not sure what blocks the connection in your device 🤔 @longhoangwkm

**Comment by longhoangwkm** [comment]
@NghiaTranUIT Ops, I can't access proxy.man/ssl on macOS safari. It seem have some trouble about DNS ?. Is there `http://proxy.man/ssl`will be decode to  `192.168.1.124:9090/ssl`. I tried a both but not works

**Comment by NghiaTranUIT** [comment]
Look like it's an edge case where Proxyman Local Service (http://localhost:10090) is blocked by some services in your comany.

Basically, when you open `http://proxy.man` or `http://proxy.man/ssl`, Proxyman will redirect you to `http://localhost:10090` where you can download the certificate

Please help me:
1. Open Proxyman app
2. Open Safari on macOS, and visit `http://localhost:10090`
3. See if you can access the page like the following screenshot or not

<img width="1300" alt="Screen Shot 2021-02-01 at 10 59 29" src="https://user-images.githubusercontent.com/5878421/106413489-c217e400-647c-11eb-9df4-1f268956f738.png">

5. If yes, you can download and share to iPhone by AirDrop

### Alternative
If you are not able to access `http://localhost:10090` from your macOS, you can manually get the certificate at `~/.proxyman/proxyman-ca.pem` -> Then sharing to your iPhone by AirDrop

**Comment by longhoangwkm** [comment]
@NghiaTranUIT, Thanks for your kind support, I have installed it by airdrop way. Hope you can find the root soon!

**Comment by NghiaTranUIT** [comment]
Thanks @longhoangwkm . You're welcome. When you're at home or not using corporation wifi -> Please try again by normal steps (open http://proxy.man/ssl in your iPhone after setting the Proxy) to see if it works or not.

I believe that some services in your corporation wifi accidentally block it but I could not reproduce it atm.

Thank you in advance 🌮

**Comment by longhoangwkm** [comment]
I will try to test at home and let you know result
