### ISSUE TITLE
How time support  Binary Preview 

### ISSUE THREAD

**Issue by guoeq** [ProxymanApp/Proxyman#372]
How time support  Binary Preview

**Comment by NghiaTranUIT** [comment]
Actually, Hex view for Binary Preview is already implemented in BETA build. Ticket https://github.com/ProxymanApp/Proxyman/issues/369

It gonna release in a next release phase 👍 

I'm uploading and send you soon.

**Comment by NghiaTranUIT** [comment]
@guoeq Here is the beta build for Hex view: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.13.1_HexView.dmg

Basically, you can switch to Hex mode from Body Panel :hex

**Comment by NghiaTranUIT** [comment]
Hex Previewer is out with Proxyman 1.14.0 https://github.com/ProxymanApp/Proxyman/releases/tag/1.14.0 🎉
