### ISSUE TITLE
Ambiguous SSL certificate error

### ISSUE THREAD

**Issue by cameroncooke** [ProxymanApp/Proxyman#374]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.13.1 (11310)

### macOS Version? (Ex. mac 10.14)

macOS Catalina 10.15.3 Beta (19D49f)

### Steps to reproduce 

1. Execute a request which the server aborts or where it timeout with no response.
2. Note that Proxyman shows "Missing SSL certificate from iOS simulator"

### Expected behavior

Couple of thoughts on this one.

1. There is no guarantee this request came from an iOS Simulator, in my example above it didn't. 
2. The message is ambiguous in that the issue was that the request timed out or was aborted by the API server not that there was a SSL certificate issue.

### Screenshots (optional)

<img width="422" alt="Screenshot 2020-01-13 at 08 50 54" src="https://user-images.githubusercontent.com/630601/72243417-cd833d80-35e3-11ea-86fe-8644d40367b8.png">

**Comment by NghiaTranUIT** [comment]
Thank for that. It's definitely a bug 👍 On the way to squash them 🐛

**Comment by NghiaTranUIT** [comment]
Fixed 🤚
