### ISSUE TITLE
URL parts are missing if the URL contains double slashes (//) after the host part

### ISSUE THREAD

**Issue by tiwood** [ProxymanApp/Proxyman#376]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.13.1

### macOS Version? (Ex. mac 10.14)

10.15.2

### Steps to reproduce

I'm tying the request the following:

`https://foobar.vault.azure.net//secrets?api-version=7.0`
Notice the double `/` which gets added by the CLI command (I can't change that).

The requests fails, as the `/secrets` seems to get stripped from the uri:

![screenshot_2020-01-21_11-03-10](https://user-images.githubusercontent.com/6249819/72795317-b83e8c80-3c3d-11ea-9ef9-37e7025bc614.png)

### Expected behavior

The uri should be as provided:
`https://foobar.vault.azure.net//secrets?api-version=7.0`

The same requests works in `Charles Proxy`:

![screenshot_2020-01-21_11-06-51](https://user-images.githubusercontent.com/6249819/72795556-28e5a900-3c3e-11ea-8550-5e8790deab56.png)

Note: The `401` response is expected.

**Comment by NghiaTranUIT** [comment]
Thank for the report 👍 It's the first time I see double splash `//` in the URL.

I'm on it now 🥇

**Comment by NghiaTranUIT** [comment]
Hey @tiwood, here is the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.13.1_Fix_Double_Slashes.dmg

<img width="2032" alt="Screen Shot 2020-01-21 at 20 50 50" src="https://user-images.githubusercontent.com/5878421/72810284-d2a15600-3c8f-11ea-9d51-dab062a933e2.png">


I will rollout the stable build soon. Thank you so much for the bug report 💯

**Comment by NghiaTranUIT** [comment]
Just friendly reminder that we officially release the fix on Proxyman 1.14.0 (https://github.com/ProxymanApp/Proxyman/releases/tag/1.14.0)

Let check it out. Thank you in advance 💯

**Comment by tiwood** [comment]
@NghiaTranUIT, I've just tried it, it works like a charm!

Thank you for your fast support, I will recommend Proxyman to my coworkers for sure!

**Comment by NghiaTranUIT** [comment]
Glad to hear that 👍 and appreciate your reference for Proxyman too 😄
