### ISSUE TITLE
Empty response body can't be changed

### ISSUE THREAD

**Issue by ArtemeeSenin** [ProxymanApp/Proxyman#381]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.14.0
### macOS Version? (Ex. mac 10.14)
OSX 1.15.2
### Steps to reproduce 
- Add breakpoint on any url
- Send put request on matching url
- Wait for response
- Body in response is empty, status 200
- No body tab is present (only header, other)
### Expected behavior
- Empty body tab is present. Can be edited with some content to be returned in response

**Comment by NghiaTranUIT** [comment]
If the body is empty, there is not body tab to edit. I'm fixing it now 🙌

**Comment by NghiaTranUIT** [comment]
Hey @ArtemeeSenin, here is the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.14.1_Breakpoint_Empty_Body.dmg

Let check it out 🤚 

I will push it in next release 👍 Thank you so much 🌮

**Comment by ArtemeeSenin** [comment]
Hello @NghiaTranUIT, thank you a lot for such a quick answer and fix!

Have a nice day :)
