### ISSUE TITLE
Trailing slashes are removed when sending modified URLs with trailing slashes

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#382]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.14.1 (11410)
### macOS Version? (Ex. mac 10.14)
macOS 10.14.6
### Steps to reproduce 

I've noticed that when editing a URL to add a new path, my trailing slash (required by our API) is getting dropped when it's sent. If I end the new path with double slashes (//) the request is sent with the expected single slash.

This isn't something I've done previous to 1.14.1, so I don't know if this is a new bug, but I noticed [Issue 376](https://github.com/ProxymanApp/Proxyman/issues/376) addressed an issue with double slashes and I wonder if perhaps this is a regression due to that change?

1. Right-click on a valid request and choose **Edit and Repeat...**
2. Modify the URL by adding and additional path to the end, e.g.:
   * original request: https://example.com/endpoint/
   * modify to: https://example.com/endpoint/path/
3. Send the modified request
4. Find the result and view the URL of the request
5. Observe the user entered trailing slash has been removed
### Expected behavior
Full user entered path is sent

**Comment by NghiaTranUIT** [comment]
Hey @crankygeek, it looks like the behavior is not correct for composing the request with an extra slash. I'm looking on it and other tickets too 👍 

Thank for raising them 🥇

**Comment by NghiaTranUIT** [comment]
Hey @crankygeek let try a BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Trailing_Slash_Missing.dmg

Sorry for being late, I forgot it 😢. It's done now 👍 

Thank you for reporting

**Comment by crankygeek** [comment]
@NghiaTranUIT Looks good in 1.18.0.

I also tested by adding double slashes at the end and I see the extra slash isn't removed. I think this is fine, since it's entered by the user and should be honored, but thought I'd mention it since it was in my initial report.

**Comment by NghiaTranUIT** [comment]
Yup, I test around other apps and it would be better to keep whatever the user enter 😄 
In the past, I fixed the bug where this weird URL: www.myapi.com//version?tag=1.0. All slashes must be retained 👍
