### ISSUE TITLE
Support for External Sock 5 Proxy

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#385]
Sock 5 is an very easy protocol to implement with tons of libraries. I am sure that adding socks external proxy would be very helpful.

**Comment by NghiaTranUIT** [comment]
To admit, I've heard the term "SOCK" but I have no idea what is different with HTTP/HTTPS Proxy 😅

Let me do a research 👍

**Comment by shirshak55** [comment]
@NghiaTranUIT its similar to http proxy. You can use openssh for testing it

**Comment by JasonBoy** [comment]
any updates?

**Comment by NghiaTranUIT** [comment]
Sorry @JasonBoy, I did a research about SOCK5 but I'm not sure how to actually implement it into the app 😿

I will keep this ticket open and come back in near future soon 👍

**Comment by Brontojoris** [comment]
I too am interested in this feature. 

Use case for me is:

Mac Development Machine with Charles Proxy > External Proxy > Second Mac with Charles + Open VPN connection to Remote location.
Mac Development machine can connect to remote location, while also being able to inspect local network traffic.

When I try the same setup with Proxy Man on Mac Development machine, it doesn't work.

I compared the settings, and the difference is that Charles Proxy is configured to use External SOCKS proxy.

**Comment by NghiaTranUIT** [comment]
Just wondering @Brontojoris, If you disable SOCKS Proxy on Charles Proxy. Does it work? 🤔

**Comment by Brontojoris** [comment]
It doesn't work if I disable SOCKS proxy. 

In fact, when using Charles on Mac Development Machine > External Proxy > Second Mac with Charles + Open VPN connection, I need to make sure that HTTP/HTTPS external proxy is disabled, and only SOCKS proxy is enabled, or it doesn't work.

The whole setup is quite delicate.

**Comment by NghiaTranUIT** [comment]
Thanks for the hint. Our team is working on this feature 👍

**Comment by NghiaTranUIT** [comment]
Hi @Brontojoris, I'm working on the SOCKS External Proxy, and I have a question:

As you mention in your previous comment: On `Second Mac with Charles + Open VPN`, do you enable SOCKS Proxy in Proxyt Menu -> Proxy Setting? (Screenshot)

<img width="704" alt="Screen_Shot_2021-07-09_at_17_06_31" src="https://user-images.githubusercontent.com/5878421/125062050-3021a080-e0d8-11eb-91e7-b9296879c153.png">

**Comment by NghiaTranUIT** [comment]
Hey @Brontojoris @JasonBoy @shirshak55, if you don't mind, please check this Beta build:  https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.29.0_SOCKS_Proxy_for_External_Proxy.dmg

Proxyman supports SOCKS Proxy as an External Proxy (Tools Menu -> Proxy Setting -> External Proxy)👍 

<img width="677" alt="Screen Shot 2021-07-13 at 21 52 21" src="https://user-images.githubusercontent.com/5878421/125473968-48debc53-9a27-4162-aee3-bf01f368d9d1.png">

### How to test
1. Change the SOCKS Proxy to your External Proxy server and see if it works.

If you don't have a SOCKS Proxy Server, we can open Charles Proxy, enable SOCKS mode at port 8889. Open Proxyman and change the SOCKS to 8889 and test it.

Thanks in advance 😄

**Comment by Brontojoris** [comment]
Amazing! Working perfect for me! Thanks very much for such a quick turnaround

**Comment by shirshak55** [comment]
@NghiaTranUIT  to add more for socks proxy we can just use ssh server. My second comment or third comment address this :D

**Comment by RedWolfChao** [comment]
If Proxyman's socks work requires charles's assistance, How does it work on Socks independently

**Comment by shirshak55** [comment]
I think this feature is done? Closing it

**Comment by RedWolfChao** [comment]
@NghiaTranUIT Thanks

**Comment by nonameplum** [comment]
Is it some kind of bug that when I turn on SOCKS in the Proxyman and when I run Proxy man and verify the Network setup in the macOS settings, SOCKS are disabled (do I have to enable then each time manually to truly make it work?)
<img width="1342" alt="Screenshot 2022-12-20 at 12 50 40" src="https://user-images.githubusercontent.com/1753816/208660454-5c68c768-0798-49e8-a099-e5df2b14494e.png">

In comparison if I enable SOCKS in Charles and run it and can verify that it automatically enables SOCKS in the macOS's settings:
![Screenshot 2022-12-20 at 12 53 15](https://user-images.githubusercontent.com/1753816/208660941-4411d8bd-e67e-4366-a18c-fa5abf980750.png)

**Comment by NghiaTranUIT** [comment]
@nonameplum I've answered your question in this comment: https://github.com/ProxymanApp/Proxyman/issues/1472#issuecomment-1360612078
