### ISSUE TITLE
[Feature Request] Map Remote

### ISSUE THREAD

**Issue by thang-nm** [ProxymanApp/Proxyman#395]
I really like Charles's Map Remote feature (https://www.charlesproxy.com/documentation/tools/map-remote/).
So can you add this feature to Proxyman?
Thank you!

**Comment by NghiaTranUIT** [comment]
Yup, since we just support Map Local from Local Directory, Remote Map is in progress now 🙌 I will notify you when it releases a BETA build 🌮

**Comment by NghiaTranUIT** [comment]
It's 80% done, but I have to move to next release 1.18.0 🤚

**Comment by thang-nm** [comment]
So sad to hear that, but it's worth to wait!
I can get rid of Charles soon! Thank you!

**Comment by NghiaTranUIT** [comment]
The reason is that I am going to ship 1.17.0 with bunch of improvement and hot-fix bugs tonight or tmr. So Remote Map would be finalized in the next release 🙌

**Comment by NghiaTranUIT** [comment]
Hey @thang-nm @finnsch @slang25

Let check out this BETA build with Map Remote: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Map_Remote.dmg

Basically, we're able map:
- From Localhost -> To Production
- From Production -> To Localhost 
It's easier to app/web development
 
I will officially release tmr 👍 

<img width="1271" alt="Screen Shot 2020-03-08 at 23 30 43" src="https://user-images.githubusercontent.com/5878421/76167085-adf93300-6196-11ea-93b2-1fa9b2211daa.png">

<img width="1185" alt="Screen Shot 2020-03-08 at 23 30 40" src="https://user-images.githubusercontent.com/5878421/76167083-a9cd1580-6196-11ea-8f37-3d3483336b61.png">

**Comment by thang-nm** [comment]
Thank you @NghiaTranUIT.
Remote Map is great, but I feel like is something is wrong, but it's hard to explain!
Something different to the Charles.
And also, i found some bugs:
- It can't keep the latest window size and position.
- URL area is too big.
<img width="661" alt="Screen Shot 2020-03-09 at 9 33 50 PM" src="https://user-images.githubusercontent.com/7601352/76222850-be201980-624d-11ea-9656-01b5a0b513e8.png">

**Comment by NghiaTranUIT** [comment]
hey @thang-nm , which macOS version are you in?

**Comment by thang-nm** [comment]
@NghiaTranUIT My Mac runs Catalina 10.15.3.

**Comment by NghiaTranUIT** [comment]
I couldn't reproduce the URL Bug unfortunately : /

Can you try to Dock to Right and let see if it still happen?


<img width="1727" alt="Screen_Shot_2020-03-09_at_21_39_01" src="https://user-images.githubusercontent.com/5878421/76225330-ed835600-624e-11ea-871e-a75e8af89bf7.png">

**Comment by thang-nm** [comment]
I tried, but it became bigger :(
My screen resolution is 1440x900.
<img width="1405" alt="Screen Shot 2020-03-09 at 9 50 59 PM" src="https://user-images.githubusercontent.com/7601352/76226350-54553f00-6250-11ea-85a2-78359451c75a.png">

**Comment by thang-nm** [comment]
Hey @NghiaTranUIT, It's is not bug. It's a feature. I know why now :D

**Comment by NghiaTranUIT** [comment]
Sorry for that. 

This URL layout is changed from the previous build, which is 1.17.1, and I don't heard any feedback about this weird bug.

1. Which version was you in before updating to 1.18.0? 🤔 
2. Can you help me to reset by Help -> Advanced -> Reset all Data & Cert

**Comment by thang-nm** [comment]
Thank @NghiaTranUIT, it happens when I resize Request & Response frames.
But I think if the whole URL is shown, the URL area will not be resized.
![Screen Recording 2020-03-09 at 10 20 35 PM 2020-03-09 22_22_40](https://user-images.githubusercontent.com/7601352/76229745-4229cf80-6255-11ea-8804-a70b388a1692.gif)

**Comment by NghiaTranUIT** [comment]
Thank for the GIF, I will investigate this way 👍

**Comment by thang-nm** [comment]
Hey @NghiaTranUIT, I know why Remote Map different from Charles.
The reason is ProxyMan sends request without body data!

**Comment by NghiaTranUIT** [comment]
I'm able to reproduce the bug. It only happen if we select Horizontal Layout in Preference.

@thang-nm to work around, please select Vertical in Preference and all's good 👍

**Comment by NghiaTranUIT** [comment]
Hm. let me check the Remote Map again. Do you have any URL that I could test?

**Comment by NghiaTranUIT** [comment]
@thang-nm I'm able to reproduce the bug on Map Remote, which the body is missing. I'm working on it and submit a hotfix build tonight and tmr 🤚

**Comment by thang-nm** [comment]
Thank you, @NghiaTranUIT.

**Comment by thang-nm** [comment]
And also, can you parse URL when I paste whole URL to "Host" field and fill out the other fields?

**Comment by NghiaTranUIT** [comment]
You can do it by, right-click on this request on the list to open the Menu Context -> Tool -> Map Remote -> It will automatically parses into those fields.

But, the idea is great to do it. Take note 👍

**Comment by NghiaTranUIT** [comment]
@thang-nm let update to 1.18.1 build. I fixed it 🙌 

Please let me know if it works for you

**Comment by thang-nm** [comment]
It works like a charm! Thank you! 🎉

**Comment by NghiaTranUIT** [comment]
Awesome. Thank you so much for this serious bug report 🍻

**Comment by NghiaTranUIT** [comment]
Hey @thang-nm 

Regarding your bug: https://github.com/ProxymanApp/Proxyman/issues/395#issuecomment-596581232, Let check out the BETA build at https://github.com/ProxymanApp/Proxyman/issues/436#issuecomment-599035661

Thank you 👍

**Comment by thang-nm** [comment]
That's great. I will check it soon. Thank you.
And i have another small feature request:
Can you add the display as web option if response content is HTML?

**Comment by NghiaTranUIT** [comment]
Hey @thang-nm 

Let check out the latest build https://github.com/ProxymanApp/Proxyman/releases/tag/2.2.0

You can add the WebView tab from Tools menu -> Custom Previewer Tab. It will render the webpage if the content is HTML 👍

**Comment by thang-nm** [comment]
Love it 🌹
Thank yo so much!
