### ISSUE TITLE
[BUG] Ctrl+Click is not recognised as a secondary click

### ISSUE THREAD

**Issue by josshad** [ProxymanApp/Proxyman#399]
### Proxyman version
1.16.0

### macOS Version?
10.14.6

### Steps to reproduce 
1. Open app
2. Ctrl + Click on item in "Source list" or "Flow list"
3. Incorrect menu popover is presented

### Expected behaviour
Ctrl + Click has same behaviour as secondary click (Click with two fingers)

### Screenshots 
* Ctrl + Click in the source list shows only the "New folder" item
<img width="256" alt="Screenshot 2020-02-13 at 19 11 13" src="https://user-images.githubusercontent.com/755348/74454437-f291f700-4e94-11ea-9610-2e244160ff2a.png">

* Ctrl + Click in the flow list shows all items in disabled state
<img width="342" alt="Screenshot 2020-02-13 at 19 11 24" src="https://user-images.githubusercontent.com/755348/74454318-c24a5880-4e94-11ea-8d94-d13cb87d6540.png">

* Ctrl + Click in request viewer shows all items in disabled state
<img width="400" alt="Screenshot 2020-02-13 at 19 15 25" src="https://user-images.githubusercontent.com/755348/74454676-47357200-4e95-11ea-8950-263ccee49126.png">

**Comment by NghiaTranUIT** [comment]
Thank for the report. I'm not aware why Ctr+click doesn't work.

Let me fix it 🙌

**Comment by NghiaTranUIT** [comment]
Hi @josshad, here is the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.16.0_Menu_Context_Bug.dmg

I will rollout in the next release. Thank you so much 👍
