### ISSUE TITLE
Support deflate compression

### ISSUE THREAD

**Issue by doubleday** [ProxymanApp/Proxyman#400]
gzip compression works fine but Proxyman does not seem to support deflate.

### Proxyman version? (Ex. Proxyman 1.4.3)
1.16.0
### macOS Version? (Ex. mac 10.14)
10.14.6
### Steps to reproduce 
Call a service that uses deflate as response encoding
### Expected behavior
Show the uncompressed response in the response tab
### Example Log
[deflatenotsupported.proxymanlog.zip](https://github.com/ProxymanApp/Proxyman/files/4225680/deflatenotsupported.proxymanlog.zip)

**Comment by NghiaTranUIT** [comment]
Thank for the report @doubleday. Proxyman is currently supported all type of encoding, but I'm not sure why it doesn't decode `deflate` properly.

Let me investigate it 👍

**Comment by NghiaTranUIT** [comment]
Hey @doubleday, let try this BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.16.0_Decode_deflate.dmg

I will officially ship in the next release 👍 

<img width="1840" alt="Screen Shot 2020-02-19 at 23 52 15" src="https://user-images.githubusercontent.com/5878421/74855195-f29d6580-5372-11ea-93ad-65a44108de69.png">

**Comment by doubleday** [comment]
Just tested it and it works 👍

Thanks!
