### ISSUE TITLE
"Clear" button does not reset the count in the left pane

### ISSUE THREAD

**Issue by kspeeckaert** [ProxymanApp/Proxyman#405]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 1.16.0
### macOS Version? (Ex. mac 10.14)
Mac OS X 10.15.3
### Steps to reproduce 
- Launch app
- Wait for events to come in
- Click the _Clear_ button at the bottom
### Expected behaviour
- The numbers in the left pane should reset to 0, as the corresponding entries have been erased.
### Screenshots (optional)
<img width="1589" alt="0C34F456-49E8-4984-8DC6-EDEFCD423D7A" src="https://user-images.githubusercontent.com/6348619/75109306-471a3c80-5622-11ea-92d3-975a53c5f6a1.png">

**Comment by NghiaTranUIT** [comment]
Hey there, the `11` number is the number of its sub-nodes, not the number of total flows in this Folder. As a result, the clear button doesn't reset the count.

If you would to remove the sub-nodes, you can expand the folder, select all, and hit Delete. The number will be reset 👍

**Comment by kspeeckaert** [comment]
Thanks for the clarification. But it feels a little counter-intuitive as I expected the left pane to be a (structured) representation of the right pane. 

When the right pane is cleared by pressing the _Clear_ button, there are indeed sub-nodes as you mentioned. Expanding those will show e.g. the applications and beneath that the domains they accessed. But when I select any of them, there isn't anything showing up on the right anymore (as I cleared them earlier). So I'm a little lost as to what the point is of keeping them and having to delete them manually.

Don't get me wrong, I think the structuring on the left is an excellent idea as it gives a clear oversight and an easy way to filter specific apps/domains, but I would've expected the left and the right pane to stay in sync.

Let me clarify the workflow I had in mind: if I want to quickly clear the current data (e.g. imagine having started Proxyman, but it already started capturing network traffic before you had your test case ready, or if you are between test cases and want to "reset" the current data), I have to:

1. press _Clear_
1. expand _Apps_, select all entries below and delete them
1. expand _Domains_, select all entries below and delete them

The alternative is to open a new tab and leave the current one open or close it.

**Comment by kspeeckaert** [comment]
While I was playing around with the left pane, I noticed a discrepancy when using the _Clear_ button having an application selected. To clarify things, I made a [screen recording](https://imgur.com/Dn575mS). 

You'll notice that when clearing the entries while having an app selected, going back to the _All_ top node will reveal all entries again.

**Comment by NghiaTranUIT** [comment]
> You'll notice that when clearing the entries while having an app selected, going back to the All top node will reveal all entries again.

It's the problem we're facing too. Technically:
- Each node (Folder, Node, Domain, ....) maintains an array of flows
- When a new flow (Request) is initialized. It will append too the parent Node, All Folder for instance, then going through all sub-nodes. If this flow is matched, it's added to this node and pass through to its sub-nodes.

=> It's for performance purpose. As we select any node, it will **immediately** render the array of flows without accumulating flows from sub-nodes.

For that reason, when we clear the array of flows in particular sub-nodes. It's a heavy task to go back to the parent and remove it from the array if we have 1000-2000 flows (usual cases).
As a result, we consider removing the flows in this node, but not for the parent => The `All folder` still have it.
