### ISSUE TITLE
Application window resizes outside screen dimensions for large URLs

### ISSUE THREAD

**Issue by iandol** [ProxymanApp/Proxyman#410]
### Proxyman version? (Ex. Proxyman 1.4.3)
V1.16
### macOS Version? (Ex. mac 10.14)
10.15.3
### Steps to reproduce 
When I select an item with a very long URL, the whole window resizes outside the screen height, and the request/response panels and the bottom search bar disappear from view. screenshot1.jpg shows this, red lines are the screen size outline. Then clicking on an item with a small URL and the window is still much taller than screen height, and I have to drag the window bar title down to cause the window to snap back to a correct size (screenshot2.png)

### Expected behavior
Large URLs do not break the UI.

### Screenshots (optional)
![screenshot1](https://user-images.githubusercontent.com/153905/75148838-8daf8a00-573b-11ea-9fe2-980913aed692.jpg)

![screenshot2](https://user-images.githubusercontent.com/153905/75148851-9902b580-573b-11ea-8462-53b3ce5e9ddb.png)

**Comment by NghiaTranUIT** [comment]
Wow, it's a huge URL I have seen 😱

I will improve it by:
- Set a maximum height when expanding the URL (80% or something)
- Automatically restore to the previous position if we select the normal URL -> So, We don't need to drag back again.

**Comment by NghiaTranUIT** [comment]
Hey @iandol , let check this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.16.0_Fix_Layout_Long_URL.dmg

Basically, I add some constraints and set minimum height for those views to make sure the layout doesn't break.

<img width="927" alt="Screen Shot 2020-02-25 at 00 07 08" src="https://user-images.githubusercontent.com/5878421/75175264-98cae000-5764-11ea-91b7-d432767b7a45.png">

Please let me know if it works for you 🙌 🌮

**Comment by iandol** [comment]
First off, thanks for a brilliant and wonderfully designed app! Seconds, thanks for such a speedy reply!!

This build is much better with requests and panels always present, although the bottom bar is still disappearing:

Before long URL:
![1_SML](https://user-images.githubusercontent.com/153905/75206343-29c7a880-57b1-11ea-8465-f158e3d05883.png)

With long URL, notice the bottom search bar is missing:
![2_SML](https://user-images.githubusercontent.com/153905/75206365-3946f180-57b1-11ea-9158-4e074296cb50.png)

Back to a small URL, bottom bar still missing:
![3_SML](https://user-images.githubusercontent.com/153905/75206407-4d8aee80-57b1-11ea-9a8b-7cc3d3add299.png)

**Comment by NghiaTranUIT** [comment]
Thank. Let us double check and fix the case 🙌

**Comment by NghiaTranUIT** [comment]
@iandol let check this v2 build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.16.0_Fix_Long_URL_v2.dmg

I reduce the Compression Priority from the URL TextField to prevent it pushes the Bottom Bar 👍
 
GIF: https://imgur.com/gallery/xqVUt5B

**Comment by iandol** [comment]
Works great, thank you!!! Is it included in the new release yet?

**Comment by NghiaTranUIT** [comment]
Yup, it's fixed in 1.17.0 and 1.17.1 too 🙌 

Thank you for reporting the bug 🌮
