### ISSUE TITLE
Why can't I access the internet using Safari while Proxyman app is denied to connect to proxyman.io servers?

### ISSUE THREAD

**Issue by jm4rc05** [ProxymanApp/Proxyman#413]
### Steps to reproduce: 
1. OPT-OUT TO COLLECT DIAGNOSTICS DATA OR WHATEVER
2. *BLOCK ACCESS TO PROXYMAIN.IO FROM PROXYMAN APP*
3. *WHILE PROXYMAN APP IS RUNNING*
4. TRY TO ACCESS ANY SITE USING SAFARI

### Expected behavior: 
NO CONNECTION TO PROXYMAN.IO SERVERS 
ACCESS TO EVERYTHING ELSE WORKING AS EXPECTED

**Comment by NghiaTranUIT** [comment]
Hi there, How can you "BLOCK ACCESS TO PROXYMAIN.IO FROM PROXYMAN APP" 🤔 

- Do you mean that using app like AdGuard to block all connections from specific app?
- Or you mean the Black List Tool in Proxyman?

**Comment by NghiaTranUIT** [comment]
Technically, here is how Proxyman works:
1. Proxyman opens the local server at 9090, and act like Man-in-the-middle. 
2. Proxyman overrides the HTTP/HTTP Setting in Network.prefPane from you computer
3. All traffic from your device will go thought Proxyman 9090 and then forwarding to the destination server.
Similar approach like Charles Proxy and Fiddler. There are no traffic to Proxyman.io server at all (Unless License Validation and Get Update build APIs).

Can you help me to double check the HTTP Proxy Setting? Is it point to 9090?
<img width="780" alt="Screen Shot 2020-02-25 at 23 00 42" src="https://user-images.githubusercontent.com/5878421/75264889-aba3ea00-5822-11ea-8442-bac557afb4dc.png">

**Comment by jm4rc05** [comment]
Sorry for not responding sooner...

I confirm that you're right!!! In my hurry I overlooked the network settings and got overzealous about non existing security issues!

Greate work!

Cheers and apologies once more.
