### ISSUE TITLE
[Enhancement] Allow version to be copiable

### ISSUE THREAD

**Issue by patrickbdev** [ProxymanApp/Proxyman#414]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.17.1 (11710)

### macOS Version? (Ex. mac 10.14)
10.15.3 (19D76)

### Steps to reproduce 
1. Click Proxyman in Menu Bar
1. Click About Proxyman

### Expected behavior
Be able to copy version number

### Screenshots (optional)
![About Proxyman](https://i.imgur.com/4s3kBbe.png)

### Comparison
Open up "About This Mac" and you'll see you're able to copy the version.
![About This Mac](https://i.imgur.com/OJmb8tn.png)

### Benefits?
Every time needing to create an issue we need to write the version manually :/

**Comment by NghiaTranUIT** [comment]
Consider it's done 🙌

**Comment by patrickbdev** [comment]
Thank you!
