### ISSUE TITLE
[Enhancement] Allow option to turn off word wrapping

### ISSUE THREAD

**Issue by patrickbdev** [ProxymanApp/Proxyman#415]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.17.1 (11710)

### macOS Version? (Ex. mac 10.14)
10.15.3 (19D76)

### Steps to reproduce 
1. View any scroll view with text (especially in request and response bottom layout)

### Expected behavior
Be able to toggle word wrap off. Word wrap can make text be much harder to read.

**Comment by NghiaTranUIT** [comment]
That totally make sense. Let me research other apps to see how it handles this case, in favor of char wrap or word warp.

Btw, thank you for bringing it up 🎉

**Comment by NghiaTranUIT** [comment]
Just wondering, if we turn off word warp. So the long line doesn't go to the second lines, and it cuts off by the width of the view. How can you read it?

Can you show me the screenshot where you see that it's hard to read 🤔 @patrickbdev

**Comment by NghiaTranUIT** [comment]
### Word warp
<img width="525" alt="Screen Shot 2020-02-26 at 09 20 54" src="https://user-images.githubusercontent.com/5878421/75305689-66f76d80-5879-11ea-88bf-50638df6f9a8.png">

### Char Warp
<img width="458" alt="Screen Shot 2020-02-26 at 09 21 23" src="https://user-images.githubusercontent.com/5878421/75305680-62cb5000-5879-11ea-94aa-f127ff2f62f8.png">

It's obvious that Word Warp is better 🤚

**Comment by patrickbdev** [comment]
Thanks for looking into this @NghiaTranUIT 

The best example is a response body in something like XML or JSON.
When you're on small screens or wanting to tile your screens, it's handy to be able to retain the indented structure (even if you need to scroll).

<img width="376" alt="image" src="https://user-images.githubusercontent.com/11362913/75309919-8a84dd00-58a6-11ea-8981-60a36aa5423d.png">

**Comment by NghiaTranUIT** [comment]
Thank you for the screenshot. I understand your situation.
I see some apps, which offer this option in Preference to turn the Word Warp off. and It's possible to disable Word Warp in CodeMirror too.

I will add it 🙌

**Comment by NghiaTranUIT** [comment]
Let check this BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Word_Warp.dmg
- Able to on/off the Word Warp in Body Previewer.

<img width="672" alt="Screen Shot 2020-02-27 at 11 20 46" src="https://user-images.githubusercontent.com/5878421/75412294-9f1fae80-5954-11ea-8932-6ba1875813ed.png">
<img width="475" alt="Screen Shot 2020-02-27 at 11 20 48" src="https://user-images.githubusercontent.com/5878421/75412306-a34bcc00-5954-11ea-9999-7adf4dc6167d.png">
<img width="471" alt="Screen Shot 2020-02-27 at 11 20 53" src="https://user-images.githubusercontent.com/5878421/75412307-a3e46280-5954-11ea-9343-89a9d8fc880a.png">

**Comment by patrickbdev** [comment]
Works perfectly, thank you @NghiaTranUIT

**Comment by anthumchris** [comment]
This is now in the _Appearance_ tab (`v5.x`)

<img src="https://github.com/user-attachments/assets/c79f0fd7-3d1f-4596-b0b0-11b9d6295811" width="595">
