### ISSUE TITLE
Add useful guideline to proxy.man/ssl if the user doesn't install Proxyman Certificate first

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#422]
## 🐶 Brief
Some small users forgot to install the Proxyman Certificate before accessing to http://proxy.man/ssl (Local server). As a result, the users get 400 Bad Request with no useful information.

We should add some tip to help the use to fix it 👍 

## 👑 Criteria
- [x] Add some useful information in Body if the request is 400

**Comment by NghiaTranUIT** [comment]
Done

**Comment by FinHorsley** [comment]
Is this something that could be added to the UI? 

If the the Root CA hasn’t been created then the “Install on iOS” is disabled? (For example)

**Comment by NghiaTranUIT** [comment]
It's not good UX to disable "Install on iOS" because new users don't know that they need to install the Certificate on macOS in order to enable the button "Install on iOS".

For now, I add the useful tip in the response, so the user could see on the Safari or on the app easily.

<img width="917" alt="Screen Shot 2020-03-03 at 21 51 03" src="https://user-images.githubusercontent.com/5878421/75787307-18763180-5d99-11ea-8c34-de7788941b19.png">

**Comment by FinHorsley** [comment]
Great to see the updated HTTP response 👍

Sorry, forgot to mention that there should be an explanation why the “Install iOS Certificate” was disabled. 

I think it’s better to disable the button, as it makes it clear to the user that something needs to be done to continue; however I agree that without some explanation message this would be bad UX
