### ISSUE TITLE
[Feature Request] XML Pretty Print or Tree View

### ISSUE THREAD

**Issue by rinsuki** [ProxymanApp/Proxyman#424]
Many services are now using JSON, but some services still use XML, and I also need to see communication with that service.

Proxyman works perfectly, but it would be better if you could display the XML tree structure more clearly!

thank you <3

## currently:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Example><User><Name>example</Name></User></Example>
```

## expected:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Example>
    <User>
        <Name>example</Name>
    </User>
</Example>
```

**Comment by NghiaTranUIT** [comment]
Thank for the suggestion. I will research and support XML Prettier in the next second release 👍

**Comment by NghiaTranUIT** [comment]
@rinsuki let check out this BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.18.1_XML_Prettier.dmg

<img width="1840" alt="Screen_Shot_2020-03-13_at_10_56_16" src="https://user-images.githubusercontent.com/5878421/76588334-569dee80-6519-11ea-9658-2d37a62c4418.png">

I will officially release soon 🙌

**Comment by rinsuki** [comment]
woooooow so good!!!!! thanks!!!!!!!!!

**Comment by juliasleeps** [comment]
@NghiaTranUIT 
hello! can this feature also be provided for Windows?

**Comment by NghiaTranUIT** [comment]
sure, I will open this ticket on Windows 👍

**Comment by NghiaTranUIT** [comment]
@juliasleeps this feature is available on Windows.

![Image](https://github.com/user-attachments/assets/bb5f284b-9bf0-412e-af3f-8bbbfa0bd2d6)

**Comment by juliasleeps** [comment]
@NghiaTranUIT 
i set it but do not see tree view

<img width="1529" alt="Image" src="https://github.com/user-attachments/assets/d740d8ad-690f-48b7-832f-28f5313da817" />

**Comment by NghiaTranUIT** [comment]
thanks, I see, for some reason, it doesn't prettify your XML. Let's me fix it
