### ISSUE TITLE
Suggestion - "Does Not Contain" filter option

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#426]
Our app has a "heartbeat" check that can get really noisy over long sessions. I'd love to be able to hide them by filtering with a matching string.

**Comment by NghiaTranUIT** [comment]
That's totally make sense. I will add this filter to 1.19.0 ✅

**Comment by NghiaTranUIT** [comment]
Let try "No Contain" filter with this BETA build @crankygeek https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_No_Contain_Filter.dmg 🙌

**Comment by crankygeek** [comment]
Sorry, I was out over the weekend, but I just took a look at 1.18.0 and this works great. Thanks!
