### ISSUE TITLE
[BUG] (/) is accidentally removed from the URL

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#428]
### Description
Proxyman mistakenly removes the slash (/) at the end of the URL which become a different Requests.

### Criteria Acceptance 
- [ ] Make sure Proxyman won't remove the /

**Comment by NghiaTranUIT** [comment]
Related to #382

**Comment by NghiaTranUIT** [comment]
All done. BETA at https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Trailing_Slash_Missing.dmg

**Comment by shaynem** [comment]
confirmed this has been fixed.

**Comment by NghiaTranUIT** [comment]
Glad to hear that 🙌
