### ISSUE TITLE
Request is not displayed

### ISSUE THREAD

**Issue by yauheniprakapenka** [ProxymanApp/Proxyman#429]
Proxyman 1.17.1
mac 10.15.3

### Steps to reproduce 
1. Download my project 
https://drive.google.com/file/d/1F4uAaCiQEcE_WEv8aC2sNagrszhB9Zg-/view?usp=sharing

2. Run app with uncommented 
**let urlString = "https://rickandmortyapi.com/api/character/"**

### Expected behavior
Proxyman displays rick morty request

For example, with mail.ru it works.

### Video
https://drive.google.com/file/d/1LpTS4fdUZ_LE6y27KATF3CgW6IW3YUSC/view?usp=sharing

**Comment by NghiaTranUIT** [comment]
Let me investigate bug, look like Proxyman couldn't parse the data properly.

**Comment by NghiaTranUIT** [comment]
Turn out that URLSession automatically **caches** the response -> Doesn't make a real request -> Doesn't appear on Proxyman. (https://stackoverflow.com/questions/24328461/how-to-disable-caching-from-nsurlsessiontask)

Let check out this code, I disable a caching from URLSession, and the requests are appeared on Proxyman.

```swift
        let config = URLSessionConfiguration.default
        config.requestCachePolicy = .reloadIgnoringLocalCacheData
        config.urlCache = nil
        let session = URLSession(configuration: config)

        session.dataTask(with: url) { (data, response, error) in

            if let error = error { print(error); return }
            guard let data = data else { return }
            
            do {
                let character = try JSONDecoder().decode(Character.self, from: data)
                completion(character)
            } catch let error {
                print(error)
            }
        }.resume()
```

<img width="1856" alt="Screen Shot 2020-03-08 at 13 36 56" src="https://user-images.githubusercontent.com/5878421/76157909-54ffaf80-6142-11ea-8568-134f4a46dfe9.png">

 -------------------
Additionally, if you would to get the latest response, please consider to use No Caching Tool (Option+Command+N)

**Comment by yauheniprakapenka** [comment]
Sorry to bother you! 

One more question. When I launch the application, I want the sorting from the last time to be always remembered. In the settings did not find saving sorting.

**Comment by NghiaTranUIT** [comment]
At the moment, the Sorting state isn't persisted. I will support this feature now 👍

**Comment by yauheniprakapenka** [comment]
You are the best! I love Proxyman with all my heart

**Comment by NghiaTranUIT** [comment]
Let check out the build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Sorting.dmg 👍 

Ticket https://github.com/ProxymanApp/Proxyman/issues/430
