### ISSUE TITLE
Persist the previous Sorting state

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#430]
### Description
At the moment, the sorting state always resets to the default sorting after relaunching the app, which causes inconvenience to the end users.

### Acceptance Criteria 
- [ ] Use `autosaveTableColumns` to persist the Column state (order and sorting)

**Comment by NghiaTranUIT** [comment]
All done. Beta: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.17.1_Sorting.dmg

**Comment by yauheniprakapenka** [comment]
Its work great!))

**Comment by NghiaTranUIT** [comment]
Awesome 😍
