### ISSUE TITLE
Performance hit using Clear button under Activity list

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#432]
In 1.18.0, there's a bit of a performance hit when clearing the request activity history list using the Clear button. This seems to be new in this version.

### Proxyman version?
Proxyman 1.18.0

### macOS Version?
MacBook Pro (15-inch, 2016) macOS 10.14.6

### Steps to reproduce 
1. Allow a few thousand requests to log in the Activity list
2. Select any node in the Source list
3. Press the Clear button below the Activity list

### Expected behavior
List is cleared without a performance hit/beachball.

**Comment by NghiaTranUIT** [comment]
Thank for the report. I will investigate it 👍 

Btw, in the latest build 1.18.0 and 1.18.1, we update the "Clear Session" Tools, which will clear and reset all requests. It's handy tool to reset the session and release some memory 🙌

**Comment by crankygeek** [comment]
Yeah, I noticed it while checking out the Clear session tool. FWIW, if I could optionally configure the button to run that command, I’d use that. ;)

**Comment by NghiaTranUIT** [comment]
Fixed. I remove the serial queue in AsyncCocoaSocket, which improves the performance 👍

**Comment by NghiaTranUIT** [comment]
Hi @crankygeek, in the latest build 1.20.0, I fixed it and add some improvement when processing some huge body data. As a result, the performance is better 😄 

Let update it: https://github.com/ProxymanApp/Proxyman/releases/tag/1.20.0

**Comment by crankygeek** [comment]
@NghiaTranUIT confirmed this is looking good in 1.20.0. Thanks!
