### ISSUE TITLE
[Feature Request] System proxy setting logic optimization

### ISSUE THREAD

**Issue by njzydark** [ProxymanApp/Proxyman#433]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.18.0

### macOS Version? (Ex. mac 10.14)
10.15.3

### Introduction
Thank you in advance for the effort, the software is great!

### Content

System proxy refers to this:
![image](https://user-images.githubusercontent.com/19601720/76273283-7387b700-62b8-11ea-9983-349fe139d31e.png)

1. Every time you open the software, you must cover the system proxy，can you provide options in the settings for startup and shutdown?
2. Can the system proxy click on the bottom toolbar add a shortcut function to open and close?
3. Can the software save the current system proxy settings when it starts up, so that it can restore the previous system proxy settings when closed?

**Comment by NghiaTranUIT** [comment]
Hey there, 

What do you mean the "System Agent"? Is it a system popup (Username/Password) 🤔 

It would be great if we have a screenshot too 😄 

At the moment, if the user is admin, Proxyman doesn't prompt any popup to override the Proxy Config (It's implicitly done by Privileged Help Tool, which we installed at the first launch)

**Comment by 0njzy0** [comment]
> Hey there,
> 
> What do you mean the "System Agent"? Is it a system popup (Username/Password) 🤔
> 
> It would be great if we have a screenshot too 😄
> 
> At the moment, ~if the user is admin~ (work on admin and guest), Proxyman doesn't prompt any popup to override the Proxy Config (It's implicitly done by Privileged Help Tool, which we installed at the first launch)

Sorry, not described clearly, I have updated

**Comment by NghiaTranUIT** [comment]
Thank for the screenshot 🙌 

> 1. Every time you open the software, you must cover the system proxy，can you provide options in the settings for startup and shutdown?

We can stop the Proxy Config being overridden when Proxyman launches in preference.

<img width="672" alt="Screen_Shot_2020-03-10_at_09_24_06" src="https://user-images.githubusercontent.com/5878421/76273679-06245800-62b1-11ea-8acb-65446fd297be.png">

> 2. Can the system proxy click on the bottom toolbar add a shortcut function to open and close?

It's great idea, I will research how to open the Proxy System Panel from Proxyman when clicking on the "macOS Proxy" button in the bottom bar.

Btw, you can use shortcut Option+CMD+O to turn on/off quickly.

 > 3. Can the software save the current system proxy settings when it starts up, so that it can restore the previous system proxy settings when closed?

I remember that I already support this feature before, but from you mention, I will double check it 👍

**Comment by 0njzy0** [comment]
> 1. Can the system proxy click on the bottom toolbar add a shortcut function to open and close?
> 
> It's great idea, I will research how to open the Proxy System Panel from Proxyman when clicking on the "macOS Proxy" button in the bottom bar.
> 
> Btw, you can use shortcut Option+CMD+O to turn on/off quickly.

If the system proxy is off by default, I still want the system proxy button at the bottom of the system to be displayed. 

> 2. Can the software save the current system proxy settings when it starts up, so that it can restore the previous system proxy settings when closed?
> 
> I remember that I already support this feature before, but from you mention, I will double check it 👍

1. The current version should not be restored to previous settings but reset
2. Even if I turn off the system proxy settings by default, I still reset the system proxy settings when I close the software

**Comment by JasonBoy** [comment]
> 2. Even if I turn off the system proxy settings by default, I still reset the system proxy settings when I close the software

@NghiaTranUIT  When close the app, the current system proxy will still be changed, any updates? when I uncheck the override option, I should not change proxy when close since I may use another proxy at the moment

**Comment by NghiaTranUIT** [comment]
Thanks for pushing it. I will fix this issue in 2.12.0 🖐️

**Comment by NghiaTranUIT** [comment]
Hey @JasonBoy @njzydark, please check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.11.0_Do_not_Revert_Proxy_If_it_is_not_override.dmg

If you disable "macOS Proxy Override" in Tool -> Proxy Setting, when you quit the app, it won't revert the System Proxy anymore 👍 

Regarding revert back to the previous changes, I'm still stuck on it and not found a way to fix it.

**Comment by njzydark** [comment]
>please check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.11.0_Do_not_Revert_Proxy_If_it_is_not_override.dmg
> 
> If you disable "macOS Proxy Override" in Tool -> Proxy Setting, when you quit the app, it won't revert the System Proxy anymore 👍
> 
It work, thank you
> Regarding revert back to the previous changes, I'm still stuck on it and not found a way to fix it.
>
Can you get the current system proxy information when the app is opened? If possible, reset the proxy information obtained before when you exit the app.
