### ISSUE TITLE
No scrollbar in source list when content exceeds height of the window

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#438]
I have scrollbars set to always on and have observed that the scrollbar is never displayed in the source list. I've tried all three scrollbar options in System Prefs (System Preferences > General > Show scroll bars)

### Proxyman version? (Ex. Proxyman 1.4.3)
Version 1.18.1 (11810)

### macOS Version? (Ex. mac 10.14)
macOS 10.14.6

### Steps to reproduce 
1. Set scrollbars to Always
2. Make the source list longer than the window
3. Observe scrollbar is not visible
4. Scroll the source list
5. Observe scroll bar does not appear when scrolling

**Comment by NghiaTranUIT** [comment]
Hey, it's correct that the Scrollbar of Source List won't appear because I intentionally hide it 😄 

But, it violate the Apple Design Guideline. I will put it back 👍 

Thank for rising it 🙌

**Comment by NghiaTranUIT** [comment]
Fixed in 1.20.0, which is going to release today 👍
