### ISSUE TITLE
[BUG] Map Remote does not work if a request is repeated.

### ISSUE THREAD

**Issue by bpdev97** [ProxymanApp/Proxyman#439]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.18.1
### macOS Version? (Ex. mac 10.14)
10.15
### Steps to reproduce 
1 - Map something using the map remote feature
2 - Make a request that should be mapped (This works fine)
3 - Repeat that request. 

When the request is repeated the map remote is not followed. 

### Expected behavior
Map remote should also be followed when a request is repeated.

**Comment by NghiaTranUIT** [comment]
Thank for pointing it out. At the moment, repeated requests are not going through the Proxy -> It goes straight to the Internet, so Map Remote doesn't affect on it.

I will improve the behavior that Repeat or Compose requests should be applied from Map Local + Map Remote too 👍 

For now, to workaround, I suggest to temporarily use `Copy as cURL` then executing on Terminal to see the changes (Map Remote applied)

**Comment by NghiaTranUIT** [comment]
Hey @bpdev97 , let check this BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.18.1_Repeat%26Compose_Map_Remote_Local.dmg

From now, we can repeat or Repeat&Compose and the Map Local and Remote are applied as usual 💪
