### ISSUE TITLE
Typo: "Word Warp" -> "Word Wrap"

### ISSUE THREAD

**Issue by zrzka** [ProxymanApp/Proxyman#445]
### Proxyman version? (Ex. Proxyman 1.4.3)

Version 1.19.0 (11900)

### Screenshots (optional)

<img width="672" alt="Screen Shot 2020-03-23 at 09 28 21" src="https://user-images.githubusercontent.com/1084172/77297075-0f69e780-6ce9-11ea-9fc7-dd4018d8cf66.png">

**Comment by NghiaTranUIT** [comment]
Thank you for pointing it out. It'ss my mistake 😬

Consider it's done 🌮

**Comment by NghiaTranUIT** [comment]
Done with https://github.com/ProxymanApp/Proxyman/issues/446
