### ISSUE TITLE
Style: "." at the end should be removed

### ISSUE THREAD

**Issue by zrzka** [ProxymanApp/Proxyman#446]
### Proxyman version? (Ex. Proxyman 1.4.3)

Version 1.19.0 (11900)

### Screenshots (optional)

<img width="672" alt="Screen Shot 2020-03-23 at 09 33 49" src="https://user-images.githubusercontent.com/1084172/77297506-ab93ee80-6ce9-11ea-8d8d-68a79e8bff5e.png">

<img width="672" alt="Screen Shot 2020-03-23 at 09 34 17" src="https://user-images.githubusercontent.com/1084172/77297524-b3539300-6ce9-11ea-84ee-041a02b303b8.png">

**Comment by NghiaTranUIT** [comment]
Good point 👍

**Comment by NghiaTranUIT** [comment]
Done. If you're interested in a beta build. Here you go https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.19.0_Improve_Wording.dmg

## Changelog
- Fix typo
- Improve wordings in Proxyman Proxy Helper Tool Window

Thank you so much 👍
