### ISSUE TITLE
Typo in Advanced Preferences

### ISSUE THREAD

**Issue by Saklad5** [ProxymanApp/Proxyman#448]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 1.19.0
### macOS Version? (Ex. mac 10.14)
macOS 10.15
### Steps to reproduce 
Open Preferences from the menu bar and look at the Advanced tab.
### Expected behavior
“Montior” should be “Monitor”. In addition, the capitalization in the description of that option is inconsistent, and the description of the option below it needs revising.
### Screenshots (optional)
![image](https://user-images.githubusercontent.com/4258823/77381587-48877380-6d4c-11ea-80e7-6a32e4f8015b.png)

**Comment by NghiaTranUIT** [comment]
Thanks for that 👍 I also fixed some typo in https://github.com/ProxymanApp/Proxyman/issues/445 and https://github.com/ProxymanApp/Proxyman/issues/446 and refactor some wording in Mac Certificate and Proxy Helper Window too 👍

**Comment by Saklad5** [comment]
I was _wondering_ what “Word Warp” meant! That makes more sense, yes.

**Comment by NghiaTranUIT** [comment]
all done 🌮
