### ISSUE TITLE
Investigate why Firebase traffics "Realtime Database" doesn't show up on Proxyman

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#449]
### Description
A user reports that Firebase traffic (Realtime Database traffic) doesn't present on the app even though he can see other traffic as usual.

Conversation: https://twitter.com/jeanetienne/status/1242659703185764357

### Acceptance Criteria
- Investigate why
- Fix if possible

**Comment by NghiaTranUIT** [comment]
After the investigation, it turns out that Proxyman or other tools couldn't capture the traffic from Firebase Realtime Database since it's not an HTTP/HTTPS application layer, so the traffic doesn't respect the HTTP/HTTPS Proxy Config -> Doesn't go through Proxyman -> Doesn't show up.

However, Proxyman can capture other HTTP/HTTPS Requests as usual when authorizing with Firebase server as an example 👍

**Comment by jamesdixon** [comment]
Hello! Is the traffic not sent over a common protocol that Proxyman could recognize?

**Comment by jamesdixon** [comment]
Would love a workaround

**Comment by NghiaTranUIT** [comment]
@jamesdixon You can workaround by using Atlantis (https://github.com/ProxymanApp/atlantis) (see Advanced Usage section)

Basically, you can construct a Request/Response from Firebase and add to Atlantis, then it will display on Proxyman for inspector.

```swift
// Add to Atlantis and show it on Proxyman app
Atlantis.add(request: request, response: response, responseBody: responseData)
```

It's manual, but we can see the Firebase traffic 😄

**Comment by NicolasCombe5555** [comment]
Is this ever going to be integrated or be less manual? Asking for a friend 😅

**Comment by NghiaTranUIT** [comment]
Unfortunately, Firebase SKD is a closed source so I'm unable to integrate Proxyman to Firebase.

From what I investigate recently on Firebase, they are still using a non-HTTP protocol to communicate to Firebase Server. Therefore, Proxyman could not automatically capture it.

I suppose that using Atlantis framework and add the request/response manually is a solution I can think of 👍

**Comment by NghiaTranUIT** [comment]
@jamesdixon @NicolasCombe5555 I did an investigation this morning and turnss out Proxyman can capture Firebase Google Analytic. (Some reports mentions that Proxyman could not see any Firebase GA traffic)

### Traffic from https://app-mesurement.com/a

<img width="1858" alt="Screen Shot 2021-11-25 at 09 56 38" src="https://user-images.githubusercontent.com/5878421/143375624-675312c3-d2f9-42de-8090-9f1afe79e189.png">

### Traffic from https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog

<img width="1858" alt="Screen_Shot_2021-11-25_at_09_51_15" src="https://user-images.githubusercontent.com/5878421/143375715-ad0c1049-011a-4ef7-9a6f-a608bf6ffdba.png">

----------------------------------

As you can see, Proxyman can capture and partially read the value of the protobuf content. We can also see the event name, event ID, Event Description.

### Suggestion

If Proxyman could not capture Firebse GA traffic, I guess that your event is batched and on the schedule.

In order to capture the traffic in real-time, we should use` -FIRDebugEnabled` (https://firebase.google.com/docs/analytics/debugview) to force the SDK to send the event immediately (instead of batching and sending in an hour later).

Hope that help 👍
