### ISSUE TITLE
[Feature Request] Add Method to Breakpoint Rules

### ISSUE THREAD

**Issue by robmathers** [ProxymanApp/Proxyman#453]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.19.0 (11900)
### macOS Version? (Ex. mac 10.14)
10.14.6

### Feature Request
It would be great if there were an option to choose an HTTP method for Breakpoints. For example, only break on `POST` requests for a given URL.

**Comment by NghiaTranUIT** [comment]
Hi, it's reasonable to add a specific method to the breakpoint. I will add it in the next release, which is 1.21.0. Tomorrow is a release day for 1.20.0 😄

**Comment by NghiaTranUIT** [comment]
Hey @robmathers, let check the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.20.0_Breakpoint_With_Method.dmg

I support a Method matching option for ANY or exact method as you wish 👍  

<img width="1079" alt="Screen Shot 2020-03-29 at 20 07 33" src="https://user-images.githubusercontent.com/5878421/77850413-9264d380-71fc-11ea-95b8-c88bd7632e41.png">

Thank you for raising this missing improvement 🌮

**Comment by robmathers** [comment]
Wow, that's a fast response. Thanks!

**Comment by robmathers** [comment]
Saw this appear in the new release, works great.
