### ISSUE TITLE
JSON Previewer with non-json Content-Type

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#456]
### Description
Some servers respond to a Response with JSON body but the header is an incorrect Content-Type, so Proxyman doesn't pretty the JSON body. 

We have to find a way to force render JSON to mitigate this situation.

### Acceptance Criteria
 - Improve the UI to introduce some buttons to force pretty JSON, XML, ... if possible

**Comment by NghiaTranUIT** [comment]
Done 👍 BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.20.0_Add_Format_JSON_Prettier.dmg
## Changelogs
- Support Format JSON Prettier in Breakpoint and Body.

<img width="1304" alt="Screen Shot 2020-04-01 at 21 24 49" src="https://user-images.githubusercontent.com/5878421/78151392-c2151500-7462-11ea-8284-ec04de8d1355.png">

<img width="1031" alt="Screen Shot 2020-04-01 at 21 49 38" src="https://user-images.githubusercontent.com/5878421/78151365-ba557080-7462-11ea-963f-e3a90827522c.png">

**Comment by foxt** [comment]
@NghiaTranUIT Apologies for the necro - but would it be possible to get this for XML too?

**Comment by NghiaTranUIT** [comment]
@foxt you mean you'd like to prettify your XML in the body? 🤔
