### ISSUE TITLE
[Request feature] Throttling like Charles tool

### ISSUE THREAD

**Issue by pvthiendeveloper** [ProxymanApp/Proxyman#459]
### Feature expect

I'm mobile developer. I need a proxy tool to handle Request and  Response from the server api, and Proxyman is a software very nice for me. But, I think mobile developer guys very need a feature for support change network bandwidth because sometimes I need the config's network to test some case with slow network. If Proxyman have this feature I think it will gigantic development. 

See more info form mage bellow. 

Thank you!
### Screenshots

![Screen Shot 2020-03-30 at 3 36 43 PM](https://user-images.githubusercontent.com/26134662/77892134-48cbc580-729c-11ea-90fe-831407d01f78.png)

**Comment by NghiaTranUIT** [comment]
Hey @pvthiendeveloper , we're developing this feature, but it might take longer than a bit since the initial implementation didn't meet my requirement : /. Thus, I prefer not to ship it.

To workaround, I suggest using Network Link Conditioner from Apple (https://nshipster.com/network-link-conditioner/), which provides many network profiles too 👍 

Meanwhile, I'm working on the v2 of Throttle and ship it soon 🌮

**Comment by pvthiendeveloper** [comment]
> Hey @pvthiendeveloper , we're developing this feature, but it might take longer than a bit since the initial implementation didn't meet my requirement : /. Thus, I prefer not to ship it.
> 
> To workaround, I suggest using Network Link Conditioner from Apple (https://nshipster.com/network-link-conditioner/), which provides many network profiles too 👍
> 
> Meanwhile, I'm working on the v2 of Throttle and ship it soon 🌮

Very fast reply, thank you for recommending a new software very nice. Good luck and have a successful feature.

**Comment by NghiaTranUIT** [comment]
Progress update: https://github.com/ProxymanApp/Proxyman/issues/119#issuecomment-789715568 🎉

**Comment by NghiaTranUIT** [comment]
Just a friendly reminder @pvthiendeveloper that this feature is implemented in the latest build 👍 

Ref: https://docs.proxyman.io/advanced-features/network-throttling

**Comment by pvthiendeveloper** [comment]
> Just a friendly reminder @pvthiendeveloper that this feature is implemented in the latest build 👍
> 
> Ref: https://docs.proxyman.io/advanced-features/network-throttling

**Comment by pvthiendeveloper** [comment]
@NghiaTranUIT Great, this is really a feature useful. I can't wait to use it.
