### ISSUE TITLE
Sorting by remote device IP address does not work

### ISSUE THREAD

**Issue by yauheniprakapenka** [ProxymanApp/Proxyman#461]
Proxyman 1.20.0

My MacBook is connected to the network through a wire. Macbook distributes the Internet to devices. Proximen shows all traffic.

**Now**: traffic is not sorted by IP. Therefore, it is not clear from which device than the request
**Waiting**: traffic is sorted by IP

![Untitled-1](https://user-images.githubusercontent.com/47568606/77931469-e29f6c80-72b4-11ea-9324-bc6b42d293ac.jpg)

Видео:
https://drive.google.com/file/d/18BoTjX0CAXKHhK6lNLb4S5Gauw4cDrAD/view?usp=sharing

**Comment by NghiaTranUIT** [comment]
Hey @yauheniprakapenka, from your video, it's definitely a bug. Ideally, those requests should properly group on the device where the source is. I will investigate and fix it 👍 Thank for the report 🌮

**Comment by NghiaTranUIT** [comment]
Hey @yauheniprakapenka, check out this BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.20.0_Bug_Grouping_Remote_Device_IP.dmg

From now, all requests are properly grouped by IP remote device 👍 
 
<img width="926" alt="Screen Shot 2020-03-31 at 11 40 19" src="https://user-images.githubusercontent.com/5878421/77988803-60ac5380-7347-11ea-97a8-4011d54cdd2e.png">

**Comment by yauheniprakapenka** [comment]
Thanks, works great ^_^
