### ISSUE TITLE
[Feature] Decode Bearer to jwt inside the app

### ISSUE THREAD

**Issue by tiwood** [ProxymanApp/Proxyman#467]
It would be really nice to present the actual/decoded `jwt` next to the `bearer token` in the `auth` tab.

Thank you for your great app.

**Comment by NghiaTranUIT** [comment]
Hey, it totally makes sense to decode JWT. I will put this feature to 1.23.0 build 👍

**Comment by NghiaTranUIT** [comment]
@tiwood Let check out this BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.21.0_JWT_Previewer.dmg

Proxyman will try decoding JWT from Bearer 👍 

<img width="875" alt="Screen_Shot_2020-04-11_at_21_30_16" src="https://user-images.githubusercontent.com/5878421/79046898-ab7a7500-7c3d-11ea-8362-e26da179493d.png">
