### ISSUE TITLE
Not capturing local domain traffic

### ISSUE THREAD

**Issue by lumaxis** [ProxymanApp/Proxyman#472]
I'm using a smart home device that is controlled via an app on my Mac. The Mac app sends the commands to a `.local` domain, e.g. `my-device.local`. That traffic doesn't appear in Proxyman.

### Proxyman version? (Ex. Proxyman 1.4.3)
1.21.0
### macOS Version? (Ex. mac 10.14)
10.15.4
### Steps to reproduce 
Send traffic to a device via `.local` domain on local network.
### Expected behavior
The traffic is capture and displayed in Proxyman

**Comment by NghiaTranUIT** [comment]
@lumaxis Technically, I'm not sure how can Proxyman capture it because the Mac traffic directly sends to `my-device.local` without going through Proxyman Port 9090. 

Can you show me the code of how to sends the commands to a .local domain?

**Comment by lumaxis** [comment]
Actually, I think this has to do with me using multiple network connections on the Mac, i.e. Wifi and Ethernet at the same time. It seems like the app is specifically sending traffic via a wifi interface but my primary network connection that is configured in macOS system settings is ethernet.

Once I unplug the ethernet cable so that all traffic goes through wifi, the traffic also shows up in Proxyman.

The app is [Elgato Control Center](https://www.elgato.com/en/gaming/downloads)

**Comment by NghiaTranUIT** [comment]
Yup, at the moment, Proxyman would only override the HTTP/HTTPS Proxy config in Network.prefPane -> Wifi -> Proxy Tab.

If you're using Ethernet, please check if this setting is available. I couldn't check it since I don't have Ethernet port in my MacBook, unfortunately 😅

**Comment by lumaxis** [comment]
No, actually not. It's setting the proxy settings correctly in both but I think I found it:

![image](https://user-images.githubusercontent.com/406937/78585915-f01ba000-783a-11ea-84a7-670b2a8f7030.png)

For some reason, the Tunderbolt network interface was configured to skip a proxy for `*.local` traffic. I did not configure this myself ¯\\\_(ツ)_/¯

**Comment by lumaxis** [comment]
It seems, that is a default configuration for either all Thunderbolt Slots or all Ethernet slots in general.

**Comment by NghiaTranUIT** [comment]
I suppose that’s it’s a default value from macOS. For example, ‘localhost’ won’t go through any proxy unless we map to different name in host/etc.

**Comment by NghiaTranUIT** [comment]
Anw, thank for raising a ticket 👍

**Comment by lumaxis** [comment]
Anytime! Maybe something to add to the documentation or so.
