### ISSUE TITLE
[BUG] Pressing Keyboard Shortcut for Filter makes alert noise

### ISSUE THREAD

**Issue by patrickbdev** [ProxymanApp/Proxyman#477]
### Proxyman version?
Version 1.21.0 (12100)

### macOS Version?
10.15.3 (19D76)

### Steps to reproduce 
1. Press CMD+F
1. Observe sound is made and filter is in focus

### Expected behavior
No sound is made

**Comment by NghiaTranUIT** [comment]
Consider it's done. I notice this bump sound as well 😆

**Comment by NghiaTranUIT** [comment]
If you hate the beep sound, let check out this quick fix 🎧: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.21.0_Duplicate_Local_File.dmg

Thank you 👍

**Comment by patrickbdev** [comment]
Perfect, thanks a lot!
