### ISSUE TITLE
Keep the same content file after duplicate request in Map Local

### ISSUE THREAD

**Issue by thang-nm** [ProxymanApp/Proxyman#478]
### Proxyman version?
1.12.0

### macOS Version?
10.15.4

### Steps to reproduce 
1. Tool > Map Local
2. Right click on a request
3. Hit "Duplicate"
-> New request is created but it uses source request's file.

### Expected behavior
Create a new file for new request.

**Comment by NghiaTranUIT** [comment]
It's my intention to create a new local file rather than reusing the old one. Because sometime I would try a different set of param, then I can enable/disable the one I need without touching the original Map Local Entry.

If those local files are the same source, it would mess up.

**Comment by thang-nm** [comment]
Yes, i expect it will create a new local file, but it's not.

**Comment by NghiaTranUIT** [comment]
Ah, I see. My mistake 😅

I'm going to fix it this weekend 👍

**Comment by thang-nm** [comment]
Thank you :)

**Comment by NghiaTranUIT** [comment]
@thang-nm check out this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.21.0_Duplicate_Local_File.dmg

From now, only `.json` file (HTTPMessage) will be duplicated. The directory or other file will keep the same 🙌

**Comment by thang-nm** [comment]
Thank you ao much. I will try it ;)

**Comment by tbaranes** [comment]
I was going to write this same issue then I see an available beta, thanks a lot for your reactivity :)
