### ISSUE TITLE
Deactivate keyboard shortcut to remove a local map when updating its fields

### ISSUE THREAD

**Issue by tbaranes** [ProxymanApp/Proxyman#479]
Thanks for this awesome tool! I used for a long time Charles, but now, I definitely move to ProxyMan!

### Proxyman version? (Ex. Proxyman 1.4.3)

1.21.0

### macOS Version? (Ex. mac 10.14)

10.15.4

### Steps to reproduce 

- Create a new local map (otherwise you may loose it)
- Start updating a field (I tried only with the map content, but I think I may have the issue with others fields as well)
- Remove a full line using keyboard shortcut cmd + delete
- The local map has been removed from the sidebar

A few times I didn't understand what did happen (I'm often using cmd + delete to drop a line), then I understood that there was a conflict with that keyboard shortcut in the map feature (maybe others).

### Expected behavior

Don't remove the file when using this Mac shortcut to drop a full line. I don't mind that shortcut exists in ProxyMan, but I think it should either be another keys combination or at least deactivate this shortcut while editing fields.

**Comment by NghiaTranUIT** [comment]
It's definitely a bug. Thanks for the detail report 🌮 

I will disable all shortcut when we're editing in the Local File 👍 and glad to know that you have a new home - Proxyman 😄

**Comment by NghiaTranUIT** [comment]
@tbaranes Here is the BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.21.0_MapLocal_Shortcut.dmg

I goona release soon after the Protobuf feature is done (it's 70% now) 🙌
