### ISSUE TITLE
Query parameters are reordered on repeating a request

### ISSUE THREAD

**Issue by hlynursmari1** [ProxymanApp/Proxyman#489]
### Proxyman version?

Proxyman Version 1.21.0 (12100)

### macOS Version?

macOS Catalina 10.15.4 (19E287)

### Steps to reproduce

- Make a request with multiple query parameters, say:
    `https://www.google.com/search?q=proxyman&oq=proxyman&sourceid=chrome&ie=UTF-8`
- When you repeat the request through Proxyman the query parameters are reordered alphabetically: 
    `https://www.google.com/search?ie=UTF-8&oq=proxyman&q=proxyman&sourceid=chrome`

### Expected behaviour

The query parameter order should be preserved, or should be manually editable when repeating the request. Reordering query parameters can break signed requests where server-side verification does not parse the query string before using it in computing the request signature.

### Screenshots

![image](https://user-images.githubusercontent.com/7827436/80428157-381c6880-88b7-11ea-86c3-3464cf6049bb.png)

**Comment by NghiaTranUIT** [comment]
Good point about the order of the query. I'm not aware that it might break the request signature. 

I will fix it in the next release 👍

**Comment by NghiaTranUIT** [comment]
Hi @hlynursmari1 The bug is fixed in this BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.22.0_Bug_Keep_Order_Query_In_Repeated_Flow.dmg

It gonna release on Monday next week. Thank you for raising this bug 👍

**Comment by hlynursmari1** [comment]
Perfect! Thank you for the quick turn around and nice work on a great app 👍

**Comment by NghiaTranUIT** [comment]
You're welcome 🌮
