### ISSUE TITLE
Commerial use of a free version

### ISSUE THREAD

**Issue by petersamokhin** [ProxymanApp/Proxyman#495]
Hello! Are there any restrictions on commercial using of a free version?
e.g. Postman policy: https://support.getpostman.com/hc/en-us/articles/360003675853-Commercial-Use-Restrictions

**Comment by NghiaTranUIT** [comment]
Hey @petersamokhin, there are no restrictions at all 👍

**Comment by NghiaTranUIT** [comment]
Meanwhile, I will update this policy to make it clear 🌮

**Comment by petersamokhin** [comment]
@NghiaTranUIT thank you for this! And for Proxyman, of course 👍
