### ISSUE TITLE
music stream not working when proxyman is opened

### ISSUE THREAD

**Issue by superandrew** [ProxymanApp/Proxyman#505]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.23.0
### macOS Version? (Ex. mac 10.14)
10.15.4
### Steps to reproduce 
Launch Proxyman
Launch the SomaFM app
Press play
(example url: http://ice5.somafm.com/groovesalad-128-aac)

If I open proxyman after pressing play the music stream continues.

With Charles I am able to reproduce music no matter what so I assume there is some kind of blocking on Proxyman's side.
### Expected behavior
Music should play

**Comment by NghiaTranUIT** [comment]
Confirmed that there is a bug about steaming music (your case is http) in the latest build of Proxyman. I'm redesigning the Core and fixed in the V2 (https://github.com/ProxymanApp/Proxyman/issues/500). Stay tuned when it live soon 👍

**Comment by superandrew** [comment]
you can't live a programmer without Groove Salad! :D

Cool, watching for updates!

**Comment by NghiaTranUIT** [comment]
@superandrew  You can use HTTPS instead, https://ice5.somafm.com/groovesalad-128-aac, and don't enable SSL-Proxying on Proxyman. Work fine 🌮

**Comment by superandrew** [comment]
@NghiaTranUIT I am using the app so I don't think I could. Anyway just kidding, glad that you are working on it. Thanks!

**Comment by NghiaTranUIT** [comment]
Fixed on the v2 build: https://github.com/ProxymanApp/Proxyman/issues/515#issuecomment-638596963 👍

**Comment by superandrew** [comment]
it works on the new build!

**Comment by superandrew** [comment]
@NghiaTranUIT you might want to close this?

**Comment by NghiaTranUIT** [comment]
It’s up to you @superandrew 😆
