### ISSUE TITLE
Inconsistent scroll bar UI

### ISSUE THREAD

**Issue by patrickbdev** [ProxymanApp/Proxyman#508]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 1.23.0 (12300)

### macOS Version? (Ex. mac 10.14)
10.15.4 (19E287)

### Steps to reproduce 
1. Look at request list and scroll to see the scroll bar
2. Look at response body and notice scroll bar

### Expected behavior
1. Both are consistent within the app and consistent within the apple platform.

### Suggestion
* Have both use the same one.
* Have both use the one that is commonly found in macOS (the green one shown in the screenshot)

### Why?
* Having non macOS scroll bars means users have to learn a new component
* Having a non hiding scroll bar means scroll bar takes up additional real estate.

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/11362913/82420555-37947d80-9ac3-11ea-8e7d-8e3aff57bc3b.png)

**Comment by NghiaTranUIT** [comment]
Hey, thanks for the report 👍 

The below scrollbar is basically a ScrollBar from [CodeMirror](https://github.com/ProxymanApp/CodeMirror-Swift) (WebView), so it might be inconsistent with the native ScrollBar (Above)

I will update the CSS and make sure they're the same size and color 🙌

**Comment by patrickbdev** [comment]
Ahh that explains it. Thank you for the response 🙏

**Comment by yauheniprakapenka** [comment]
Good day :)

How i can to scroll left and right? I have many columns on the right 

![Screenshot 05-22-2020 10 53 49](https://user-images.githubusercontent.com/47568606/82644829-a0423e00-9c1a-11ea-9480-3b0c8361e450.jpg)

**Comment by NghiaTranUIT** [comment]
Look like I accidentally disable the Horizontal Scroll Bar 😳

To workaround, you can use the Touch Bar or hold the mouse and drag to right. I will send you a hotfix build soon 👍

**Comment by NghiaTranUIT** [comment]
Hey @yauheniprakapenka, please check out this hotfix build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.23.0_Show_Horizontal_Scroller.dmg

<img width="1327" alt="Screen_Shot_2020-05-22_at_19_30_39" src="https://user-images.githubusercontent.com/5878421/82668871-8fb6b580-9c64-11ea-8882-9818b3ba058f.png">


If we enable "Always" in the System Prefernece -> General, we can see both scrollers.

<img width="780" alt="Screen_Shot_2020-05-22_at_19_30_28" src="https://user-images.githubusercontent.com/5878421/82668859-8b8a9800-9c64-11ea-991a-aa0478d936f0.png">

**Comment by yauheniprakapenka** [comment]
It works great) thank you very much ^_^

**Comment by NghiaTranUIT** [comment]
BETA here: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.23.0_Monospace_Font.dmg

I updated the Scroller Bar CSS to make it fit with the macOS 👍 

<img width="1813" alt="Screen_Shot_2020-05-23_at_10_00_02" src="https://user-images.githubusercontent.com/5878421/82720781-faa5d200-9ce0-11ea-9e52-dfd6a1ad79f1.png">

**Comment by patrickbdev** [comment]
Love it @NghiaTranUIT , thank you!

**Comment by NghiaTranUIT** [comment]
Just release an official build 1.24.0 with this fix. Sorry for the delay. I was really busy with the final assignments at the end of this semester 😬

And now, I'm totally free now. Time to push up the Core v2 👍
