### ISSUE TITLE
Possible setup issues

### ISSUE THREAD

**Issue by bb6** [ProxymanApp/Proxyman#509]
### Steps to reproduce 
Installed Proxyman, Installed Proxy Helper Tool, Installed Certificate on Mac.

Followed Android instructions exactly:
Adjusted Wifi settings to include proxy settings
Browsed to Proxy.Man/ssl and installed certificate for Wifi. There is also an option to install the certificate (separately) for VPN and Apps but this seems to make no difference - the same errors are encountered in the following steps.
Android did not have /res/xml folders present so I created the folders and created the XML files from scratch and added them.

Attempting to view HTTPS results in Proxyman just after enabling Enable HTTPS Response delivers the following error:
'The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9829.) (code=-9829)'
Right Click -> Repeat provides separate 'Error 400' results.

Is there something that I missed here with the instructions. Can't seem to find any help from Googling the Error codes other than 9829 means 'invalid certificate'. The docs page 
https://docs.proxyman.io/troubleshooting/get-ssl-error-from-https-request-and-response 
says I can 'disable SSL-pinning' but I do not see such an option anywhere.

Thanks in advance.

**Comment by NghiaTranUIT** [comment]
Hey @bb6, the problem might be that you set up r`es/xml/network_security_config.xml` and `manifest.xml` incorrectly. Please double check

I have few questions:

1. Do you add the line `<application android:networkSecurityConfig="@xml/network_security_config"` in `manifest.xml`? From your description, I don't see you did it

2. Are you the developer of the app? Please bear in mind that Proxyman is only capable of seeing HTTPS content from your app (You have the app source code to edit `network_security_config.xml ` and `manifest.xml` )

3. When installing the Certificate from proxy.man/ssl, please select App

Please try again and let me know @bb6

**Comment by bb6** [comment]
Thank you for the quick reply @NghiaTranUIT.

I was under the impression that the /res/xml folder must be in Android System root. I created the /res and /res/xml folders and both network_security_config.xml and manifest.xml files on my Android file system. I guess from what you are saying is that it must be in the (individual) app folders? So essentially - HTTPS data cannot be gleaned from any third party apps on Android?

I am not the developer. Proxyman was recommended from someone who is able to get HTTPS/TLS data out of third party apps on iPhone. From glancing at the installation notes it appears that what I am looking to do may not be possible on Android? Is this only possible on iOS?

Sorry if I am confused here.

**Comment by NghiaTranUIT** [comment]
>  HTTPS data cannot be gleaned from any third party apps on Android?

Yes, it's correct. It's a limitation of Android Apps. You are only able to intercept the HTTPS Content from **your apps**. Another app won't work because there is no way to add `network_security_config.xml` to the source code.

> Proxyman was recommended from someone who is able to get HTTPS/TLS data out of third-party apps on iPhone

Yes, iOS is different. You can see HTTPS on **all** apps (except some apps are protected by SSL-Pinning)

Hopefully, it might help you 🙌

**Comment by bb6** [comment]
Thank you @NghiaTranUIT. I had initially thought this meant that you could only use it on apps active on the screen and not in the background. Thank you for clearing it up.
