### ISSUE TITLE
Issue with partial download mp4 

### ISSUE THREAD

**Issue by marcelbeumer** [ProxymanApp/Proxyman#515]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.24.0

### macOS Version? (Ex. mac 10.14)

10.15.4

### Steps to reproduce 

Open `http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4` in Safari or Chrome *without* running Proxyman. The video will download and play

Start Proxyman. Open the same url. The video wil not play. Loading will get stuck.

Running `wget http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4` works, indicating issue with partial download?

### Expected behavior

MP4 downloads and plays the same as without Proxyman

**Comment by NghiaTranUIT** [comment]
Thanks for the link. I'm fixing it now 👍

**Comment by NghiaTranUIT** [comment]
Related to https://github.com/ProxymanApp/Proxyman/issues/505

**Comment by NghiaTranUIT** [comment]
Fixed here: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.24.0_Core_v2_Steaming_Body.dmg

<img width="1766" alt="Screen Shot 2020-06-04 at 11 34 58" src="https://user-images.githubusercontent.com/5878421/83715398-7267eb00-a657-11ea-956a-8667ec840078.png">

It's a beta build of the [ProxymanCore v2](https://github.com/ProxymanApp/Proxyman/issues/500), that I'm working on. Known-issue: Breakpoint and WebSocket don't work at this moment 🙌

**Comment by marcelbeumer** [comment]
Tried the beta: works for me too!
That was fast! Thanks, and thanks for making ProxyMan! 💪
