### ISSUE TITLE
[BUG] Don't change Source List focus after using Clear Session

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#545]
When using Clear Session, the Source List automatically switches focus to All > Apps. This appears to happen for any selection in the Source List.

### Proxyman version? (Ex. Proxyman 1.4.3)
2.1.1 (20110)

### macOS Version? (Ex. mac 10.14)

macOS 10.14.6

### Steps to reproduce 
1. Select Pin root folder in Source List
2. Click Clear Session toolbar button
3. Observe Source List focus automatically switches to All > Apps

### Expected behavior
Previously selected Source List item remains selected after clearing session.

**Comment by NghiaTranUIT** [comment]
Consider it's done now 🎉

**Comment by NghiaTranUIT** [comment]
Let check out this BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.1.1_Fix_Clear_Session.dmg

I improve the behavior after we clear the session by trying to select the nearest TreeNode. Thus, the selection is still maintain and we don't have to click again to select the previous selection 👍

**Comment by crankygeek** [comment]
@NghiaTranUIT That's working better. Thanks!
