### ISSUE TITLE
Script engine supported

### ISSUE THREAD

**Issue by xiaozhuai** [ProxymanApp/Proxyman#547]
### Proxyman version
2.1.1
### MacOS Version
10.14.6
### Feature request
Can we have a script engine which can write some scripts to handle request and response?
I'd suggest javascript.

**Comment by NghiaTranUIT** [comment]
Proxyman team is working on this feature and it gonna release after the Proxyman 2.2.0 (This weekend) 👍 

FYI: iOS Proxyman is going to release the beta soon 🎉

**Comment by xiaozhuai** [comment]
That would be nice! Thank you!

**Comment by NghiaTranUIT** [comment]
Just let an update that this feature is implemented. Please checkout the latest build with the Scripting Tool (https://docs.proxyman.io/scripting/script) 🎉

**Comment by xiaozhuai** [comment]
@NghiaTranUIT Good job! Thank you!
