### ISSUE TITLE
Feature request: record/display responses when using "Repeat" and "Edit and Repeat" when recording is paused

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#553]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.2.0
### macOS Version? (Ex. mac 10.14)
macOS 10.14.6

It would be helpful if any time a request is generated from within Proxyman that the request/response are recorded, since there may be no other way to see the result of this manual request.

I typically have a lot of remote devices sending traffic through proxyman. Sometimes I pause recording to help me focus on a specific range of requests. While in this state, I may edit and repeat a request, only to remember afterwards that recording is paused.

I could see this happening in a few different ways, though I don't know whether any of these are the best approach:
- always record edited requests (could be an option?)
- prompt to enable recording when submitting an edited request while paused
- add an option, e.g. "Record response" to the Compose window, similar to "Close window after send"

I prefer the first option, as I won't have to remember to enable anything, but I'm sure the others would work just as well after a little muscle memory retraining. :)

Thanks

**Comment by NghiaTranUIT** [comment]
> always record edited requests (could be an option?)

Totally agree with you, and I prefer the first approach since it's easier for the end-users 😄 

I'm working on it now and send you a beta asap 👍

**Comment by NghiaTranUIT** [comment]
Please check out this fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.2.0_Edited_Request_Issues.dmg

Basically, you can the edited requested will always show on the Table regardless of the Recording or Overriden HTTP Proxy option.

![2020-07-16 09 50 25](https://user-images.githubusercontent.com/5878421/87622824-23c96880-c74e-11ea-99bb-97cd20d1ef44.gif)

**Comment by crankygeek** [comment]
I ran the fix through a few sessions and the implementation is perfect for me. Couldn't think of good edge cases to play with, but basic functionality looks to be working as expected.

Thanks!
