### ISSUE TITLE
[Feature Request] Upstream proxy support

### ISSUE THREAD

**Issue by gredman** [ProxymanApp/Proxyman#568]
### Proxyman version? (Ex. Proxyman 1.4.3)

2.3.0

### macOS Version? (Ex. mac 10.14)

10.15.5

### Steps to reproduce 

Use Proxyman behind a corporate HTTP proxy.

### Expected behavior

Proxyman sends requests via upstream proxy.

### Actual behavior

Proxyman appears to be unable to use an upstream proxy.

**Comment by NghiaTranUIT** [comment]
Hi, if I understand correctly, you can use [External Proxy tool](https://docs.proxyman.io/advanced-features/external-proxy) to config Proxyman as an upstream proxy.

Basically, you set proxy host/port to the External Proxy, and all traffic will go through your corporate HTTP Proxy 👍

**Comment by gredman** [comment]
That's perfect, thanks a lot! 😄
