### ISSUE TITLE
Crash when reordering rules in Allow List

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#571]
Proxyman is crashing when I try to reorder the rules in the Allow List. Crash log attached.

[Proxyman_2020-08-05-094539_Argon.crash.zip](https://github.com/ProxymanApp/Proxyman/files/5029904/Proxyman_2020-08-05-094539_Argon.crash.zip)

### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.3.0 (20300)

### macOS Version? (Ex. mac 10.14)
MacBook Pro (15-inch, 2016) macOS 10.14.6

### Steps to reproduce 
1. Open Tools > Allow List
2. Check "Enable Allow List Tool"
3. Add a few rules
4. Click and drag a rule to another position in the list
5. Drop and observe Proxyman quits

**Comment by NghiaTranUIT** [comment]
I plan to support #550 and fix this issue too 🙌

**Comment by NghiaTranUIT** [comment]
Fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.3.0_Improve_UI_Add_Repeat_With_No_Caching.dmg
