### ISSUE TITLE
unzip response body 

### ISSUE THREAD

**Issue by trycatchx** [ProxymanApp/Proxyman#604]
hi:
I am the author of this issue [#600 ](https://github.com/ProxymanApp/Proxyman/issues/600#issue-687944474)
 I use scripting to modify response.body.
this is my code:
```
function onResponse(context, url, request, response) {
  console.log('begin');
  var bodyString = JSON.stringify(response.body);
  console.log(bodyString);
  console.log(typeof(response.body));
  // Done
  return response;
}
```
console output:
----------------------------------
```
13:02:31.661: [onResponse] with Request ID=133
begin
{}
object
```
I am sure the body is non-empty, but it is gzip.
Why body prints ->  {} , it is null ?

Looking forward to your reply！

**Comment by NghiaTranUIT** [comment]
Hi @zhangchaojiong can you show me the `console.log(response)` 🤔

**Comment by NghiaTranUIT** [comment]
`response.body` might be not a JSON object, so `JSON.stringify()` would return `{}`.

Please help me to log the response or response.body to see what it's 😄

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT  

Sorry to keep you waiting.

According to your suggestion, I modified my code：


```
function onResponse(context, url, request, response) {

  console.log('begin');
  
 var bodyString = JSON.stringify(response.body);
 console.log(bodyString);
 console.log(response.body);
 console.log(response);
   //unzip(bodyString)；
 
  // Done
  return response;
}
```


console ouput:

```
----------------------------------
21:24:09.755: [onResponse] with Request ID=351
begin
{}
{}
{
	"statusCode": 200,
	"headers": {
		"U-Location": "1682005182_1683911704",
		"Date": "Sun, 30 Aug 2020 13:24:09 GMT",
		"Keep-Alive": "timeout=50",
		"Server": "nginx",
		"Connection": "keep-alive",
		"Area": "sz",
		"Content-Type": "application/octet-stream",
		"Content-Length": "1241",
		"Content-Encoding": "gzip"
	},
	"body": {},
	"httpVersion": "HTTP/1.1",
	"statusPhrase": "OK"
}
21:24:09.773 onResponse() is executed!
```

I am sure the http response.body is not null  .
I use postMan to send http post requests, and use proxyMan to intercept them. 
But the body on postman is not empty, proxyMan cannot print out body？

![image](https://user-images.githubusercontent.com/6050250/91660470-b0669500-eb08-11ea-9e73-c55b3a1ab3af.png)



Finally, I request a non-gzip body, both postman and proxyman can run normally.
Why is the gzip body missing?

**Comment by NghiaTranUIT** [comment]
Thank for the screenshot. It looks like a bug for the binary body. I’m fixing it now 👍

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT 

Thank you for your precious time and look forward to your repair！

**Comment by NghiaTranUIT** [comment]
@zhangchaojiong Please check out this build: https://download.proxyman.io/beta/Proxyman_2.5.2_Binary_Body_Scripting.dmg

If the body is a binary data, it will convert to base64 encoded String, so please make sure using `atob()` to decode to `Uint8Array`. If you would like to ungzip, you can directly pass it as a param

```js
const { ungzip, gzip } = require("@addons/Pako.js")

console.log(request.body) 
// Print: Base64 encoding string

var content = ungzip(request.body)
console.log(content);
// Print content string
```

If you would like to pass the Binary to the body, make sure you convert to base64 Encoded String too 👍 

For instance,
```js
// Import gz file
// File is converted to base64 encoded string
const file = require("@users/4BFC1646.httpbin.gz");

function onResponse(context, url, request, response) {

  response.body = file;

  // Done
  return response;
}
```

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT 

[https://download.proxyman.io/beta/Proxyman_2.5.2_Binary_Body_Scripting.dmg](https://download.proxyman.io/beta/Proxyman_2.5.2_Binary_Body_Scripting.dmg)

wow, it works well ！
Save me a lot of time.

**Comment by NghiaTranUIT** [comment]
Glad to hear that 😄 and thank you for reporting those bugs 👍
