### ISSUE TITLE
SSL Handshake Failed handshakeFailed (NIOSSL.BoringSSLError.sslError ([Error: 268436502 error: 10000416: SSL routines: OPENSSL_internal: SSLV3_ALERT_CERTIFICATE_UNKNOWN]))

### ISSUE THREAD

**Issue by chornerman** [ProxymanApp/Proxyman#609]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.5.3

### macOS Version? (Ex. mac 10.14)
10.15.6

### Steps to reproduce
1. Connect Android device with the same network as laptop (Android device and laptop both have certificate installed, and already set the Wifi proxy, also I already added network_security_config.xml in the manifest file of the application, and it has exact same code as the tutorial)
2. Open the app that enabled HTTPS response

### Expected behavior
Show response correctly with no error

### Screenshots (optional)
<img width="630" alt="Screen Shot 2563-08-31 at 16 14 00" src="https://user-images.githubusercontent.com/13492460/91703842-0557e900-eba5-11ea-87b1-7a5da05f6db4.png">

**Comment by NghiaTranUIT** [comment]
Hi @chornerman, can you help me to verify that you've config in res/xml/network_security_config.xml and manifest.xml? Step 3-4 in Android Doc https://docs.proxyman.io/debug-devices/android-device 🤔 

and make sure that it's your Android app, since it's impossible to intercept the HTTPS Traffic from apps that you don't control

**Comment by chornerman** [comment]
Thanks, @NghiaTranUIT for a really fast reply 🙏 
Here is my `network_security_config.xml` code
`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <domain-config>
        <domain includeSubdomains="true">some_url
        </domain>
        <trust-anchors>
            <certificates src="user" />
            <certificates src="system" />
        </trust-anchors>
    </domain-config>
</network-security-config>`

and I added this line to the manifest inside the application tag

`android:networkSecurityConfig="@xml/network_security_config"`

**Comment by NghiaTranUIT** [comment]
Hi, there are many reasons why you might not intercept from your Android:
1. Look like you're missing `network-security-config` tag. From your code, it only has `base-config` and `domain-config`. You can checkout the Android Doc
```xml
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <!-- Trust user added CAs while debuggable only -->
            <certificates src="user" />
            <certificates src="system" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>
```
2. Is your app using SSL-Pining? If yes, please disable it.

**Comment by chornerman** [comment]
Now my `network-security-config` code looks like this

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <!-- Trust user added CAs while debuggable only -->
            <certificates src="user" />
            <certificates src="system" />
        </trust-anchors>
    </debug-overrides>

    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <domain-config>
        <domain includeSubdomains="true">some_url
        </domain>
        <trust-anchors>
            <certificates src="user" />
            <certificates src="system" />
        </trust-anchors>
    </domain-config>
</network-security-config>
```
and it's still doesn't work 😢

**Comment by NghiaTranUIT** [comment]
Can you share with me what the Android emulator is? and the Android Version. I would like to download and try to reproduce in my machine 😄 

I will send you a sample Android project that works, then you can reapplying in your project 👍

**Comment by chornerman** [comment]
I use a physical device, Samsung Galaxy S10e with Android 10

**Comment by NghiaTranUIT** [comment]
I checked Pixel XL Emulator (Android Studio) with Android 29, and it worked fine. I'm able to see the traffic from `https://www.google.com`

<img width="1678" alt="Screen Shot 2020-08-31 at 16 56 26" src="https://user-images.githubusercontent.com/5878421/91708117-0db32280-ebab-11ea-9e3d-f5dd1c0dce3d.png">

------------------
### Config
- Set Proxy in Wifi Setting
- open `proxy.man/ssl` in Google Chrome and install the certifciate
- res/xml/network_security_config.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <!--Set application-wide security config using base-config tag.-->
    <!--Set domain-specific security config using domain-config tags. -->
    <!--See https://developer.android.com/training/articles/security-config.html for more information.-->
    <debug-overrides>
        <trust-anchors>
            <!-- Trust user added CAs while debuggable only -->
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <domain-config>
        <domain includeSubdomains="true">www.google.com</domain>
        <trust-anchors>
            <certificates src="user"/>
            <certificates src="system"/>
        </trust-anchors>
    </domain-config>
</network-security-config>
```

- manifest.xml
```xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.networkconnect"
    android:versionCode="1"
    android:versionName="1.0">

    <!-- Min/target SDK versions (<uses-sdk>) managed by build.gradle -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:theme="@style/Theme.Sample"
        android:allowBackup="true"
        android:networkSecurityConfig="@xml/network_security_config">
        <activity
            android:name="com.example.android.networkconnect.MainActivity"
            android:label="@string/app_name"
            android:uiOptions="splitActionBarWhenNarrow">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```
- Download Project: 
[NetworkConnect.zip](https://github.com/ProxymanApp/Proxyman/files/5149670/NetworkConnect.zip)


----------
Can you try to run this project on your physical device?

**Comment by chornerman** [comment]
Sorry for a late response, it's not work either
<img width="952" alt="Screen Shot 2563-08-31 at 17 58 35" src="https://user-images.githubusercontent.com/13492460/91713274-a5b50a00-ebb3-11ea-9c67-9a0da3ad5017.png">

**Comment by NghiaTranUIT** [comment]
That's strange. I'm not sure what causes the bug on your Samsung machine 🤔 

Can you try to run your project on Android Studio? and Do you app have SSL-Pining?

**Comment by chornerman** [comment]
Yes, I can run it on Android Studio and the app doesn't have SSL-Pinning

**Comment by NghiaTranUIT** [comment]
so I'm not sure how to fix it since it works fine in your Android Emulator. Maybe Samsung devices need extra steps in order to trust Proxyman Certificate 🤔 

The error means that your device doesn't trust the Proxyman Certificate.

**Comment by chornerman** [comment]
I try reinstalling the certification on my Samsung device and it's work as expected this time.
Thank you @NghiaTranUIT 😄

**Comment by NghiaTranUIT** [comment]
Happy coding 🙌
