### ISSUE TITLE
request.body in scripting is incorrect

### ISSUE THREAD

**Issue by trycatchx** [ProxymanApp/Proxyman#615]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.5.3

1、The http.body of my request on the homepage is like this.
![image](https://user-images.githubusercontent.com/6050250/92217500-5aa83900-eeca-11ea-9868-7556a255274b.png)
`{"req_0":{"method":"GetNewCommentList","module":"music.globalComment.CommentReadServer","param":{"BizType":31,"BizId":"012wNuzn25fa0b","LastCommentId":"","LastCommentSeqNo":"","PageSize":15,"PageNum":0,"FromCommentId":"","WithHot":1}},"comm":{"g_tk":5381,"uin":0,"format":"json","platform":"h5","ct":23,"cv":0}}`

2、The same http.body is displayed differently in scripting：
![image](https://user-images.githubusercontent.com/6050250/92217726-a955d300-eeca-11ea-9200-a4c8b4614ac4.png)
```
{
  "{\"req_0\":{\"method\":\"GetNewCommentList\",\"module\":\"music.globalComment.CommentReadServer\",\"param\":{\"BizType\":31,\"BizId\":\"012wNuzn25fa0b\",\"LastCommentId\":\"\",\"LastCommentSeqNo\":\"\",\"PageSize\":15,\"PageNum\":0,\"FromCommentId\":\"\",\"WithHot\":1}},\"comm\":{\"g_tk\":5381,\"uin\":0,\"format\":\"json\",\"platform\":\"h5\",\"ct\":23,\"cv\":0}}": ""
}
```
I am use this code to print it:
```
function onRequest(context, url, request) {
  // add header
  var jsonBody = request.body;
  console.log(formatJSON(JSON.stringify(jsonBody)))
  
  return request
}
```

The requset.body in scripting is wrong ? which makes me unable to modify requset.body.

@NghiaTranUIT  Can you help me solve it?

**Comment by NghiaTranUIT** [comment]
@zhangchaojiong  Since the ContentType of the Request is `form-urlencoded`, so Proxyman attempts to parse the body as a Form. Thus, you get the weird body.

There are two way to fix it:
1. If you're a developer of this app, please try to change the Content Type of the Request from your app. It should be `application/json`. Then, `request.body` is a JSON Object

2. Or You can fix in the script by using
```js
function onRequest(context, url, request) {
    // Change the Content Type to JSON
    request.headers["Content-Type"] = "application/json"

    // Get json from the weird body
    var firstKey = Object.keys(request.body)[0];
    var jsonBody = JSON.parse(firstKey)
    // Update some key
    jsonBody["new-key"] = "Proxyman"

   // Assign again
   request.body = jsonBody;
   return request;
}
```

3. I will try to guess and parse body properly or find the way to return raw Body without parsing in the next build 👍

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT 👍  you are right ！！thx ！

**Comment by NghiaTranUIT** [comment]
In the next build, I will add `rawBody` into `request` and `response`. Thus, you can get the raw body without depending on Content-Type, then you can parse whatever you like 👍 😄

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT  Looking forward to your next version！

**Comment by NghiaTranUIT** [comment]
Good news that I supported `rawBody` in the **request** and **response** objects @zhangchaojiong 

It's a raw String or Base64 encoded String (for binary data), then you can manually parse it 👍 

https://docs.proxyman.io/scripting/script

**Comment by zhangchaojiong** [comment]
@NghiaTranUIT Happy to hear it！！ 👍
