### ISSUE TITLE
[Suggestion] Send Edit and Repeat request with keyboard shortcut

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#635]
I'd like to be able to send requests from the Compose window using a keyboard shortcut instead of having to click Send. I recommend ⌘+return as it doesn't appear to have any conflicts.

**Comment by NghiaTranUIT** [comment]
Let check it out https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.7.0_Shortcut_Send_Compose_Request.dmg

You can use CMD+Return to send a request 👍 

<img width="739" alt="Screen Shot 2020-09-25 at 9 37 39 AM" src="https://user-images.githubusercontent.com/5878421/94221710-d9b2ef00-ff15-11ea-9daf-d62c3b6aaa0a.png">

**Comment by crankygeek** [comment]
@NghiaTranUIT Works great. Thanks!
