### ISSUE TITLE
Blacklist/Exclude certain domains from SSL Proxying List

### ISSUE THREAD

**Issue by ablewalmsley** [ProxymanApp/Proxyman#646]
### Proxyman version? (Ex. Proxyman 1.4.3)

2.8.0

### macOS Version? (Ex. mac 10.14)

10.15.4

### Screenshots (optional)

Is it possible to exclude certain HTTPS domains from being intercepted in the SSL Proxying List?  For example, when intercepting traffic on an iOS device, domains like apple.com or google.com usually have pinned SSL certificates that can't be worked around, and can cause some problems if the request isn't fulfilled, but I do want to track all other HTTPS traffic.  I'm looking for something similar to what Charles (an include and exclude list, see screenshot).
<img width="583" alt="Screen Shot 2020-09-30 at 7 01 29 PM" src="https://user-images.githubusercontent.com/8855697/94748445-5a774e00-034f-11eb-9e01-ad12f6d1d431.png">

**Comment by NghiaTranUIT** [comment]
Hi @ablewalmsley,

As we haven't supported this feature on Proxyman yet, but you achieve the same things by following:

- If you would like to exclude traffic from macOS, you can set it as a by-pass list. It acts like Exclude List

<img width="780" alt="Screen_Shot_2020-10-01_at_8_25_27_AM" src="https://user-images.githubusercontent.com/5878421/94755746-bd083280-03bf-11eb-991d-8cce97f62eda.png">

- If it's traffic from iOS devices/simulator, you can automatically exclude by enabling this option in Preference

<img width="702" alt="Screen_Shot_2020-10-01_at_8_24_27_AM" src="https://user-images.githubusercontent.com/5878421/94755773-cee9d580-03bf-11eb-9c72-3bcfe5c09eba.png">

**Comment by NghiaTranUIT** [comment]
Meanwhile, I will push this feature forward and would support it soon 👍

**Comment by ablewalmsley** [comment]
thanks! This is a great workaround for the time being.

**Comment by speto** [comment]
👍 this feature would be nice. I've been missing that since I migrated from Charles too.

**Comment by NghiaTranUIT** [comment]
Good news that I'm working on this feature 👍 Stay tuned for the beta build 😄

**Comment by NghiaTranUIT** [comment]
Hey @speto @ablewalmsley let check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.13.0_SSLProxying_With_Include_Exclude.dmg

From now, you can add wildcard, app, domain to Include List or Exclude List 👍 

<img width="1172" alt="Screen Shot 2020-11-24 at 16 49 16" src="https://user-images.githubusercontent.com/5878421/100077725-45adc700-2e75-11eb-96a1-05c3fe2d87e3.png">

**Comment by ablewalmsley** [comment]
Working great so far! Thanks!
