### ISSUE TITLE
[Security] External proxy settings displays password

### ISSUE THREAD

**Issue by beeloo42** [ProxymanApp/Proxyman#659]
### Proxyman version? (Ex. Proxyman 1.4.3)
version 2.9.1

### macOS Version? (Ex. mac 10.14)
macOS 10.15.6

### Steps to reproduce 
In Proxyman, open the Tools -> Proxy Settings -> External Proxy Settings... sheet
Select the HTTP or HTTPS proxy configuration.
The password text field is displayed not obfuscated.....

### Expected behavior
The text field should display some bullets instead of the password.
(ie. the NSTextField should be a NSSecureTextField)

### Screenshots (optional)

<img width="590" alt="Screenshot 2020-10-15 at 15 17 59" src="https://user-images.githubusercontent.com/8369290/96131734-dcdc4200-0ef9-11eb-9e55-8735e3d3715e.png">

**Comment by NghiaTranUIT** [comment]
Thanks for reporting it. I'm not sure why I can miss the important thing like that at the first place 😳

I'm fixing it now 👍

**Comment by beeloo42** [comment]
Sometimes it happens :)

Thank you !

**Comment by NghiaTranUIT** [comment]
All done now 🙌 https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.9.1_Secure_TextField_External_Proxying.dmg

<img width="618" alt="Screen Shot 2020-10-17 at 09 43 29" src="https://user-images.githubusercontent.com/5878421/96327068-61e16b80-1060-11eb-9774-e19ecfc549c6.png">

Thanks for your patience 😄

**Comment by beeloo42** [comment]
Thank you for the fix in 2.9.10 !
