### ISSUE TITLE
Ability to add delay for responses

### ISSUE THREAD

**Issue by amorphius** [ProxymanApp/Proxyman#664]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.10.0

### macOS Version? (Ex. mac 10.14)
mac 10.13

I really need to have ability to delay some responses in scripting. Ideally using Promises. But I was told that's not possible. Maybe there are any workarounds to achieve delays?

**Comment by NghiaTranUIT** [comment]
It seems that JavaScriptCore from Apple doesn’t officially support Promise.

I will find the way to support fetch api, then you can convert your Promise to fetch and make request asynchronously.

**Comment by amorphius** [comment]
It's not only about fetches but implementing simple delay for response when I want to emulate slow connection for particular request.

**Comment by NghiaTranUIT** [comment]
Hey @amorphius, let check out this BETA build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.10.0_Add_Sleep_Func.dmg

Basically, you can use `sleep()` function to make the current thread sleep synchronously. Please beware that `sleep()` takes milliseconds as a param.

For instance,
```js
function onResponse(context, url, request, response) {
  console.log("Start sleep");
  
  // Sleep 5 seconds
  sleep(5000);
  
  console.log("Done")
  
  // Done
  return response;
}
```

I tested and it will delay 5 seconds before returning the Response to my client app 🙌

**Comment by amorphius** [comment]
It works, great job! Thank you!
