### ISSUE TITLE
Starman Icon

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#669]
@NghiaTranUIT Here's my attempt at creating a custom icon. I've never used Figma, so let me know if you have any suggestions or need any changes made.

Thanks!

[starman.fig.zip](https://github.com/ProxymanApp/Proxyman/files/5432509/starman.fig.zip)

**Comment by NghiaTranUIT** [comment]
Thank @crankygeek for the new idea 🙌 

But the logo quality looks pixelated and the shadow of the icon is absent.

Here is the template that you can recreate from it

[Proxyman-Template.fig.zip](https://github.com/ProxymanApp/Proxyman/files/5432512/Proxyman-Template.fig.zip)

You can show/hide the template that @mhdhejazi created.

From it, you can add the icon, and change the background if you like 😄 

<img width="244" alt="Screen Shot 2020-10-24 at 13 51 21" src="https://user-images.githubusercontent.com/5878421/97070141-303c4780-1600-11eb-9914-599e8bbe338e.png">
