### ISSUE TITLE
[Bug] Do not see URLs after pinning a domain

### ISSUE THREAD

**Issue by 8bitzz** [ProxymanApp/Proxyman#67]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
`Version 1.3.2 (1320)`

### What OS Version are you using? (Ex. mac 10.13)
`MacOS 10.14.2 (Mojavae)`

### Steps to reproduce this issue
- Select a domain from `All Domain` (e.g: got-it.ai) 
- Right click to pin the domain 

### Expected result:
- See all URLs from domain `got-it.ai` on the `Flow List`

### Actual result:
- Do not see URLs from domain `got-it.ai` on the `Flow List`

### Screenshots (optional)
<img width="1479" alt="Screen Shot 2019-03-14 at 1 54 43 PM" src="https://user-images.githubusercontent.com/23531403/54337270-fc95ef00-4660-11e9-8c77-a720a1e6aa4d.png">

**Comment by NghiaTranUIT** [comment]
All done 🥇 

## 🤯 Changelogs
- [x] Introduce convenience initializer to clone the FlowItem when appending to Folder
- [x] Add FlowItem (weak) to TrackEntry
- [x] Improve the logic for appending new Flow Item -> Should clone it before proceeding.
