### ISSUE TITLE
Please allow dragging from "Listening on port" view

### ISSUE THREAD

**Issue by MerchV** [ProxymanApp/Proxyman#670]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.10.0 (21000)

### macOS Version? (Ex. mac 10.14)
macOS 11.0 Beta (20A5395g)

### Steps to reproduce 
• Drag with cursor the little area at the top where it says **Proxyman | Listening on port 9090**

### Expected behavior
• I expect to be able to drag and move the Proxyman window by dragging here. Xcode has a very similar status view at the top of its window. Not being able to drag the Proxyman window by clicking here feels very strange.

**Comment by NghiaTranUIT** [comment]
Hi, I tried before but it doesn't work as expected because Xcode might use some sort of Private APIs or something to pass the drag mouse event to the behind windows 😄   

I will research again and fix it 🙌

**Comment by NghiaTranUIT** [comment]
It's possible now with this -mousedowncanmovewindow 😄  https://developer.apple.com/documentation/appkit/nsview/1483666-mousedowncanmovewindow
