### ISSUE TITLE
[UX improvement] Detail_Panel overlap information on Flow_List

### ISSUE THREAD

**Issue by 8bitzz** [ProxymanApp/Proxyman#68]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
`Version 1.3.2 (1320)`

### What OS Version are you using? (Ex. mac 10.13)
`MacOS 10.14.2 (Mojavae)`

### Steps to reproduce this issue:
- Open app to see `All App`/ `All Domains`
- See `Detail Panel` show up before selecting an URL & overlap information on `Flow List` 

### Expected result:
- `Detail Panel` show up after selecting an URL

### Screenshots (optional) 
<img width="1385" alt="Screen Shot 2019-03-14 at 2 00 31 PM" src="https://user-images.githubusercontent.com/23531403/54337572-eb99ad80-4661-11e9-8d98-c8908f36da72.png">

**Comment by NghiaTranUIT** [comment]
All done 💯 

## 🤯 Changelogs 
- [x] Hide Flow Content (Right-panel) at the first launch
- [x] Auto select first item and expand Flow Content in first launch
- [x] Fix bug when resizing the Flow List if the Flow Content is expanding.
