### ISSUE TITLE
Proxyman could not be updated on macOS Big Sur

### ISSUE THREAD

**Issue by vani2** [ProxymanApp/Proxyman#688]
### Proxyman version?

2.12.0

### macOS Version?

11.0.1 Beta (20B5022a)

### Steps to reproduce 

Update the app from previous version or download dmg file from official website.
The error occurred.

### Expected behavior

App is updated or mounted.

### Screenshots

<img width="372" alt="Screenshot 2020-11-12 at 15 00 09" src="https://user-images.githubusercontent.com/4734983/98937666-caa0f400-24f7-11eb-8e5b-2ffa198a4b40.png">

<img width="484" alt="Screenshot 2020-11-12 at 14 59 24" src="https://user-images.githubusercontent.com/4734983/98937609-b0ffac80-24f7-11eb-81fd-eed59caa7b0c.png">

**Comment by NghiaTranUIT** [comment]
Thanks for the report. I’m checking it now

**Comment by NghiaTranUIT** [comment]
@vani2 to workaround, please download previous build from https://proxyman.io/blog/2019/06/changelogs.html

For the bug, I’m fixing now

**Comment by vani2** [comment]
Hm, after restart 2.12.0 installed successfully. Seems like a Big Sur bug.

**Comment by NghiaTranUIT** [comment]
I just tested on Big Sur 11.0.1 beta and it works fine for the first time. The bug might be from the system 🤔 

Btw, I will keep watching this issue and find the fix if possible 👍

**Comment by NghiaTranUIT** [comment]
It seems that the bug is from Big Sur. I see there are several apps that have been encountered the same issue, such as AirBuddy app.

To fix it, just restart the computer.
