### ISSUE TITLE
[UX Improvement] Keep the format selected for the next URLs

### ISSUE THREAD

**Issue by 8bitzz** [ProxymanApp/Proxyman#69]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
`Version 1.3.2 (1320)`

### What OS Version are you using? (Ex. mac 10.13)
`MacOS 10.14.2 (Mojavae)`

### Steps to reproduce this issue:
- Select an URL (id_217) to see the response
- Select `JSON` format
- Move down to the next URL (id_218)

### Expected result:
- See `JSON` format is also selected on `Response Panel` of URL (id_218)

### Actual result:
- See `Header` is selected on `Response Panel of URL (id_218)

### Screenshots (optional)
<img width="1385" alt="Screen Shot 2019-03-14 at 2 14 04 PM" src="https://user-images.githubusercontent.com/23531403/54338085-7929cd00-4663-11e9-8031-4fd2609036d5.png">
<img width="1341" alt="Screen Shot 2019-03-14 at 2 13 54 PM" src="https://user-images.githubusercontent.com/23531403/54338086-79c26380-4663-11e9-8c56-a162f673be38.png">

**Comment by NghiaTranUIT** [comment]
All done 💯 

## 🤯 Changelogs 
- [x] Don't resetAll Tabs of ContentView -> it's too heavy task -> Jump and flicking  
- [x] Improve the way to enable/disable Tabs more efficient.
