### ISSUE TITLE
Can't open Proxyman on MacOS Big Sur

### ISSUE THREAD

**Issue by pvthiendeveloper** [ProxymanApp/Proxyman#696]
### Steps to reproduce
Step 1: Just launched the app
Step 2: Observer

### Expected behavior: 
Application launches normally

**Comment by NghiaTranUIT** [comment]
Hi, can you try download from this link: https://github.com/ProxymanApp/Proxyman/issues/692#issuecomment-728143810

I'm using the latest Proxyman 2.12.0 on Big Sur 11.0.1 without any problem.

If you couldn't open, can you share the error message?

**Comment by pvthiendeveloper** [comment]
This is the error log file [proxyman_error_log.txt](https://github.com/ProxymanApp/Proxyman/files/5551160/proxyman_error_log.txt)

**Comment by NghiaTranUIT** [comment]
@pvthiendeveloper thanks for the message report.

Can you try on the build: https://download.proxyman.io/beta/Proxyman_2.12.0_Big_Sur_amd64_v2.dmg to see if work?

**Comment by pvthiendeveloper** [comment]
Yes, I deleted the old version and installed this new one, but still crashes.

**Comment by NghiaTranUIT** [comment]
It's odd. I'm unable to reproduce it in mime and my friend's machines 😢 

The error log just shows that the Main Thread is hung and it's killed by the system.

If you don't mind, please help me open the app from `/Applications/Proxyman.app/Contents/MacOS/Proxyman`

It will open the terminal with some useful Log and share with me the log 👍

**Comment by pvthiendeveloper** [comment]
Thanks for your support!

I removed Proxyman using AppCleaner software, then I installed the new version and it worked again.

I think the error happens when I don't delete all of Proxyman's linked file.

**Comment by NghiaTranUIT** [comment]
Glad to know that it works for you.

I will keep an eye on this issue because you can simply delete the app by dragging Proxyman to the Trash Bin without needing to use AppCleaner. It should work too.
