### ISSUE TITLE
[BUG] Incorrect Renewal Price

### ISSUE THREAD

**Issue by fishcharlie** [ProxymanApp/Proxyman#698]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/860375/99412231-bc652600-28b1-11eb-9a6f-05d343d53dba.png">

The Proxyman website says it costs $25 to renew per device. But it's trying to charge me double that.

**Comment by NghiaTranUIT** [comment]
Hi @fishcharlie, can you verify that your license has two seat? You can find the Proxyman license from support@proxyman.io in your inbox.

If it's two-seat, the price is correct (Qty.2)

If you would like to renew only 1 seat. Please let me know. I'm happy to change it in the database, so the price is 25$

**Comment by fishcharlie** [comment]
@NghiaTranUIT 

<img width="258" alt="image" src="https://user-images.githubusercontent.com/860375/99413578-29c58680-28b3-11eb-9278-8b493eef071d.png">

I currently only use 1 device. As long as I can add additional devices later, I'd only like to renew 1 device for now. Maybe I'll add more later if I have the need for it.

**Comment by NghiaTranUIT** [comment]
Please send me your email to support@proxyman.io. We will reduce the license seat to 1, then you can renew for 1 seat (25$) 👍

**Comment by fishcharlie** [comment]
@NghiaTranUIT Just sent! Will close this issue now. Thanks for your help.
