### ISSUE TITLE
Map Local improvements

### ISSUE THREAD

**Issue by amorphius** [ProxymanApp/Proxyman#700]
I work a lot with Map Local tool and have many rules in the list so I have few suggestions how to improve my experience when working with it.
1. There is no way to organize long list of Map Local rules (for example when there is more than 100 rules). Is it possible to group them by folder?
2. There is no way to check/uncheck selected rules. For example I have 100 rules and I want to leave 50 of them checked and other 50 unchecked. Now I have to check/uncheck each rule separately.
3. When creating new rule in Map Local Editor when I click on Select Local File folder it always opens my Desktop not the folder which I used for this for the last 100 times. Would be better to remember last used folder.

**Comment by NghiaTranUIT** [comment]
Thanks for the detailed improvement proposal. It totally makes sense 👍 

1. Unfortunately, it's not possible at the moment, there are few requests in the past at #590. I will push it forward 

2. Totally agree. I will add a shortcut to quickly enable/disable each rule. Therefore, you can select multiple items and enable/disable them

3. Cool. Doing now 

Will send you a beta build this week 👍

**Comment by NghiaTranUIT** [comment]
Hey @amorphius 

Let check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.13.0_Shortcut_Enable_Rules_Remember_Selected_Folder.dmg

From now, you can: 
- Enable/Disable Rule (⌘T) for multiple selections
- Select Folder now remember your last selection.

![2020-11-20 15 52 10](https://user-images.githubusercontent.com/5878421/99787653-99a56c80-2b52-11eb-81b7-9e99e993523a.gif)

**Comment by amorphius** [comment]
thanks!

**Comment by amorphius** [comment]
@NghiaTranUIT BTW how fast those changes get to official release? I've updated my Proxyman to version 2.14.1 and those changes were gone.
