### ISSUE TITLE
Proxyman never capture Google Chrome's request 

### ISSUE THREAD

**Issue by gniw** [ProxymanApp/Proxyman#722]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 2.14.1

### macOS Version? (Ex. mac 10.14)
macOS Big Sur 11.0.1

### Steps to reproduce 
1. Download latest dmg from Official Site
https://proxyman.io/
2. Install app
3. Install Certificate follow this page
https://docs.proxyman.io/debug-devices/macos
4. Launch Google Chrome, visit `https://www.google.com/`, or anywhere
5. Proxyman say nothing

after that, I restart Chrome, Proxyman, and also mac.
But Proxyman keep silent.

Curiously, a few requests are displayed like ...
`https://sb-ssl.google.com/safebrowsing/clientreport/download?key=...`
`https://safebrowsing.googleapis.com/v4/fullHashes:find?$req=...`
`https://update.googleapis.com/service/update2/json?cup2key=...`

Why is it like this...?

### Expected behavior

capture all request.
of course, HTTP and HTTPS.

### Screenshots (optional)

<img width="600" alt="Screen Shot 2020-12-09 at 22 28 38" src="https://user-images.githubusercontent.com/6947659/101636366-907f2f80-3a6e-11eb-982f-bd9d0d73c958.png">

**Comment by NghiaTranUIT** [comment]
Just wondering: Can you see google.com request from Safari?

**Comment by NghiaTranUIT** [comment]
If you couldn't see any HTTP/HTTPS Traffic that shows on Proxyman, it looks like your System HTTPS doesn't set to 9090.

Can you help me to open Network -> Wifi -> Proxies -> Verify that HTTP and HTTPS is checked with 127.0.0.1 at port 9090?

<img width="780" alt="Screen Shot 2020-12-09 at 20 40 51" src="https://user-images.githubusercontent.com/5878421/101637076-d59b6580-3a5e-11eb-843e-2dae73b48c11.png">

If it isn't, please install the Proxyman Helper Tool in Preference -> Advanced -> Install Helper Tool

**Comment by NghiaTranUIT** [comment]
Meanwhile, the invalid URLs from your screenshot is from Google Chrome Extension. I see it a lot and it happens in other Proxy tools like Charles too.

**Comment by gniw** [comment]
> Just wondering: Can you see google.com request from Safari?

Yes, I can access google.com by Safari, and show requests.

> Can you help me to open Network -> Wifi -> Proxies -> Verify that HTTP and HTTPS is checked with 127.0.0.1 at port 9090?

Yes, HTTP and HTTPS is checked with 127.0.0.1:9090.

> Meanwhile, the invalid URLs from your screenshot is from Google Chrome Extension.

Oh, that's right!
I installed a lot of extensions for web develop. 
For now, all extensions turned off, Proxyman capture all requests!
of course, HTTP and HTTPS :)

Thank you for your quick response!!

**Comment by gniw** [comment]
resolved, thank you ❤️

**Comment by NghiaTranUIT** [comment]
Cool. So, one of your extension causes the traffic doesn't go through Proxyman Proxy Server at port 9090 😄 

Enjoy debugging 👍
