### ISSUE TITLE
Cannot be used to intercept .local suffix requests

### ISSUE THREAD

**Issue by leixjin** [ProxymanApp/Proxyman#726]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.14.2 (21420)

### macOS Version? (Ex. mac 10.14)
macOS 10.15.6

### Steps to reproduce 
Open iOS Simulator，run any debug app，send a request with .local suffix

### Expected behavior
Can see the request in proxman

**Comment by NghiaTranUIT** [comment]
Please remove the .local in bypass list from Wifi -> Advanced -> Proxies -> Bypass list. By default, macOS will ignore all local traffic that goes to the Proxyman Proxy 👍

**Comment by NghiaTranUIT** [comment]
Here is the screenshot to make it's easier 😄 @leixjin 

<img width="780" alt="Screen_Shot_2020-12-15_at_17_37_47" src="https://user-images.githubusercontent.com/5878421/102204348-54c7e800-3efc-11eb-875d-a6ffd47a45ba.png">

**Comment by leixjin** [comment]
Thanks！On the simulator it worked.But how to make it work on the iOS device?

**Comment by NghiaTranUIT** [comment]
You can map yourdomain.local to different endpoint in /etc/hosts file, e.g yourdomain.dev 

It will go to proxyman port 👍
