### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by fishcharlie** [ProxymanApp/Proxyman#728]
It'd be great if there was a global search option to search within the body of each request. For example I have a piece of text that I know exists in some response, but I'm not sure which request/response it was part of. So it'd be great if I could search for that piece of text across all my responses.

### Proxyman version? (Ex. Proxyman 1.4.3)

Version 2.14.2 (21420)

### macOS Version? (Ex. mac 10.14)

macOS 11.1

### Steps to reproduce

NA (feature suggestion)

### Expected behavior

NA (feature suggestion)

### Screenshots (optional)

NA (feature suggestion)

**Comment by NghiaTranUIT** [comment]
You can do it with Request/Response filter @fishcharlie 

<img width="1792" alt="Screen_Shot_2020-12-16_at_08_57_54" src="https://user-images.githubusercontent.com/5878421/102294941-e840fd80-3f7c-11eb-9cf0-48b8e47624c0.png">
