### ISSUE TITLE
After X requests, new ones cease to be listed

### ISSUE THREAD

**Issue by avi-kauffmann** [ProxymanApp/Proxyman#735]
### Proxyman version? (Ex. Proxyman 1.4.3) 
2.15.0

### macOS Version? (Ex. mac 10.14) 
10.15.7

### Steps to reproduce 
start sending requests / getting responses for a bit (~2 minutes of constant comms)
at a certain point, requests will start to be listed but disappear (unless if it's manually cleared)

### Expected behavior
Continuous comms are all listed until it's cleared manually

**Comment by NghiaTranUIT** [comment]
Hi, do you have a screenshot to help us reproduce the bug 🤔 We’re trying to reproduce but not luck

**Comment by avi-kauffmann** [comment]
Hi Noah, I attempted to reproduce the issue just now on 2.15.1, but failed successfully. 
I'm certain now it was related to this issue: https://github.com/ProxymanApp/Proxyman/issues/736

Thank you!!!

**Comment by NghiaTranUIT** [comment]
Thank you for letting me know 👏
