### ISSUE TITLE
Network requests are not displayed for the application in Flutter

### ISSUE THREAD

**Issue by yauheniprakapenka** [ProxymanApp/Proxyman#749]
# Debug network requests in Flutter and Proxyman

<img src="https://user-images.githubusercontent.com/47568606/103482144-226d2480-4df0-11eb-82e1-8f3c60ec8b45.jpg" width="260"></a>

Flutter does not use a system-level proxy, so requests to Proxyman will not be displayed. To do this, you must manually configure your HTTP client used in the code to work with a proxy.

<b>Solution</b>:
1. The solution to the problem is described [here](https://flutterigniter.com/debugging-network-requests/)
2. Also example on github [here](https://github.com/yauheniprakapenka/Debug_Flutter_with_Proxyman)

**Comment by NghiaTranUIT** [comment]
Thank you for your contribution. I will add it to the Doc 👍
