### ISSUE TITLE
Proxy setting not saving after restart

### ISSUE THREAD

**Issue by airycanon** [ProxymanApp/Proxyman#750]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.15.2

### macOS Version? (Ex. mac 10.14)
11.1

### Steps to reproduce 
Disable `Tools->Proxy Setting->Override macOS Proxy`, and restart Proxyman.

### Expected behavior
The option `Override macOS Proxy` should be disabled.

**Comment by NghiaTranUIT** [comment]
Hey @airycanon there is an option “don’t override HTTP proxy at launch” in Preference -> General tab, which does the same thing you need.

**Comment by airycanon** [comment]
@NghiaTranUIT Wow, this is great, thanks for your help.
