### ISSUE TITLE
When debugging on device, CPU usage is very high.

### ISSUE THREAD

**Issue by bangerang** [ProxymanApp/Proxyman#755]
### macOS Version? 10.15.4

First of all, thanks for a great product!

I installed Atlantis 1.5.0 into my Xcode project for debugging on device running iOS 14.3. Everything works fine, but I noticed it consumes a lot of CPU and the consumption doesn't seem to go down even though the app is idle.

<img width="560" alt="Screenshot 2021-01-11 at 10 49 49" src="https://user-images.githubusercontent.com/3526934/104166388-06bedb00-53fb-11eb-9031-31a4d850881f.png">

**Comment by NghiaTranUIT** [comment]
Hey @bangerang can you share with us the number of requests are you receiving from the Atlantis framework? Do you receive a lot of request in a short amount of time? 🤔 

I assume that your app sends a huge of number requests to Proxyman, so it might take more CPU to process the data

**Comment by bangerang** [comment]
The app sends 47 request on start. But the CPU level stays at the same level afterwards even though the app isn't making any new requests.

**Comment by NghiaTranUIT** [comment]
Not sure if it's the cause, but maybe there are different requests which come from your MacBook, that not show on the app until you click on "All App/Domain" section.

1. If it happens again, please open the "All domain" section and see how many requests it's

2. Can you share with me how you set up the SSL Proxying List? Is it a huge list? If you're using all wildcard (*), it might increase the CPU usage too.

**Comment by bangerang** [comment]
Odd, I can't reproduce it anymore. I'll close this issue for now, lets call it a glitch in the Matrix 😄. Thanks for the help @NghiaTranUIT

**Comment by NghiaTranUIT** [comment]
Glad to hear that 🌮
