### ISSUE TITLE
Host header set in script is ignored

### ISSUE THREAD

**Issue by britishtea** [ProxymanApp/Proxyman#769]
I'm trying to emulate a Map Remote rule with the "Preserve host header" feature enabled using a Script. It seems that Proxyman ignores any `Host` header set in a script and uses `request.host` instead.

Here's a minimal Script to reproduce

```javascript
function onRequest(context, url, request) { 
  request.headers["Host"] =  "www.not-example.org";
  request.host = "www.example.org";
  
  console.log(request);

  return request;
}
```

### Proxyman version? (Ex. Proxyman 1.4.3)
2.16.1 (21610)
### macOS Version? (Ex. mac 10.14)
11.1 (20C69)
### Steps to reproduce 
1. Add the above script
2. Compose a request to `https://www.example.org`
### Expected behavior
Proxyman sends "www.not-example.org" as Host header instead of "www.example.org".
### Screenshots (optional)

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/791871/106308731-6de4e800-6261-11eb-95dd-6adc89aafaec.png">

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/791871/106308309-cebff080-6260-11eb-95b0-499d3294e1da.png">

**Comment by NghiaTranUIT** [comment]
Thanks. I will double-check this issue and send you a hotifix asap 👍

**Comment by NghiaTranUIT** [comment]
Hey @britishtea Please check out this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.16.1_Scripting_With_Preseve_Host_Header.dmg

You can use `request.preserveHostHeader = true`, Proxyman will keep the Host Header as you wish.

The reason why we override the Host Header in the first place is that the majority of users would change the `host` (like Map Remote), but forget (or don't know) to override the Host Header. As a result, the request might be failed.

```js
function onRequest(context, url, request) {

  request.headers["Host"] = "data.httpbin.org"
  request.preserveHostHeader = true
  
  // Done
  return request;
}
```

### Screenshots
<img width="1409" alt="Screen_Shot_2021-01-30_at_09_31_59" src="https://user-images.githubusercontent.com/5878421/106345616-18055400-62e4-11eb-8170-3f40edbe770c.png">

**Comment by britishtea** [comment]
Thanks @NghiaTranUIT, that was quick! This solves the issue.

Guess I'll be getting a license soon! 😄

**Comment by NghiaTranUIT** [comment]
I appreciate it if you purchase a license to support the development team 😄 🙌

**Comment by makarov-andrey** [comment]
This fix hasn't been released in any version, has it? I have the same problem in 3.15.0.

**Comment by NghiaTranUIT** [comment]
Hey @makarov-andrey it's already fixed. From what I see, the unit test for the `preserveHostHeader` is passed ✅ 

Can you share with me the URL and the Script content?
