### ISSUE TITLE
Font Filter

### ISSUE THREAD

**Issue by jlarmstrongiv** [ProxymanApp/Proxyman#772]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.16.1

### macOS Version? (Ex. mac 10.14)
10.15.7

### Steps to reproduce 
_**Look at the menu bar…**_
![image](https://user-images.githubusercontent.com/20903247/106373232-829aac00-6345-11eb-95a6-599caa485bdc.png)

_**Think about my developer tools…**_
Chrome:
![image](https://user-images.githubusercontent.com/20903247/106373239-9ba35d00-6345-11eb-8121-e6f5d31e04a9.png)
Firefox:
![image](https://user-images.githubusercontent.com/20903247/106373268-d5746380-6345-11eb-81a4-720a8c322289.png)
Safari:
![image](https://user-images.githubusercontent.com/20903247/106373280-e8873380-6345-11eb-8c5b-30e31701d525.png)
Even Microsoft Edge:
![image](https://user-images.githubusercontent.com/20903247/106373294-08b6f280-6346-11eb-81ba-22bd31d3cb64.png)

### Expected behavior
A font tab

### Question
- Would it be possible to add a font tab?  
- Is it possible to use the filter tools somehow to achieve the same result?  I wasn’t able to get it

**Comment by NghiaTranUIT** [comment]
yes, it's possible @jlarmstrongiv

I will add it because it's universally supported 👍

**Comment by NghiaTranUIT** [comment]
Hey @jlarmstrongiv,

I've supported the Font filter in this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.16.1_StatusCode_Font_Filters.dmg

Related: https://github.com/ProxymanApp/Proxyman/issues/770#issuecomment-770649873

<img width="1775" alt="Screen Shot 2021-02-01 at 14 38 11" src="https://user-images.githubusercontent.com/5878421/106429715-63169700-649d-11eb-8950-ef980b49fa59.png">

Please let me know if it works for you

**Comment by jlarmstrongiv** [comment]
Wow!!  Tried it out and it worked great 😄 thank you very much for your help and lightning fast replies

Will it also work when the font is directly embedded in the webpage with base64 (like images sometimes are)?

**Comment by NghiaTranUIT** [comment]
@jlarmstrongiv can you give me an example how the request looks like? As long as it's an HTTP/HTTPS Request, Proxyman can capture it

**Comment by NghiaTranUIT** [comment]
if the font is encoded base64 and embedded to the HTML page, so the browser doesn't make any HTTP/HTTPS Requests. Therefore, Proxyman might not capture it I suppose

**Comment by jlarmstrongiv** [comment]
Ahh, yes, that’s what I’m wondering.  For example, consider this image inside an html webpage:
```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```
You can do the same things with fonts in css:
```css
@font-face {
 font-family: Bazar;
 src: url(data:font/ttf;base64,AAEAAAATAQAABAAwR1BPU+Df...
}
```
As it’s not exactly a request, would this still be captured or no?  Would proxyman not capture the image either?

**Comment by NghiaTranUIT** [comment]
The Browser would the encoded base64 data and internally convert it to a font, without making any HTTP Requests. Thus, I'm afraid that Proxyman couldn't because they are not an HTTP/HTTPS request 😄

**Comment by NghiaTranUIT** [comment]
Just wondering: Are there any Proxy Tools able to capture these base64 fonts?

**Comment by jlarmstrongiv** [comment]
Browser tools are able to capture these types of embeds ([Data URLS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)) in their network panels

![image](https://user-images.githubusercontent.com/20903247/106437303-261db680-6443-11eb-97b2-41c4e2dc40f7.png)

**Comment by jlarmstrongiv** [comment]
If it’s not something proxyman supports directly, it may be possible with scripting.

When writing a custom script, I’d need to use some helpful libraries on [NPM](https://www.npmjs.com/).  

It’s not immediately clear if it is possible to install and use npm libraries.  I checked out the scripts, user, and addons folders, but they are all singular js files.  

Whether in an addon or script, the limitations are unclear:
- Does the entire script have to be in a single js file?  Or can it be a project folder?
- Are native modules or binaries supported?
  - For example, converting images from webp to jpg on the fly with the [sharp](https://sharp.pixelplumbing.com/) library?
  - For example, converting woff2 fonts to ttf fonts on the fly with the [woff2](https://www.npmjs.com/package/woff2) library?
  - For example, using [cross-spawn](https://www.npmjs.com/package/cross-spawn) to run arbitrary scripts?
- Can I require from the NodeJS standard library? (path, fs, child_process, etc.)

Also, more information about the environment would be helpful:
- Which version of NodeJS?
  - Is it run in pure NodeJS or an emulator of sorts like JXA?
  - Is it run using the system Nodejs, a packaged version, or something else entirely?
- What [ecmascript specifications](https://kangax.github.io/compat-table/es6/) are supported?

**Comment by NghiaTranUIT** [comment]
Thanks, but Chrome Developer Tool works differently than how Proxy Tools works (like Proxyman, Charles, Fiddler, and Wireshark).

The scripting is built-in from JavascriptCore from Apple (https://developer.apple.com/documentation/javascriptcore), so it lacks features and tools from Javascript devs can do.

> Does the entire script have to be in a single js file? Or can it be a project folder?
It should be a single file. You can use Browserify to bundle an NPM package into a single file. Or just use minified CDN version.

> Are native modules or binaries supported?
> For example, converting images from webp to jpg on the fly with the sharp library?
> For example, converting woff2 fonts to ttf fonts on the fly with the woff2 library?

Not supported yet, but you can use Browserify or minified files, then writing your own addon.

> For example, using cross-spawn to run arbitrary scripts?

Not sure if it works with JavascriptCore because it's not a NodeJS

> Can I require from the NodeJS standard library? (path, fs, child_process, etc.)

No, it's a limitation of JavascriptCore from Apple.

Also, more information about the environment would be helpful:

> Which version of NodeJS?
> Is it run in pure NodeJS or an emulator of sorts like JXA?
> Is it run using the system Nodejs, a packaged version, or something else entirely?

It's not NodeJS, unfortunately.

> What ecmascript specifications are supported?

From what I know, it's ECMAScript 2017

Hope that It could answer your question 😄

**Comment by jlarmstrongiv** [comment]
Oh yes, knowing it’s JSC helps a lot.  That means it’s possible to use [ncc](https://github.com/vercel/ncc) to compile my program as well as use the build-in [cli](https://stackoverflow.com/a/61740889) to test my code.  

Though, the prospect of getting my native modules to work is slim.  It took tons of time and workarounds for [pkg](https://github.com/vercel/pkg), so I’m not sure I want to dive back in anytime soon 😅

**Comment by jlarmstrongiv** [comment]
While supporting Data URLs / Data URIs would be nice, it sounds like there’s not interest in it, so I’ll go ahead and close this issue.  Thanks for adding the font tab!

**Comment by NghiaTranUIT** [comment]
Thanks for opening the ticket 😄 🎉
