### ISSUE TITLE
[BUG::iOS] If device name including non-ASCII characters, generated CA name is garbled

### ISSUE THREAD

**Issue by rinsuki** [ProxymanApp/Proxyman#777]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.0.1 (10015) from TestFlight

### macOS Version? (Ex. mac 10.14)

iOS 14.4 Release

### Steps to reproduce 

1. Add non-ASCII characters to device name
2. Install Proxyman and generate&install certificates

### Expected behavior

generated CA name isn't garbled

### Screenshots (optional)

<img height=400 src=https://user-images.githubusercontent.com/6533808/106925210-35f30e80-6753-11eb-8b63-ae7ff220b91b.png>

**Comment by NghiaTranUIT** [comment]
Thanks for the screenshot. We haven't covered this case yet.

Fixing it now 👍

**Comment by NghiaTranUIT** [comment]
Fixed @rinsuki 🙇 

The fix will release in the next Testflight build 👍 

![IMG_1439](https://user-images.githubusercontent.com/5878421/106987599-6a40ec00-67a0-11eb-8496-77cfb463d1be.PNG)

**Comment by rinsuki** [comment]
Looks good, Thanks!!
<img height=400 src=https://user-images.githubusercontent.com/6533808/107008373-0ede2080-67d7-11eb-8545-833a463e4ce3.png>
