### ISSUE TITLE
Misspelling: "Overriden"

### ISSUE THREAD

**Issue by dhennessy** [ProxymanApp/Proxyman#791]
### Proxyman version 2.18.0

Typo: "Proxy Overriden" should be "Proxy Overridden"

**Comment by dhennessy** [comment]
One more while I see it, on the Send Private Message dialog:

"It's better to leave feedbacks, feature request or bug report at..." should be "It's better to leave feedback, feature requests or bug reports at..."

"If you don't want it's public" should be "If you don't want it public"

**Comment by NghiaTranUIT** [comment]
Thanks. Please consider that it’s done 👍😊

**Comment by NghiaTranUIT** [comment]
Fixed with this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.18.0_Fix_Typo.dmg

We will ship it in the next major release. Thank you so much 🙌

**Comment by dhennessy** [comment]
Thanks for the quick fix!
