### ISSUE TITLE
Script doesn't allow ArrayBuffer as response.body

### ISSUE THREAD

**Issue by SupremeTechnopriest** [ProxymanApp/Proxyman#796]
### Proxyman version? (Ex. Proxyman 1.4.3)
`2.18.0`

### macOS Version? (Ex. mac 10.14)
`11.2.1`

### Steps to reproduce 
Attempt to respond with an ArrayBuffer

```js
function onResponse(context, url, request, response) {
  const buffer = new ArrayBuffer(256)
  const view = new Uint8Array(buffer)
  for (let i = 0; i < view.length; i++) {
    view[i] = i
  }
  response.body = buffer
  response.statusCode = 200
  response.headers['Content-Type'] = 'application/octet-stream'
  return response
}
```

### Expected behavior
It should send the buffer to the client but instead it is throwing the following error:

`❌ Error: Could not parse the body as data. (Content-Type=application/octet-stream)`

**Comment by SupremeTechnopriest** [comment]
If you can solve this issue I will be dropping Charles and picking up a license to proxyman.

**Comment by NghiaTranUIT** [comment]
@SupremeTechnopriest It's a limitation of JavascriptCore when mapping the JS Data Type to Swift. JavascriptCore doesn't allow passing directly ArrayBuffer to Swift (ref: https://nshipster.com/javascriptcore/)

To workaround it, we should convert ArrayBuffer to Base64Encoded String and set to Response as usual (https://docs.proxyman.io/scripting/script#onresponse-objects-format)

I will write down an example to you 👍

**Comment by SupremeTechnopriest** [comment]
Ah I see. And the client will receive it as an ArrayBuffer when reading the stream with `await res.arrayBuffer()`?

**Comment by NghiaTranUIT** [comment]
Here is the script. Please try again if you see if it works 😄 

```
// Addons List: https://docs.proxyman.io/scripting/addons
const { sayHello } = require("@addons/HelloWorld.js");
// Import
const { btoa } = require('@addons/Base64.js');

///
/// This func is called if the Response Checkbox is Enabled
/// You can manipulate the Response Data here before it goes to the client
/// Ex: Add/Update/Remove: headers, statusCode and body (json, plain-text, base64 encoded string)
/// Use console.log(response) to see all available fields
///
function onResponse(context, url, request, response) {
  // console.log(response);
  const buffer = new ArrayBuffer(256)
  const view = new Uint8Array(buffer)
  for (let i = 0; i < view.length; i++) {
    view[i] = i
  }
  
  var newBody = btoa(buffer);
  console.log(buffer);
  console.log(newBody);
  
  response.body = newBody;
  response.statusCode = 200
  response.headers['Content-Type'] = 'application/octet-stream'

  // Done
  return response;
}
```

Ref: https://docs.proxyman.io/scripting/script#5-notes

**Comment by NghiaTranUIT** [comment]
If you need to send a binary file, you can directly import the file and set it as a response.body (See Snippet Code https://docs.proxyman.io/scripting/snippet-code#binary-file)

**Comment by NghiaTranUIT** [comment]
> Ah I see. And the client will receive it as an ArrayBuffer when reading the stream with `await res.arrayBuffer()`?

Unfortunately, JavascriptCore doesn't support `await` or `Promise` : / 

You might directly construct an ArrayBuffer or import it from a file (as I highly recommend) 👍

**Comment by SupremeTechnopriest** [comment]
Ah I mean the client will receive a buffer and not a base64 encoded string?

**Comment by NghiaTranUIT** [comment]
yes, Proxyman will automatically convert the base64String to a buffer when making a request/response. Therefore, the client will receive correctly

**Comment by SupremeTechnopriest** [comment]
Beautiful! Take my money!

**Comment by NghiaTranUIT** [comment]
If there is something that doesn't work as you expect. Feel free to give me an example code, I will check it out 😄

**Comment by SupremeTechnopriest** [comment]
Sounds good!  We can close this for now and if I run into any issues I will re open it.  Thanks for your help!

**Comment by NghiaTranUIT** [comment]
You're welcome 🎉

**Comment by NghiaTranUIT** [comment]
Hey @SupremeTechnopriest 

I've discovered that `btoa` doesn't accept if the param is an ArrayBuffer. `btoa` only accepts Base64String.

You have to convert ArrayBuffer to String then encoding to Base64 like `var newBody = btoa(String.fromCharCode.apply(null, new Uint8Array(buffer)));`

Here is the example code: 

```js
// Addons List: https://docs.proxyman.io/scripting/addons
const { sayHello } = require("@addons/HelloWorld.js");
// Import
const { btoa } = require('@addons/Base64.js');

function onResponse(context, url, request, response) {
  
  const buffer = new ArrayBuffer(256)
  const view = new Uint8Array(buffer)
  for (let i = 0; i < view.length; i++) {
    view[i] = i
  }
  
  // Convert ArrayBuffer to Base64String
  var newBody = btoa(String.fromCharCode.apply(null, new Uint8Array(buffer)));
  console.log(newBody);
  
  response.body = newBody;
  response.statusCode = 200
  response.headers['Content-Type'] = 'application/octet-stream'

  // Done
  return response;
}
```

### Results
The response body has correct ArrayBuffer data

<img width="1290" alt="Screen Shot 2021-02-20 at 09 43 13" src="https://user-images.githubusercontent.com/5878421/108580906-406ef400-7360-11eb-9ea8-ade9353336bc.png">

### Improvements
In the next build, I will:
- Add the ArrayBuffer link in this error `❌ Error: Could not parse the body as data. (Content-Type=application/octet-stream)`, so users can know how to fix it
- Improve built-in `btoa`, it will automatically check ArrayBuffer type and do it behind the scene

**Comment by NghiaTranUIT** [comment]
Here is the beta build, which has some improvement I mention above 👍 (https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.18.0_Improve_Scripting_Array_Buffer.dmg)

You can use `btoa` to convert ArrayBuffer to Base64 without using the following helper code:

### Old
```js
var newBody = btoa(String.fromCharCode.apply(null, new Uint8Array(buffer)));
```

### New
```js
const { btoa } = require('@addons/Base64.js');

var newBody = btoa(buffer);
response.body = newBody;
```

### Notes
- Please delete the old addon at `~/Library/Application Support/com.proxyman.NSProxy/addons/Base64.js` and relaunch the beta build.
- It will automatically update the file if I bump the build version, but for now, we have to do it manually 😄

**Comment by SupremeTechnopriest** [comment]
Thanks for the update.  I will modify my custom addon to stringify the buffer until you bump the build version.

**Comment by SupremeTechnopriest** [comment]
@NghiaTranUIT Quick question.  How would I go the other way?  Parsing an ArrayBuffer on the request. It comes in as Base64, but calling `atob` on it turns it into a string.

**Comment by SupremeTechnopriest** [comment]
Nevermind, I figured it out. 

```js
function convert (str) {
  const buffer = new ArrayBuffer(str.length * 2)
  const view = new Uint8Array(buffer)
  for (var i=0, strLen=str.length; i<strLen; i++) {
    view[i] = str.charCodeAt(i)
  }
  return buffer
}```

Maybe you can add this to the Base64 addon as well 🙂

**Comment by NghiaTranUIT** [comment]
Glad to know that you found the answer 😄 I will improve the atob too 👍
