### ISSUE TITLE
Display Custom HTTP Request Headers in Table

### ISSUE THREAD

**Issue by AnthumChris** [ProxymanApp/Proxyman#801]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.18.0

### macOS Version? (Ex. mac 10.14)
10.15.7

### Feature request

It would be great to show custom HTTP request headers in the table view of requests.  All of our AWS API requests are not distinguishable in the table view, and are only uniquely identified by header `X-Amzn-Target`.  Having a way to see all of the requests and quickly find the ones we want would be amazing.  The filter feature works for now, but it's more of a work-around than a true way to see a list of API requests by action.

![image](https://user-images.githubusercontent.com/10064176/109539417-4adf6b00-7a8f-11eb-8da4-2cbf203cc7d9.png)

**Comment by NghiaTranUIT** [comment]
Thanks for opening the ticket @AnthumChris. 

I understand your problem and I suppose that it's possible to add a new custom column, which shows a particular Header Value.

I will implement and send you a beta this week soon 👍

**Comment by AnthumChris** [comment]
That would be excellent.  As a reference, Chrome Dev Tools provides something similar, but only for response headers

![image](https://user-images.githubusercontent.com/10064176/109585336-58b5e000-7ad1-11eb-8dfe-66a0dd0b9ffe.png)

**Comment by NghiaTranUIT** [comment]
Thanks. I didn't know that it's implemented in Google Chrome Dev Tool. I will check it out and bring it to Proxyman 😄

**Comment by NghiaTranUIT** [comment]
Hey @AnthumChris let try this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.18.0_Custom_Column_Header.dmg

<img width="1101" alt="Screen Shot 2021-03-02 at 15 15 37" src="https://user-images.githubusercontent.com/5878421/109621173-4f7a5100-7b6d-11eb-9a8d-cd0c171d594b.png">

I introduce a Column from the Request/Response Header.

In this v1, I hardcode the Header Key, so you can test it out. Please share with me your feedback 😄 

If it works for you, I will implement the v2, which allows us to manage the customer Header, like Chrome Dev Tools

**Comment by NghiaTranUIT** [comment]
Hey @AnthumChris let check out this v2 Beta: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.19.0_Custom_Header_Column_v2.dmg

From now, we can add/remove custom headers like Google Chrome Dev Tool 🙌 

<img width="672" alt="Screen Shot 2021-03-06 at 16 07 49" src="https://user-images.githubusercontent.com/5878421/110202092-2fae9a00-7e99-11eb-9c8b-f89d4d632329.png">
<img width="2560" alt="Screen_Shot_2021-03-06_at_16_09_42" src="https://user-images.githubusercontent.com/5878421/110202099-350be480-7e99-11eb-8cff-2bf9ac72e3de.png">

**Comment by AnthumChris** [comment]
@NghiaTranUIT this looks great! I have not had time to test will do that early next week.

**Comment by NghiaTranUIT** [comment]
Don't worry. We carefully tested it and it's going to release in next week too 👍 

If you need the latest Beta build (include this Custom Header Column Feature), please check out this https://github.com/ProxymanApp/Proxyman/issues/813#issuecomment-792622378

**Comment by AnthumChris** [comment]
Released in [2.19.0](https://github.com/ProxymanApp/Proxyman/releases/tag/2.19.0)
