### ISSUE TITLE
Map local entry's title does not update

### ISSUE THREAD

**Issue by weazyexe** [ProxymanApp/Proxyman#814]
### Proxyman version?

2.19.0

### macOS Version?

11.2.1

### Steps to reproduce 

1) Press right mouse button on any request
2) In context menu choose Tools -> Map Local...
3) Change name from "Untitled" to whatever you want
4) Close the map local window
5) This map local entry named as "Untitled" but I rename it

### Expected behavior

Map local entry name will update after close map local window.

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/35996778/110913127-ca89f700-8325-11eb-87ef-07e732b07a2f.png)

![image](https://user-images.githubusercontent.com/35996778/110913180-dc6b9a00-8325-11eb-83c3-3de44c53dc87.png)

![image](https://user-images.githubusercontent.com/35996778/110913264-f73e0e80-8325-11eb-9e91-247cf11889f6.png)

**Comment by NghiaTranUIT** [comment]
Thanks for the screenshot. I'm able to reproduce it.

To workaround, after renaming, you can hit Enter to update it properly 👍 Close the window will cause your bug

**Comment by weazyexe** [comment]
Ok, thank you!

Will it be fixed with future updates?

**Comment by NghiaTranUIT** [comment]
yes, sure. I'm fixing it now 😄

**Comment by weazyexe** [comment]
🔥🔥🔥

**Comment by NghiaTranUIT** [comment]
It's done in the latest build 2.20.0. Let update it @weazyexe 👍 

Changelog: https://github.com/ProxymanApp/Proxyman/releases/tag/2.20.0
