### ISSUE TITLE
Search field in Response panel replaces quotation mark `"` with `“`

### ISSUE THREAD

**Issue by rpassis** [ProxymanApp/Proxyman#823]
### Proxyman version? (Ex. Proxyman 1.4.3)

2.20.0

### macOS Version? (Ex. mac 10.14)

11.2.3 (Apple Silicon)

### Steps to reproduce 

Activate the search field inside the response panel and start typing text that begins with `"`. Observe that after you enter a character immediately after the quotation mark, the quotation mark itself gets replaced by the `“` symbol.

![Kapture 2021-03-18 at 08 35 05](https://user-images.githubusercontent.com/387079/111547966-b16dc400-87c5-11eb-9fca-16082254c4fe.gif)

### Expected behavior

The typed quotation mark `"` should not be replaced with `“`

**Comment by NghiaTranUIT** [comment]
Thanks for the video @rpassis 👍 It looks like a bug from CodeMirror. I'm checking it now and send you a Beta build this week  😄

**Comment by NghiaTranUIT** [comment]
@rpassis I discover that it's not but from CodeMirror either Proxyamn. It's "Smart Quotes".

You can disable it by right-click on the Body -> Substitution -> Un-check "Smart Quotes". It would fix the bug. 

<img width="391" alt="Screen Shot 2021-03-18 at 14 25 03" src="https://user-images.githubusercontent.com/5878421/111588210-cfebb380-87f5-11eb-8a33-d743f438703b.png">

Meanwhile, I will find a solution to disable it automatically 👍

**Comment by NghiaTranUIT** [comment]
@rpassis Please check the beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.20.0_Code_Mirror_Smart_Quotes.dmg

It will fix your bug 🙌

**Comment by rpassis** [comment]
I tested with the beta build and it's fixed! I guess smart quotes is not _that_ smart 😊!

Thanks for looking into it, I love Proxyman ❤️!
