### ISSUE TITLE
Proxyman doesn't restore previous proxy settings when toggling the override on/off

### ISSUE THREAD

**Issue by davidolrik** [ProxymanApp/Proxyman#830]
I use a local proxy (`127.0.0.1:8118`), and when toggling the Proxyman override off it would be nice if my precious settings were restored.

Instead what happens is the Proxyman settings are left with the http/https proxies turned off.

**Comment by NghiaTranUIT** [comment]
Thanks for opening the ticket. I didn't see it, so I create a ticket #832 too 👍

**Comment by davidolrik** [comment]
Duplicate of #832
