### ISSUE TITLE
request.scheme or request.schema?

### ISSUE THREAD

**Issue by chaoyangnz** [ProxymanApp/Proxyman#852]
### Proxyman version? (Ex. Proxyman 1.4.3)

latest

### macOS Version? (Ex. mac 10.14)

10.15

### Steps to reproduce 

I am using scripting tool to add custom script, but i found the documentation saying `request.schema`. Normally we use `scheme` to refer to `http` or `https`. is that a typo or intentional?

and another question in scripting, how can I reserve original `Host` header?

**Comment by NghiaTranUIT** [comment]
sorry, looks like it's a bug. I'm going to fix it now 👍 

It should be the `scheme`

For the Preserve host, you can use `request.preserveHostHeader `

https://github.com/ProxymanApp/Proxyman/issues/769#issuecomment-770147548

Look like it doesn't mention in the blog. I will update it

**Comment by chaoyangnz** [comment]
thanks @NghiaTranUIT nice to document it. another question: how can I label `Edited` column in scripting just like built-in `Map Remote` does?

**Comment by chaoyangnz** [comment]
@NghiaTranUIT it is not.

my script is like the below:

![image](https://user-images.githubusercontent.com/4645331/113961119-a6b0c700-9879-11eb-860b-7edc0dc854bc.png)

I only want to transparently forward my request to my localhost.

So in the flow list, the request will be put into `localhost` domain folder rather than the original `develop.example.com` domain folder with `Edit` column labeled.

**Comment by NghiaTranUIT** [comment]
Thanks. I will investigate why there is no Edited in the Scripting 👍

**Comment by NghiaTranUIT** [comment]
@chaoyangnz please check out this beta build: https://github.com/ProxymanApp/Proxyman/issues/853#issuecomment-815522521

It fixes some bugs you mentioned 👍 

> So in the flow list, the request will be put into localhost domain folder rather than the original develop.example.com domain folder with Edit column labeled.

It's the correct behavior from the Scripting. I'm not sure how to fix it

**Comment by chaoyangnz** [comment]
@NghiaTranUIT thanks for the new version.

just wondering, 
- how can `Map Remote` achieved that?
- can I use regex match with group capturing and then replace part of request path? e.g I expect to map a URL: `http://example.com/aa/(.+)` to `http://aa.com/$1`? I saw Charles can do this

**Comment by NghiaTranUIT** [comment]
If you would like to achieve the same thing with Map Remote (like your screenshot in the previous comment https://github.com/ProxymanApp/Proxyman/issues/852#issuecomment-815406950), it's not possible for now 😿 

If your script is working, please use it since it's easier to express your logic.

> can I use regex match with group capturing and then replace part of request path? e.g I expect to map a URL: http://example.com/aa/(.+) to http://aa.com/$1? I saw Charles can do this

You can do it by using Regex in the Scripting.

Here is the example code 
```js
const regex = /http:\/\/example\.com\/aa\/(.+)/gm;
const str = `http://example.com/aa/v1/data?name=proxyman
`;
let m;

while ((m = regex.exec(str)) !== null) {
    // This is necessary to avoid infinite loops with zero-width matches
    if (m.index === regex.lastIndex) {
        regex.lastIndex++;
    }
    
    // The result can be accessed through the `m`-variable.
    m.forEach((match, groupIndex) => {
        console.log(`Found match, group ${groupIndex}: ${match}`);
    });
}
```
It will return the matching groups
```
Found match, group 0: http://example.com/aa/v1/data?name=proxyman
Found match, group 1: v1/data?name=proxyman
```

After that, you get the last group and construct the URL in the script 👍

**Comment by chaoyangnz** [comment]
thanks. close this.

**Comment by NghiaTranUIT** [comment]
Thank you. I will create a ticket to improve the Map Remote, which is able to use Regex Group like Charles 👍

**Comment by patrickschulze** [comment]
@NghiaTranUIT I bought Proxyman yesterday and I really like it.

However, is this functionality already implemented when using the UI and not scripting? How would I access the matching groups? I tried named groups as well as numbered groups but it didn't seem to work. 

**Rule**
`https://test.com/b2c/app/pushnotification/1/(.+?)/partner/register-token`

Neither 
`/api/gsa/pushnotification/$1/partner/register-token` or `/api/gsa/pushnotification/${1}/partner/register-token` work.

**Comment by NghiaTranUIT** [comment]
@patrickschulze sorry, the Matching Group (`() and ${1}`) hasn't been supported for the UI yet.

I highly recommend using Scripting Tool, because it's easier to express your needs by writing a JS code.

**Comment by patrickschulze** [comment]
@NghiaTranUIT Thanks for the very quick response. That's actually what I'm already looking into since scripting will be the better option in the future anyway when it comes to efficiency.

Would still be a nice to have in the UI I guess since Proxyman's UI is really nice.

**Comment by patrickschulze** [comment]
Just if anyone is curious how to solve it with named groups, here's what I came up with:

```
const REGEX = /https:\/\/test\.com\/b2c\/app\/pushnotification\/(?<apiVersion>\d+?)\/(?<sapClientId>\d+?)\/(?<controllerName>\w+)\/(?<endpointName>[\w-]+)/

const ENDPOINT_TO_METHOD_MAPPING = {
  partner: {
    'register-token': 'POST',
    'delete-token': 'PATCH'
  },
  notification_settings: {
    'all': 'GET',
    'update': 'PATCH'
  }
}

async function onRequest(context, url, request) {
  const match = url.match(REGEX)
  
  if (match) {
    const { apiVersion, sapClientId, controllerName, endpointName } = match.groups

    if (request.method !== ENDPOINT_TO_METHOD_MAPPING?.[controllerName]?.[endpointName]) {
      console.log('Invalid METHOD')
      
      return {}
    }
    
    request.scheme = 'http'
    request.host = 'localhost'
    request.port = 3000
    request.path = `api/gsa/pushnotification/${sapClientId}/${controllerName}/${endpointName}`
  } else {
    console.log('does not match')
  }

  return request
}
```
