### ISSUE TITLE
Share all request does not work for Gmail or other apps

### ISSUE THREAD

**Issue by raheelshah31** [ProxymanApp/Proxyman#854]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.0.4
### Steps to reproduce 
Enable proxy for one of the domain 

Once request and response are collected. Click on the share all request for the domain.

Share to Gmail 

The action should share all requests however it shares a zero kb file. 

### Expected behavior

The action should share all requests

**Comment by NghiaTranUIT** [comment]
Hi @raheelshah31. Do you mean it's Proxyman for iOS? @raheelshah31

**Comment by raheelshah31** [comment]
Yes proxyman for ios

**Comment by NghiaTranUIT** [comment]
Thanks. I will check it out and fix it 👍

**Comment by NghiaTranUIT** [comment]
To workaround, you can share to your macOS via Airdrop, then sending it again to your email, it should work 👍

**Comment by NghiaTranUIT** [comment]
@raheelshah31 I've fixed this bug 👍 It is going to release in the next update 🙌 

Thank you for reporting this critical issue 💯

**Comment by raheelshah31** [comment]
Thanks 🎉🎉🎉

**Comment by NghiaTranUIT** [comment]
@raheelshah31 The build 1.0.5 Proxyman for iOS is now live on the AppStore. Please update it 👍
