### ISSUE TITLE
Scripting tool console scrolling 

### ISSUE THREAD

**Issue by chaoyangnz** [ProxymanApp/Proxyman#857]
### Proxyman version? (Ex. Proxyman 1.4.3)
Latest

### macOS Version? (Ex. mac 10.14)
10.14

### Expected behavior

can you make console logs not scrolling, which makes us easier to debug scripts .

**Comment by NghiaTranUIT** [comment]
Sure, I will add an option to prevent the Log to scroll when there is a new log 👍

**Comment by NghiaTranUIT** [comment]
@chaoyangnz please check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.23.0_Improve_Scripting_Tool.dmg

If you turn it off, the Console Log won't automatically scroll anymore 👍 

<img width="580" alt="Screen Shot 2021-04-22 at 12 21 56" src="https://user-images.githubusercontent.com/5878421/115660308-04f3a480-a366-11eb-9b28-25774a056db9.png">

**Comment by chaoyangnz** [comment]
@NghiaTranUIT awesome! that works well
