### ISSUE TITLE
Interface layout issues

### ISSUE THREAD

**Issue by zoain-it** [ProxymanApp/Proxyman#861]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.23.0
### macOS Version? (Ex. mac 10.14)
11.2.3
### Steps to reproduce 
The width of the left column of the Body bar will automatically become smaller and cannot be dragged when you click in the area of request or response

**Comment by NghiaTranUIT** [comment]
Hi @zoain-it can you share with me the screenshot? You can hide the sensitive data before uploading 😊
