### ISSUE TITLE
Automatic breakpoint behaviour without pausing

### ISSUE THREAD

**Issue by sundeepgupta** [ProxymanApp/Proxyman#880]
This is a feature request to allow for configuring a breakpoint with rules, and let the breakpoint happen without pausing. 

Example Use Case
I'm developing a feature on an iOS app which requires a network request to the backend. However, the backend has a bug and is sending the wrong response JSON. The request needs to happen though to update data in the backend's database. 

Currently, I need to set a breakpoint on that request's response so I can edit and correct the response. However, this becomes slow and cumbersome as I need to do it over and over again. It would be nice if I could setup a rule for the breakpoint, but not have it actually pause the request/response. Much like Xcode's breakpoint feature:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/2365037/117306531-c1149b00-ae4d-11eb-9b8e-559e6f891e17.png">

**Comment by NghiaTranUIT** [comment]
Hi @sundeepgupta,

You can do "Automatic Breakpoint" by Map Local or Scripting. They are more efficient and less tedious work.

### Map Local
1. Make a request with your sample response
2. Right Click on the flow -> Tool -> Map Local
3. It will create a rule with current response
4. Then, you can directly edit the JSON Response
5. As soon as you make a request again, it will bring the Map Local Response automatically 
PS: You can also edit Response Header and Status code too

<img width="1239" alt="Screen Shot 2021-05-06 at 8 34 46 PM" src="https://user-images.githubusercontent.com/5878421/117307138-81c86780-aeaa-11eb-98bc-f8cf279ad5b0.png">

Tutorial: https://proxyman.io/blog/2019/08/map-local-feature.html

### Scripting
Scripting allows you to write JS Code that set a response with a file or directly manipulate it
Here is a snipped code: https://docs.proxyman.io/scripting/snippet-code#json

**Comment by sundeepgupta** [comment]
Thanks @NghiaTranUIT , I see. Map Local doesn't work for that use case because the request does indeed need to hit the server. The Scripting feature seems to be what I'm after. I'll check it out - thanks!

**Comment by NghiaTranUIT** [comment]
@sundeepgupta  With the scripting tool, you can do whatever Breakpoint, Map Local, and Map Remote can do.

Make sure you check out the Snippet Code, where you can find all common code 👍

**Comment by NghiaTranUIT** [comment]
@sundeepgupta Glad to know that it helps you 🙌 😄
