### ISSUE TITLE
Settings → Advaced doesn't fit on small screens and isn't scrollable

### ISSUE THREAD

**Issue by florianbuerger** [ProxymanApp/Proxyman#881]
This is the full window 

<img width="702" alt="ScreenShot 2021-05-07 at 18 30 21" src="https://user-images.githubusercontent.com/119219/117481235-fbbc2780-af62-11eb-9a99-0af48321c9e6.png">

But I can not see the bottom part on a 13" MacBook using the default resolution

<img width="702" src="https://user-images.githubusercontent.com/119219/117481315-1b535000-af63-11eb-9194-e0f983dfc505.png">

Seems like the settings windows needs to be embedded in a scroll view :)

---

Proxyman Version 2.24.0 (22400)
macOS 11.3.1 (20E241)

**Comment by NghiaTranUIT** [comment]
Thanks @florianbuerger for the screenshoot. Look like I have to redesign the Advanced Tab 😄

**Comment by NghiaTranUIT** [comment]
Fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.24.0_Fix_Tool_Preference.dmg

<img width="702" alt="Screen Shot 2021-05-08 at 12 57 37 PM" src="https://user-images.githubusercontent.com/5878421/117528629-4ee2b880-affd-11eb-9cb0-d7b6f1a32506.png">

**Comment by florianbuerger** [comment]
Oh wow that was fast, thanks! Looks great 🤩
