### ISSUE TITLE
iOS simulator SSL handshake failure on some subdomains

### ISSUE THREAD

**Issue by EricMentele** [ProxymanApp/Proxyman#901]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.26.0 (22600) free version

### macOS Version? (Ex. mac 10.14)
Big Sur 11.4

### Steps to reproduce 
Install Mac OS Cert and cert on open simulators with reboot
Cert is trusted
Login to app
Error bad request in app.
Proxyman SSL handshake failure 999 on one subdomain.

### Expected behavior
All calls succeed and show payloads in json format

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/5101005/119914353-c88f0780-bf14-11eb-8e64-68dc64b62966.png)

**Comment by EricMentele** [comment]
Happy to jump on a call with you if it will help.

**Comment by NghiaTranUIT** [comment]
Hi, I'm not sure what caused the error on this particular domain 🤔 

I tried to get this domain and it works on my end.
```bash
curl -v 'https://fhir-staging.medinformatix.cc' --proxy http://localhost:9090
```
<img width="1653" alt="Screen Shot 2021-05-28 at 12 31 21" src="https://user-images.githubusercontent.com/5878421/119934821-9f23b980-bfb0-11eb-9e9a-da95e8939f0c.png">

@EricMentele Can you help me to execute this command in your Terminal app? (Please make sure Proxyman app is opening), and see if you're able to see the HTTPS Response 👍

**Comment by EricMentele** [comment]
![image](https://user-images.githubusercontent.com/5101005/119938645-95af3880-bf41-11eb-9c0c-6a20c0b376ee.png)

**Comment by NghiaTranUIT** [comment]
So it works from curl but doesn't work from your iOS Simulator. 

From what I see in your first screenshot, you're able to see other HTTPS Requests from iOS Simulator, which means the certificate is installed and trusted properly.

Just wondering: Does this issue happen in your real iOS Device or it happens only with iOS Simulator?

**Comment by EricMentele** [comment]
It doesn't work. That has an error. On the simulator one two calls work and one gets an ssl handshake failure.

**Comment by EricMentele** [comment]
It's strange because the MacOs proxy seems to work. Tested it on Google.com and also the two calls from the app from the simulator. Haven't tried it on device because I need it to work on the simulator.

**Comment by EricMentele** [comment]
I have Charles Proxy and it can't even install certs on the simulator anymore.

**Comment by NghiaTranUIT** [comment]
Thanks for getting back. You can fix the Charles Proxy by following this answer: https://stackoverflow.com/a/67297897/3127477

and try to use Charles Proxy to see if you're able to reproduce the bug 🤔 

I'm not sure why only this domain doesn't work. If it's a bug from Proxyman, I suppose you couldn't see any Request from your iOS Simulator.

**Comment by EricMentele** [comment]
I tried the manual root cert; however, my admin account gets rejected. It would be great to get Proxyman working because I like it more.

**Comment by EricMentele** [comment]
Strange... now I don't see any traffic from the simulator.

**Comment by EricMentele** [comment]
Saw this in the earlier terminal output: * ALPN, server did not agree to a protocol

**Comment by EricMentele** [comment]
Very strange. I rebooted Proxyman and now it only shows firebase and doesn't seem to log any other traffic even though ssl is active for the app.

**Comment by EricMentele** [comment]
The app calls are all succeeding without being recorded. Thank you for trying to help. I understand if this is too weird of an issue spend time on. Did not used to have it and think it may be related to an Xcode update.

**Comment by NghiaTranUIT** [comment]
Sorry to hear that.

> Saw this in the earlier terminal output: * ALPN, server did not agree to a protocol

It's correct behavior because Proxyman doesn't support HTTP/2 yet, so ALPN would use HTTP/1.1 => cURL will print this warning.

------------
Regarding the issue, I would like to suggest:
1. Turn off all VPN app (if it's opening)
2. Try again with iOS Simulator and iOS Devices
3. If the bug remains, maybe we should try Charles Proxy, to see if you can reproduce it.

Meanwhile, I will investigate the bug

**Comment by EricMentele** [comment]
I just tried Charles and it told me no devices are booted... Use the command line version of the link you sent me. That is odd because I have a simulator open and running.

**Comment by NghiaTranUIT** [comment]
Thanks for the link @EricMentele 🌮 

Look like it's the issue from the Networking library from Apple (URLSession), which automatically rejected the HTTPS `https://fhir-staging.medinformatix.cc`, which doesn't match the certificate.

<img width="1026" alt="Screen Shot 2021-05-28 at 14 28 32" src="https://user-images.githubusercontent.com/5878421/119946589-fd589880-bfc0-11eb-88fc-0eaf36c6cbca.png">

Therefore, we could not do anything to fix it.

You should raise this issue to your team, and update the domain in order to make it work 🌮

**Comment by NghiaTranUIT** [comment]
Hmm, sorry, look like the domain is already correct `https://fhir-staging.medinformatix.cc` (no underscore)

**Comment by EricMentele** [comment]
The underscore is in the full path: getEncountersForPatientId URL https://fhir-staging.medinformatix.cc/v3/Encounter?patient=T500014&_include=*

**Comment by EricMentele** [comment]
Does that count? That is the main difference I see between the one that is failing that those that are succeeding.

**Comment by EricMentele** [comment]
I reached out to my team and asked them if we can replace underscores.

**Comment by EricMentele** [comment]
None of this turned out to be the issue. I had a space in my request header... 🤦‍♂️

**Comment by NghiaTranUIT** [comment]
Glad to know you finally fix a bug 😄 🌮
