### ISSUE TITLE
Support older mac (OS X El Capitan)

### ISSUE THREAD

**Issue by fabiocaccamo** [ProxymanApp/Proxyman#92]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
`1.3.4`

### What OS Version are you using? (Ex. mac 10.13)
`10.11.6`

### Steps to reproduce this issue
Just install the app

### Screenshots (optional)
![Schermata 2019-04-01 alle 10 52 16](https://user-images.githubusercontent.com/1035294/55315334-6a695580-546c-11e9-8fc3-b99e6422013e.png)

**Comment by NghiaTranUIT** [comment]
Hi @fabiocaccamo 

Because of the absent of native Tab feature in OSX 10.11, so I have to disable it temporary.

I'm considering to write my own Tab logic, so I can support old OS in next month.

I will inform you when it releases. Thank you 👍

**Comment by fabiocaccamo** [comment]
@NghiaTranUIT thank you for the quick feedback, hope to try it soon!

**Comment by NghiaTranUIT** [comment]
Hey @fabiocaccamo. It's good news for you 🎉 

I tried to overcome the problem in OS 10.11, and completely fixed it in Proxyman 1.3.4.1.

However, there is some broken UIs on OS 10.11, if you don't mind you can try it here: [Proxyman 1.3.4.1](https://s3.us-east-2.amazonaws.com/proxyman/1341/Proxyman_1.3.4.1.dmg)

--------
I will rollout a official support in Proxyman 1.3.5 👍 

Thank you in advance.

**Comment by fabiocaccamo** [comment]
@NghiaTranUIT thank you very much, I try it now!

**Comment by fabiocaccamo** [comment]
@NghiaTranUIT it is very nice!!
- The icon in the dock is missing
- The password prompt appeared many times, once for each action like start/pause/close app, and for each action it appeared twice... is it possible to prompt password just once on app open?

**Comment by NghiaTranUIT** [comment]
Hey @NghiaTranUIT, 

Prompt password should be asked **once** when we setup the Certificate and it shouldn't present again.

From what's your problem, I can't reproduce in my macOS 10.11 on Parallels. If you don't mind, I would like to ask couple questions in order to catch the bug 🐞 

1. Have you installed the Proxyman CA by "Automatic" or "Manual"?
2. Are you root user or guest? I suppose that it could be a problem 🤔 
3. Try to reset the app (Debug Menu -> Reset -> Data & Certificate) and install Proxyman Certificate by Automatic (if you installs Manual before)

Thank you in advance 😄

**Comment by fabiocaccamo** [comment]
@NghiaTranUIT 
1. I installed the Proxyman CA by "Automatic"
2. I'm root user
3. I did Debug Menu -> Reset -> Data & Certificate -> I clicked restart -> a prompt for credentials appears in an infinite loop -> I killed the process manually.

**Comment by NghiaTranUIT** [comment]
Thank @fabiocaccamo, it's valuable feedback.

I suppose there is problem with OS 10.11 which I couldn't fully aware. I will investigate it carefully when I officially support OS 10.11.

**Comment by fabiocaccamo** [comment]
Ok, I can understand. If you need some test/debug just let me know.

**Comment by NghiaTranUIT** [comment]
Hey @fabiocaccamo, we glad to inform you that Proxyman is now supported macOS 10.11 after implementing the Helper Tool (https://github.com/ProxymanApp/Proxyman/issues/177)

I've tested around and it works perfectly 🎉 

Proxyman 1.4.3 is going to release in couple hours.

**Comment by NghiaTranUIT** [comment]
Hey @fabiocaccamo, You can download Proxyman 1.4.3 in https://github.com/ProxymanApp/Proxyman/releases/tag/1.4.3

See you on macOS 10.11 🌮

**Comment by fabiocaccamo** [comment]
@NghiaTranUIT thank you!
