### ISSUE TITLE
[Question] ignore mac os traffic

### ISSUE THREAD

**Issue by akapitoha** [ProxymanApp/Proxyman#921]
Hi,

is it possible to ignore (don't decrypt) traffic from mac os? a setting maybe.

thank you

**Comment by NghiaTranUIT** [comment]
Hey @akapitoha 

By default, Proxyman doesn't decrypt traffic that goes through the Proxyman app. Proxyman acts as an HTTP Proxy Server, which proxies all data in between.

If you would like to decrypt the traffic in particular domains, you can Enable SSL Proxying on it (Right-Click on the request -> Enable SSL Proxying). You can check out the list of the domain which Proxyman will decrypt it in [SSL Proxying List](https://docs.proxyman.io/basic-features/ssl-proxying).

If you mean "Don't capture all traffic from macOS":

You can turn off the macOS Proxy in Tools Menu -> Proxy Setting -> Override macOS Proxy. By doing this way, there is no traffic that goes through Proxyman.

**Comment by akapitoha** [comment]
hey, that's what I was looking for, thank a lot!

**Comment by NghiaTranUIT** [comment]
Glad to know it helps you 👍 😄
