### ISSUE TITLE
[BUG] iPhone Setup Guide window is too big for small screen

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#93]
## 🐶 Brief
Currently, the iPhone Setup Guide window is unable to scroll if the screen is small, such as Macbook 13".

We have to support the scroller if the content size is bigger than the Display screen.

## 👑 Criteria
- [ ] Add scroller if the content size is bigger than main screen.
- [ ] Automatically Horizontal & Vertial alignment

**Comment by duraki** [comment]
Confirm occurrence of the issue at my lab.

**Comment by NghiaTranUIT** [comment]
Yes, I was aware when testing on mac 12".

We will roll out this bug in this week @duraki  ⚡️

**Comment by NghiaTranUIT** [comment]
Hey @duraki , here is the hot-fix for this issue (https://www.dropbox.com/s/asd249bu9iz97wi/Proxyman_1.3.4%281%29.dmg?dl=0)

From now, we can scroll the content of iPhone Certificate Guideline in small screen.

I will roll out this official fix in end of today. Happy hacking 👍

**Comment by NghiaTranUIT** [comment]
## 🤯 Changelogs 
- [x] Embed the content of iPhone Certificate Guideline to ScrollView.
- [x] Able to scroll in small screen

**Comment by duraki** [comment]
Seems fixed from the shared dmg! Thanks @NghiaTranUIT 💯

**Comment by NghiaTranUIT** [comment]
Nice to hear that @duraki 👍 

Btw, I've officially released the Proxyman 1.3.4.1, which including the fix 💣 

You can download at https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.1 or from Proxyman (Preference -> Check for Update) 🥇
