### ISSUE TITLE
[Feature request] Continue execution after breakpoint

### ISSUE THREAD

**Issue by NicolasCombe5555** [ProxymanApp/Proxyman#957]
Is it possible that we could enter a response for a specific url, and when triggered, the breakpoint would not stop but take our response and execute said request?
I think this would be useful specially if say you are constantly listening for a certain path, there a lot of breakpoints would accumulate and it is tedious to keep up with all of them, so if we could continue the execution as soon as we can that would be great.

**Comment by NghiaTranUIT** [comment]
Yeah, you basically describe what [Map Local](https://docs.proxyman.io/advanced-features/map-local) tool does 😄 

You can quickly create a Map Local by right-click on the Request (That has a response) -> Tool -> Map Local.

From there, you can modify the response, and Proxyman automatically get a response and return it if it's matched 👍

**Comment by NicolasCombe5555** [comment]
Oh awesome! Did not know that, thanks 👍🏻 
Sorry for the issue 😅

**Comment by NghiaTranUIT** [comment]
You're always welcome to open a ticket 👍
