### ISSUE TITLE
[BUG] Can't override the System Proxy if it's from Ethernet

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#96]
## 🐶 Brief
During debugging in OS 10.11 in Parallels, it turns out that Proxyman is unable to override the System Proxy if the connection is from Ethernet, not Wifi.

We have to fix it.

## 👑 Criteria
- [ ] Able to detect current connection and override Proxy automatically 
- [ ] Work on Wifi and Ethernet

**Comment by colealanroberts** [comment]
👍 Excellent, I just ran into this myself.

**Comment by NghiaTranUIT** [comment]
@colealanroberts You can override the Proxy manually in Network -> Select Ethernet -> Advance -> Proxies then filling ip `127.0.0.1` port `9090` for HTTP/HTTPS Proxy 👍 

I will do official fix in next release.

## Photo 📷 

![Screen Shot 2019-04-01 at 10 21 44 PM](https://user-images.githubusercontent.com/5878421/55376131-22643480-5539-11e9-8b6f-1581ed76bf9d.png)

**Comment by NghiaTranUIT** [comment]
All done in Proxyman 1.3.4.1 ⚡️

## 🤯 Changelogs 
- [x] Improve logic to able override / revert the Proxy config of connected network devices.
- [x] Work in Ethernet, iPhone Bridge or Wifi

**Comment by NghiaTranUIT** [comment]
@colealanroberts Check out the official [Proxyman 1.3.4.1](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.1) or update directly from the app (Preference -> Check for Update) 🥇 

From now, Proxyman is able to override the Ethernet, Wifi or even iPhone internet sharing 👍
