### ISSUE TITLE
"Use onResponse() as a Mock API" not available

### ISSUE THREAD

**Issue by florentmorin** [ProxymanApp/Proxyman#962]
### Proxyman version? (Ex. Proxyman 1.4.3)

Proxyman 2.31.0 (23100)

### macOS Version? (Ex. mac 10.14)

mac 11.5.1

### Steps to reproduce 

Follow steps from [documentation](https://docs.proxyman.io/scripting/script#8-use-scripting-as-a-mock-api) :

1. Open the Scripting Tool -> Select the Script
2. Open More button -> ...
3. "Use onResponse() as a Mock API" is not available

### Expected behavior

Check "Use onResponse() as a Mock API"

### Screenshots (optional)

<img width="266" alt="Capture d’écran 2021-08-19 à 12 27 39" src="https://user-images.githubusercontent.com/1071783/130054114-4e6d00e3-dbbc-444d-a2a8-f2d5b4cc2a5a.png">

**Comment by NghiaTranUIT** [comment]
Hey @florentmorin 

It's not available on the production yet. Please try this beta build at https://github.com/ProxymanApp/Proxyman/issues/946#issuecomment-898470661 😄
