### ISSUE TITLE
Export as Charles, Fiddler, etc.

### ISSUE THREAD

**Issue by jj0e** [ProxymanApp/Proxyman#972]
### Proxyman version? 2.32.0

I would love to be able to share my Proxyman sessions with colleagues who do not have macOS device, rather linux or windows. Can we add a feature that exports the entire session to something like Charles or Fiddler?

**Comment by NghiaTranUIT** [comment]
You can select your request -> Right Click -> Export as HAR format. Then your colleagues can open it with Google Dev Tool, Charles and Fiddler :+1

**Comment by NghiaTranUIT** [comment]
You can export as HAR format, and open it with Google Dev Tool, Charles and Fiddler :+1

**Comment by jj0e** [comment]
Thanks, I was not familiar with what har was!
