### ISSUE TITLE
Quit Proxyman, restore system proxy settings.

### ISSUE THREAD

**Issue by XaoflySho** [ProxymanApp/Proxyman#988]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.32.1 (23210)
### macOS Version? (Ex. mac 10.14)
12.0
### Steps to reproduce 
Quit proxyman.
### Expected behavior
Restore system proxy settings.

**Comment by NghiaTranUIT** [comment]
Hey, if you install [Helper Tool 1.3.0](https://docs.proxyman.io/basic-features/proxy-setting-tool#changelog), it will remember and restore the proxy setting after the app is quit.

Please open Preference -> Advanced -> Install or update the helper tool if need 👍 

<img width="702" alt="Screen_Shot_2021-09-10_at_10_21_21" src="https://user-images.githubusercontent.com/5878421/132794359-dd1a7d9e-52e0-4705-a8b2-84c0e824a46a.png">

**Comment by XaoflySho** [comment]
Thank you, now it seems to work properly.
