### ISSUE TITLE
[Request] Move Use as Mock API setting with a checkbox to the editing window

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#999]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.32.1 (23210)

The **Use as Mock API** setting in Proxyman is fantastic. I'm getting a ton of use out of it. I think it's so helpful, that it should be moved up to the main script editor window instead of hidden away under the More button! I think that it would be nice to give it a permanent home where the current label is, along with a checkbox to toggle it on and off. (Terrible quality mock-up attached)

I think a color checkbox would be nice to stand out more when enabled. The dark mode windows are fairly low contrast so the color would help folks with older eyes, like me. :)

<img width="512" alt="proxyman-mock-api" src="https://user-images.githubusercontent.com/1638278/133704818-3f193a0f-b4ae-41b8-ab91-0c01626426fc.png">

**Comment by NghiaTranUIT** [comment]
Thanks for your insight @crankygeek. I move this feature to the main view, so everyone can discover it easily 👍 😄 
Build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.32.1_Improve_Mock_API_UI.dmg

<img width="1479" alt="Screen_Shot_2021-09-17_at_14_59_30" src="https://user-images.githubusercontent.com/5878421/133752631-b1634a65-f7e8-4bf1-8608-8cfdb7615784.png">

**Comment by crankygeek** [comment]
LGTM. Ship it! :)
